### ISSUE TITLE
non-interactive docker login fails

### ISSUE THREAD

**Issue by jamesrgrinter** [docker/cli#1002]
**Description**

Since an update in our build system that lead to Docker 18.04 (`Docker version 18.04.0-ce, build 3d479c0`), the combination of awscli's `ecr get-login ...` and the resulting `docker login` command that it generates, are failing.

**Steps to reproduce the issue:**
1. apt-get update an Ubuntu Trusty environment to the latest docker-ce (18.04.0-ce)
2. Run `eval $(aws ecr get-login --no-include-email)` via an unattended build process like Travis CI
3. wait..
4. Observe login failure in the logs

**Describe the results you received:**

```
$ eval $(aws ecr get-login --no-include-email)
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
WARNING! Your password will be stored unencrypted in /home/travis/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store
Are you sure you want to proceed? [y/N] 
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

**Describe the results you expected:**

```
$ eval $(aws ecr get-login --region us-west-2 --no-include-email)
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Login Succeeded
```

**Additional information you deem important (e.g. issue happens only occasionally):**

My hunch is that it might have something to do with #139 - but I haven't actually spotted the change that is responsible, yet.

**Output of `docker version`:**

I don't have full output in our build logs, but `docker -v` reported:
```
Docker version 18.04.0-ce, build 3d479c0
```

previously, we can see from our historical build logs that whilst we were upgrading to the earlier version 18.03.0-ce it was working.

```
Docker version 18.03.0-ce, build 0520e24 
```

**Output of `docker info`:**

(I'll obtain this if the version alone is not enough)
```
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

running inside of a Travis CI build on their "trusty" environment (`services: docker`).

AWScli version is currently `awscli-1.15.4`.

**Comment by thaJeztah** [comment]
The prompt was reverted in https://github.com/docker/cli/pull/1008, so this is fixed in Docker 18.05 and up
