### ISSUE TITLE
Document how to install the CLI

### ISSUE THREAD

**Issue by MartinMuzatko** [docker/cli#1015]
Is it in the linux repositories? Is there a package on chocolatey? What is the package name? Is it on NPM?
This needs to be in the README.md

**Comment by jaswdr** [comment]
@MartinMuzatko  `cli` is only a part of docker environment, if you are in Linux/Mac, you can look at this [link](https://get.docker.com/), otherwise I suggest to take a look at [docker-ce](https://www.docker.com/community-edition) website.

**Comment by thaJeztah** [comment]
let me close this one in favour of https://github.com/docker/cli/issues/2281
