### ISSUE TITLE
Add support to forward TLS passphrase to go-connections

### ISSUE THREAD

**Issue by marcosnils** [docker/cli#103]
the `go-connections` library recently included an option to set TLS passphrase when decrypting  private keys (https://github.com/docker/go-connections/pull/35). It'd be nice if this option could be added to the CLI as well so users don't have to type their passphrase each time they want to execute a command with an encrypted key.

I can send the PR if you think this should go in. I propose the flag to be `--tlspassphrase`

@vdemeester WDYT?

**Comment by vdemeester** [comment]
Seems good to me
/cc @cyli @dnephin @n4ss

**Comment by bsousaa** [comment]
Support of password encrypted TLS was deprecated. Please see https://github.com/docker/cli/blob/v23.0.0-rc.3/docs/deprecated.md#support-for-encrypted-tls-private-keys. Corresponding PR https://github.com/docker/cli/pull/3218
