### ISSUE TITLE
Cannot find documentation on "-Bbn"

### ISSUE THREAD

**Issue by gintautassulskus** [docker/cli#1032]
**Description**

I have been following the [docker registry setup instructions](https://docs.docker.com/registry/deploying/#restricting-access) and came across the following command line:
```
docker run \
  --entrypoint htpasswd \
  registry:2 -Bbn testuser testpassword > auth/htpasswd
```
I understand the `-Bbn` parameter has something to do with the ecnryption/encoding of the provided password. I would like to reproduce this step manually in a deployment tool. However, without knowing what this `-Bbn` does, I find it difficult to acheive.

Could someone explain it to me and/or ideally add a documentation entry?

**Comment by cpuguy83** [comment]
This is not from the docker CLI but rather the htpasswd command.
https://httpd.apache.org/docs/2.4/programs/htpasswd.html

**Comment by gintautassulskus** [comment]
My bad. Overlooked the obvious - the entrypoint.

Thanks.
