### ISSUE TITLE
Fix mounts output style to match the rest of output

### ISSUE THREAD

**Issue by essamhassan** [docker/cli#1036]
**Description**
Provided an example output of pretty print
you can see that mounts output does not match the rest. In mounts its using a = instead of : in the rest of the output. Same for Labels

```
ID:		x2l4mdjijqncfeebbq7zmz5tr
Name:		testie
Service Mode:	Replicated
 Replicas:	1
Placement:
UpdateConfig:
 Parallelism:	1
 On failure:	pause
 Monitoring Period: 5s
 Max failure ratio: 0
 Update order:      stop-first
RollbackConfig:
 Parallelism:	1
 On failure:	pause
 Monitoring Period: 5s
 Max failure ratio: 0
 Rollback order:    stop-first
ContainerSpec:
 Image:		nginx:alpine@sha256:3a44395131c5a9704417d19ab4c8d6cb104013659f5babb2f1c632e789588196
Labels:
 bar=baz
 foo=bar
Mounts:
  Target = /bax
   Source = foobar
   ReadOnly = false
   Type = volume
  Target = /baz
   Source = foobar
   ReadOnly = false
   Type = volume
Resources:
Networks: testnet 
Endpoint Mode:	vip
```

**Steps to reproduce the issue:**
1. run 
```
$ docker service create \
  --label foo=bar \
  --label bar=baz \
  --mount type=volume,src=foobar,target=/bax \
  --mount type=volume,src=foobar,target=/baz \
  --network testnet \
  --name testie \
  nginx:alpine
```
2. run `docker service inspect testie --pretty`

**Describe the results you received:**
running `docker service inspect testie --pretty` outputs mounts using = 

**Describe the results you expected:**
mount output should use : instead of =

**Additional information you deem important (e.g. issue happens only occasionally):**

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by essamhassan** [comment]
@vdemeester this is related to our previous discussion about configs and secrets

**Comment by thaJeztah** [comment]
fixed in https://github.com/docker/cli/issues/1037
