### ISSUE TITLE
Docker Engine service on Windows should depend on com.docker.service

### ISSUE THREAD

**Issue by fredrikhr** [docker/cli#1056]
When running `dockerd --register-service` on Windows, the registered `Docker Engine` service should get a dependency on the `com.docker.service` service, so that starting the `docker` service also starts the `com.docker.service` service.

**Comment by bsousaa** [comment]
This issue is most likely stale, anyhow if still valid it should be reported in https://github.com/docker/for-win/issues or https://github.com/moby/moby.
