### ISSUE TITLE
Find cleaner solution for fetching all Kubernetes namespaces

### ISSUE THREAD

**Issue by chris-crone** [docker/cli#1067]
**Description**
We currently fallback to a UCP API for fetching Kubernetes namespaces when the given user does not have permission to do so (see: https://github.com/docker/cli/pull/1034).

We should find a cleaner way to handle this case such as that suggested by @vdemeester:
> As discussed a bit offline earlier, a cleaner way (way cleaner) would have been to have a kubernetes api extension (same as the current "compose on kubernetes" one):
> - we wouldn't need to hack docker/docker client around, we would just consume the go code from the > extension (again, same way as "compose on kubernetes")
> - it would be "automatically" versionned (because of k8s way of doing things)
> - it wouldn't be a direct dependency on UCP as it could be easily deployed on other cluster in the future if we wanted

**Comment by thaJeztah** [comment]
kubernetes integration was deprecated and removed; let me close this one
