### ISSUE TITLE
A malformed stack can prevent from listing stacks on Kubernetes

### ISSUE THREAD

**Issue by silvin-lubecki** [docker/cli#1107]
**Description**

If a malformed stack (v1beta1 version) is deployed on Kubernetes, `docker stack ls` will fail to parse it and error out before listing all the other valid stacks.

**Steps to reproduce the issue:**
1. Deploy a v1beta1 stack with a malformed compose file
2. Deploy a valid other stack
3. List the stacks

**Comment by justyntemme** [comment]
Hi there, I would like to tackle this bug. I have my environment setup and I do see where the error is being thrown where it should continue while printing out the error. Could you give me an example of a malformed compose file that is still allowed to deploy?

**Comment by justyntemme** [comment]
It seems this can only be tested on docker-for-mac at the moment?

**Comment by thaJeztah** [comment]
kubernetes integration was deprecated and removed; let me close this one
