### ISSUE TITLE
docker pull in windows does not show appropriate error when pulling image from private registry.

### ISSUE THREAD

**Issue by SakalyaDeshpande** [docker/cli#1108]
I tried to pull a docker image from private registry(artifactory) on my Windows Docker Host.But docker CLI is giving error as "invalid reference format".After I could resolve the issue by adding artifactory URL in insecure-registeries.It would be better if this error is meaningful(something like make sure that private registry you are pulling from is secure or something like that)

**Comment by jaswdr** [comment]
@sakky11 did you can add more information about how to reproduce this issue?

**Comment by sakky11** [comment]
@jaswdr Yes sure.Install Docker for windows.And try to pull any docker image from a private registry(Without adding te registry entry in insecure-registries),and you will see this error.

**Comment by thaJeztah** [comment]
closing as stale, and this may be related to how the registry is configured.
