### ISSUE TITLE
Cross Compile Issue

### ISSUE THREAD

**Issue by abhinavkorpal** [docker/cli#1118]
**Description**

configure: error: cannot check for file existence when cross compiling
facing issue on container

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by silvin-lubecki** [comment]
Hi @abhinavkorpal , thank you for reporting an issue, but your issue lacks some common information we need to understand and/or fix it. You can find more on how to describe an issue in the [contribution section](https://github.com/docker/cli/blob/master/CONTRIBUTING.md#reporting-other-issues) . I'm closing it for now, but feel free to add more description and then re-open it.
