### ISSUE TITLE
unhelpful stacktrace instead of error message when file's version is malformed

### ISSUE THREAD

**Issue by techieshark** [docker/cli#1132]
**Description**

If you have a typo like an extra space, in the version field, you'll see a stack trace rather than error message. 

**Steps to reproduce the issue:**
1. create a `docker-compose.yml`  containing:

```
version: '3 '

services:
  web:
    image: alpine:latest
```

(Note the space following the 3)

2. Run compose

```
docker-compose -f docker-compose.yml config
```

**Describe the results you received:**

Stack trace is printed:

```
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 121, in perform_command
  File "compose/cli/main.py", line 332, in config
  File "compose/cli/command.py", line 68, in get_config_from_options
  File "compose/config/config.py", line 385, in load
  File "compose/config/config.py", line 385, in <listcomp>
  File "compose/config/config.py", line 535, in process_config_file
  File "distutils/version.py", line 70, in __ge__
  File "distutils/version.py", line 337, in _cmp
TypeError: '<' not supported between instances of 'str' and 'int'
[70770] Failed to execute script docker-compose
```

**Describe the results you expected:**

Helpful message like:

```
The `version` field in the file `docker-compose.yml` contains an unexpected character. It should be either 1, 2, or 3. We found: "3 ".
```

**Output of `docker version`:**

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:13:02 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: true
```

**Output of `docker info`:**

```
Containers: 14
 Running: 0
 Paused: 0
 Stopped: 14
Images: 24
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.87-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: JVES:2JW2:PTUF:H7DK:HBIJ:CFST:MVDU:KO5U:DWZE:FJ43:H2E6:OMDW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 23
 Goroutines: 42
 System Time: 2018-06-19T18:47:41.7678266Z
 EventsListeners: 2
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Local dev box.

**Comment by cpuguy83** [comment]
This should go in https://github.com/docker/compose

**Comment by techieshark** [comment]
@cpuguy83 I had originally thought to leave this issue in https://github.com/docker/compose, but this message is shown when you open a new issue there:

> 
> 1. This tracker should only be used to report bugs and request features / enhancements to docker-compose
>   ...
>     - For issues with the `docker stack` commands **and the version 3 of the Compose file, use
>       https://github.com/docker/cli**

I must have misinterpreted that part of the instruction. I'll post in docker/compose. Thanks.

**Comment by cpuguy83** [comment]
`docker-compose -f docker-compose.yml config` is a docker-compose command not related to stacks, even though `docker stack` and `docker-compose` use the same format ;)

**Comment by techieshark** [comment]
Yeah, no I just mis-parsed the sentence. 

I interpreted it to mean "For issues related to stack, **or for issues** related to compose file version 3", rather than "For issues with the docker stack commands **which are specific to** version 3 of the Compose file". 

I should have read 'and' in the logical / programmer sense rather than the ambiguous English sense.

Thanks again for the clarification! :)

**Comment by cpuguy83** [comment]
Thanks for taking the time to report the issue... and then re-report it in another repo! 😍
