### ISSUE TITLE
[buildkit] help definition of `docker build --console` is confusing 

### ISSUE THREAD

**Issue by AntaresS** [docker/cli#1133]
**Description**

**Steps to reproduce the issue:**
This is not really an issue but something we can discuss to improve.
With docker experimental mode on and buildkit enabled,
1. `docker build --help | grep "console"` produces the following output. 
```
--console                 Show console output (with buildkit only) (true, false, auto) (default auto)
```
Both `--console=true` and `--console=false` will produce console output except the former one is interactive with progress rewritting terminal buffer. This seems to be somewhat confusing. IMHO, either reword the help description or renaming the option to something like `--show-progress` could make it more straightforward.

**Output of `docker version`:**

```
Client:
 Version:      18.06.0-ce-dev
 API version:  1.38
 Go version:   go1.10.3
 Git commit:   3863dd0
 Built:        Mon Jun 18 14:56:58 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.06.0-ce-dev
  API version:  1.38 (minimum version 1.12)
  Go version:   go1.10.3
  Git commit:   3863dd0
  Built:        Mon Jun 18 14:55:03 2018
  OS/Arch:      linux/amd64
  Experimental: true
```

cc @tiborvass @tonistiigi

**Comment by glensc** [comment]
i think this is already renamed to `--progress`?

```
$ DOCKER_BUILDKIT=1 docker build --help | grep -c "console"
0

$ docker --version
Docker version 18.09.0, build 4d60db4

$ DOCKER_BUILDKIT=1 docker build --help | grep "progress"
      --progress string         Set type of progress output (auto, plain, tty). Use plain to show container output (default "auto")
```

**Comment by AntaresS** [comment]
@glensc Yup. Old issue never been closed. Thanks for digging it out!

closed in favor of https://github.com/moby/buildkit/pull/504
