### ISSUE TITLE
--health-start-period value isn't shown when pretty inspecting service

### ISSUE THREAD

**Issue by vide** [docker/cli#117]
**Description**

When I set the `--health-start-period` in a service, I cannot see the set value using `docker service inspect --pretty`, 

**Steps to reproduce the issue:**
1. `docker service update foo --health-start-period 2m`
2. `docker service inspect --pretty foo | grep -i health`

**Describe the results you received:**

No results while looking for an "Health Start Period value"

**Describe the results you expected:**

I think this is an important value that should appear in the prettified output too by default. I'm aware that the whole JSON inspect output carries indeed this info under
```
                "ContainerSpec": {
                    "Healthcheck": {
                        "StartPeriod": 120000000000
                    },
```

**Output of `docker version`:**

```
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by thaJeztah** [comment]
Trying to reproduce the issue to check if it's still current;

```bash
docker service create --name foo nginx:alpine
docker service update foo --health-start-period 2m
```

Inspecting in the default (JSON) format:

```bash
docker service inspect foo | grep -i health -n2  
                    "Init": false,
16-                    "StopGracePeriod": 10000000000,
17:                    "Healthcheck": {
18-                        "StartPeriod": 120000000000
19-                    },
```

Or, when using the `--format` option;

```bash
docker service inspect --format='{{json .Spec.TaskTemplate.ContainerSpec.Healthcheck }}' foo
{"StartPeriod":120000000000}
```

So it looks like it's indeed still missing when using the `--pretty` option:

```bash
docker service inspect --pretty foo | grep -i health
```

Given that the information is known by the CLI (it's present in the JSON output), I suspect this needs a change in the Go template that is used for the `--pretty` output;
https://github.com/docker/cli/blob/0904fbfc77dbd4b6296c56e68be573b889d049e3/cli/command/service/formatter.go#L20

Looks like that template is currently missing a section for HealthChecks, so something would have to be added, similar to what was done in  https://github.com/docker/cli/commit/3ae2d4b24c2156240503f47f42c158318a5df88a#diff-cf223d788e2813f2abd145d9036bd6c2 (https://github.com/docker/cli/pull/1006) to add configs and secrets to the template
