### ISSUE TITLE
Image calculated size is wrong

### ISSUE THREAD

**Issue by mterron** [docker/cli#1206]
**Description**

When you execute ```docker images``` the reported size is off

**Steps to reproduce the issue:**
1. From base --> base size 10 MB as reported by docker history imagename
2. Run download a.zip (10 MB) --> layer size 20 MB as reported by docker history imagename
3. Run download b.zip (10 MB) --> layer size 30 MB as reported by docker history imagename

**Describe the results you received:**
docker images show image size is 60MB

**Describe the results you expected:**
docker images show image size is 30MB

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:48 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

**Output of `docker info`:**

```
Containers: 4
 Running: 2
 Paused: 0
 Stopped: 2
Images: 23
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.87-linuxkit-aufs
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 2.915GiB
Name: linuxkit-000000000
ID:
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 48
 Goroutines: 66
 System Time: 2018-07-12T19:52:56.8601675Z
 EventsListeners: 2
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
Without fully reproducible steps, I think this behavior is correct, but it depends on what files are updated. In a Copy-on-Write filesystem, updating files that exist in prior layers means that these files will land as _new_ files in the new layer, and files in lower layers won't be removed (you can only _add_ size, never _remove_ size).

As this is a very old ticket, I'll close it, but if you have a runnable example, with exact steps to reproduce, we can continue the conversation.
