### ISSUE TITLE
Migrate TestTrustedCreateFromBadTrustServer to cli/e2e

### ISSUE THREAD

**Issue by thaJeztah** [docker/cli#1218]
Noticed this TODO, so let's create a ticket in case someone wants to work on this; https://github.com/docker/cli/blob/4cb3c70f36baeade76879694a587358be2a74854/e2e/container/create_test.go#L35

The `TestTrustedCreateFromBadTrustServer ` test was removed from the moby/moby integration tests (because it's testing client-side functionality), but didn't get re-implemented as an e2e test in this repository; the existing test can be found here; https://github.com/moby/moby/pull/36515/files#diff-4b1e56bb77ac16f2ccf956fc24cf0a82L331, but needs a rewrite to work in the e2e suite in this repo

/cc @vdemeester

**Comment by glefloch** [comment]
Hi, I would like to work on this is it possible? Regards
