### ISSUE TITLE
poor error message when no VBox installed OS X

### ISSUE THREAD

**Issue by rdp** [docker/cli#1224]
**Description**

When first setting up docker on a mac:

```
$  docker-machine  create  default12
Running pre-create checks...
Error with pre-create check: "VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path"
$
```

**Steps to reproduce the issue:**
1.  See above.

**Describe the results you received:**
See above.

**Describe the results you expected:**
I expect it to also mention that xhyve is an option, the message makes it sound like VBox is the only option...

**Additional information you deem important (e.g. issue happens only occasionally):**

No vbox or xhyve installed.

**Output of `docker version`:**

```
$ docker version
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             unknown-buildtime
 OS/Arch:           darwin/amd64
 Experimental:      false
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Output of `docker info`:**

```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

OS X (installed via homebrew)

**Comment by silvin-lubecki** [comment]
Thank you @rdp for filling this issue, but I think it is the wrong repository (docker CLI) as it seams to reference `docker-machine`. I will close this issue, but feel free to re-open it on https://github.com/docker/machine . You can re-open it if you think the CLI is impacted.
