### ISSUE TITLE
I can't build cli binary. How to solve the following errors?

### ISSUE THREAD

**Issue by jeffyjf** [docker/cli#1253]
[aws@instance-8 cli]$ sudo make -f docker.Makefile binary
docker build -t docker-cli-native -f ./dockerfiles/Dockerfile.binary-native .
Sending build context to Docker daemon 34.75 MB
Step 1/5 : FROM golang:1.10.3-alpine
 ---> 34d3217973fd
Step 2/5 : RUN apk add -U git bash coreutils gcc musl-dev
 ---> Using cache
 ---> 33812e22c925
Step 3/5 : ENV CGO_ENABLED 0 DISABLE_WARN_OUTSIDE_CONTAINER 1
 ---> Using cache
 ---> d69209bc21a8
Step 4/5 : WORKDIR /go/src/github.com/docker/cli
 ---> Using cache
 ---> f553f6f5f7c9
Step 5/5 : CMD ./scripts/build/binary
 ---> Using cache
 ---> 9e75979fd600
Successfully built 9e75979fd600
docker run --rm -e VERSION=18.09.0-dev -e GITCOMMIT -e PLATFORM -v "/home/aws/gowork/src/github.com/docker/cli":/go/src/github.com/docker/cli docker-cli-native
/bin/sh: ./scripts/build/binary: Permission denied
make: *** [binary] Error 126
[aws@instance-8 cli]$

**Comment by RobTiki** [comment]
I know this is issue is old, but I was getting the same error building on centos 7.6 with kernel 3.10.x.  The build was able to complete once I updated the kernel to 4.20.7.  A requirements or wiki page would be of some help for this repo.

**Comment by thaJeztah** [comment]
closing as stale
