### ISSUE TITLE
Add visual feedback on how far copying files to and from docker container is going.

### ISSUE THREAD

**Issue by Crare** [docker/cli#1281]
**Description**

I'm copying files to and from docker container to edit them locally.
I would like to see how long it takes, or how many files is there to copy still.
Maybe an estimate how long it takes and how long it has been running copy command.
These could be extra command options you could choose to show the progress of copying files.
It would be useful when you're copying a lot of files.
Expecially it would seem better than what it now is. Currently it looks like the whole console is jammed up when copying because there's no visual feedback of how the copying is going.

**Steps to reproduce the issue:**
1. copy file to docker container
`docker cp ./www container_name:/var/`

2. copy files from docker container
`docker cp container_name:/var/www ./`

**Describe the results you received:**
No visual feedback how far is the copying going. It looks like the console is frozen.

**Describe the results you expected:**
Some indication of how far the progress is going on with copying files.

**Additional information you deem important (e.g. issue happens only occasionally):**
visual clue that console is not frozen, that it's still copying files.

**Comment by silvin-lubecki** [comment]
Hi @Crare thank you for filling this issue! You're right it seems to be a good enhancement. PRs are welcomed 😉

**Comment by Crare** [comment]
You're welcome! @silvin-lubecki I actually would find this useful elsewhere in the CLI too. Like when making a commit after a while it takes a bit longer and that looks like it's frozen too. It's a minor enhancement, but would look better and I wouldn't be so confused every-time it happens. (thinking it's frozen when it's actually not. I've sometimes restarted the whole docker because of this.)

**Comment by adeniyistephen** [comment]
@Crare @silvin-lubecki Hi, I would love to work on this, Please provide pointers and input on how to work on it. Thanks

**Comment by thaJeztah** [comment]
I think this is being worked on in https://github.com/docker/cli/pull/2708
