### ISSUE TITLE
Build hangs under Dropbox synced folder

### ISSUE THREAD

**Issue by brbrowning21** [docker/cli#1305]
**Description**

`docker build` hangs when trying to build a Dockerfile that lives in my personal Dropbox folder on macOS. When moving that project outside of the Dropbox folder to a regular folder on my SSD, build succeeds.

**Steps to reproduce the issue:**
1. Create a Dockerfile somewhere under your Dropbox folder.
2. Try building it. It hangs.
3. Move that Dockerfile to a local (unsynced) folder.
4. Retry build. It succeeds.

**Describe the results you received:**

`docker build .` just hangs when building a project in the Dropbox folder.

**Describe the results you expected:**

The build to succeed.

**Additional information you deem important (e.g. issue happens only occasionally):**

Problems resolves itself when I restart Docker for Mac. After a while it will reappear though.

**Output of `docker version`:**

```
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:05:26 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:13:46 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```

**Output of `docker info`:**

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 27
Server Version: 18.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: d64c661f1d51c48782c9cec8fda7604785f93587
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.93-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: KLMU:RKOP:RT45:MGYH:JCDO:KOUG:6EXU:TJIY:PBUK:2FDB:TTG4:5NHX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 44
 Goroutines: 71
 System Time: 2018-08-22T13:44:27.5331812Z
 EventsListeners: 2
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I'm running Docker for Mac and all my code lives in my Dropbox folder (~/Dropbox (Personal)/Programming). All but only one unrelated folder is set to selective sync to Dropbox.

**Comment by thaJeztah** [comment]
Tried to reproduce with a very minimal example, but was not able to.

```bash
mkdir ~/Dropbox/docker-build
touch one two three four

cat <<EOF > Dockerfile
FROM busybox
COPY . /content
EOF

docker build .
Sending build context to Docker daemon  4.096kB
Step 1/2 : FROM busybox
 ---> e1ddd7948a1c
Step 2/2 : COPY . /content
 ---> b2915f5ed9ab
Successfully built b2915f5ed9ab
```


> Problems resolves itself when I restart Docker for Mac. After a while it will reappear though.

It's definitely possible that dropbox syncing interferes with Docker for Mac (e.g. if it locks files); do the logs show anything useful?

**Comment by thaJeztah** [comment]
closing as stale
