### ISSUE TITLE
RFC docker cp from local to remote can be working like rsync

### ISSUE THREAD

**Issue by netroby** [docker/cli#1367]
The current docker cp(include docker build [ which contains cp action]) using `tar ` to copy file from local to remote .

I tested with my location machine (China), connect to remote server (  Location France ), The network ttl > 360ms, and not very stable.
When i try to build a Dockerfile, COPY file always failed. Due to the network lags, or not stable network .
So i request docker cp working like rsync ( it can transfer files at the last broken point. not just begin from zero)

**Comment by AkihiroSuda** [comment]
w.r.t. `docker build` this is already implemented in BuildKit mode (or `--stream` with legacy builder)

**Comment by AkihiroSuda** [comment]
@tonistiigi @cpuguy83 @dmcgowan 

Can we have `docker cp --diffcopy` using https://github.com/tonistiigi/fsutil ?
Probably useful for fetching build artifact from an image to a local filesystem.

(and we should also allow `docker image cp IMAGE SRCPATH TARGETPATH`)
