### ISSUE TITLE
[Feature Request] Allow container to detach itself from host

### ISSUE THREAD

**Issue by jazzdelightsme** [docker/cli#1384]
When attached to a container, you can use the special keystrokes <kbd>ctrl-p</kbd> <kbd>ctrl-q</kbd> (by default) to detach from it. The `hijackedIOStreamer` is what watches for these `escapeKeys` (byte values [16 and 17][1], by default) to come in through stdin.

What if the container itself could detach the host TTY? That is, instead of the user sending bytes 16 and 17 in through stdin, the container could send bytes 16 and 17 through its stdout, and cause the detach?

When combined with #1383, this would allow you to create a "hybrid shell" experience, where you could be working in a local shell, send a command to the remote shell (running in the container), which would run the command interactively (allowing <kbd>ctrl-c</kbd>, for instance), and then automatically return control to the host shell.

Example (let's suppose #1383 is implemented with a switch called `--tty-input`, and this feature request is implemented with `--allow-self-detach`):

```powershell
function RunThingInContainer( $containerName )
{
    $detachKeys = @( [char] 16, [char] 17 )

    $containerCmd = "echo `"Running in the container... PWD is `$PWD`" ; echo $detachKeys"

    docker attach $containerName `
                  --allow-self-detach `
                  --tty-input $containerCmd
}
```

Mockup:

```
PS C:\src\thing> RunThingInContainer thirsty_wright

Running in the container... PWD is /

PS C:\src\thing> # (I'm back in the host here)
```

[1]: https://github.com/docker/cli/blob/ae1618713f83e7da07317d579d0675f578de22fa/cli/command/container/hijack.go#L20

**Comment by thaJeztah** [comment]
closing as stale
