### ISSUE TITLE
Document 'rollback' for 'update_config.failure_action' in docker compose

### ISSUE THREAD

**Issue by amegianeg** [docker/cli#141]
https://github.com/moby/moby/pull/31108 introduced support for a "rollback" failure action but the documentation does not show it.

**Comment by thaJeztah** [comment]
There's actually another issue; the docker-compose file currently doesn't seem to support the new flags that were added;

```
--rollback-delay
--rollback-failure-action
--rollback-max-failure-ratio
--rollback-monitor
--rollback-parallelism
```

those should probably be added

/cc @dnephin @vdemeester

**Comment by thaJeztah** [comment]
looks like we had an issue in moby/moby for this; let me link it here https://github.com/moby/moby/issues/32585

**Comment by neersighted** [comment]
Looks like this was solved in the intermediate period: https://docs.docker.com/compose/compose-file/compose-file-v3/#rollback_config
