### ISSUE TITLE
[RFC] Add "docker service rollback" subcommand

### ISSUE THREAD

**Issue by thaJeztah** [docker/cli#142]
docker 1.13 added a `--rollback` flag to `docker service update` (https://github.com/moby/moby/pull/26421) to allow manually rolling back a service to a previous version.

This flag cannot be combined with other flags on the `service update` subcommand, which is confusing (https://github.com/moby/moby/issues/33444)

Looking at this functionality, I think this flag is essentially a subcommand "disguised" as a flag, and I suggest to add a `rollback` subcommand;

    docker service rollback <service-name|service-id>

which would be the equivalent of

    docker service update --rollback <service-name|service-id>

Given that this functionality is already present in the API, this can be implemented as a cli-only change.

ping @aaronlehmann @dnephin @tiborvass

**Comment by aaronlehmann** [comment]
It used to be possible to combine --rollback with other flags.

Now that it isn't, I'm fine with adding the subcommand.

**Comment by dnephin** [comment]
SGTM
