### ISSUE TITLE
Docker stuck while download and ran a corrupted image after rebuild.

### ISSUE THREAD

**Issue by Kuinox** [docker/cli#1471]
**Description**
Docker stuck while download and ran a corrupted image after rebuild.  
I thought the problem was coming for my script, while it was a corrupted image.

**Steps to reproduce the issue:**
1. Ran a docker build, with an image I don't have: "microsoft/dotnet:2.1-sdk-bionic"
2. Download got stuck while downloading. (Could be network failure, but no resume/failing/error after reconnecting to the network, just stuck)
3. Stopped download and relaunched the build.  
**Describe the results you received:**
The build didn't attempt to re download(or i didn't seen it, odd because i got a slow network) the image that it failed to download previously.
The build failed later because dotnet core crashed because of an empty file in dotnet install.

Re ran the same script on another machine: 
Build without problem, the empty file causing issue was not empty.

**Describe the results you expected:**
Docker don't start the corrupted image, re-download it, or warn the user about the corrupted image.

**Output of `docker version`:**

```
PS C:\Users\Kuinox> docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:34 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 25
 Running: 0
 Paused: 0
 Stopped: 25
Images: 40
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.93-linuxkit-aufs
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: linuxkit-00155d3c1003
ID: EXBH:6TMG:QOWD:CAPA:PVFR:JSHS:ISHT:54RB:AYP6:VYME:7A3Q:P43N
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 22
 Goroutines: 47
 System Time: 2018-10-22T08:10:32.6686563Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
Do you have any daemon logs from when this happened? I'm curious what happened here, because images are validated after download completes, so no "partially downloaded" images should be present in the local cache (either they're there, or they're not, but not partially).

/cc @tonistiigi
