### ISSUE TITLE
HTTP status: 503 Service Unavailable

### ISSUE THREAD

**Issue by francesco2013** [docker/cli#1491]
Hello,

All of a sudden I am receiving this message when using docker build:

Step 1/37 : FROM ubuntu:14.04
Get https://registry-1.docker.io/v2/library/ubuntu/manifests/14.04: received unexpected HTTP status: 503 Service Unavailable

Anybody experiencing the same ? What the hell is going on ?

**Comment by felixPG** [comment]
Yes
I have the same result, there is a problem with dockerhub

https://status.docker.com/

**Comment by felixPG** [comment]
working for me now!

**Comment by francesco2013** [comment]
works for me as well now

**Comment by thaJeztah** [comment]
Looks like there was a temporary issue with Docker Hub; let me close
