### ISSUE TITLE
make the ping timout for notary/trust configuraable

### ISSUE THREAD

**Issue by nicolaka** [docker/cli#1494]
**Description**
 
In low-bandwidth environment, the 5s ping timeout(https://github.com/docker/cli/blob/master/cli/trust/trust.go#L134) is causing failures to communicate with server and sign images using notary . By changing the timeout to 30s, we were able to resolve this problem. But wondering if we can make it configurable? or is it better to just increase it to something more reasonable like 30s?

Thanks,

**Output of `docker version`:**

```

root @ ~  [6] 🐳  → docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:24:56 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```

**Comment by nicolaka** [comment]
https://github.com/docker/voc/issues/335

**Comment by bsousaa** [comment]
We have no plans to make changes in this area at the moment. I'm closing this issue for now but we may reconsider in the future.
