### ISSUE TITLE
Memo per image

### ISSUE THREAD

**Issue by QwertyZW** [docker/cli#153]
I wasn't sure where to open this feature request, it might be more appropriately placed in moby/*

I'd like the ability to add a comment/description to new image layers on every commit. Something like a commit message in a versioning system.

So I should be able to do something like
```
docker commit <running_container> <image_to_be_saved> -m "This new layer adds <thing1> and <thing2>
```

and when I do something like 
```
docker image <name> log
```

I would be able to see my commit messages.

**Comment by dnephin** [comment]
That already exists. `docker commit -m "msg"`.

They can be viewed using `docker history <image>`

Going to close this issue, but let me know if that doesn't work for some reason.
