### ISSUE TITLE
dns_option missing from compose schema

### ISSUE THREAD

**Issue by ps-jay** [docker/cli#1557]
**`dns_option` missing from the schema for compose**

As discussed in https://github.com/docker/compose/issues/5010#issuecomment-445732874, in order for Docker Compose to support an option provided by `docker run`, it needs to be added to the compose schema in this repository.

Could that be done, so that we may use the functionality to provide DNS options when using Docker Compose?

**Steps to reproduce the issue:**
1. Observe that `dns` and `dns_search` are in the [schemas](https://github.com/docker/cli/tree/master/cli/compose/schema/data), but `dns_option` is not

**Describe the results you received:**
n/a

**Describe the results you expected:**
n/a

**Additional information you deem important (e.g. issue happens only occasionally):**
n/a

**Output of `docker version`:**
n/a

**Output of `docker info`:**
n/a

**Additional environment details (AWS, VirtualBox, physical, etc.):**
n/a

**Comment by Marco01809** [comment]
Any update on this? dns_opt is still desperately needed to work around gliderlabs/docker-alpine/issues/255

This option was supported perfectly fine in in docker-compose V2: https://docs.docker.com/compose/compose-file/compose-file-v2/#dns_opt, but has gone missing in V3 for no apparent reason.

Relates issues: docker/compose#6680, docker/compose#5010

**Comment by jbkoh** [comment]
I'm pinging this thread as it's already 2 years old.

**Comment by ndeloof** [comment]
Compose file format is now manage as part of the compose specification, feel free to open an issue and discuss defining this attribute http://github.com/compose-spec/compose-spec/issues 
Then we can add support into docker/compose-cli
