### ISSUE TITLE
Link not found in the doc experimental/checkpoint-restore.md

### ISSUE THREAD

**Issue by bharathappali** [docker/cli#1563]
A link in the file [experimental/checkpoint-restore.md](https://github.com/docker/cli/blob/master/experimental/checkpoint-restore.md) is not found. I really don't know if its important to be updated. Just raising the issue to notify.

The Line in first paragraph :  `A good overview of the history of checkpoint and restore in Docker is available in this Kubernetes blog post.`

The [Kubernetes blog post link](https://kubernetes.io/2015/07/how-did-quake-demo-from-dockercon-work.html) is showing page not found. So it would be helpful if its replaced with something which is available. 

Thanks!

**Comment by albers** [comment]
Thanks for reporting. Fixed in #1592.
