### ISSUE TITLE
[Feature request] Copy/Extract files from docker image to host

### ISSUE THREAD

**Issue by dhanvi** [docker/cli#1568]
Copying/Extracting files from docker images to host is a feature that we heavily depend on.

We are currently starting a container copying files using `docker cp`, there are also packages like https://github.com/larsks/undocker/ 

It would be nice to have this feature in docker cli

**Comment by thaJeztah** [comment]
Going through old tickets; can you provide some use-cases how you would use this feature?

**Comment by dhanvi** [comment]
@thaJeztah the current workaround is to start a container from the image with a volume, override the entry point, and copy the files to the volume.

Having an inbuilt command to copy something like `docker cpi` makes life easier.


Related tickets and links:
* https://github.com/moby/moby/issues/38366
* https://github.com/moby/moby/issues/38197
* https://medium.com/@cyril.delmas/how-to-keep-the-build-reports-with-a-docker-multi-stage-build-on-jenkins-507200f4007f

**Comment by thaJeztah** [comment]
Thanks, so mostly looking at what flows you need the functionality for. While implementing a `docker cpi` (and/or `docker image cp`) command would be _possible_, it's always good to look at "how" and "what for" will it be used.


If this is to (e.g.) copy build-artifacts out of an image, then there's already options with BuildKit enabled.

In the example below, the multi-stage build has a stage that collects the build-artifacts in an empty (scratch) image. BuildKit allows you to copy files to your host (but (currently) only allows _all_ files to be copied, so it's important to have _only_ those files (not the files from the base image itself (alpine in this case));  

```dockerfile
# syntax=docker/dockerfile:1

FROM alpine AS build
WORKDIR /app/release
RUN echo "I am an artifact" > some-file.txt
RUN echo "I am another artifact" > some-other-file.txt

# collect build artifacts in an empty (scratch) image
FROM scratch AS artifacts
COPY --from=build /app/release /
```

Build the `artifacts` stage of the Dockerfile; note that (in this case) the build is not tagged, and no actual image is produced, but the `--output` option copies the files from the build to a local directory (`./out`).

```bash
docker build --output=./out --target=artifacts .
```

Running the above;

```bash
docker build --output=./out --target=artifacts .
[+] Building 2.9s (13/13) FINISHED
 => [internal] load .dockerignore                                                                                                0.0s
 => => transferring context: 2B                                                                                                  0.0s
 => [internal] load build definition from Dockerfile                                                                             0.0s
 => => transferring dockerfile: 279B                                                                                             0.0s
 => resolve image config for docker.io/docker/dockerfile:1                                                                       1.5s
 => [auth] docker/dockerfile:pull token for registry-1.docker.io                                                                 0.0s
 => CACHED docker-image://docker.io/docker/dockerfile:1@sha256:d2d74ff22a0e47b21f4bbde337e2ac4cd0a02a2226ef79264878db3dc7e87df8  0.0s
 => => resolve docker.io/docker/dockerfile:1@sha256:d2d74ff22a0e47b21f4bbde337e2ac4cd0a02a2226ef79264878db3dc7e87df8             0.0s
 => [internal] load metadata for docker.io/library/alpine:latest                                                                 0.3s
 => [auth] library/alpine:pull token for registry-1.docker.io                                                                    0.0s
 => CACHED [build 1/4] FROM docker.io/library/alpine@sha256:f271e74b17ced29b915d351685fd4644785c6d1559dd1f2d4189a5e851ef753a     0.0s
 => => resolve docker.io/library/alpine@sha256:f271e74b17ced29b915d351685fd4644785c6d1559dd1f2d4189a5e851ef753a                  0.0s
 => [build 2/4] WORKDIR /app/release                                                                                             0.0s
 => [build 3/4] RUN echo "I am an artifact" > some-file.txt                                                                      0.4s
 => [build 4/4] RUN echo "I am another artifact" > some-other-file.txt                                                           0.3s
 => [artifacts 1/1] COPY --from=build /app/release /                                                                             0.0s
 => exporting to client                                                                                                          0.0s
 => => copying files 152B                                                                                                        0.0s
```

After the build completes; the files are in the `out` directory;

```
tree .
.
├── Dockerfile
└── out
    ├── some-file.txt
    └── some-other-file.txt

1 directory, 3 files
```

**Comment by dhanvi** [comment]
@thaJeztah here is how typically every application build works

```
FROM eclipse-temurin:8-jdk-alpine AS build
WORKDIR /app/release
RUN echo "I am test result" > test-result.xml
RUN echo "I am the final jar" > app.jar

FROM eclipse-temurin:8-jre-alpine
WORKDIR /app/release
COPY --from=build /app/release/app.jar .
```

What is the current best way to get `test-result.xml` to the host?

I was trying to do this cleanly so created all these feature requests 😄

**Comment by dhanvi** [comment]
IMO `docker cpi` or `docker image cp` would also be useful to extract artifacts out of the image that is already built.

**Comment by sam-thibault** [comment]
Some related discussions and suggestions on how to do this:
- https://github.com/moby/buildkit/issues/1421

**Comment by sam-thibault** [comment]
I think this discussion is wrapped up (based on the 👍 ), so I will close this issue.
