### ISSUE TITLE
Unable quiet message in images argument

### ISSUE THREAD

**Issue by WHK102** [docker/cli#1570]
I canot hide the error message from docker:

`docker images -a -q -f since=foooooooooo > /dev/null`

The response is: Error response from daemon: No such image:...

**Comment by thaJeztah** [comment]
You need to redirect `stderr`, not `stdout`;

```
docker images -a -q -f since=foooooooooo 2> /dev/null
```

See https://serverfault.com/questions/41964/how-to-hide-the-output-of-a-shell-application-in-linux


closing this issue because this is not a bug, but feel free to continue the conversation
