### ISSUE TITLE
fast context switching

### ISSUE THREAD

**Issue by andrewhsu** [docker/cli#1586]
This issue is to track a new feature to store credentials to connect to different clusters and quickly switch from one to the other. Inspired by [kubectl context](https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/). This will allow a user to quickly switch between different `DOCKER_HOST` and kubernetes endpoints as well as other endpoints in the future.

Will bring a new subcommand that will look like:
```
$ docker context --help

Usage:  docker context COMMAND

Manage contexts

Management Commands:
  set         Modify an existing context

Commands:
  create      Create a context
  export      Export a context
  import      Import a context
  ls          List contexts
  rm          Remove one or more contexts
  use         Set the current docker context

Run 'docker context COMMAND --help' for more information on a command.
```

Older PR to moby for reference: https://github.com/moby/moby/pull/38148

- [x] foundation changes to docker/cli https://github.com/docker/cli/pull/1500
- [x] docker cli ui changes https://github.com/docker/cli/pull/1501
- [x] tests TBD
- [ ] documentation TBD
- [x] completion #1619

**Comment by simonferquel** [comment]
First checkbox can now be checked. #1500 is validated and closed in favor of #1501

**Comment by simonferquel** [comment]
#1501 now brings tests to the high level commands

**Comment by albers** [comment]
@simonferquel I'll add the completion after the feature is merged.

**Comment by simonferquel** [comment]
Ok thanks @albers

**Comment by albers** [comment]
@simonferquel bash completion is done, see #1619

**Comment by theycallmemac** [comment]
@andrewhsu is this just awaiting documentation?

**Comment by theycallmemac** [comment]
@andrewhsu if this is just awaiting docs I can help

**Comment by thaJeztah** [comment]
Looks like this is done
