### ISSUE TITLE
Missing documentation for `--config*` flags for `docker service ...`

### ISSUE THREAD

**Issue by jlhawn** [docker/cli#159]
The current repo doesn't document how to use the `--config` flag when running `docker service create ...`   nor does it document how to use either the `--config-rm` or `--config-add` flags when running `docker service update ...`.

Links:

- [Documentation for `docker service create`](https://github.com/docker/cli/blob/master/docs/reference/commandline/service_create.md)
- [Documentation for `docker service update`](https://github.com/docker/cli/blob/master/docs/reference/commandline/service_update.md)

**Comment by thaJeztah** [comment]
The flags were added to the reference docs in https://github.com/docker/cli/pull/403, and this section of the documentation handles using configs; https://docs.docker.com/engine/swarm/configs/

Closing this one, but some additional information in the command line reference docs could still be needed
