### ISSUE TITLE
Add option to warm build cache for --cache-from when building images

### ISSUE THREAD

**Issue by corneliusweig** [docker/cli#1597]
**Description**

When building images in a CI environment, the `--cache-from` flag allows to add images to consider as cache source for the current build. However, when the images are not yet present on that machine, docker will silently ignore the cache directive and do a full rebuild. A workaround is to do a `docker pull` of the cache-provider images before executing the build. Then the caching works as expected.

However, this is cumbersome and can easily be overlooked. I wonder why the CLI doesn't always try to pull cache-provider images upfront if the referenced cache-provider images are missing. Maybe there's a good reason for that. In that case, would it be possible to add a build option to automatically warm the image cache by pulling missing cache-provider images when executing the build?

**Comment by corneliusweig** [comment]
I have a hunch that this will be superseded by 19.3. Is that correct?

**Comment by radix** [comment]
my question is: why do we even need to pass `--cache-from`? Why can't docker just look in all local images for caches? If it did, we would still only need to remember one thing, and it would be "pull all the images you want to be able to cache from before you build".

**Comment by tonistiigi** [comment]
Building with buildkit doesn't require images to be pre-pulled. The matched layers are pulled automatically during build and rest is ignored.

**Comment by corneliusweig** [comment]
Thanks for clarifying this!
