### ISSUE TITLE
ps: Don’t abbreviate commands

### ISSUE THREAD

**Issue by mcandre** [docker/cli#1601]
Please show the full command on `ps [-a]`, so that it is easier to find out exactly what is running

**Comment by thaJeztah** [comment]
It's truncated by default, but you can use `docker ps -a --no-trunc` to disable truncating, and you'll see the full command.

See https://docs.docker.com/engine/reference/commandline/ps/#usage


I'll close this ticket, because this is already possible, but feel free to continue the conversation

**Comment by mcandre** [comment]
Is this configurable by a text file? I'm not sure I could write an alias for this, that wouldn't conflict with non-ps docker commands.
