### ISSUE TITLE
Docker manifest push ignoring --insecure

### ISSUE THREAD

**Issue by stephencsnow** [docker/cli#1631]
**Description**

When attempting to push a manifest to an insecure registry, the command fails, indicating an issue with the registry server giving an HTTP response to a HTTPS client. The documentation states that passing the `--insecure` flag into the push command should fix this, but it does nothing.

**Steps to reproduce the issue:**
1. Create a manifest via `docker manifest create --insecure 192.168.0.20:5000/my-img:latest 192.168.0.20:5000/my-img-arm:latest 192.168.0.20:5000/my-img-x86:latest`
2. Annotate the manifest via `docker manifest annotate 192.168.0.20:5000/my-img:latest 192.168.0.20:5000/my-img-arm:latest --arch arm`
3. Attempt to push manifest via `docker -D manifest push --insecure 192.168.0.20:5000/my-img:latest`

**Describe the results you received:**

```
DEBU[0000] hostDir: /etc/docker/certs.d/192.168.0.20:5000 
DEBU[0000] hostDir: /etc/docker/certs.d/192.168.0.20:5000 
DEBU[0000] hostDir: /etc/docker/certs.d/192.168.0.20:5000 
DEBU[0000] hostDir: /etc/docker/certs.d/192.168.0.20:5000 
DEBU[0000] hostDir: /etc/docker/certs.d/192.168.0.20:5000 
DEBU[0000] hostDir: /etc/docker/certs.d/192.168.0.20:5000 
DEBU[0000] hostDir: /etc/docker/certs.d/192.168.0.20:5000 
DEBU[0000] hostDir: /etc/docker/certs.d/192.168.0.20:5000 
failed to configure transport: error pinging v2 registry: Get https://192.168.0.20:5000/v2/: http: server gave HTTP response to HTTPS client
```
This is the same exact result as when running without `--insecure`.

**Describe the results you expected:**

The manifest push succeeds.

**Additional information you deem important (e.g. issue happens only occasionally):**

I was having issues with `manifest create` as well until I updated my docker from 18.0.6 to 18.0.9. Docker pull/push with this insecure registry works fine.

**Output of `docker version`:**

```
Client:
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:35:31 2019
 OS/Arch:           linux/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:02:44 2019
  OS/Arch:          linux/amd64
  Experimental:     true
```

**Output of `docker info`:**

```
Containers: 64
 Running: 24
 Paused: 0
 Stopped: 40
Images: 1149
Server Version: 18.09.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 96ec2177ae841256168fcf76954f7177af9446eb
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-43-generic
Operating System: Ubuntu 18.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 31.33GiB
Name: my-server
ID: DVZR:G3ZK:DAL5:BUHT:IG3J:LL5R:ITDH:UMCI:WM3Y:KI3X:ERXF:XTKQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 192.168.0.20:5000
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

The registry is hosted on the same server that I am attempting to push the manifest from. The registry was version 2.6.2 (didn't work), so I updated to 2.7.1 and the bug remains.
Registry hash:
```
$ docker container inspect registry | jq .[0].Image
"sha256:116995fd662403e7ac3fd9dd698f95a7f9c8c3c321aa34cb7090a8721d68573a"
```

**Comment by stephen-snow** [comment]
I think I found the problem. My insecure registry was [using plain HTTP](https://docs.docker.com/registry/insecure/#deploy-a-plain-http-registry). I switched over to [using self-signed certs](https://docs.docker.com/registry/insecure/#use-self-signed-certificates) with TLS and tried the push again and it succeeded.

Perhaps the documentation should be updated for `manifest` so that it indicates that using an insecure registry with HTTP does not work? If this behavior is expected, then the issue can be closed.

To clarify, I tried running with and without `--insecure` with the self-signed certs and got the following:

```
$ docker -D manifest push --insecure 192.168.0.20:5000/my-img:latest
DEBU[0000] hostDir: /etc/docker/certs.d/192.168.0.20:5000 
DEBU[0000] crt: /etc/docker/certs.d/192.168.0.20:5000/ca.crt 
DEBU[0000] hostDir: /etc/docker/certs.d/192.168.0.20:5000 
DEBU[0000] crt: /etc/docker/certs.d/192.168.0.20:5000/ca.crt 
DEBU[0000] hostDir: /etc/docker/certs.d/192.168.0.20:5000 
DEBU[0000] crt: /etc/docker/certs.d/192.168.0.20:5000/ca.crt 
DEBU[0000] hostDir: /etc/docker/certs.d/192.168.0.20:5000 
DEBU[0000] crt: /etc/docker/certs.d/192.168.0.20:5000/ca.crt 
DEBU[0000] hostDir: /etc/docker/certs.d/192.168.0.20:5000 
DEBU[0000] crt: /etc/docker/certs.d/192.168.0.20:5000/ca.crt 
DEBU[0000] hostDir: /etc/docker/certs.d/192.168.0.20:5000 
DEBU[0000] crt: /etc/docker/certs.d/192.168.0.20:5000/ca.crt 
DEBU[0000] hostDir: /etc/docker/certs.d/192.168.0.20:5000 
DEBU[0000] crt: /etc/docker/certs.d/192.168.0.20:5000/ca.crt 
DEBU[0000] hostDir: /etc/docker/certs.d/192.168.0.20:5000 
DEBU[0000] crt: /etc/docker/certs.d/192.168.0.20:5000/ca.crt 
sha256:f3abc58ccaa272340044a2792e1d6d0f352900ccb951b94c2329c6c88daf4c4f
```

```
$ docker -D manifest push 192.168.0.20:5000/my-img:latest
DEBU[0000] hostDir: /etc/docker/certs.d/192.168.0.20:5000 
DEBU[0000] crt: /etc/docker/certs.d/192.168.0.20:5000/ca.crt 
DEBU[0000] hostDir: /etc/docker/certs.d/192.168.0.20:5000 
DEBU[0000] crt: /etc/docker/certs.d/192.168.0.20:5000/ca.crt 
DEBU[0000] hostDir: /etc/docker/certs.d/192.168.0.20:5000 
DEBU[0000] crt: /etc/docker/certs.d/192.168.0.20:5000/ca.crt 
DEBU[0000] hostDir: /etc/docker/certs.d/192.168.0.20:5000 
DEBU[0000] crt: /etc/docker/certs.d/192.168.0.20:5000/ca.crt 
DEBU[0000] hostDir: /etc/docker/certs.d/192.168.0.20:5000 
DEBU[0000] crt: /etc/docker/certs.d/192.168.0.20:5000/ca.crt 
DEBU[0000] hostDir: /etc/docker/certs.d/192.168.0.20:5000 
DEBU[0000] crt: /etc/docker/certs.d/192.168.0.20:5000/ca.crt 
DEBU[0000] hostDir: /etc/docker/certs.d/192.168.0.20:5000 
DEBU[0000] crt: /etc/docker/certs.d/192.168.0.20:5000/ca.crt 
DEBU[0000] hostDir: /etc/docker/certs.d/192.168.0.20:5000 
DEBU[0000] crt: /etc/docker/certs.d/192.168.0.20:5000/ca.crt 
failed to put manifest 192.168.0.20:5000/my-img:latest: Put https://192.168.0.20:5000/v2/my-img/manifests/latest: x509: cannot validate certificate for 192.168.0.20 because it doesn't contain any IP SANs
```

**Comment by clauderobi** [comment]
This ticket https://github.com/docker/cli/issues/1358#issue-358534205 was also having a similar issue and apparently was fixed.

docker create do honour --insecure,  as it succeeds at getting info from the registry for the non-local images. 

So, this behaviour with push is wrong; based on the subcommands, it does not appear that the intent is to only work with TLS protected registry (self signed or CA signed).

**Comment by Iridescens** [comment]
Can confirm what @clauderobi said:
`14:54:43 someserv.localdomain dockerd[1041]: time="2019-11-26T14:54:43.044288160+03:00" level=debug msg="Calling POST /v1.39/images/<registry_FQDN>/root/test-project-1-pue/mybusybox/push?tag="
14:54:43 someserv.localdomain dockerd[1041]: time="2019-11-26T14:54:43.044535183+03:00" level=debug msg="Trying to push <registry_FQDN>/root/test-project-1-pue/mybusybox to https://<registry_FQDN> v2"
14:54:43 someserv.localdomain dockerd[1041]: time="2019-11-26T14:54:43.048433256+03:00" level=debug msg="Pushing repository: <registry_FQDN>/root/test-project-1-pue/mybusybox:latest"
14:54:43 someserv.localdomain dockerd[1041]: time="2019-11-26T14:54:43.048823589+03:00" level=debug msg="Checking for presence of layer sha256:1da8e4c8d30765bea127dc2f11a17bc723b59480f4ab5292edb00eb8eb1d96b1 (sha256:0f8c40e1270f10d085dda8ce12b7c5b17cd808f055df5a7222f54837ca0feae0) in <registry_FQDN>/root/test-project-1-pue/mybusybox"
14:54:43 someserv.localdomain dockerd[1041]: time="2019-11-26T14:54:43.054664237+03:00" level=debug msg="Skipping non-TLS endpoint http://<registry_FQDN> for host/port that appears to use TLS"`
Notice the **HTTPS** in second line (trying to push), While it is clearly set in insecure-repositories.

**Comment by ndjhartman** [comment]
I believe this is still an issue. With the server listed as an insecure registry on `/etc/docker/daemon.json`, I can push images succesfully:

```docker push ip:5000/image:tag```

But with the manifests:

```
docker -D manifest push --insecure ip:5000/image:latest

 DEBU[0000] hostDir: /etc/docker/certs.d/ip:5000 
 DEBU[0000] hostDir: /etc/docker/certs.d/ip:5000 
 DEBU[0001] hostDir: /etc/docker/certs.d/ip:5000 
 DEBU[0001] hostDir: /etc/docker/certs.d/ip:5000 

failed to configure transport: error pinging v2 registry: Get https://ip:5000/v2/: http: server gave HTTP response to HTTPS client

```
