### ISSUE TITLE
i can't make build docker

### ISSUE THREAD

**Issue by m0o0hammad** [docker/cli#1632]
$ sudo apt-get install git-all
$ sudo apt-get install build-essential
$ git clone https://github.com/docker/docker.git
$ cd docker/
$ mv Dockerfile Dockerfile.backup
$ wget https://gist.githubusercontent.com/prateekgogia/05f058bafbccc2478fcc/raw/1db60ea471678cfb55185215defcf371f7dcec1d/Dockerfile

$ make build
Makefile:129: The docker client CLI has moved to github.com/docker/cli. For a dev-test cycle involving the CLI, run:
 DOCKER_CLI_PATH=/host/path/to/cli/binary make shell 
 then change the cli and compile into a binary at the same location.

docker build    -t "docker-dev:master" -f "Dockerfile" .
/bin/sh: 1: docker: not found
Makefile:129: recipe for target 'build' failed
make: *** [build] Error 127

please help tnx
 $uname -r 
4.9.0-7-686-pae

**Comment by fridel83** [comment]
Hello,

As seen at the line 

> /bin/sh: 1: docker: not found

it's look like you don't have docker installed or the docker binary is not on the PATH.

**Comment by thaJeztah** [comment]
Yes, this doesn't look like a bug; closing
