### ISSUE TITLE
build cli-18.09.1 version shows as 18.09.0-dev

### ISSUE THREAD

**Issue by Rob-Wal** [docker/cli#1667]
build 18.0.9.1 on centos 7.6 with kernel 4.20.7-ml.

[root@Cen-Docker01 cli-18.09.1]$ make -f docker.Makefile binary-windows

The binary package properties and docker-windows-amd64.exe version shows 18.09.0-dev.

Client:
 Version:           18.09.0-dev
 API version:       1.39
 Go version:        go1.10.6
 Git commit:
 Built:             Sun Feb 10 01:06:19 2019
 OS/Arch:           windows/amd64
 Experimental:      false

===================
[root@Cen-Docker01 cli-18.09.1]$ make -f docker.Makefile binary-windows
docker build  -t docker-cli-cross -f ./dockerfiles/Dockerfile.cross .
Sending build context to Docker daemon  38.37MB
Step 1/3 : FROM    dockercore/golang-cross:1.10.6@sha256:2054e793010774e9dbafc808dd550a99f8468013731728bea7fce56681510078
 ---> 6d3d677b448c
Step 2/3 : ENV     DISABLE_WARN_OUTSIDE_CONTAINER=1
 ---> Using cache
 ---> 97cd6307f8d0
Step 3/3 : WORKDIR /go/src/github.com/docker/cli
 ---> Using cache
 ---> 92d78d9413e7
Successfully built 92d78d9413e7
Successfully tagged docker-cli-cross:latest
docker run --rm -e `VERSION=18.09.0-dev` -e GITCOMMIT -e PLATFORM -v "/root/docker-vscode/cli-18.09.1":/go/src/github.com/docker/cli docker-cli-cross make binary-windows
./scripts/build/windows
Generating windows resources
/go/src/github.com/docker/cli/scripts/gen/../winresources/common.rc:11: digit exceeds base
/go/src/github.com/docker/cli/scripts/gen/../winresources/common.rc:12: digit exceeds base
/go/src/github.com/docker/cli/scripts/gen/../winresources/common.rc:11: digit exceeds base
/go/src/github.com/docker/cli/scripts/gen/../winresources/common.rc:12: digit exceeds base
Building build/docker-windows-amd64

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
