### ISSUE TITLE
Service creation with duplicate network name on different scopes (one in local and one in swarm)

### ISSUE THREAD

**Issue by yongtang** [docker/cli#167]
**Description**

In command line `docker service create`, the network name is now converted to network ID then passed to daemon (vs. done in the daemon previously):
https://github.com/docker/cli/blob/ab3ea637b6f6ad766a61117f3040b82e45a59dc0/cli/command/service/opts.go#L348-L360

However, as `convertNetworks` uses `inspect` to do the network name conversion, a duplication error would be returned in case there are multiple network IDs available for the same network name.

In certain situations, it might be possible that there are multiple networks with the same name but with different scope, e.g, one `foo` in local and one `foo` in swarm.

For that I think it makes sense to change the way `convertNetworks` is done so that only networks related to swarm scope are searched.

**Additional information you deem important (e.g. issue happens only occasionally):**

This issue may need to be resolved in order to eventually fix network duplication issue in moby/moby/pull/30897 , moby/moby/issues/33561, moby/moby/issues/30242

**Comment by dnephin** [comment]
Are you proposing to add a parameter to service inspect that allows the user to specify which scope they are inspecting? I think that sounds good.
