### ISSUE TITLE
docker ps/exec performance regression between xenial releases of docker.io

### ISSUE THREAD

**Issue by dgoldstein0** [docker/cli#1673]
**Description**

Recently I have observed slower performance of `docker` commands.

In particular, on the old Xenial docker (http://launchpadlibrarian.net/377343979/docker.io_17.03.2-0ubuntu2~16.04.1_amd64.deb), `docker ps` takes  8-12ms to run when there are no containers running; the slowdown is also there with containers running.

On the new one - http://launchpadlibrarian.net/397758324/docker.io_18.06.1-ubuntu1~16.04.2_amd64.deb, released December 15, 2018 - the same command takes about 50ms more.

I also think that docker exec has about the same slowdown.

Now, why do I care that this is 50ms slower?  If I was just using docker directly, I probably wouldn't, but it's been woven into development tools such that it's part of the workflow that we use to recompile and update our development instances of the dropbox.com website - many engineers run that tool on every minute js or css change they make; the net impact of this regression is between 100 and 200ms on that workflow.

We would appreciate if performance could be restored to previous levels.

**Steps to reproduce the issue:**
1. wget http://launchpadlibrarian.net/397758324/docker.io_18.06.1-ubuntu1~16.04.2_amd64.deb
2. sudo dpkg -i docker.io_18.06.1-ubuntu1~16.04.2_amd64.deb
3. docker ps

**Describe the results you received:**

```
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
$ time docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

real    0m0.064s
user    0m0.060s
sys     0m0.012s
$ time docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

real    0m0.059s
user    0m0.068s
sys     0m0.004s
$ time docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

real    0m0.060s
user    0m0.072s
sys     0m0.004s
$ time docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

real    0m0.060s
user    0m0.064s
sys     0m0.008s
```

**Describe the results you expected:**
installing instead from http://launchpadlibrarian.net/377343979/docker.io_17.03.2-0ubuntu2~16.04.1_amd64.deb we get much faster performance

```
$ time docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

real    0m0.011s
user    0m0.004s
sys     0m0.004s
$ time docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

real    0m0.011s
user    0m0.004s
sys     0m0.004s
$ time docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

real    0m0.011s
user    0m0.000s
sys     0m0.008s
$ time docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

real    0m0.012s
user    0m0.008s
sys     0m0.000s
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Docker version 18.06.1-ce, build e68fc7a
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 5
Server Version: 18.06.1-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version:  (expected: 468a545b9edcd5932818eb9de8e72413e616e86e)
runc version: N/A (expected: 69663f0bd4b60df09991c08812a60108003fa340)
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-140-generic
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.67GiB
Name: dgoldstein-dbx
ID: DDDR:ZCXW:VSR6:FIEZ:FQ22:GSHZ:CEHJ:D2DV:4UTD:BCUZ:J33C:6VT7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS ec2 - m4.xlarge (4 cpus, 16GB ram)

**Comment by bsousaa** [comment]
It looks like this issue went stale. Let me close it for now. Feel free to comment and we can re-open if we have more info.

**Comment by dgoldstein0** [comment]
it looks like it's improved a bit since I last filed, though I'm now running on better hardware (m5.2xlarge) on ubuntu 20, and typically see ~25-30ms for docker ps.  so don't know if the software improved or this is a consequence of my hardware improving.

**Comment by thaJeztah** [comment]
@dgoldstein0 thanks for the update; given that Docker uses a client/server architecture (`docker ps` is the client, which will make an API call to the daemon to get the containers), it may also be worth comparing without the CLI itself involved, e.g. using `curl` to get the API response. That would help narrowing down if the performance differences are client side (`docker` cli) or the daemon API being slower to return the results.

e.g.;

```bash
curl --unix-socket /var/run/docker.sock  http://foo/containers/json
```

**Comment by dgoldstein0** [comment]
How do I determine which url to use for that?
