### ISSUE TITLE
Should cli plugins install to ~/.docker/plugins

### ISSUE THREAD

**Issue by ijc** [docker/cli#1677]
This is part of https://github.com/docker/cli/issues/1661, originally https://github.com/docker/cli/pull/1564#discussion_r251819147.

> Also for a follow-up bike-shed; wondering if we should change the path to just ~/.docker/plugins (as the daemon won't install plugins in this location, so there should be no real ambiguity there)

In isolation it seems like a sensible suggestion, but there is the global path to consider too, which is (from `docs/extend/cli_plugins.md):

> Plugins distributed in packages for system wide installation on
> Unix(-like) systems should be installed in either
> `/usr/lib/docker/cli-plugins` or `/usr/libexec/docker/cli-plugins`
> depending on which of `/usr/lib` and `/usr/libexec` is usual on that
> system. System Administrators may also choose to manually install into
> the `/usr/local/lib` or `/usr/local/libexec` equivalents but packages
> should not do so.

I think in that context there is a greater possibility of confusion with daemon plugins (even if it goes nowhere near anything like those paths, they are not so unambiguous when they are in `/usr`).

I think the name `cli-plugins` is the lesser evil compared with having the per-user and per-system directories have different names, so we should leave it alone but I'm happy to be guided by the maintainers.

/cc @thaJeztah @silvin-lubecki @vdemeester (who else?) WDYT? Happy to raise a PR with the change if that is your consensus.

**Comment by thaJeztah** [comment]
Discussing with @ijc on Slack, and indeed, in a situation where the daemon and cli are both installed on the same host, using just `plugins` will make things more confusing, so I agree that we should not change

**Comment by silvin-lubecki** [comment]
I think the more obvious it is, the less issues we'll have with cli plugins. So I'm fine with keeping things as-is 👍

**Comment by cpuguy83** [comment]
Don't forget rootless mode. Supporting cli plugins totally from a user home directory is definitely a boon here.
