### ISSUE TITLE
`label` filter for `docker system prune` ignored by non-recent Docker hosts

### ISSUE THREAD

**Issue by aduermael** [docker/cli#17]
`label` filter for `docker system prune` (and others like `docker container prune`) has been added in that commit: https://github.com/moby/moby/commit/702524732427ce028277f99f215e1fab297e6001

But using it targeting non-recent Docker hosts may be dangerous has this filter is not even considered. 

It leads to situations like this one:

```shell
$ docker create --label foo=bar redis
5fb69165f8069420f34117c7ec1bc62b55c56cf1f9d9c148188bab1814b3d859
$ docker container prune --filter label=foo=nope
WARNING! This will remove all stopped containers.
Are you sure you want to continue? [y/N] y
Deleted Containers:
5fb69165f8069420f34117c7ec1bc62b55c56cf1f9d9c148188bab1814b3d859
```

The CLI should display return an error when using that filter if remote API version to **1.29**.

**Comment by thomassuckow** [comment]
Just updated to docker for mac 17.12.0-ce-mac49 and got bit by this.

Seems like if a filter option is provided that isn't understood by the engine it should be fatal and would prevent these kinds of issues in the future if more filter options are provided.
