### ISSUE TITLE
[RFC] Strip "Error response from daemon:" prefix

### ISSUE THREAD

**Issue by thaJeztah** [docker/cli#170]
**Description**

Whenever an error is coming from the "daemon", we prefix error messages with "Error response from daemon".

I realise this could help "us" quickly determine where the client is coming from (although in most cases, we probably know), the prefix doesn't add much for the user, and in fact may make the information that _is_ important to them less visible.

We're also not consistent; some messages have the prefix, but others don't

```bash
$ docker inspect nosuchthing
[]
Error: No such object: nosuchthing


$ docker network create -d blablabla foo
Error response from daemon: legacy plugin: plugin not found
```

**Describe the results you expected:**

I suggest to remove/strip the `Error response from daemon:` and just print the error message that was returned (or a friendlier message generated in the CLI)

**Comment by dnephin** [comment]
I think there is value in understanding where the error is coming from. "from daemon" is probably not the right term, so we should change that part to something more meaningful. "from server", "from api" ?

**Comment by thaJeztah** [comment]
Idk, perhaps we should look at errors individually, but from a UX perspective, there's many examples where it doesn't really matter I guess. Sometimes errors are wrapped three times (error response from daemon: error while doing something: something was not found).

Perhaps logging such errors would be useful, but printing a more user-friendly message.

**Comment by aaronlehmann** [comment]
I don't think `Error response from daemon` is so bad, but the messages get very messy when the error returned by the daemon have a lot of unnecessary prefixes.

For example, trying to run a binary that doesn't exist:

```
docker: Error response from daemon: oci runtime error: container_linux.go:262: starting container process caused "exec: \"mozilla\": executable file not found in $PATH".
```

There are so many `:`s in that message, and most of it isn't useful. The source file and line number is the most egregious part - that's absolutely no help to the user and makes it look like something is wrong internally. And we have a quoted string with backslash-escaped characters for no good reason.

I think it should read:

```
docker: Error response from daemon: executable "mozilla" file not found in $PATH.
```

**Comment by sam-thibault** [comment]
This is an old issue.  I will close it as stale.
