### ISSUE TITLE
Can't log in to docker hub while docker desktop is running

### ISSUE THREAD

**Issue by famasya** [docker/cli#1730]
**Description**
I've been running docker flawlessly before, but then I can't pull any images. Apparently, I'm not logged in. When I tried to log in using `docker login` with correct username and password, it returned `Error response from daemon: Get https://registry-1.docker.io/v2/: Service Unavailable`

Then I tried not to quit docker desktop and login again using CLI. It works. I assume there's some conflict between docker desktop and CLI.

**Steps to reproduce the issue:**
1. Install docker desktop for mac
2. Login to docker desktop
3. Run `docker login`
4. Type username & password
5. Got error message

**Describe the results you received:**
Error response from daemon: Get https://registry-1.docker.io/v2/: Service Unavailable

**Describe the results you expected:**
Logged in

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: M7IU:B7IO:34DY:NTWW:575Q:UO6S:5ZMT:YV7C:LMTM:F74D:O3X3:HJKW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 24
 Goroutines: 50
 System Time: 2019-03-12T10:15:06.5301583Z
 EventsListeners: 2
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by kurazsiosif** [comment]
was this ever diagnosed, i have this issue since the latest docker desktop update to version: Docker Desktop 4.36.0 (175267)

**Comment by famasya** [comment]
@kurazsiosif have you debugged your network connection? IIRC, this was caused by particular ISP that blocked DNS to docker host. When I switched provider, everything worked very well
