### ISSUE TITLE
ARG values are not used in RUN commands when using the new style syntax

### ISSUE THREAD

**Issue by valarauca** [docker/cli#1735]
**Description**

`ARG` values are nice as they let you parameterizing your dockerfile, simplifying future configuration changes. A common usage for this is paths, and variables. Where developers may wish to change file locations, or configuration parameters. 

Therefore it seems logical for `ARG` to be used in initialization. 

The error I am experiencing is that `ARG` values are not propagated to `RUN` commands before they are converted into JSON form. 

**Steps to reproduce the issue:**
1. `ARG Hello=World`
2. `RUN [ "echo", ${Hello}]`

**Describe the results you received:**

`docker build` will fail

**Describe the results you expected:**

Most commands eagerly expand `ARG` values, but `RUN` does not appear too. This means that parameterization of `RUN` commands need to be done via a shell like system I.E.:

```
RUN ["/bin/bash", "-c", "echo \"${HELLO}\""]
```

Which defeats the purpose of the new style `RUN` syntax, as everything ends up _within_ a single group of quotes, also it depends on all `ARG` values being propagated to the environment of `RUN`

**PLEASE NOTE**: I am not reporting an issue with **ENVIRONMENT VARIABLES** but **DOCKER ARGUMENTS** which are passed at build time. 

**Output of `docker version`:**

```
Client:
 Version:           18.06.2-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        6d37f41
 Built:             Sun Feb 10 03:47:42 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.2-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       6d37f41
  Built:            Sun Feb 10 03:46:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 49
 Running: 0
 Paused: 0
 Stopped: 49
Images: 401
Server Version: 18.06.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: a592beb5bc4c4092b1b1bac971afed27687340c5 (expected: 69663f0bd4b60df09991c08812a60108003fa340)
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.19.20
Operating System: Debian GNU/Linux buster/sid
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 62.9GiB
Name: 🤫
ID: RTEG:QILB:L4QZ:4LHR:FKMU:26JJ:4U4E:OGL4:SMQK:AYMH:4VNM:WGJ3
Docker Root Dir: 🤫
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 22
 Goroutines: 44
 System Time: 2019-03-13T15:42:38.476389468-07:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 🤫
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
Build-args are used as environment variables for `RUN`, which is the reason they won't work in the `exec`  (JSON) syntax, which is explicitly running without a default shell.

I'm don't think this could be changed without introducing a huge breaking change.

Given that this is around the builder, and the Dockerfile syntax is maintained in the BuildKit repository; perhaps you could open this ticket in that repository for discussion? https://github.com/moby/buildkit/issues

**Comment by valarauca** [comment]
I will because it seems odd that 

```
RUN echo ${HELLO}
```

will work as expected while

```
RUN [ "echo", ${HELLO}]
RUN ["echo", "${HELLO}"]
```

will not. It seems to discourage the easier to parse syntax
