### ISSUE TITLE
Will Docker use dotfiles  in future?

### ISSUE THREAD

**Issue by vastpeng** [docker/cli#1762]
Like `git`, Docker will read dotfiles(like `${XDG_CONFIG/docker/config`)?

why?

It show much information when using `docker ps -a`, but it is not necessary. I want `ID Names Ports` only, so I must input `docker ps --format "table {{.ID}}\t{{.Names}}\t{{.Ports}}"` every time.

Or, is there a better way?

**Comment by silvin-lubecki** [comment]
If I understand correctly your question, I think this documentation might help you https://github.com/docker/cli/blob/ae1618713f83e7da07317d579d0675f578de22fa/man/docker-config-json.5.md
You can configure the `ps format` in your `~/.docker/config.json` file.
I will close this issue, unless you think it was not helpful and then feel free to re-open it 👍
