### ISSUE TITLE
Cannot use template-driver with a docker-compose.yml defined config

### ISSUE THREAD

**Issue by neetle** [docker/cli#1771]
Currently, there is no way to create a `secret` nor `config` with a `template-driver` value within a `docker-compose.yml` without it being external.  

Can we add the `template-driver` field to the `docker-compose.yml` standard for `secret`s and `config`s?

**Comment by dirkschneemann** [comment]
It looks like this will be part of the upcoming `19.03` release: [This PR](https://github.com/docker/cli/pull/1746) is linked in the [release notes](https://github.com/docker/docker-ce/releases/tag/v19.03.0-beta4) of the latest beta version.

**Comment by thaJeztah** [comment]
Yes, this should be implemented in https://github.com/docker/cli/pull/1746

I'll close this ticket, but feel free to continue the conversation
