### ISSUE TITLE
How to start a stopped Docker container with a different command?

### ISSUE THREAD

**Issue by dave-dm** [docker/cli#1786]
I get these results when I do start and exec:

```
$ docker container exec -i my_app echo hello
Error response from daemon: Container 8a64e2f9ee33971a41c18f28dfc519c3ab66f5261ceb01f3397376bf9d9ad565 is not running
$ docker container start -i my_app2 echo hello
you cannot start and attach multiple containers at once
```
Doesn't seem like there's any way to change the command without rebuilding. My apps have multiple different base entry points, like pm2, node, npm. How can I run all these different commands?

**Comment by cpuguy83** [comment]
You cannot change the command on start.
A container is considered exited when the command that was run has exited.
You can start a container and run an additional command inside it with `docker exec`.
You can just start a new container to run your command `docker run my_app echo hello`

The docker CLI thinks that `docker start -i my_app2 echo hello` is trying to start 3 containers, `my_app2`, `echo`, and `hello`.

**Comment by dave-dm** [comment]
> You can just start a new container to run your command `docker run my_app echo hello`

Wouldn't that create hundreds of containers over time when I do `docker container ls -a`? I just want one container with custom commands

**Comment by cpuguy83** [comment]
@dave-dm `docker run --rm` would remove the container immediately on exit.
It depends on what you need as to what to use.

If you want to run a new command in an already *running* container, then `docker exec` is your friend, but otherwise you need to use a new container.

**Comment by dave-dm** [comment]
--rm seems like that might be an acceptable option. What about running a container with "sh" so it stays permanently open and then exec? Is that something people do?

**Comment by cpuguy83** [comment]
It's not unheard of, but also why not just create a new one when you need it?

**Comment by JoshMcCullough** [comment]
> It's not unheard of, but also why not just create a new one when you need it?

It would be helpful at times to get into a failing container and poke around.
