### ISSUE TITLE
Feature: add "docker image export" command

### ISSUE THREAD

**Issue by XVilka** [docker/cli#1796]
It is widely known that Docker supports export of the containers, with squashing it within one layer. But for this you need first to start the container, which can be sometimes very slow, especially if you do this in a bulk. It would be amazing to avoid this step and be able to export the images directly.

**Comment by thaJeztah** [comment]
you mean;

```
docker run --name mycontainer image-with-many-layers
docker export mycontainer ...
```

Note that `docker export` does not preserve the image's information; it exports the container's root filesystem, but any information about the image is lost.

Is there a reason you need to squash all layers _after_ building the image, instead of optimising the build?

**Comment by AkihiroSuda** [comment]
`docker build -o type=local,dest=/path/to/dir` or `docker build -o type=tar,dest=/path/to/file.tar`  works for you? (coming in Docker 19.03)

**Comment by XVilka** [comment]
@AkihiroSuda yes, this can be a solution, thank you!

**Comment by XVilka** [comment]
@thaJeztah I optimize build where possible, but squashing the image helps considerably nevertheless.

**Comment by thaJeztah** [comment]
An alternative could be to "squash" by copying a stage to a `FROM scratch` image;

```Dockerfile
FROM some-image AS build
RUN some steps
RUN some steps

FROM scratch AS squashed
COPY --from=build / /
```

This may require using BuildKit or a version of Docker that has https://github.com/moby/moby/pull/38599 (will be in 19.03, but may be backported to 18.09)

**Comment by bsousaa** [comment]
It looks like this issue went stale. Let me close it for now. Feel free to comment and we can re-open if we have more info.
