### ISSUE TITLE
Reclaimable space for images reported incorrectly by "docker system df"

### ISSUE THREAD

**Issue by Davidian1024** [docker/cli#1798]
**Description**
When I issue the 'docker system df' command it reports that all images are active, yet at the same time it reports 21% of the space is reclaimable.

**Steps to reproduce the issue:**
1. Issue 'docker system df'

**Describe the results you received:**
TYPE                TOTAL               ACTIVE              SIZE                RECLAIMABLE
Images              10                  10                  10.25GB             2.164GB (21%)

**Describe the results you expected:**
I expected to see a situation that seems possible.  My understanding is that the reclaimable space value is based on the number of inactive images, yet all images are reported as active.

**Additional information you deem important (e.g. issue happens only occasionally):**
I have two sets of systems test and prod, I see the same issue on both.

**Output of `docker version`:**

```
Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        6247962
 Built:             Sun Feb 10 04:13:47 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 03:42:13 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 11
 Running: 11
 Paused: 0
 Stopped: 0
Images: 10
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: active
 NodeID: bbjpi8f2k0ibwu8lzhpoizkdw
 Is Manager: false
 Node Address: 10.195.10.42
 Manager Addresses:
  10.195.10.55:2377
  10.195.20.112:2377
  10.195.30.102:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-1010-aws
Operating System: Ubuntu 18.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 62.89GiB
Name: ip-10-195-10-42
ID: FG33:QVSU:NIVG:WXF2:LJZX:QSI5:UTM2:BK6M:NNNZ:RIE5:WRER:SVJD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 com.opentext.optimost.core-ui.testqaops=true
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Environment is AWS

**Comment by bsousaa** [comment]
It looks like this issue went stale. If you can reproduce this issue with a recent version of Docker please open a new issue or comment on this one and we may re-open if we have more info.
