### ISSUE TITLE
docker -H /var/run/docker.sock always fail

### ISSUE THREAD

**Issue by simonferquel** [docker/cli#1801]
**Description**

In master, top level flags are parsed twice. This is not a problem for single value flags, but for lists (such as `-H`), it create duplicate values, which cause issues. As an example, setting `-H` currently breaks the CLI

**Steps to reproduce the issue:**
1. run `docker -H /var/run/docker.sock version`

**Describe the results you received:**

```
Please specify only one -H
```

**Describe the results you expected:**

normal version output

**Output of `docker version`:**

current master

cc @thaJeztah @silvin-lubecki @vdemeester  @ijc

**Comment by thaJeztah** [comment]
possible suspect https://github.com/docker/cli/pull/1722

**Comment by ijc** [comment]
I thing I know what is wrong here, will look at it today

**Comment by ijc** [comment]
Apart from this issue (which I will fix), why is `-H` an array if you can only pass it once?

**Comment by ijc** [comment]
Are you aware of any other list-based global options I could use for an e2e (since if the global `-H` is fixed to not be a list then an e2e test based on it wouldn't be effective any longer...). I don't see any in that `common.go` nor in `cli/cobra.go`

**Comment by thaJeztah** [comment]
hm... no, don't think there's any 🤔

**Comment by ijc** [comment]
OK, nevermind, I'll cope  ;-)
