### ISSUE TITLE
cli-plugins: -H causes plugin to fail

### ISSUE THREAD

**Issue by tonistiigi** [docker/cli#1821]
When running `docker -H unix://foo.sock plugin <cmd>` plugin will error with `unable to resolve docker endpoint: Please specify only one -H`.  `DOCKER_HOST=unix://foo.sock docker plugin <cmd>` works correctly.

@ijc @tiborvass

**Comment by ijc** [comment]
I think this should have been fixed by #1802, which commit did you see this with?

**Comment by ijc** [comment]
ping @tonistiigi can you confirm if this was with a build before or after #1802 was merged?

**Comment by tonistiigi** [comment]
Yes, seems to be working with newer versions. Thanks!
