### ISSUE TITLE
slow after being idle for about 10 seconds (win10)

### ISSUE THREAD

**Issue by philipodev** [docker/cli#1847]
Hi!
When i run any docker cli commands in the console (tried a few) it takes about 10-15 seconds for it to even begin the request IF it has been idle for about 10-20 seconds.
So if i run `docker ps` it takes about 10 seconds for it to process and respond and if i run `docker ps` (or any other command for that matter) within seconds it will respond immediately.

If i use a framework that utilizes the docker api (not cli), every request is processed immediately too. 

Any idea on where i could debug?

Running Docker for Windows (CE) `Docker version 18.09.2, build 6247962` on `Windows 10`.

**Comment by thaJeztah** [comment]
@simonferquel any ideas?
