### ISSUE TITLE
AIX Support 

### ISSUE THREAD

**Issue by Helflym** [docker/cli#1858]
Hi,

I've made a similar issue https://github.com/moby/moby/issues/39159. But people have suggested it would be more appropriate to post it there. 

Now that AIX support has been added to Go toolchain, we might be able to port some Docker packages.
We (my team and I) already know that having the whole Docker environment is impossible on AIX. The daemon isn't compatible with it (at least noone have managed to do it).
However, discussing with elastic/beats community (which are using Docker), it seems that they are some Docker packages which can still be ported on AIX, especially the "client" side which, if I do understand, can be connected to a remote Linux docker with TCP (please do correct me if I'm wrong).

Anyway, before porting the Docker packages like a mad man, I wish to understand a few things:
- is there any other OS where only the client part is available without the daemon ?
 - which packages are needed by the docker client (not all but the main/hardest ones) ?
 - Are you, the community, accepting unfinished port ? This question might be strange but docker/pkg/* might be imported by other Go packages as helpers and thus be must ported for AIX. Or are the whole cli/client packages must be ported in order to have even some +build aix? To sum up, which are the must-have packages ?

We don't know yet, we will do such a port. It's depending on how long it will take, how many people want it, etc. But if you're interesting in having some Docker packages available on AIX, please don't hesitate to reply.

**Comment by bsousaa** [comment]
We currently have no plans in doing this, so we are closing for now.
