### ISSUE TITLE
docker build sometimes hangs on OS X when using buildkit

### ISSUE THREAD

**Issue by tiborvass** [docker/cli#1862]
**Description**
docker build sometimes hangs on OS X when using buildkit.

**Steps to reproduce the issue:**
1.  On OS X
```
$ git clone https://github.com/Azure/aad-pod-identity
$ cd aad-pod-identity
$ i=0; while :; do make image-mic; echo; echo; echo "=== $i ==="; echo; echo; i=$((i+1)); done
```
2.
3.

**Describe the results you received:**
Eventually, (after ~30-50 loops on my machine) docker build hangs indefinitely.

**Describe the results you expected:**
All builds to pass without hanging.

**Additional information you deem important (e.g. issue happens only occasionally):**
Stack traces: https://gist.github.com/tiborvass/a79de558c700c34eab3ea063ac064891

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.0-beta3
 API version:       1.40
 Go version:        go1.12.4
 Git commit:        c55e026
 Built:             Thu Apr 25 19:05:38 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.0-beta3
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.4
  Git commit:       c55e026
  Built:            Thu Apr 25 19:13:00 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc7+dev
  GitCommit:        029124da7af7360afa781a0234d1b083550f797c
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by Billy-** [comment]
Could someone advise how I can track progression on this issue in buildkit, and then consequently in docker? 🙇

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
