### ISSUE TITLE
Add documentation on DOCKER_CONTEXT environment variable

### ISSUE THREAD

**Issue by silvin-lubecki** [docker/cli#1901]
There isn't any mention of the `DOCKER_CONTEXT` environment variable in the documentation nor in the help message.

Linked to #1899

**Comment by bobcowher** [comment]
It looks like this is covered on the "Docker Context" page - https://docs.docker.com/engine/context/working-with-contexts/

Which help message would you like this to show up in? I'm new to this, but I would be happy to take a crack at it.

**Comment by bsousaa** [comment]
It was added in https://github.com/docker/cli/pull/1501 and in the docs https://github.com/docker/cli/blob/c1733165159c08101adb0e1f120c7181533550ef/docs/reference/commandline/cli.md?plain=1#L133
