### ISSUE TITLE
Context import erroneously reports successful import for any tar

### ISSUE THREAD

**Issue by kinghuang** [docker/cli#1920]
**Description**

`docker context import …` succeeds even if the file is not a valid context archive.

**Steps to reproduce the issue:**

```sh
$ touch foo
$ tar -cf foo.tar foo
$ docker context import foo foo.tar
foo
Successfully imported context "foo"
```

**Describe the results you received:**

The command returned successfully.

**Describe the results you expected:**

An error should occur. The context was not imported because the file was not a valid context file.

**Additional information you deem important (e.g. issue happens only occasionally):**

N/A

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.0-beta3
 API version:       1.40
 Go version:        go1.12.4
 Git commit:        c55e026
 Built:             Thu Apr 25 19:05:38 2019
 OS/Arch:           darwin/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.0-beta3
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.4
  Git commit:       c55e026
  Built:            Thu Apr 25 19:13:00 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc7+dev
  GitCommit:        029124da7af7360afa781a0234d1b083550f797c
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

N/A

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Docker for Mac 2.0.4.1

**Comment by thaJeztah** [comment]
Thanks for reporting; I ran into this when testing a recent PR, and will be looking at a fix.

The TL;DR is that it checks if importing the expected data went successfully, but doesn't produce an error if no metadata was found.

**Comment by thaJeztah** [comment]
opened https://github.com/docker/cli/pull/1924
