### ISSUE TITLE
[question] cli is for docker ce and docker ee, is there still docker ce, not moby project instead?  

### ISSUE THREAD

**Issue by allencloud** [docker/cli#2]
In readme, it says that cli is for Docker CE and Docker EE products.

Is there still docker ce, not moby project instead?

**Comment by dnephin** [comment]
There is still a Docker CE which is not the same as moby. moby is upstream from Docker CE

**Comment by allencloud** [comment]
Thanks a lot. Just now I communicate some with @thaJeztah. I think I have more background now.Closing this.
