### ISSUE TITLE
docker build --pretend to know whether a build will use the cache without actually building it

### ISSUE THREAD

**Issue by ehipp-altair** [docker/cli#2011]
I would like to know in advance whether a docker build command will use only the cache or whether it will run some ADD or RUN commands.

That command would show approximately the same output as the docker build command, except it would not actually build the container.

For example, if I have the following Dockerfile :

```
FROM node:12.6.0-alpine as builder
ADD package.json yarn.lock /usr/app/
```

If I run `docker build --pretend` with an empty cache, it would show : 

```
Sending build context to Docker daemon  3.072kB
Step 1/2 : FROM node:12.6.0-alpine as builder
Step 2/2 : ADD package.json yarn.lock /usr/app/
```

If however the image was already built and no changes happened to the files, it would show : 

```
Sending build context to Docker daemon  3.072kB
Step 1/2 : FROM node:12.6.0-alpine as builder
----> Cached (a9a8b83644f7)
Step 2/2 : ADD package.json yarn.lock /usr/app/
 ---> Cached (9af8a29582db)
```

Is there already a way to know whether a dockerfile will use the cache (and until which step it will use the cache) ?

If no such command exists, what do you think of that proposal ? Do you think this would make more sense in a separate command to query the cache ?

```
docker cache ls -d Dockerfile .
```

**Comment by AkihiroSuda** [comment]
This should be discussed in https://github.com/moby/buildkit/issues

**Comment by ehipp-altair** [comment]
Ok, I'm closing this and opening it in buildkit
