### ISSUE TITLE
Less verbose logging

### ISSUE THREAD

**Issue by zafarella** [docker/cli#2017]
### Feature request
Consider less verbose logging on the `docker` cli (flag `--quiet , -q`):
* `run`
* `pull`
* other applicable commands

As for example you don't really require to see progress of downloading or building image, sometimes you also don't need output of `docker run.

Consider making the cli less verbose (like `docker build` have), but providing only vital info and printing out error message in case of any error. Using it on daily basis in CI makes a bit harder to read the log of the jobs.

**Comment by theycallmemac** [comment]
This open? I'm sure I can take it on

**Comment by thaJeztah** [comment]
Both `docker run` and `docker pull` now have a `--quiet` flag to suppress pull progress output, so let me close this ticket.
