### ISSUE TITLE
docker does not gracefully logout for non-default registry

### ISSUE THREAD

**Issue by shhsu** [docker/cli#204]
**Steps to reproduce the issue:**
We are developer an [ACR credential helper](https://github.com/Azure/acr-docker-credential-helper). The issue was discovered during our test on os X.

We ran
1. `az acr login -name <our registry>`
2. `az acr logout`

The log out succeeded and the credentials were removed from osxkeychain. However, We do see the following output

> WARNING: could not erase credentials: error erasing credentials - err: exit status 1, out: 'The specified item could not be found int the keychain'

After looking into the docker code. We realized this is not an ACR specific issue. This issue should repro on any non-default registry if osxkeychain was used in cred store .

Problem with the code:
https://github.com/docker/cli/blob/master/cli/command/registry/logout.go#L42-L53

In the case where `hostnameAddress` and `serverAddress` are the same, we would have duplicated entries in  `regsToTry`. Assuming you can find `serverAddress` in the config file, `Erase()` will be called twice for this `serverAddress`. Cred stores such as file store or WinCred does not complain if you try to remove an entry that does not exist, but osxkeychain would.

**Comment by shhsu** [comment]
We are closing our issue https://github.com/Azure/acr-docker-credential-helper/issues/12 for this.
@sajaya @davidobando

**Comment by Rapix-x** [comment]
This also happens on Ubuntu 18.04 with the pass credential helper.

**Comment by shqear93** [comment]
Same issue here!

 Model Name:	Mac mini
 Model Identifier:	Macmini8,1

Docker version 19.03.2, build 6a30dfc

**Comment by shqear93** [comment]
Same issue here!

Model Name: Mac mini
Model Identifier: Macmini8,1

Docker version 19.03.2, build 6a30dfc
