### ISSUE TITLE
make cross error on OSx

### ISSUE THREAD

**Issue by vieux** [docker/cli#208]
Hi,

I installed parallel and here what I get when I `make cross` on my mac:

```
$ make cross
./scripts/build/cross
Building binaries for all platforms
make: *** [cross] Error 6
```

Any idea ?

**Comment by dnephin** [comment]
https://github.com/docker/cli/blob/master/README.md#development

```
make -f docker.Makefile cross
```

**Comment by vieux** [comment]
@dnephin oh ok my bad, didn't read :/
