### ISSUE TITLE
Reducing transitive dependencies of cli/config

### ISSUE THREAD

**Issue by jonjohnsonjr** [docker/cli#2082]
**Description**

I'd love to be able to use [`config.Load`](https://godoc.org/github.com/docker/cli/cli/config#Load) for parsing the docker config file and shelling out to credential helpers, rather than reinventing the wheel. Unfortunately, that package ends up pulling in a ton of seemingly unrelated dependencies, e.g.:

* github.com/sirupsen/logrus (biggest offender)
* github.com/containerd/continuity
* github.com/opencontainers/runc

The root of the issue is that this repo relies on github.com/docker/docker/pkg/homedir, which ends up pulling in everything else. I opened [a PR](https://github.com/moby/moby/pull/39873) against moby/moby to help with this a bit, but it will be tough to untangle all of this without just replacing homedir.

I'm curious if this project is open to re-implementing a minimal homedir replacement in order to trim down these dependencies. I'm not sure how complex that would be, but I can try my hand at a PR as well.

Cheers

**Comment by dmcgowan** [comment]
I looked at the `github.com/docker/docker/pkg/homedir` package and its dependencies. It seems a simpler minimal package would make more sense, there is a lot of other cleanup needed in the original. @tonistiigi and @tiborvass have similar dependency chain concerns.

**Comment by tiborvass** [comment]
I can have a stab at this, I agree this is overly complex.

**Comment by tiborvass** [comment]
@jonjohnsonjr i believe this is now resolved as the simpler #2101 solution was accepted, so I'm closing this. Let us know if you have other dependency issues!

**Comment by jonjohnsonjr** [comment]
Thanks!
