### ISSUE TITLE
Feature request: session-bound context

### ISSUE THREAD

**Issue by sixeyed** [docker/cli#2096]
`docker context use` is a great feature and way easier than setting environment variables, but it is machine wide. 

With the `DOCKER_HOST` variable I can target different engines in different terminal sessions, but when I switch contexts that affects all my sessions.

It would be great to have something like `docker context use --session` which switches context just for the current session.

**Comment by thaJeztah** [comment]
I think the `DOCKER_CONTEXT` env var is meant for that
