### ISSUE TITLE
ERROR: Preparation failed: Error response from daemon: received unexpected HTTP status: 503 Service Unavailable

### ISSUE THREAD

**Issue by objohnson** [docker/cli#2141]
Hello,

We are getting errors trying to access the following image:

datadog/agent:latest-jmx

ERROR: Preparation failed: Error response from daemon: received unexpected HTTP status: 503 Service Unavailable

**Comment by covertxd** [comment]
https://status.docker.com/

**Comment by cpuguy83** [comment]
Thanks for the report. Please track status on status.docker.com.
Closing since there is nothing we can do here.
