### ISSUE TITLE
ADD having trouble with target filename integrity for Google Drive downloads

### ISSUE THREAD

**Issue by mcandre** [docker/cli#2168]
When I try to use `ADD` to download a Google Drive tar.gz file and extract the archive onto root, then the resulting Docker image does not extract the file contents, but instead places a "1pgdyfxfG9LMwp6BqBJzQEgln9nQnpswp" file in the root directory. How well does `ADD` behave with HTTP redirects?

Unknown if the mimetype is correct in either `ADD` target or Google Drive HTTP(S) response.

kubernetes v1.11.0+d4cacc0

**Comment by thaJeztah** [comment]
What version of Docker are you using? Do you have a minimal example that can be used to reproduce the issue?

Note that `ADD` will not extract files if they are from a remote location, only if they're from a local file

**Comment by bsousaa** [comment]
It looks like this issue went stale. Let me close it for now. Feel free to comment and we can re-open if we have more info.
