### ISSUE TITLE
how can I build man pages as of now? 

### ISSUE THREAD

**Issue by ninrod** [docker/cli#217]
the docs/man folder has moved and I can't find it over the other repo.

how can I build the man pages for the docker version that I'm using?

**Comment by dnephin** [comment]
```
make -f docker.Makefile manpages
```

They'll be under `man/man*`

**Comment by ninrod** [comment]
Thanks @dnephin. But how can I be sure that the manpage that I'm building actually matches, say, the docker 17.03-ce cli version?

**Comment by dnephin** [comment]
If you `git checkout` the tag for the release, they should be the same

**Comment by ninrod** [comment]
@dnephin sorry, I'm confused: I can't see no tags or releases in this repo: 

releases: https://github.com/docker/cli/releases
tags: https://github.com/docker/cli/tags

**Comment by dnephin** [comment]
Oh right. The tags for previous releases are in `moby/moby`. The tag for current and future releases are in https://github.com/docker/docker-ce

**Comment by ninrod** [comment]
@dnephin, this command does not work under `docker-ce/components/cli/man` when you git clone the [docker-ce](https://github.com/docker/docker-ce) repo. 

`make -f docker.Makefile manpages` fails with: 

```sh
man $ make -f docker.Makefile manpages
make: docker.Makefile: No such file or directory
make: *** No rule to make target `docker.Makefile'.  Stop.
man $
```

**Comment by dnephin** [comment]
The makefile is in `docker-ce/components/cli/` not `docker-ce/components/cli/man`
