### ISSUE TITLE
AuthConfig struct duplication between docker/cli and docker/engine breaks other packages (19.03)

### ISSUE THREAD

**Issue by elboulangero** [docker/cli#2181]
Hi,

I package docker for Debian. At the moment we're transitioning from Docker `18.09` to `19.03`. We could build [Docker 19.03.4](https://packages.debian.org/experimental/docker.io), and now we are rebuilding the packages that depend on docker.

During this transition, we observe two packages that don't build anymore against docker `19.03`, and it seems that the cause is the same. These are:

1. https://gitlab.com/gitlab-org/gitlab-runner/issues/4832

```
src/gitlab.com/gitlab-org/gitlab-runner/helpers/docker/auth_config.go:102:22: cannot use config.AuthConfigs (type map[string]"github.com/docker/cli/cli/config/types".AuthConfig] as type map[string]"github.com/docker/docker/api/types".AuthConfig] in argument to addAll 
src/gitlab.com/gitlab-org/gitlab-runner/helpers/docker/auth_config.go:130:2: cannot use newAuths (type map[string]"github.com/docker/cli/cli/config/types".AuthConfig] as type map[string]"github.com/docker/docker/api/types".AuthConfig] in return argument 
src/gitlab.com/gitlab-org/gitlab-runner/helpers/docker/auth_config.go:144:26: cannot use newAuths (type "github.com/docker/cli/cli/config/types".AuthConfig)
```

2. https://github.com/hashicorp/nomad/issues/6583

```
src/github.com/hashicorp/nomad/drivers/docker/utils.go:118:57: cannot use cfile.AuthConfigs (type map[string]"github.com/docker/cli/cli/config/types".AuthConfig] as type map[string]"github.com/docker/docker/api/types".AuthConfig] in argument to "github.com/docker/docker/registry".ResolveAuthConfig
```

It seems to me that the failure was introduced by this commit in docker cli: https://github.com/docker/cli/commit/27b2797f7deb3ca5b7f80371d825113deb1faca1

After this commit, the struct `AuthConfig` is now defined in two places:
- https://github.com/docker/cli/blob/master/cli/config/types/authconfig.go
- https://github.com/docker/engine/blob/master/api/types/auth.go

It seems to be the cause of the build failures in both `gitlab-runner` and `nomad`.

How should I handle that? Or am I missing something? 

Thanks

**Comment by thaJeztah** [comment]
ping @tonistiigi @tiborvass PTAL

**Comment by bsousaa** [comment]
It looks like this issue went stale. Let me close it.
