### ISSUE TITLE
dead link to slack channel in Contributing.md

### ISSUE THREAD

**Issue by DeclanFarrell** [docker/cli#2191]
**Description**
The link to the slack channel in CONTRIBUTING.md appears to be dead.

**Steps to reproduce the issue:**
NA

**Describe the results you received:**
Current link displays the following:
![slack-link](https://user-images.githubusercontent.com/22755099/68553466-71e8d800-0419-11ea-8a84-7538c5704f7d.png)

**Describe the results you expected:**
Working Slack link

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
NA

**Output of `docker info`:**
NA

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
Can you try if this link works? http://dockr.ly/slack
