### ISSUE TITLE
The stack list command does not support tasks format from the configuration file 

### ISSUE THREAD

**Issue by adshmh** [docker/cli#224]
**Description**

docker stack list command does not support TasksFormat from the config file, while other commands, e.g. docker node list support their corresponding format string from the config file.

**Steps to reproduce the issue:**
1. Specify TasksFormat in config file.
2. Run the command 'docker stack list' 

**Describe the results you received:**
The stack list command ignores the TasksFormat string in the config file.

**Describe the results you expected:**
Perhaps the stack list command can support the TasksFormat (the node list command supports NodesFormat string) in the configuration file.

**Comment by adshmh** [comment]
If supporting the configuration option would be the correct behavior, I can submit a PR for it.

**Comment by dnephin** [comment]
`docker stack list` lists stacks not tasks, so it wouldn't use the `TasksFormat`. Do you mean `docker stack ps` ?

**Comment by adshmh** [comment]
Yes, sorry about the mistake. Looking at the latest code on docker stack ps, however, it seems to already check the configuration file:
```
if len(format) == 0 {
                if len(dockerCli.ConfigFile().TasksFormat) > 0 && !options.quiet {
                        format = dockerCli.ConfigFile().TasksFormat
                } else {
                        format = formatter.TableFormatKey
                }
        }
```

**Comment by dnephin** [comment]
Cool, so anything to do here?

**Comment by adshmh** [comment]
I think it is already covered by the ps command.
