### ISSUE TITLE
Docker image deleted from repository

### ISSUE THREAD

**Issue by rajputvishwas** [docker/cli#2247]
**Description**

**Steps to reproduce the issue:**
I came across strange incident, wherein few of docker images deleted automatically from repository.

I have list of images saved in .tar file format and I am loading these images using script.

cd /root/docker_images
files=`ls /root/docker_images`
for f in $files
do
docker load -i $f
done

It works fine and loads all the docker images to repository, but after some times few images were missing. 

**Describe the results you received:**
docker images loaded successfully, but after some time few images were missing.

**Describe the results you expected:**

images should be there in the repository permanently.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:50:12 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:48:43 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 5
  Running: 3
  Paused: 0
  Stopped: 2
 Images: 3
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.4.0-1083-aws
 Operating System: Ubuntu 16.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 61.48GiB
 Name: CapstoneNode-Test-new
 ID: DNS7:CBN7:LIX7:EAV4:KTMB:2H3T:2434:XXB3:NAKY:HVN7:T3ZL:Y7VU
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  172.30.0.0/16
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS

**Comment by rajputvishwas** [comment]
![image](https://user-images.githubusercontent.com/15668995/71962919-8d593f00-3220-11ea-96b0-d2bf645c28d5.png)

**Comment by thaJeztah** [comment]
Docker won't remove image by itself; are there no cleanup scripts running that (e.g.) call `docker system prune` or `docker image prune`?

**Comment by rajputvishwas** [comment]
@thaJeztah there are cleanup scripts running as I just have 10 docker images. However I have not faced such incidents on regular basis.

**Comment by thaJeztah** [comment]
If those script use `docker image prune -a` (`--all`), then images that are unused by a running container will be pruned;


start a container using the `busybox:latest` image

```bash
docker run -dit --name mycontainer busybox:latest
```

check that the image exists in the local image cache

```bash
docker image ls --filter reference=busybox

REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
busybox             latest              b534869c81f0        5 weeks ago         1.22MB
```

pruning images will remove untagged and unused images

```bash
docker image prune -a
WARNING! This will remove all images without at least one container associated to them.
Are you sure you want to continue? [y/N] y
....
untagged: centos:7
untagged: centos@sha256:4a701376d03f6b39b8c2a8f4a8e499441b0d567f9ab9d58e4991de4472fb813c
deleted: sha256:5e35e350aded98340bc8fcb0ba392d809c807bc3eb5c618d4a0674d98d88bccd
deleted: sha256:77b174a6a187b610e4699546bd973a8d1e77663796e3724318a2a4b24cb07ea0

Total reclaimed space: 1.68GB
```

The `busybox:latest` image is still in use, so not removed:

```bash
docker image ls --filter reference=busybox

REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
busybox             latest              b534869c81f0        5 weeks ago         1.22MB
```


Removing the container, then running image prune, and the image will be removed:

```
docker rm -f mycontainer
docker image prune -a
WARNING! This will remove all images without at least one container associated to them.
Are you sure you want to continue? [y/N] y
Deleted Images:
untagged: busybox:latest
untagged: busybox@sha256:6915be4043561d64e0ab0f8f098dc2ac48e077fe23f488ac24b665166898115a
deleted: sha256:6d5fcfe5ff170471fcc3c8b47631d6d71202a1fd44cf3c147e50c8de21cf0648
deleted: sha256:195be5f8be1df6709dafbba7ce48f2eee785ab7775b88e0c115d8205407265c5

Total reclaimed space: 1.22MB
```


_However_ there is one corner-case (I think there's a discussion/tracking issue for that somewhere); 
If an image is in use, and tagged under multiple names, then running `docker image prune` will not remove the image itself but _will_ remove references (tags). When doing so, it will keep 1 tag for the image, but the tag it keeps may not be the tag that was used by the container.

```bash
docker image pull busybox:latest

# tag the image under other names as well
docker image tag busybox:latest  thajeztah/busybox:latest
docker image tag busybox:latest  thajeztah/busybox2:latest

# there's now three tags for the same image
docker image ls
REPOSITORY           TAG                 IMAGE ID            CREATED             SIZE
busybox              latest              6d5fcfe5ff17        13 days ago         1.22MB
thajeztah/busybox2   latest              6d5fcfe5ff17        13 days ago         1.22MB
thajeztah/busybox    latest              6d5fcfe5ff17        13 days ago         1.22MB

# run a container, using the `busybox:latest` tag
docker run -dit --name mycontainer busybox:latest

# prune images with the `-a/--all` option set
docker image prune -a
WARNING! This will remove all images without at least one container associated to them.
Are you sure you want to continue? [y/N] y
Deleted Images:
untagged: busybox:latest
untagged: busybox@sha256:6915be4043561d64e0ab0f8f098dc2ac48e077fe23f488ac24b665166898115a
untagged: thajeztah/busybox2:latest

Total reclaimed space: 0B
```

Notice that in this case, it removed the `thajeztah/busybox2:latest` and `busybox:latest` tags (even though the container was using that), but keeps one tag so that the image still is referenced.

Removing the container, and running `docker image prune -a` again will remove the remaining tag for the image, and will remove the image itself:

```bash
docker rm -f mycontainer

WARNING! This will remove all images without at least one container associated to them.
Are you sure you want to continue? [y/N] y
Deleted Images:
untagged: thajeztah/busybox:latest
deleted: sha256:6d5fcfe5ff170471fcc3c8b47631d6d71202a1fd44cf3c147e50c8de21cf0648
deleted: sha256:195be5f8be1df6709dafbba7ce48f2eee785ab7775b88e0c115d8205407265c5

Total reclaimed space: 1.22MB
```

**Comment by thaJeztah** [comment]
related issue: https://github.com/moby/moby/issues/36295

**Comment by rajputvishwas** [comment]
I am explicitly not removing or running the container. I have OKD (3.11) installed on top of docker. I am consuming application images from docker repository.

Let us say if I have to run busybox application, I will use 

oc  new-app --docker-image=busybox:latest

Then, OKD internally run and manage the image. 

Coming to point where the image is reference under multiple tags, yes I have seen such cases in my environment.

I can remove an application from OKD web console, this action usually stop running container. But I really doubt, this removes image from the repository.

**Comment by thaJeztah** [comment]
I'm not familiar enough with OKD to tell if it would run other jobs behind the scenes to clean up 🤔. My thinking with the `image prune` situation was that it _could_ be a race condition (i.e., no container started yet for an image and a cleanup script triggering at that time).

**Comment by rajputvishwas** [comment]
It could be, as of now I am not able to reproduce it, but will try to capture more details if possible. Thanks @thaJeztah

**Comment by thaJeztah** [comment]
Let me close this issue for now, because without more information, there's nothing actionable.

Also, if there's a bug, that would be most likely in the engine (https://github.com/moby/moby) itself, not the CLI (which  is what this repository contains).

Feel free to continue the conversation though!
