### ISSUE TITLE
docker push fails to private docker IP but not to localhost

### ISSUE THREAD

**Issue by davesargrad** [docker/cli#2270]
I created a private docker registry as follows:
`docker run -d -p 5007:5000 --restart=always --name registry registry:2`

I then tried the commands found [here](https://docs.docker.com/registry/deploying/):

`docker push localhost:5007/my-ubuntu `

succeeds. However docker 
`push docker push 10.93.97.131:5007/my-ubuntua `
fails

The tag and push for each is seen below.
![image](https://user-images.githubusercontent.com/48793689/72620949-4fd66f00-390e-11ea-8786-4ce2fe9e36a9.png)

The message log (/var/log/messages) is seen here:
![image](https://user-images.githubusercontent.com/48793689/72621003-6b417a00-390e-11ea-93b6-4b42193c944e.png)

I am behind a corporate proxy. However I think I've properly configured for that.
![image](https://user-images.githubusercontent.com/48793689/72622175-afce1500-3910-11ea-9ac1-28dcf839b9d2.png)

![image](https://user-images.githubusercontent.com/48793689/72621383-2833d680-390f-11ea-8d54-e3afeaa56e7a.png)

![image](https://user-images.githubusercontent.com/48793689/72621422-3681f280-390f-11ea-98a6-e7b29d0f99f3.png)

It would seem that the proxy is getting in the way.. note the proxy address seems to align with the last error message in /var/log/messages

![image](https://user-images.githubusercontent.com/48793689/72621563-7d6fe800-390f-11ea-95fa-03a093373b17.png)

![image](https://user-images.githubusercontent.com/48793689/72621637-a42e1e80-390f-11ea-89ee-795036274ebb.png)

What is the proper way to ensure that the docker cli does not use the proxy?

**Comment by thaJeztah** [comment]
By default, registries should have TLS enabled. An exception is made for `localhost` (and `127.0.x.x` IP addresses), because those are a common case for local testing; see the output of `docker info`, which shows what registries are configured as "insecure";

```
Insecure Registries:
  127.0.0.0/8
```

When pushing to an insecure registry, docker will first attempt to push with a TLS connection (https://), but falls back to non-TLS, as well as allows the use of self-signed certificates.

For other IP-addresses, this is not the case, and docker will fail (as having a public registry without TLS is a security risk).

You can find some information about configuring a registry in the docs: https://docs.docker.com/registry/configuration/

And (for testing purposes) how to configure the daemon to mark a registry as "insecure"; https://docs.docker.com/registry/insecure/

**Comment by davesargrad** [comment]
Hi @thaJeztah 

Thanks for your response.

I have configured my registry as insecure. I first learned to do this over a year ago when i started using docker. In the following you will see that 10.93.97.131:5007 is marked insecure

![image](https://user-images.githubusercontent.com/48793689/72622659-af824980-3911-11ea-8e30-4d7eeaecd3f9.png)

**Comment by davesargrad** [comment]
Oddly I just noticed that No Proxy isnt set, even though 
` systemctl show --property=Environment docker`

seems to suggest it is.

This may be my problem. How is it that these are out of sync?

**Comment by thaJeztah** [comment]
Does it work if you specify them on separate `Environment` options?

```
Environment="HTTP_PROXY=........"
Environment="NO_PROXY=.........."
```

**Comment by davesargrad** [comment]
Turns out a reboot resulted in no_proxy being handled correctly. I dont know why there seemed to be a disconnect between
`docker info`
and 
`systemctl show --property=Environment docker`

**Comment by davesargrad** [comment]
Hi again @thaJeztah 

I will close this issue. Your input did help me. Even though it wasn't the insecure registry, it did help me to realize how easy it is to see the current configuration that docker is working with.

I would like to know why docker info and systemctl show ... provided seemingly conflicting information.

If you have some thoughts on this, I'd appreciated.

Regardless, thank you for your fast response. It helped.

**Comment by thaJeztah** [comment]
No idea why it would show different information in your case; are you using the `live-restore` feature perhaps? systemd would set the environment variables, and the docker daemon directly reads those variables when starting the daemon.

Let me close this issue, but feel free to continue the conversation
