### ISSUE TITLE
docker push --quiet suppresses errors and non-zero exit code

### ISSUE THREAD

**Issue by thaJeztah** [docker/cli#2284]
(as commented by @BarakBD-Globality in https://github.com/moby/moby/issues/36655#issuecomment-577968227)

The `docker push --quiet` option was implemented in https://github.com/docker/cli/pull/2197 (not in a release yet), but appears to not print errors and returns a `zero` exit code on failure;

Without `--quiet`

```bash
$ docker push nosuchimage
The push refers to repository [docker.io/library/nosuchimage]
An image does not exist locally with the tag: nosuchimage

echo $?
1

$ docker push busybox
The push refers to repository [docker.io/library/busybox]
195be5f8be1d: Layer already exists
[DEPRECATION NOTICE] registry v2 schema1 support will be removed in an upcoming release. Please contact admins of the docker.io registry NOW to avoid future disruption. More information at https://docs.docker.com/registry/spec/deprecated-schema-v1/
errors:
denied: requested access to the resource is denied
unauthorized: authentication required

echo $?
1
```

With `--quiet`:

```bash
$ docker push --quiet nosuchimage
docker.io/library/nosuchimage

$ echo $?
0

$ docker push --quiet busybox
docker.io/library/busybox

$ echo $?
0
```

**Comment by Jo0** [comment]
@silvin-lubecki  Is there a reason why this was pulled out or no longer exists in v19.03.13?

**Comment by thaJeztah** [comment]
it was never part of 19.03; the `--quiet` flag on `docker push` is a new flag that's added in docker 20.10

**Comment by Jo0** [comment]
Ah apologies. I was going off the date of tags and the date of the completed PR. Thanks for clearing that up.
