### ISSUE TITLE
Docker build sometimes fail on “file not found or excluded by .dockerignore” for a nested ignored file

### ISSUE THREAD

**Issue by liiri** [docker/cli#2305]
My directory structure:

```
├── src/
├───── backend/
├─────── Dockerfile
├─────── ...
├───── frontend/
├─────── Dockerfile
├─────── node_modules/
├─────── ...
├───── commons/
├─────── ...
├── .dockerignore
```

`.dockerignore` includes the line `**/node_modules` and my build context is the root directory due to usage of `commons`.

I'm running both

`docker build ... -f src/backend/Dockerfile .`

`docker build ... -f src/frontend/Dockerfile .`

in parallel, and sometimes the `backend` build will fail on the following specific error:

> error checking context: 'file ('/workspace/src/frontend/node_modules/.staging/wrap-ansi-2a6f888f') not found or excluded by .dockerignore'.

From my understanding (see [why-do-node-modules-go-into-staging-folder](https://github.com/docker/cli/blob/master/cli/command/image/build/context.go#L50)) the `.staging` folder is temporary and there might be a race condition when walking it (see Docker cli [source][1]).

However, why is this file walked in the first place if `node_modules` is ignored? Am I misusing the ignore context functionality or is it an actual race condition?

The issue is reproduced in Google Cloud Build environment, where I'm using docker cli via the image `gcr.io/cloud-builders/docker`, which uses docker client version `19.03.5` and is run with docker server version `18.09.3`, API version `1.39`.

Full version commands output:

```
Client: Docker Engine - Community
Version: 19.03.5
API version: 1.39 (downgraded from 1.40)
Go version: go1.12.12
Git commit: 633a0ea838
Built: Wed Nov 13 07:22:05 2019
OS/Arch: linux/amd64
Experimental: false

Server: Docker Engine - Community
Engine:
Version: 18.09.3
API version: 1.39 (minimum version 1.12)
Go version: go1.10.8
Git commit: 774a1f4
Built: Thu Feb 28 05:59:55 2019
OS/Arch: linux/amd64
Experimental: false
```

```
Client:
Debug Mode: false

Server:
Containers: 4
Running: 3
Paused: 0
Stopped: 1
Images: 170
Server Version: 18.09.3
Storage Driver: overlay2
Backing Filesystem: extfs
Supports d_type: true
Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
Volume: local
Network: bridge host macvlan null overlay
Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
init version: fec3683
Security Options:
apparmor
seccomp
Profile: default
Kernel Version: 4.15.0-1044-gcp
Operating System: Ubuntu 18.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.607GiB
Name: worker-824dd2d6-b2b4-476b-b59b-b5d174c0d682
ID: UZVV:CNSH:L34X:M35U:7RDX:3LFR:FQTN:ZKFX:STWD:KGD4:6XID:F3CI
Docker Root Dir: /var/lib/docker
Debug Mode: true
File Descriptors: 49
Goroutines: 73
System Time: 2020-01-20T10:30:58.766640791Z
EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
127.0.0.0/8
Registry Mirrors:
https://mirror.gcr.io/
Live Restore Enabled: false
Product License: Community Engine
```

**Comment by silvin-lubecki** [comment]
Hello @liiri thank you for filling this issue 👍 
The code responsible for your problem is here https://github.com/docker/cli/blob/968ce1ae4d45722c6ae70aa1dff6ee28d88e976a/cli/command/image/build/context.go#L55
We should check the exclude patterns before doing anything else 👍 

Related to https://github.com/moby/moby/issues/40319

**Comment by jeradrose** [comment]
We have a similar issue, where our builds are failing intermittently (but increasingly so), and the failure is always of the pattern:

```
error checking context: 'file ('/workspace/xxxxxxxxx') not found or excluded by .dockerignore'.
```

Is it maybe some race condition where a temporary file is getting generated, and deleted during the build before a permissions check?

**Comment by satyaarthchhabra** [comment]
basically i was getting the same problem basically it was issue with the installation of docker on my setup

**Comment by liiri** [comment]
> basically i was getting the same problem basically it was issue with the installation of docker on my setup

I was using the built in docker version in Google Cloud build, which was upgraded since and indeed I haven't seen this issue for a long time. I'll close the issue for now.

**Comment by RPGillespie6** [comment]
Still seeing this in 2024 with `gcr.io/cloud-builders/docker`:

```
error checking context: file ('/workspace/node_modules/fsevents') not found or excluded by .dockerignore
```
