### ISSUE TITLE
Off-topic: Docker, your blogs have a misconfiguration, comments don't work.

### ISSUE THREAD

**Issue by alexanderkjeldaas** [docker/cli#2313]
Hey Docker,

it's not possible to comment on your blog posts, due to some WP misconfiguration.

For example, please try to add a comment to the following blog post:

https://www.docker.com/blog/simplifying-kubernetes-with-docker-compose-and-friends/

**Comment by bsousaa** [comment]
It looks like this issue went stale. Let me close it.
