### ISSUE TITLE
Numeric vs. Alphanumeric

### ISSUE THREAD

**Issue by fracturedface** [docker/cli#2363]
**Description**

When running `docker ps -h`, the description for `-q` shows the text "Only display numeric IDs". This text should say "Only display alphanumeric IDs".

**Steps to reproduce the issue:**
1. Run `docker ps -h` and look at the `-q` options description.

**Describe the results you received:**
I received "Only display numeric IDs"

**Describe the results you expected:**
I expected to receive "Only display alphanumeric IDs"

**Output of `docker version`:**

```
Client:
 Version:           18.09.9
 API version:       1.39
 Go version:        go1.13.4
 Git commit:        1752eb3
 Built:             Sat Nov 16 01:05:26 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.9
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.13.4
  Git commit:       9552f2b
  Built:            Sat Nov 16 01:07:48 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 18.09.9
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
runc version: N/A
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 5.3.0-28-generic
Operating System: Ubuntu Core 16
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.211GiB
Name: DESKTOP-P6B1U8
ID: 3KJ4:GLKH:SF27:OEI2:JBXK:ATBE:3R3E:MJMB:S2JN:F7JK:A34W:6VDP
Docker Root Dir: /var/snap/docker/common/var-lib-docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running on elementary OS 5.1 Hera

**Comment by silvin-lubecki** [comment]
Hello @fracturedface , thank you for noticing it and open an issue !
Do you think you can open a PR fixing this? If you don't feel comfortable with git or open a PR, please let me know so I can guide and help you 👍

**Comment by thaJeztah** [comment]
Perhaps we should just remove "numeric", and change to "Only display numeric IDs". If we update, we should update it in all locations (docs, flag descriptions, completion-scripts); https://github.com/docker/cli/search?q=numeric&unscoped_q=numeric

**Comment by fracturedface** [comment]
> Hello @fracturedface , thank you for noticing it and open an issue !
> Do you think you can open a PR fixing this? If you don't feel comfortable with git or open a PR, please let me know so I can guide and help you 👍

I'd be happy to open a PR. I'll have to read through the contribution guide first and might have a few questions but i'll definitely give it a shot!

**Comment by fracturedface** [comment]
> Perhaps we should just remove "numeric", and change to "Only display numeric IDs". If we update, we should update it in all locations (docs, flag descriptions, completion-scripts); https://github.com/docker/cli/search?q=numeric&unscoped_q=numeric

I'm assuming you meant "Only idsplay IDs".

If so, I think we should stick to alphanumeric as it is only a single word that describes the actual strings returned better than just an "ID" which could get confusing.

**Comment by thaJeztah** [comment]
Whoops, sorry, yes, I meant "Only display IDs".

> If so, I think we should stick to alphanumeric as it is only a single word that describes the actual strings returned better than just an "ID" which could get confusing.

My train of thought was: what "value" does `alphanumeric` provide in that context? (e.g., we don't describe the characters used for "names").

I was also considering that `alphanumeric` may not be correct for some commands, for example:

```bash
docker image ls -q

6fed14184255
7badb680cd96
4bbdb3b9e7c8
6afcce61f815
9b7a3562430f
```

But

```bash
docker image ls -q --no-trunc

sha256:6fed141842553c91b9e63fd478fb8207f775a0afb51649869fb63b4d7faafbbf
sha256:7badb680cd96a7aae0aa7ed5e360226f546af8519e9e1d9facd7db21cf041556
sha256:4bbdb3b9e7c885843d43e170330e414a2181482410c8440f2fa4c3fbf23c2ab0
sha256:6afcce61f815ee08afed28dad69361394756274ddf597e671c7bb4e41441eef1
sha256:9b7a3562430f53927e63eb3bbf1519bb033c8b3ba0771df1deeb567f4e4ff890
```

**Comment by thaJeztah** [comment]
Perhaps we _could_ consider including the "object" in those descriptions;

- `Only display container IDs` 
- `Only display image IDs`
- `Only display network IDs`

Which would be consistent with what's used for volumes (which don't have an ID, only a name);

```
  -q, --quiet           Only display volume names
```

**Comment by dominikbraun** [comment]
I have taken the liberty to change the descriptions since I already had this thing in mind for a while and nothing seemed to happen here yet.

**Comment by fracturedface** [comment]
@dominikbraun Thanks! I would have done this sooner but there seemed to be some confusion on what everyone wanted to be done.
