### ISSUE TITLE
Make the `--pull` behaviour being configurable over env var

### ISSUE THREAD

**Issue by jcchavezs** [docker/cli#2370]
**Description**

Given this great issue https://github.com/docker/cli/pull/1498 I always wondered if the default could be configured over an env var for a user.

**Describe the results you expected:**
```
$DOCKER_PULL_IMAGES=missing|never|always
```

Ping @yshen

**Comment by thaJeztah** [comment]
Discussing this with other maintainers, and we currently don't plan to add environment variables for specific options/flags, but you can probably create a shell alias if you want to set this option by default.


If you're using Docker Compose, you can also set the pull-policy in a compose-file (which may help for such scenarios)
