### ISSUE TITLE
Why docker cli redirect all output to stderr?

### ISSUE THREAD

**Issue by YongHaoWu** [docker/cli#2386]
```
func main() {
	dockerCli, err := command.NewDockerCli()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	logrus.SetOutput(dockerCli.Err())

```

I know that 
>       The stream stderr is unbuffered.  The stream stdout is line-buffered when it points to  a  termi       nal.

But I think that `line-buffered` is better than `2>&1` every time to grep the `docker logs`.

Thanks.

**Comment by silvin-lubecki** [comment]
Hello @YongHaoWu , thank you for filling this issue, but I don't think the result of `docker logs` is printing on `stderr`. The code you are referring to is there to setup the `logrus` logger, which we use to print some debug messages (example [here](https://github.com/docker/cli/blob/8ca1f0bb7df46b3772fd59b985139ebe2997d5c5/cli/connhelper/commandconn/commandconn.go#L42) ). Those messages can be shown using `docker --log-level=debug <command>`. 
The result of `docker logs` should print everything on `stdout`.
I will now close this issue, feel free to re-open it if you need more information about it 👍

**Comment by YongHaoWu** [comment]
@silvin-lubecki Hi, `docker logs ` is redirect to stderr I think.
```
root@localhost:~# docker logs  --tail 5 myapi  2> /tmp/x
root@localhost:~# cat /tmp/x
[GIN-debug] POST   
[GIN-debug] POST   
[GIN-debug] POST  
[GIN-debug] Listening and serving HTTP on :8000
2020-03-09 02:55:57.955988|DEBUG|-|1:0:1|-|log.go:21|-:log.SetLogger|-|logger initialized|-:-|
```

**Comment by YongHaoWu** [comment]
@silvin-lubecki  ps, I can not reopen this issue.

**Comment by cpuguy83** [comment]
`docker logs` sends stderr messages (from the container) to stderr and stdout messages to stdout.

**Comment by cpuguy83** [comment]
This is working as designed.

**Comment by silvin-lubecki** [comment]
Hello @YongHaoWu, let me add more context here.
If you check the `docker logs` code [here](https://github.com/docker/cli/blob/master/cli/command/container/logs.go#L74), you can see that in case of non interactive container, the logs are demultiplexed into `stdout` and `stderr` streams. I think your `myapi` container is logging on `stderr`, so that's why it ends with everything on `stderr` on your side. My bad I tested locally with a process only printing on `stdout`.
Does that make sense to you?

**Comment by YongHaoWu** [comment]
@silvin-lubecki  Aah, I know how it works now, thanks. Sry for my bothering.

**Comment by silvin-lubecki** [comment]
Not bothering at all 👍
