### ISSUE TITLE
CI: test-certificates in e2e tests have expired

### ISSUE THREAD

**Issue by thaJeztah** [docker/cli#2412]
Looks like new ones have to be generated;

```

=== FAIL: e2e/trust TestSignWithLocalFlag (0.12s)
    sign_test.go:57: assertion failed: 
        Command:  docker -D trust sign registry:5000/signlocal:v1
        ExitCode: 1
        Error:    exit status 1
        Stdout:   
        Stderr:   time="2020-03-31T12:07:58Z" level=debug msg="reading certificate directory: /tmp/trust_test-414110099/tls/notary-server:4443"
        time="2020-03-31T12:07:58Z" level=debug msg="Error pinging notary server \"https://notary-server:4443/v2/\": Get https://notary-server:4443/v2/: x509: certificate has expired or is not yet valid"
        time="2020-03-31T12:07:58Z" level=debug msg="Making dir path: /tmp/trust_test-414110099/trust/tuf/registry:5000/signlocal/changelist"
        Error: error contacting notary server: x509: certificate has expired or is not yet valid
        
        
        Failures:
        ExitCode was 1 expected 0
        Expected no error
```

/cc @justincormack @silvin-lubecki

**Comment by XiaodongLoong** [comment]
I also meet this problem with e2e test:
RUN   TestCreateWithContentTrust
--- FAIL: TestCreateWithContentTrust (2.37s)
    create_test.go:18: assertion failed: 
        Command:  docker image push registry:5000/trust-create:latest
        ExitCode: 1
        Error:    exit status 1
        Stdout:   The push refers to repository [registry:5000/trust-create]
        cd6996bb66d2: Preparing
        cd6996bb66d2: Mounted from alpine
        latest: digest: sha256:8453ac1b14da2ab285f13ca91727384762b3db46c7cbb47b1b0b4b713ccf6eca size: 528
        Signing and pushing trust metadata
        Stderr:   Error: error contacting notary server: x509: certificate has expired or is not yet valid
openssl s_client -connect 172.28.0.4:4443
...
-----BEGIN CERTIFICATE-----
MIIFKjCCAxKgAwIBAgIJAMyOpNbHzq7KMA0GCSqGSIb3DQEBCwUAMGwxCzAJBgNV
BAYTAlVTMQswCQYDVQQIDAJDQTEWMBQGA1UEBwwNU2FuIEZyYW5jaXNjbzEPMA0G
A1UECgwGRG9ja2VyMScwJQYDVQQDDB5Ob3RhcnkgSW50ZXJtZWRpYXRlIFRlc3Rp
bmcgQ0EwHhcNMTgwMzA3MDk0MjAxWhcNMjAwMzI2MDk0MjAxWjBbMQswCQYDVQQG
EwJVUzELMAkGA1UECAwCQ0ExFjAUBgNVBAcMDVNhbiBGcmFuY2lzY28xDzANBgNV
BAoMBkRvY2tlcjEWMBQGA1UEAwwNbm90YXJ5LXNlcnZlcjCCASIwDQYJKoZIhvcN
AQEBBQADggEPADCCAQoCggEBAKjbeflOtVrOv0IOeJGKfi5LHH3Di0O2nlZu8AIT
SJbDZPSXoYc+cprpoEWYncbFFC3C94z5xBW5vcAqMhLs50ml5ADl86umcLl2C/mX
8NuZnlIevMCb0mBiavDtSPV3J5DqOk+trgKEXs9g4hyh5Onh5Y5InPO1lDJ+2cEt
VGBMhhddfWRVlV9ZUWxPYVCTt6L0bD9SeyXJVB0dnFhr3xICayhDlhlvcjXVOTUs
ewJLo/L2nq0ve93Jb2smKio27ZGE79bCGqJK213/FNqfAlGUPkhYTfYJTcgjhS1p
lmtgN6KZF6RVXvOrCBMEDM2yZq1mEPWjoT0tn0MkWErDANcCAwEAAaOB3zCB3DAf
BgNVHSMEGDAWgBSIZiRbIhk/26DjfXrjiqS2UiRgEjAMBgNVHRMBAf8EAjAAMB0G
A1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAOBgNVHQ8BAf8EBAMCBaAwXQYD
VR0RBFYwVIINbm90YXJ5LXNlcnZlcoIMbm90YXJ5c2VydmVyghJldmlsLW5vdGFy
eS1zZXJ2ZXKCEGV2aWxub3RhcnlzZXJ2ZXKCCWxvY2FsaG9zdIcEfwAAATAdBgNV
HQ4EFgQUFBwKiXKF7LSjRFMuKIYC1pGFQi4wDQYJKoZIhvcNAQELBQADggIBACE6
Y+XRchaN7B8+z+4qXxNTTPT5WZYWU4IMddPLWPcSj9U+XFBz19nObrZLAf6Z3Te7
6BlcVfEdIRMNCspcjX6RZjeC0iJAaDKo+SdqoajKpEwph9R4OP2I4mwcpf/oMG7p
IsNyzeA7427ignwQ+XfwSElJ5BeTUSPgkYujrTZDxRfCA01t0X0tpzv/3o4dfoZ0
QKA+2djJagrjU82kTneWRktn6+G+zQuZdupcwUEPvlH3YdEgH22W0m0mavnJMYI/
J/J4rmanvknLnjCmChEdpwCORL+G84Hu9hdy0WSbvQzQ9puGyukWJO/71Z0fhis2
DuLIt2esRJoKyrnaCDA+EFJ0JkzozZfS2BcRe3UL9awnwa/iKlUcs/u4bhKu9gwL
F2dXtYPJzyr3PUdPGT4FixTpVZG37BvUSy2IH97qxgK9vn1FGTLDqQlSwCLXvrzr
g2Zz7+JpF2SK3yR1G/IYmAFa37vmbBjW7dZp2JepTMelpblxiTthH1jPN7Lf3uvd
tDe2ZLxTNOVpymDupUqOEXanvcTAkRD3ye3/yhWaXQ44lxVJqG+FNdjQCKcARHWH
H1Otd12QzOsHytUSe7n4zsT06Seyt9huq4g6h0EcuVZaJbi43u5mJtn9yZiZOLF+
dJsYWaDeSXDnyaFl1tHwcF1tqvguI41E63QqrM0N
-----END CERTIFICATE-----
....
SSL handshake has read 3399 bytes and written 269 bytes
Verification error: certificate has expired

openssl x509 -text -noout -in ../server-ca.pem
... 
Validity
            Not Before: Mar  7 09:42:01 2018 GMT
            Not After : Mar 26 09:42:01 2020 GMT
We need to update cli/e2e/testdata/notary/notary-server.cert  and the key file.

Thanks!

**Comment by thaJeztah** [comment]
I had a quick look at this; these certificates were added as part of https://github.com/docker/cli/pull/924, which migrated tests from the moby/moby repository, which were later removed there https://github.com/moby/moby/pull/36515

That didn't remove the fixtures though; https://github.com/moby/moby/tree/5433ceb12ead305d8c85e8e27c4b4d842ef88ae0/integration-cli/fixtures/notary

Looking at that directory, there's a `gen.sh` (https://github.com/moby/moby/blob/5433ceb12ead305d8c85e8e27c4b4d842ef88ae0/integration-cli/fixtures/notary/gen.sh) to generate the certificates, so I think we should copy that to this repository and use it to update fixtures

**Comment by thaJeztah** [comment]
Looks like they were removed in moby in https://github.com/moby/moby/pull/36838

**Comment by thaJeztah** [comment]
Oh, actually; that `gen.sh` was copied, but it's only for the certificates in this directory; https://github.com/docker/cli/tree/8b00c5cfd87ac653e2a1dc4b95df30ca23e1d40d/e2e/image/testdata/notary
