### ISSUE TITLE
ContainerFormat's CreatedAt has wrong documentation

### ISSUE THREAD

**Issue by diamondo25** [docker/cli#2413]
https://github.com/docker/cli/blob/389fa742ff0ebfeda5d94735ac0ca09eac8ecc4f/cli/command/formatter/container.go#L179-L182

time.Unix().String() will not create a unix timestamp (number), but instead will create an string as explained in the documentation: https://golang.org/pkg/time/#Time.String .

Maybe add another variant, eg CreatedAtTimestamp to support this option nonetheless.

**Comment by GOTAM672** [comment]
Hey, I'm a newcomer and I want to contribute to this project. Is this issue good to start?

**Comment by leungyukshing** [comment]
Hi, do we still work on this issue? I can help

**Comment by milanvthakor** [comment]
Hey, I have been working with GoLang for the past year and I would like to contribute to this project.

**Comment by simonha9** [comment]
Hi, not sure if this is still being worked on but the change also needs a test update provided here: https://github.com/docker/cli/pull/4765

(Or feel free to update the original PR I'm easy)
