### ISSUE TITLE
docker save loses configuration information

### ISSUE THREAD

**Issue by davecramer** [docker/cli#2440]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST
-->

**Description**

**Steps to reproduce the issue:**
1.
docker save someimage > someimage.tar
2.
tar -tvf someimage.tar
3.

**Describe the results you received:**
-rw-r--r-- 0/0             882 1970-01-01 00:00 manifest.json

**Describe the results you expected:**
manifest.json with the correct date

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-109.gitcccb291.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      cccb291/1.13.1
 Built:           Tue Mar  3 17:21:24 2020
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-109.gitcccb291.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      cccb291/1.13.1
 Built:           Tue Mar  3 17:21:24 2020
 OS/Arch:         linux/amd64
 Experimental:    false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 14
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc docker-runc
Default Runtime: docker-runc
Init Binary: /usr/libexec/docker/docker-init-current
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: 66aedde759f33c190954815fb765eedc1d782dd9 (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: fec3683b971d9c3ef73f284f176672c44b448662 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker/seccomp.json
 selinux
Kernel Version: 3.10.0-1062.18.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 4
Total Memory: 3.7 GiB
Name: localhost.localdomain
ID: YWTB:P3C4:VQQP:XD5M:GIIW:JBMV:DTWB:PBRB:5JHQ:DCUF:VFL6:UIAU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Registries: docker.io (secure)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running inside VirtualBox

**Comment by cpuguy83** [comment]
I'm pretty sure this is intentional.
Ping @tonistiigi

**Comment by tonistiigi** [comment]
Yes, this is so that the content of the tarball stays deterministic.

**Comment by davecramer** [comment]
how are you supposed to save and import an image then ?

**Comment by tonistiigi** [comment]
Importing an image tarball has no requirements for the manifest.json date.

**Comment by davecramer** [comment]
But the container config is not imported if the date is not current. If I change the date of manifest.json to the current date and put it back in the tarball then the config is imported. Otherwise it is lost.

**Comment by tonistiigi** [comment]
No, `manifest.json` timestamp does not change `docker load` behavior.

**Comment by davecramer** [comment]
ok, perhaps I am confusing load with import? I was getting this behaviour with docker import.

**Comment by tonistiigi** [comment]
What you want is `docker load`. `docker import` is opposite of `docker export` and takes a tarball containing the raw container filesystem without any specific defined format

**Comment by davecramer** [comment]
k, thanks
