### ISSUE TITLE
docker run -v "$(pwd):/src"... silently breaks in Git Bash

### ISSUE THREAD

**Issue by mcandre** [docker/cli#2460]
When the volume option is used in Git Bash, the path becomes malformed in the container. No errors or warnings are displayed.

I found this by trying to mount a local tyk clone into library/golang for building on a Windows host.

* The specified target path is ignored.
* The target path uses Windows notation.
* The target path is rendered as one long name rather than a nested directory structure.

Please detect when `docker` launches in a Git Bash / Cygwin / MSYS / MinGW / WSL environment, and update the volume mounting logic accordingly.

**Comment by mcandre** [comment]
Update: `docker -v` also misbehaves in WSL. When you try to mount a file this way, Docker proceeds to mount an empty directory.

This does not happen on macOS hosts, only Windows hosts using WSL, Git Bash, etc.

**Comment by thaJeztah** [comment]
Can you given an example of the path you're providing and what happens?

I suspect this is the same as mentioned in https://github.com/moby/moby/issues/31370#issuecomment-282758977 and https://github.com/moby/moby/issues/13741#issuecomment-128893740

> That's a known issue ("feature") of mingw. mingw is trying to be smart. See https://github.com/docker/docker/issues/13741#issuecomment-128893740, and http://www.mingw.org/wiki/Posix_path_conversion
>
> you can also try using a double-slash for paths;  `-v //foo/bar/`
>
> Note that the mount-path inside the container must be an _absolute_ path, so using `~/` or `./` is not a valid format. You need to specify an absolute path inside the container (e.g. `/home/foo/something`).


If that's indeed the case, I don't think there's much we can do; those paths are converted before docker receives them, so we wouldn't know what the original path was, so the best solution is to either use the double slash prefix, or set the `MSYS_NO_PATHCONV=1` environment variable to disable that functionality

**Comment by thaJeztah** [comment]
closing as this went stale
