### ISSUE TITLE
feature request for override ENV option

### ISSUE THREAD

**Issue by justinphebey** [docker/cli#2463]
Feature request for sticky env variables / override option so you could easily influence how an upstream image builds it's layer in your own project, such as;

e.g. my project based on the upstream tomcat image:

--ENV CATALINA_HOME /some/other/path
FROM tomcat:8.5.54-jdk8-openjdk
...

Where an ENV is declared with -- it should be elevated to a sticky status and hold on to the value declared / override any value encountered for this variable later in the chain of processing the Dockerfile.

Therefore this could be used at the beginning of a Dockerfile if you wanted it to take precedence over any further encounter of the same variable.  Would also allow for flexibility depending on where in the Dockerfile it was placed, for references to the same ENV higher in the file to be independent, possibly where an unintentional clash of naming occurs.

At present you can't place an ENV variable higher than the FROM statement as this causes an error and would not be consistent anyway with expectations of such a variable not being reset to whatever is encountered lower in the Dockerfile.  This proposal would enhance the ability to make use of existing images instead of forking existing Dockerfile contents which is messier to maintain.

**Comment by thaJeztah** [comment]
This won't work, because `FROM tomcat:8.5.54-jdk8-openjdk` uses the image `tomcat:8.5.54-jdk8-openjdk` but does not build it, so overriding the ENV var won't make any changes to that image that depend on the environment variable during build

**Comment by justinphebey** [comment]
> This won't work, because `FROM tomcat:8.5.54-jdk8-openjdk` uses the image `tomcat:8.5.54-jdk8-openjdk` but does not build it, so overriding the ENV var won't make any changes to that image that depend on the environment variable during build

I thought it was using this one:
https://github.com/docker-library/tomcat/blob/69651de48dbaede28806408828f42d68409bd1df/8.5/jdk8/openjdk/Dockerfile

**Comment by thaJeztah** [comment]
That's the Dockerfile used to build the `tomcat:8.5.54-jdk8-openjdk` image yes, but if you run `FROM <some image>`, then you're using the image that was already built, so changing an environment variable that was used during build of that image won't make changes to what's already built, e.g. https://github.com/docker-library/tomcat/blob/69651de48dbaede28806408828f42d68409bd1df/8.5/jdk8/openjdk/Dockerfile#L86 is already baked into that image

**Comment by justinphebey** [comment]
> That's the Dockerfile used to build the `tomcat:8.5.54-jdk8-openjdk` image yes, but if you run `FROM <some image>`, then you're using the image that was already built, so changing an environment variable that was used during build of that image won't make changes to what's already built, e.g. https://github.com/docker-library/tomcat/blob/69651de48dbaede28806408828f42d68409bd1df/8.5/jdk8/openjdk/Dockerfile#L86 is already baked into that image

I see, in that case perhaps there should be a FROMFILE option that takes a URL to a Dockerfile in addition to overridable ENV variables.

**Comment by thaJeztah** [comment]
Building the Dockerfile most of the time also requires the source-files related to the Dockerfile, so just the dockerfile won't really work.

If you're specifically interested in that Dockerfile; to customise settings during build, you can use build-args (if the Dockerfile has them specified), so for example, to make that `` configurable, the Dockerfile could be changed to;

```dockerfile
ARG DEFAULT_CATALINA_HOME=/usr/local/tomcat
ENV CATALINA_HOME=$DEFAULT_CATALINA_HOME
```

Or

```dockerfile
ARG CATALINA_HOME
ENV CATALINA_HOME=${CATALINA_HOME:-/usr/local/tomcat}
```

But you'd have to build the full image yourself, and pass the `--build-arg CATALINA_HOME=/my/custom/path`.

**Comment by justinphebey** [comment]
> Building the Dockerfile most of the time also requires the source-files related to the Dockerfile, so just the dockerfile won't really work.
> 
> If you're specifically interested in that Dockerfile; to customise settings during build, you can use build-args (if the Dockerfile has them specified), so for example, to make that `` configurable, the Dockerfile could be changed to;
> 
> ```dockerfile
> ARG DEFAULT_CATALINA_HOME=/usr/local/tomcat
> ENV CATALINA_HOME=$DEFAULT_CATALINA_HOME
> ```
> 
> Or
> 
> ```dockerfile
> ARG CATALINA_HOME
> ENV CATALINA_HOME=${CATALINA_HOME:-/usr/local/tomcat}
> ```
> 
> But you'd have to build the full image yourself, and pass the `--build-arg CATALINA_HOME=/my/custom/path`.

Thanks for the suggestion.

The thing I was aiming to avoid was reinventing the wheel or copying an existing Dockerfile severs a link to its upstream maintenance. 

Whilst being true that a Dockerfile can require source files to be present to copy in to an image, that doesn't mean that should be best practice instead of those files being in a public repository if the Dockerfile itself is open source.  In fact if the Dockerfile had been included as it's own layer in the image it should have enabled selectively overriding aspects of it so that some or all of the cache layers were rebuilt.  

I just think some improvements could be made which would improve the Docker experience in so much as making the build process more powerful and dynamic.

**Comment by thaJeztah** [comment]
> The thing I was aiming to avoid was reinventing the wheel or copying an existing Dockerfile severs a link to its upstream maintenance.

The Dockerfile is the "recipe" to build an image (a bit similar to a `Makefile`), roughly, this feature request would be similar to "I have a `.deb` / `.rpm` package, and want to install it, but change the compile options that were used when it was created". The `.deb` won't contain the source code used to build the package (similar to how the image may not contain the source - for example, if a multi-stage image is used, the intermediate stages are not present in the final image), so to rebuild the package (image), you'd need a "source package"; for `.deb` / `.rpm` package, that would be a source-rpm/source-deb package, for Docker images there's no such equivalent, so you'd need the (GitHub) source repository to build.

Overriding options for building depends on the Dockerfile (just as a `Makefile` _could_ have Makefile variables to override options when building); the maintainers of the image / Dockerfile you took as an example did not add variables to override these settings, so there's no option to change those, other than cloning the upstream source repository and modifying the Dockerfile, or clone the upstream repository and build with a custom Dockerfile.

If the Dockerfile _did_ provide `ARG`'s to customize the build, rebuilding would already be possible. For example; I just updated this repository https://github.com/thaJeztah/angry-unicorn to provide some build-args in the Dockerfile

You can pass the `TOP_MSG`, `BOTTOM_MSG` and/or `LISTEN_PORT` build-args when building the image to customize it;

```bash
docker build -t angry-unicorn --build-arg TOP_MSG="hello world" https://github.com/thaJeztah/angry-unicorn.git
```

> In fact if the Dockerfile had been included as it's own layer in the image it should have enabled selectively overriding aspects of it so that some or all of the cache layers were rebuilt.

From the above; even with the dockerfile included in the image, you wouldn't be able to rebuild the image. In addition, there's different ways to build an image than using a Dockerfile (e.g., there's build-tools that create an image by automating `docker run` and `docker commit` steps, or using BuildKit with a different "front-end").

**Comment by thaJeztah** [comment]
let me close this issue
