### ISSUE TITLE
FR: 'docker ls'

### ISSUE THREAD

**Issue by flancian** [docker/cli#2467]
Feature request: 'docker ls'. It could iterate over every command that has an 'ls' subcommand. Provides an overall view of all docker state. 

As a new docker user, I've found myself wanting to reach for such a command often. Perhaps it's a new-user need only; but if you think this could be useful it doesn't seem too hard to implement as a starter community contribution.

**Comment by AkihiroSuda** [comment]
There is already `docker container ls`

**Comment by thaJeztah** [comment]
I don't think this fits well with the current UX (`docker <object> <verb>`); in addition, each object (containers, volumes, images) may have options that are specific to the type of "object" you're interacting with, so combining them to a single command would be complicated.

I'm closing this issue, but thanks for suggesting 🤗
