### ISSUE TITLE
broken link to Parent Image entry in glossary

### ISSUE THREAD

**Issue by johnmcwade** [docker/cli#2482]
**Description**

When browsing the online reference material, a hyperlink in the Dockerfile reference appears to be broken at the moment.

**Steps to reproduce the issue:**
1. Go to https://docs.docker.com/engine/reference/builder/
2. Scroll to Format section or use the link for the Format topic in the right sidebar.
3. In the sentence which reads 'The FROM instruction specifies the Parent Image from which you are building.'  click on the link where the link text is 'Parent Image'
4. This currently brings you to https://docs.docker.com/engine/reference/builder/glossary.md#parent-image

**Describe the results you received:**

Received the 'Sorry not found' page content

**Describe the results you expected:**

Expecting to read about Parent Images in the documentation.

**Additional information you deem important (e.g. issue happens only occasionally):**

This occurs in the online Dockerfile reference , not the docker command line tool, hence the N/As below.

**Output of `docker version`:**

```
N/A
```

**Output of `docker info`:**

```
N/A
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
Thanks for reporting; this looks like the same issue as reported in https://github.com/docker/docker.github.io/issues/10710, and will be fixed by https://github.com/docker/cli/pull/2481

**Comment by thaJeztah** [comment]
https://github.com/docker/cli/pull/2481 was merged, and will be published on docs.docker.com soon (probably tomorrow); I'll go ahead and close this ticket

**Comment by johnmcwade** [comment]
Looks good, thanks
