### ISSUE TITLE
missing documentation for swarm events

### ISSUE THREAD

**Issue by albers** [docker/cli#252]
https://github.com/moby/moby/pull/32421 added 
- new event types: `service`, `node` and `secret`
- a new `scope` filter. 
- new events (which events?)

These changes should be documented in the CLI reference docs.

**Comment by allencloud** [comment]
Yeah, I think new event for `config` is also need in moby/moby and docker/cli.

**Comment by dnephin** [comment]
I believe that #314 resolved this, so I'm going to close the issue. If there's still something missing let me know, and I can re-open
