### ISSUE TITLE
exec foo in docs/reference/commandline/cp.md

### ISSUE THREAD

**Issue by jayvdb** [docker/cli#253]
[docs/reference/commandline/cp.md](https://docs.docker.com/engine/reference/commandline/cp/) contains the following:

> ... However, you can still copy such files by manually running tar in `docker exec`. Both of the following examples do the same thing in different ways (consider `SRC_PATH` and `DEST_PATH` are directories):
>
> `$ docker exec foo tar Ccf $(dirname SRC_PATH) - $(basename SRC_PATH) | tar Cxf DEST_PATH -`
>
> `$ tar Ccf $(dirname SRC_PATH) - $(basename SRC_PATH) | docker exec -i foo tar Cxf DEST_PATH -`

(and that also appears in the man page)

I found the use of `foo` in those examples to be a bit confusing.  The man pages usually use `CONTAINER` to when a container name is expected.

**Comment by Zebrilee** [comment]
Hi @dnephin ,

I can modify it like this:
`$ docker exec CONTAINER tar Ccf $(dirname SRC_PATH) - $(basename SRC_PATH) | tar Cxf DEST_PATH -`
`$ tar Ccf $(dirname SRC_PATH) - $(basename SRC_PATH) | docker exec -i CONTAINER tar Cxf DEST_PATH -`

I also found an example based on "my_container" in [docker exec's doc](https://docs.docker.com/engine/reference/commandline/exec/#extended-description). Which would give:

`$ docker exec my_container tar Ccf $(dirname SRC_PATH) - $(basename SRC_PATH) | tar Cxf DEST_PATH -`
`$ tar Ccf $(dirname SRC_PATH) - $(basename SRC_PATH) | docker exec -i my_container tar Cxf DEST_PATH -`

Does one of these suggestions sounds good to you?

**Comment by thaJeztah** [comment]
I think both are good solutions; so pick either one :+1:

**Comment by Zebrilee** [comment]
Hi @thaJeztah ,
thanks for the reply, the PR will follow

**Comment by vdemeester** [comment]
Closed by #399
