### ISSUE TITLE
`docker container run --g[TAB]` no `--gpus` completion for `zsh`

### ISSUE THREAD

**Issue by yantaozhao** [docker/cli#2549]
**Description**

**Steps to reproduce the issue:**
1. In `zsh` shell prompt, input `docker container run --g[TAB][TAB]`, there's no `--gpus` completion shows in the candidates.

**Describe the results you expected:**
In `zsh` shell prompt, when press [TAB][TAB] to trigger the completion, the `--gpus` option should shows, along with such as `--group`, in the candidates.

Moreover, followed with the value set of `all` and `device=` would be better (i.e.: --gpus [all device=] ), just like the `--network` ways.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
% docker --version 
Docker version 19.03.8, build afacb8b7f0
```

**Output of `docker info`:**

```
$ docker info     
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 6
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.0.0-32-generic
 Operating System: Ubuntu 18.04.4LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.55GiB
 ID: WZP2:QT4J:PRAA:ZXIF:JMXR:TLOL:ZES3:MX7S:5QOQ:4C7N:7IMY:65CZ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Ubuntu 18.04LTS 64bit

**Comment by 0xfaust** [comment]
I'm happy to take a look at this! I have also reproduced the issue and it appears that there is a problem with all of the `--g[TAB]` flags as `--g[TAB]` is completing to `--groups` which is an unknown flag, the intended flag is `--group-add` which also does not autocomplete.

**Comment by rchenzheng** [comment]
WIP on my end, I need to do some cleanup before posting my first PR 🥇
