### ISSUE TITLE
Feature Proposal: Copying activity indicator for docker cp command

### ISSUE THREAD

**Issue by jeffabailey** [docker/cli#2564]
When running this command show an activity indicator.

`docker cp`

When running it could some sort of spinner like this.

https://www.shellscript.sh/tips/spinner/spinner.gif

If progress doesn't start or fails midstream the spinner would stop.

**Comment by maximillianfx** [comment]
Good point @jeffabailey! @thaJeztah what do you think about expanding this to Dockerfile instruction COPY too? If you wish, I can contribute whit this.

**Comment by jeffabailey** [comment]
Sure, I don't know the internals enough to make the greatest judgment call.

It sounds reasonable to me.

**Comment by maximillianfx** [comment]
@thaJeztah how are you? Can you help me in the PR with tests/coverage?
