### ISSUE TITLE
Custom object types in compose file

### ISSUE THREAD

**Issue by archisgore** [docker/cli#261]
I wanted to file a feature request to begin a conversation on this. I'll also state that once we arrive at a good design or even basic agreement that this feature will be allowed, we are willing to contribute the code needed to do this.

We at Polyverse build tools that utilize docker and swarm and create very complex stacks from simple definitions. Today we go through a great deal of trouble in adapting our Polyverse definition into compose definitions which cause a maintenance nightmare for us and our customers.

What I would love to see - and this can be quite generic and I imagine open up a lot of scenarios, is provide the ability (through plugins, perhaps) of supporting new types of parameterized "things" in compose that are higher-level constructs built using the swarm-provided primitives.

A great example of this is Etcd. I can imagine the following workflow:

```
docker plugin install etcd
```

This would install a CLI Plugin that understands "etcd" as some sort of higher-level construct.

You could then run sub commands:
```
docker etcd ...
```

Or the more important part, add definitions in a compose file:
```
etcds:
  cluster1:
    name: passwordStore
    size: 3
```

That would then get converted into API calls to start the number of components, in the right order, wire them together, etc.

This would also allow the plugin to parse "state of the object" where you might probably not want to see all etcd services, but instead view them as "clusters"

```
docker etcd ls

Listing etcd clusters
Name                                      Size
passwordStore                       3
```

Such a feature would allow for an incredible amount of specification power where sub-groups or patterns could be encapsulated into plugins that could then be reused as more logical concepts downstream.

**Comment by archisgore** [comment]
I also wanted to note that this is very similar to what Kubernetes has with their Custom Resource Definitions - CRDs. Higher level "things" that are created out of services, networks, etc. on a swarm.

**Comment by dnephin** [comment]
With the `etcd` example above how is this different from defining a service with the name `passwordStore` which runs an etcd image, and has 3 replicas?

My concern with this proposal is that it muddies the distinction between "Docker concepts" (services, network, volumes, etc) with "user defined services". I'm not really clear on why this is a good thing. Personally it seems like it would make both the CLI and config much harder to understand.

**Comment by archisgore** [comment]
So I'll add more color to this. And I'm writing up a different deeper proposal that captures a lot of this. I recognize that I failed to establish much background here, which makes my feature request a bit shallow.

First of all, and quite shamelessly, it would MASSIVELY help our product (from my company Polyverse) to be easily consumable by docker end users. Today we build on top of Docker and have a parameterized solution (think Compose files akin to a cloud formation stack) which makes more sense when viewed as a "system" than as a set of 400-500 containers (could be potentially thousands to millions on a swarm.) There's a lot of wiring and networking that is obvious and simple, but could do with automation. Now the obvious answer here is - "Wrap the swarm API" which is where we already are.

This is also why I mentioned Kubernetes's CRDs as an example - a concrete example that this concept is not only sound, but also validated by a second party that it is useful to define custom resources sometimes. On Kubernetes, we don't need a wrapper over YAML files. People can define a CRD with 500 containers, and we can launch them and create network policies. But this policy can be CRUD-managed over the REST API as a logical piece.

Secondly, the reason for mentioning etcd, above something symmetric like say, nginx, was SPECIFICALLY because you cannot run an etcd cluster as a service of scale 3. Other things that fall into a similar category are Elastic Search clusters that I know of.

Last I checked, individual service tasks do not have stable names (names predictable before they are launched), and they are also not reachable by name over an overlay network (you can't go to service.1.sha directly by name).

This means that the best way to run an etcd cluster today is to start three distinct services and they must be done in that order, with some coordination of their startup parameters. Scaling it up, requires some imperative operations such as adding it to an existing cluster, then launching the process that serves it.

In my opinion, the current situation makes the config much harder to launch etcd. If I had to send you instructions to launch an etcd cluster right now, I could probably send you a compose file. If I had to tell you to scale it up, it would be a multi-step list of commands which can be cumbersome.

I'm not necessarily saying that these concepts need to be "peers" of Docker concepts - that was my bad, and not something I really have my heart set on. It's more about having higher-level abstractions that can be managed as a logical unit.

When you have multiple etcd clusters on top of a swarm, for instance. It makes more sense to send commands about mananging them as "cluster1" instead of looking for service "etcd_cluster1_service1". Think about also having a logical p2p internal overlay network that they use for peer coordination vs an external network for client connections.

I can see it being quite a compelling thing to launch etcd "right" and be able to scale it up and down as a logical concept. I can see this being useful for a lot of other things - in addition to being supremely helpful for Polyverse.

**Comment by dnephin** [comment]
>  It's more about having higher-level abstractions that can be managed as a logical unit...it makes more sense to send commands about mananging them as "cluster1"

This sounds like `docker stack`. Is it different ?

**Comment by archisgore** [comment]
Let me approach this another way. I'll present the problem here:

Can you send me a docker stack example of a 3-container Etcd cluster?

Also tell me how to scale it to 7 machines seamlessly, and then scale down to 5 machines?

How would you do this today?

**Comment by archisgore** [comment]
Literally any system with a Master/Slave asymmetry (Etcd, Elastic Search, Redis, Failover/Replicated SQL servers, NSQ, etc.) would benefit from such a feature.

Basically swarm services are very powerful for launching "replicas", but there are a dozen services where all things behind a service are not the same or identical. Now they're not different enough to be separate types of containers. They're different in terms of the data they hold, rather than the code they run.

Can these be done through Docker Stack? Yes of course. :-) Anything can be done using Docker Stack. But that's like saying "Can we do stuff with docker without docker?" The answer is an unequivocal and technically accurate "yes".

Docker isn't "necessary". Swarm isn't "necessary". I can launch 5 etcd's today just fine without Docker.

I'm hoping that I don't have to defend this request in the sense of "Why can't you just do this using what we have?" - I'll admit I can. This is a common argument in any corporation "Why do we need Docker? What we have works."

But I'm begging the audience from Docker to look at the promise of Docker: "If you can package something in a box of a certain size, and a certain weight, and put it with a certain interface - doors that lock a certain way, boxes that stack a certain way, then we can run it."

What I'm talking about here is that there are a large number of services that don't just scale out by launching five more replicas. Sometimes even if they did, there might be more useful and cool things that can be done - an example would be pair overlay networks between two containers of that service. And those things are automatable but parameterized.

And this isn't quite "Stack within a stack". It is semantically very different.

**Comment by dnephin** [comment]
I understand that some of the stock images out there are not designed to work correctly with stacks and swarm mode, but with the correct configuration I believe it is possible to run them as a stack. I'm not familiar with etcd, but if you could elaborate on the problems with using replicas I might be able to suggest a solution.

One solutions I have seen is to use an entrypoint script to do some work before starting a new instance. 

This [blog post](http://derpturkey.com/elasticsearch-cluster-with-docker-engine-swarm-mode/) suggests it is possible to run Elasticsearch with replicas given the right config. The `endpoint_mode` was added to compose file version 3.2 so that is no longer a manual step.

> Last I checked, individual service tasks do not have stable names (names predictable before they are launched), and they are also not reachable by name over an overlay network (you can't go to service.1.sha directly by name).

All tasks should be accessible by their task name I believe.

--- 
I'm not sure how a configuration file solves these problems. Maybe with more detail about the problems I will better understand.

**Comment by archisgore** [comment]
*Sigh*

Yes I read that blog post. It doesn't talk about migrating data off an Elastic Search node to other nodes before it is taken out, etc. etc.

And like I said - I fully admit that entry point's can do some stuff. Introspection can do other stuff.

Today there is no consistent way for any arbitrary task to introspect about the swarm. Again I know what you're going to say "It can be done".

So I need to send swarm endpoint credentials through the stack, into every task along with certs/creds to call into the endpoint. So just to enumerate my peer tasks, I have to do a lot of scaffolding. Can `docker stack` automatically provide the swarm credentials as metadata into a container? No. So what do I do?

1. Figure out what your docker ENV settings are to connect to the swarm
2. Set some variables/parameters in the compose file.
3. But wait - if the machines where the swarm is running can't reach that remote address, it might be different settings.
4. Then "docker stack up" should do it.

Now I'll explain the problems with Etcd. Also, this question was explicitly asked at DockerCon, so this is a well known accepted problem in the swarm world. Also to save a lot of time prove that I'm not making this up or haven't explored every possible avenue, here's a link from DockerCon 2017, less than two months ago: https://youtu.be/Mw4ImA2IB10?t=38m14s

At time 38:14 is a question asked, to which I'm proposing a possible solution here. These are Swarm developers who're saying why this doesn't work. So I promise you I'm not overlooking something obviously trivial on a "stack". You'll notice the Swarm speaker mentions, "People try to create a different service..."

But here goes the deeper explanation here:

Etcd is a distributed Key-Value store where all members of the cluster join other members in the cluster. You need to pass parameters at startup, to all members, what the other member names are.

For example:
```
docker service create --name etcd1 quay.io/coreos/etcd -initial-cluster "etcd1=etcd1:2379,etcd2=etcd2:2379"

docker service create --name etcd2 quay.io/coreos/etcd -initial-cluster "etcd1=etcd1:2379,etcd2=etcd2:2379"
```
(There's some more parameters I've excluded for brevity.)

Now imagine wanting a cluster of five etcd's. You have to run 5 separate services and change a lot of parameters. What I'm suggesting is - this entire expansion of params is automatable. Its not as trivial as saying "docker service update etcd..." but it doesn't have to be quite as complicated as having to add more entries to a compose file to create 5 services and modify a bunch of parameters.

All that's really needed is a thin translation layer that can capture this requirement of 5 etcds and translate them into service primitives.

**Comment by dnephin** [comment]
Thanks for elaborating. There are a few features being discussed here so I'd like to see if I can summarize them:

* "declarative tasks" - some way to define multiple API operations to form workflows (from: "migrating data off an Elastic Search node to other nodes before it is taken out")
* "introspection" - https://github.com/moby/moby/issues/8427 (from: "there is no consistent way for any arbitrary task to introspect about the swarm")
* "dynamic values in a stack" - (from "You need to pass parameters at startup, to all members, what the other member names are.")


I'd really like to see a declarative tasks feature implemented. 
Introspection would have to be implemented in the engine (there's already an issue for it).

Since those don't exist yet, it seems like your next option (and what this issue proposes) is to support some way of generating these stacks from a higher level config. It seems to me like there is some application specific logic required. How would the client know that it needs to generate this list of hosts? Where does that logic live? If it's application specific it doesn't really belong in the docker client.

If you had a script which generated a compose file, I think you could run `docker stack deploy` with the generate config and that would work to update services when a new instance of the service is added.

**Comment by archisgore** [comment]
Yes you're absolutely right! And I'm totally not faulting that.

Where I'm coming from is, I think all these features are good and needed on their own, but they could be driven by an over-arching narrative. A compelling end-user use-case that would make sure they are developed and work in harmony.

For me that use case is related to these complex stacks which are more proactive than being passive like a compose file. Stacks that can be packaged with parameters exposed, small scripts run  before they are launched, etc. etc. which is why I called it a plugin.

I see this as being a significantly missing narrative across all orchestration platforms, and I'm happy to play a part in making Swarm to be the first to have it. Kubernetes has CRDs and Service Accounts (any pod can speak to the API). It's close, but there's no formal interface model, distribution model, etc. The part of sending someone a CRD implementation is still... well highly manual.

Docker Engine+SwarmKit has this beautiful interface called "docker plugin install ..." and a perfect socket-based interface for engine to talk to plugins. It's elegant and simple and wonderful.

To me, if the plugin had two more features:
1. A service account to the API and a transparent API that it can call.
2. A way to expose to the CLI "commands" the plugin supports. The commands might be under a name-space - I've taken to calling it a "ship" (as in a container ship - a group of containers in one ship that is independently named and operated and managed - above a homogenous swarm service, but below a full application stack.)

Then this opens up some incredibly powerful scenarios for both users of docker. Instead of looking at the problem from the Docker side, let's invert it to look at it from the customer side. I could send you or anyone a "ship" that can run a distributed wordpress, with a sharded failure-tolerant redis, and a distributed live-failover MySQL instance.

None of this is impossible to do today, however, it has no way to be "captured" in code. So we are stuck between two abstractions.
1. On the lower end you have microservice containers - Wordpress, Redis and MySQL.
2. On the upper end you have a full application stack, with all decisions already made - the networks, the wiring, the DNS lookups, secrets, etc. etc.

I could even see myself selling this "ship" on the Docker Store for lots of money - it would capture my tribal knowledge in a way that is accessible and consumable by anyone who runs Docker Engine in Swarm Mode. They wouldn't have to read blogs and interpret them and edit config files, etc. etc.

I also want to clarify I'm a huge fan of Docker and Swarm, and am not really faulting anyone here. this is a new scenario, and in my opinion, before Docker, I couldn't have ever pulled it off or even thought of such a thing.

So I'm merely advocating that this be a kind of overarching vision that is based off this problem statement: "How do we enable anyone who is running Docker Swarm or UCP, to run a distributed load-balanced wordpress, with a distributed sharded, replicated and live-failover redis cache, with a distributed live-failover MySQL by simply specifying scale parameters, and managing the rest?"

And then work backwards from there.

**Comment by sam-thibault** [comment]
This is an old issue.  If you are looking to extend compose the definition is here:
https://github.com/compose-spec/compose-spec
