### ISSUE TITLE
Adding service labels does not update existing labels.

### ISSUE THREAD

**Issue by dougcooper** [docker/cli#2647]
**Description**

When adding service labels, labels with the same key are appended and not updated. 

**Steps to reproduce the issue:**
1. docker service update --label-add key=value1 service
2. docker service update --label-add key=value2 service
3.

**Describe the results you received:**

when inspecting the service both values appear for the same key.

**Describe the results you expected:**

value2 should replace value1. This is the behavior of adding labels to nodes.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

Docker version 19.03.12, build 48a66213fe

**Output of `docker info`:**
Client:
 Debug Mode: false

Server:
 Containers: 5
  Running: 1
  Paused: 0
  Stopped: 4
 Images: 7
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: zjb1g0pq0ip4sk414kmbk27i4
  Is Manager: true
  ClusterID: xb41xlw59nn44n9368p6ntijv
  Managers: 1
  Nodes: 3
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 172.23.168.60
  Manager Addresses:
   172.23.168.60:2377
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.4.0-62-generic
 Operating System: Ubuntu 16.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.78GiB
 Name: DF_MAIN
 ID: AV5U:3CJI:XTPU:VEWQ:DEUD:ALUO:VYPI:ZF2Y:ID5E:3CJS:FCLW:RPWI
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

**Additional environment details (AWS, VirtualBox, physical, etc.):**
vSphere

**Comment by thaJeztah** [comment]
Can you provide the exact steps to reproduce? I'm trying to reproduce, but I don't see the issue appear. Labels use a "map" in the service spec, so it should technically not be possible to have two values for the same key;


Create a service

```bash
docker service create --name=myservice nginx:alpine
```

Update the service, and set label `key` with value `value1`:

```bash
docker service update --label-add key=value1 myservice
docker service inspect --format '{{ json .Spec.Labels}}' myservice
{"key":"value1"}
```

Update the service, and set label `key` with value `value2`:

```bash
docker service update --label-add key=value2 myservice
docker service inspect --format '{{ json .Spec.Labels}}' myservice
{"key":"value2"}
```


Were you perhaps looking at the "previous" version of the service? If you `docker inspect` a service, both the _current_ and _previous_ specs are returned (which is used to allow rolling back to a previous version);

```bash
docker service inspect --format '{{ json .Spec.Labels}}' myservice
{"key":"value2"}

docker service inspect --format '{{ json .PreviousSpec.Labels}}' myservice
{"key":"value1"}
```

So if you "grep" the output, both will be found;

```bash
docker service inspect foo | grep key
                "key": "value2"
                "key": "value1"
```

**Comment by dougcooper** [comment]
I wasn't sure if multiple values for the same key with container labels was expected behavior. When I update node labels this is not the case - it replaces the current value of an existing key.

**Comment by thaJeztah** [comment]
It's not setting multiple values for the same labels; see the output of 

```bash
docker service update --label-add key=value2 myservice
docker service inspect --format '{{ json .Spec.Labels}}' myservice
{"key":"value2"}
```

**Comment by dougcooper** [comment]
I understand my confusion now. Thanks for explaining that.
