### ISSUE TITLE
Use docker stack deploy without swarm

### ISSUE THREAD

**Issue by fdellabetta** [docker/cli#265]
Feature request:
Is it possible to use docker stack without swarm (and maybe call it docker compose) ?
See also docker/compose#4969

**Comment by dnephin** [comment]
`docker stack` is designed to work with swarm mode. It will never work with non-service containers. You can use `docker-compose` to run containers without swarm mode.

**Comment by fdellabetta** [comment]
But why another tool (docker-compose) to do nearly the same, or better, less ?
According to "Batteries included, but replaceable", and IMHO I think docker-compose should become docker compose...
