### ISSUE TITLE
Error response from daemon: invalid IP address in add-host: "host-gateway".

### ISSUE THREAD

**Issue by pheel** [docker/cli#2664]
```
❯ docker --version
Docker version 19.03.12, build 48a66213fe
```
(via Docker Desktop CE 2.3.0.4 on MacOS)

https://github.com/docker/cli/pull/2337 adds a bit of code exempting `host-gateway` from validation. I was excited for 19.03.12 to come out on MacOS, to test if we could finally rely on `host.docker.internal` across platforms.

However:

```
❯ docker run --add-host host.docker.internal:host-gateway hey:latest
docker: Error response from daemon: invalid IP address in add-host: "host-gateway".
```

Any idea how this could be, given the PR referenced above?

**Comment by thaJeztah** [comment]
The feature itself is not yet in the Docker 19.03 (daemon); the PR removed the validation in the cli, delegating the validation to the daemon, so that once docker 20.0x is released, a 19.03 cli would be able to use the feature that the 20.0x daemon provides.

So this is currently expected.

Let me close this issue because of the above, but feel free to continue the discussion

**Comment by atilkan** [comment]
@DeltiKron Updating what exactly?

**Comment by gregorylegarec** [comment]
@DeltiKron same question than @atilkan :)

**Comment by akashp1712** [comment]
If anyone else facing the same issue in Docker version 19 or below, I've tried following technique and it worked for me.

`--add-host=host.docker.interna:$(ip addr show docker0 | grep -Po 'inet \K[\d.]+')
`

PS: I found above solution from StackOverflow answer, I'll place credit link once I find.

**Comment by elrokket** [comment]
> If anyone else facing the same issue in Docker version 19 or below, I've tried following technique and it worked for me.
> 
> `--add-host=host.docker.interna:$(ip addr show docker0 | grep -Po 'inet \K[\d.]+') `
> 
> PS: I found above solution from StackOverflow answer, I'll place credit link once I find.

how and where set this?

**Comment by g-kartik** [comment]
I am still facing this issue
Docker Compose version v2.23.3
Docker version 26.0.0, build 2ae903e86c

**Comment by Isuxiz** [comment]
> > If anyone else facing the same issue in Docker version 19 or below, I've tried following technique and it worked for me.
> > `--add-host=host.docker.interna:$(ip addr show docker0 | grep -Po 'inet \K[\d.]+') `
> > PS: I found above solution from StackOverflow answer, I'll place credit link once I find.
> 
> how and where set this?

As I tried, add this in `docker run ...`.

**Comment by XuHaodong-github** [comment]
> > > If anyone else facing the same issue in Docker version 19 or below, I've tried following technique and it worked for me.
> > > `--add-host=host.docker.interna:$(ip addr show docker0 | grep -Po 'inet \K[\d.]+') `
> > > PS: I found above solution from StackOverflow answer, I'll place credit link once I find.
> > 
> > 
> > how and where set this?
> 
> As I tried, add this in `docker run ...`.

How to do this in docker-compose

**Comment by Isuxiz** [comment]
> > > > If anyone else facing the same issue in Docker version 19 or below, I've tried following technique and it worked for me.
> > > > `--add-host=host.docker.interna:$(ip addr show docker0 | grep -Po 'inet \K[\d.]+') `
> > > > PS: I found above solution from StackOverflow answer, I'll place credit link once I find.
> > > 
> > > 
> > > how and where set this?
> > 
> > 
> > As I tried, add this in `docker run ...`.
> 
> How to do this in docker-compose

(in compose.yaml) services --> your_service --> extra_hosts

Note that commands are not allowed here, so either get ip in advance and write the constant directly, or use environment variables to provide dynamism.
