### ISSUE TITLE
Ubuntu container error: standard_init_linux.go:211: exec user process caused "no such file or directory"

### ISSUE THREAD

**Issue by f1am3d** [docker/cli#2681]
Docker version 19.03.12, build 48a66213fe

**Dockerfile:**
```
FROM ubuntu:18.04 AS q2pro-ded-duel-ubuntu

EXPOSE 27910
EXPOSE 27911

WORKDIR  /home/q2

COPY /quake2/q2proded .

RUN ls
ENTRYPOINT [ "./q2proded" ]
```

After successful build I run: docker run -it <image_id>
And get this error:

`standard_init_linux.go:211: exec user process caused "no such file or directory"`

I tested it on VM Ubunty and everything works correct.

I spend 2 days on this shit. What I'm doing wrong?

**Comment by cpuguy83** [comment]
How is q2proded compiled?
Might want to run `ldd /quake2/q2proded` and checking what it's linked to.

Usually this happens when the binary is linked to a toolchain that doesn't exist in the container.

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
