### ISSUE TITLE
DOCKER FOR WINDOWS - Fresh Install - Error saving credentials: error storing credentials - err: exit status 1, out: `error storing credentials - err: exit status 1, out: `A specified logon session does not exist. It may already have been terminated.``

### ISSUE THREAD

**Issue by owlyowl** [docker/cli#2682]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST
-->

**Description**

Attempting any login to a container registry is met with 

**Steps to reproduce the issue:**
1. docker login <container registry url>
2. enter username
3. enter password

**Describe the results you received:**
Error saving credentials: error storing credentials - err: exit status 1, out: `error storing credentials - err: exit status 1, out: `A specified logon session does not exist. It may already have been terminated.``

**Describe the results you expected:**
I would be able to log in to my azure container registry

**Additional information you deem important (e.g. issue happens only occasionally):**
Here is what I have tried:
1. I can see the credential in the windows credential manager
2. I have tried clearing that credential and logging back in again
3. I have checked windows event viewer with nothing of note
4. I have tried clearing out docker.config's entry for credsStore
5. I have checked that Network access: Do not allow storage of passwords and credentials for network authentication is disabled

**Output of `docker version`:**

```
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false
 Plugins:
  app: Docker Application (Docker Inc., v0.8.0)
  buildx: Build with BuildKit (Docker Inc., v0.3.1-tp-docker)
  mutagen: Synchronize files with Docker Desktop (Docker Inc., testing)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 11.71GiB
 Name: docker-desktop
 ID: HHR6:EUEN:NN7N:QBAB:QEST:MGOP:GMFX:YZDX:NLVE:VJDC:VXPO:MAGV
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 39
  Goroutines: 50
  System Time: 2020-08-17T21:16:47.191071156Z
  EventsListeners: 3
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  10.200.17.94:5001
  10.200.4.10:5000
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by owlyowl** [comment]
It turns out you cannot Docker login via an elevated shell depending on your environment as it appears the credentials don't get passed through

**Comment by apthagowda97** [comment]
Don't use the elevated shell while logging into any container registry.

**Comment by kernelzeroday** [comment]
I got this same error while using `docker build` from a powershell session over openssh for windows (installed with windows features panel), switching to a gui rdp cmd window fixed this error. very strange.

**Comment by apassy** [comment]
I got this same error while using `docker login` from a remote powershell session  ('Enter-PSSession -ComputerName'),  switching to a gui rdp cmd window fixed this error. very strange.

Docker 4.5.0 (74594), window 10 on both ends

**Comment by MichaelVoelkel** [comment]
I ssh into the server and seems rather uneasy from an elevated session to start a non-elevated session... Is there no way that docker can just run with elevated session, that is, login?

**Comment by jankap** [comment]
> I got this same error while using `docker build` from a powershell session over openssh for windows (installed with windows features panel), switching to a gui rdp cmd window fixed this error. very strange.

and

> I got this same error while using `docker login` from a remote powershell session ('Enter-PSSession -ComputerName'), switching to a gui rdp cmd window fixed this error. very strange.
> 
> Docker 4.5.0 (74594), window 10 on both ends

Same here. Remote loggin to Windows 10 via OpenSSH. That configuration should work. Can the ticket be re-opened?

**Comment by developerasun** [comment]
> I got this same error while using docker build from a powershell session over openssh for windows (installed with windows features panel)

same here

- Windows 11
- ssh remote
- Docker version 24.0.7, build afdd53b

**Comment by bf109f** [comment]
> I got this same error while using `docker build` from a powershell session over openssh for windows (installed with windows features panel), switching to a gui rdp cmd window fixed this error. very strange.

Have you solved this problem?

**Comment by bf109f** [comment]
see [Solution](https://github.com/docker/cli/issues/4353)

![Image](https://github.com/user-attachments/assets/5a746faf-22c2-4044-8378-d8e4c9d40a37)

**Comment by keith-miller** [comment]
I was having this issue on our build agents that run on Windows and our ECR repos. We had to add a step before running `docker login`:

```
echo $ecrRepo | docker-credential-wincred.exe erase
```

`$ecrRepo` being your ECR repo url, of course. I've leaving this comment for when I get stumped by this again in six months.

**Comment by keith-miller** [comment]
Even that doesn't work reliably. Spun up a new build machine and immediately got the `A specified logon session does not exist. It may already have been terminated.` error. If anyone knows of an alternative credential manager for docker on windows please let me know.

**Comment by silverham** [comment]
FYI - 2x workarounds:
**(1)** If you run and leave running the `sshd.exe` programs (ssh server) via an interactive cmd.exe command prompt, then ssh into the windows computer, then the error does not occur.

Cmd commands:
```cmd
powershell Stop-Service sshd
"C:\Windows\System32\OpenSSH\sshd.exe"
```

**(2)** Another way to move password from windows credential store to `C:\Users\<username>\.docker\config.json`

Cmd steps:
```cmd
echo https://index.docker.io/v1/ | docker-credential-desktop get
```

Or repeat for all servers:
```cmd
powershell -NoProfile -Command "$urls=(docker-credential-desktop list | ConvertFrom-Json).PSObject.Properties.Name; foreach($url in $urls){ $url | docker-credential-desktop get }"
```

shows:
```json
{"ServerURL":"https://index.docker.io/v1/","Username":"<username>","Secret":"<password>"}
```

then run (without <> characters)
```cmd
powershell "[System.Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes('<username>:<password>'))"
```
Shows
```
<base64-string>
```
Then adjust `C:\Users\<username>\.docker\config.json`
```diff
{
-	"auths": {},
+	"auths": {
+		"https://index.docker.io/v1/": {
+			"auth": "<base64-string>"
+		}
+	},
-	"credsStore": "desktop",
+	"credsStore": "",
	"currentContext": "desktop-linux",
	[...]
}
```
Should work straight away.
