### ISSUE TITLE
feature request: support regex in container/image names

### ISSUE THREAD

**Issue by sahildua2305** [docker/cli#272]
**Description**

I'd love to see regex for doing operations on matching containers or images or networks (so on). I'll be interested in working on it, if viable.

**Steps to reproduce the issue:**
1. Run multiple containers with names - `prefix_0`, `prefix_1` and `prefix_2`.
2. Try to `stop` or `rm` all of them using one docker command.
```
sudo docker rm prefix_[0-2]
```

**Describe the results you received:**
```
Error response from daemon: No such container: prefix_[0-2]
```

**Describe the results you expected:**
I'd expect it apply the operation on all matching containers.

**Comment by dnephin** [comment]
Stopping or removing things based on a pattern or regex seems pretty dangerous. It would be pretty easy to remove something unintentionally.

**Comment by sahildua2305** [comment]
@dnephin Yes, that's a fair argument.

Well then, we can have a flag for enabling regex in the command. Basically, the regex will be expanded only if that flag is present. This will guard against unwanted regex matching.

**Comment by sahildua2305** [comment]
Or alternatively, we can make it show the link of all items to be affected whenever the regex is passed. Asking for [Y/n] as a confirmation before performing the operation will be a safeguard while providing extra powerful feature to those wanting it.

**Comment by dnephin** [comment]
This is easy enough to do with `docker ps | grep ... | docker rm`. 

Since there is an easy way to accomplish this without adding to the docker cli, and since the addition would be potentially unsafe, I don't think we should add this feature.

**Comment by sahildua2305** [comment]
Yes, true that there's an easy way to do this but that involves basically 3 different commands piping their output to each other. Or the alternative is to have this as an alias.

However, if it can be included in the docker cli, it will potentially be one command. Regarding being unsafe, we can actually safeguard it whenever regexp is seen in the object name. (As I suggested in comments above).

**Comment by thaJeztah** [comment]
I'm with @dnephin on this one; I can see having regex support being "convenient" to have, but it's a sliding slope. Although there's already "feature creep", Ideally, docker would follow the Linux philosophy, [the first two rules stating](https://en.wikipedia.org/wiki/Unix_philosophy);

```
1. Make each program do one thing well. To do a new job, build afresh rather
   than complicate old programs by adding new "features".
2. Expect the output of every program to become the input to another, as yet
   unknown, program. Don't clutter output with extraneous information. Avoid
   stringently columnar or binary input formats. Don't insist on interactive input.
```

The risk here is that Regexes can quickly get complex; not just to _use_, also to implement _right_; implementing them for one command (`docker rm`, `docker stop`), implicitly adds a requirement to implementing it for _all_ commands. 

For your use case, consider filtering using other options, for example labels (`docker container rm --filter label=my.project.name=<projectname>`)

I'm closing this issue for now; rejecting a feature does not mean it will _never_ be implemented, just that at this moment we don't think it's needed. We can revisit in future if there's a strong use case that cannot be solved differently.

Thanks for opening this feature request though; even though it's not accepted, it is definitely appreciated 👍 (also, feel free to continue the conversation)
