### ISSUE TITLE
need option to disable /dev/shm

### ISSUE THREAD

**Issue by jelmd** [docker/cli#2795]
Right now there is no way to instruct docker to __not__ create a `/dev/shm` inside the container. Either --shm-size should accept 0 (disable, don't even create the mountpoint inside the container), or provide another option to be able to disable it.

**Comment by cpuguy83** [comment]
What's the use case for such an option?

**Comment by jelmd** [comment]
Deny /dev/shm use. Anyway, found a way: the `--ipc=none` option does exactly what we need.

**Comment by thaJeztah** [comment]
looks like this is resolved
