### ISSUE TITLE
Err: failed to register layer: ApplyLayer exit status 1 stdout:  stderr: no such file or directory 

### ISSUE THREAD

**Issue by kami1983** [docker/cli#2805]
I got an err, when I set up " --data-root=mydir " on MacOs 10.15.7
 
```
   $ docker pull centos 
   failed to register layer: ApplyLayer exit status 1 stdout:  stderr: no such file or directory  

```
What's the problem? Thanks.

**Comment by yanxianhe** [comment]
可能是新版的docker base Device Size默认只有10G，而你pull的image在解压的过程中所需的空间超过了这个size
--storage-opt dm.basesize

**Comment by thaJeztah** [comment]
I don't think Docker Desktop allows for the storage location inside the VM to be configured.

Let me close this ticket for now, as it looks like it went stale.
