### ISSUE TITLE
Docker build failing on raspberry pi (arm64)

### ISSUE THREAD

**Issue by stevenhurwitt** [docker/cli#2813]
**Description**

My docker build is failing on my raspberry pi with an arm64 os, but succeeds on linux. I'm not sure where to post this, but the error makes me feel like it's not using the proper binaries or something. It works pulling the ubuntu, python, & anaconda images but fails when I try to make a directory and copy my local one over.

**Steps to reproduce the issue:**
1. `sudo apt install docker.io` on raspberry pi 64-bit raspbian os (arm64)
2. `git clone https://github.com/stevenhurwitt/reliant-scrape` and `git checkout -b ubuntu`, `git pull origin ubuntu`
2. `docker pull stevenhurwitt/reliant-scrape:latest` and `docker build -t stevenhurwitt/reliant-scrape:latest .`
3. get this error message:

```
Step 9/23 : RUN mkdir -p /root/reliant-scrape
 ---> Running in be93657310bd
standard_init_linux.go:211: exec user process caused "exec format error"
```

**Describe the results you received:**
Error at [line 26 in this dockerfile](https://github.com/stevenhurwitt/reliant-scrape/blob/ubuntu/Dockerfile).

**Describe the results you expected:**
Dockerfile to build successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**
Issue happens only on raspberry pi.

**Output of `docker version`:**

```
Client:
 Version:           3.0.13+azure
 API version:       1.40
 Go version:        go1.13.11
 Git commit:        dd360c7c0de8d9132a3965db6a59d3ae74f43ba7
 Built:             Thu May 28 20:41:25 2020
 OS/Arch:           linux/arm64
 Experimental:      false

Server:
 Engine:
  Version:          3.0.13+azure
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.11
  Git commit:       77e06fda0c
  Built:            Mon Jun  1 20:23:47 2020
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false

Server:
 Containers: 7
  Running: 3
  Paused: 0
  Stopped: 4
 Images: 14
 Server Version: 3.0.13+azure
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.72-v8+
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 7.632GiB
 Name: raspberrypi
 ID: NPWK:HKRQ:VPTE:R2LJ:OKL3:LW2E:RKPA:EIGA:GL3L:6H3Y:BPAV:HS53
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No kernel memory TCP limit support
WARNING: No oom kill disable support
```

**Output of `uname -a`:**

```
Linux raspberrypi 5.4.72-v8+ #1356 SMP PREEMPT Thu Oct 22 13:58:52 BST 2020 aarch64 GNU/Linux
```

**Comment by stevenhurwitt** [comment]
getting the same error on my jetson nano's, which are also arm64

**Comment by thaJeztah** [comment]
The continuumio/miniconda3 image does not appear to be a multi-arch image, and is only available for x86 / amd64; https://hub.docker.com/r/continuumio/miniconda3/tags, so for that to work, you'd need to either build your own variant of that image that's compatible with other architectures, or ask the maintainers of that image if it's possible to provide a multi-arch image.

I see the dockerfile currently is using an x86 script, which is likely a line that needs to be updated for other architectures;

```dockerfile
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-4.5.11-Linux-x86_64.sh -O ~/miniconda.sh && \
...
```

Looking at the above, I don't think there's a bug to fix here, so I'll close this ticket, but feel free to continue the conversation

**Comment by stevenhurwitt** [comment]
shoot i'm an idiot! thanks so much for looking this over

**Comment by thaJeztah** [comment]
You're welcome! No worries, it's easy to forget not all images are multi-arch. Definitely ran into that myself a couple of times 😂
