### ISSUE TITLE
non root bind mount access

### ISSUE THREAD

**Issue by mskoenz** [docker/cli#2817]
**Description**

I am running docker-machine (version 0.16.2, build bd45ab1) on OSX (10.15.7 (19H2)) and am trying to do the following:
Mostly I write this issue, since others might have the same question.

- For good practice reasons, the user in the container should be non-root.
- I operate the docker-cli out of my OSX environment and run the container with a bind-mount.
- The container user should be able to write to this mounted folder
- But the permission is denied

**Steps to reproduce the issue:**
1. Create the following Dockerfile
```
FROM ubuntu:latest

RUN addgroup --gid 5000 container
RUN useradd --uid 5000 --gid 5000 --shell /bin/bash container
USER container

CMD echo `id` > log.txt
```
2. Build the image
```
docker build -t non-root .
```
3. Run the container with $PWD bind mounted:
```
docker run --rm -ti -v $PWD:/workdir:rw --workdir=/workdir non-root:latest
```
I will refer to this cmd-string as ```run_non_root```.

**Describe the results you received:**

The cmd ```run_non_root``` failed with
```
/bin/sh: 1: cannot create log.txt: Permission denied
```
The same happens if I add ```-u5000``` to ```run_non_root```

**Describe the results you expected:**

I would expect an option to specify the ownership of the mounted directory within the container.
Running ```run_non_root ls -la``` shows me that all files belong to:
```
...
-rw-r--r-- 1 1000 staff    16 Oct 23 19:41 .dockerignore
...
```

while running ```ls -la``` on my OSX terminal yields:
```
...
-rw-r--r--  1 mskoenz    16 Oct 23 21:41 .dockerignore
...
```

If I change the uid to 1000 in the dockerfile, it works, since the uid matches with what ```run_non_root ls -la``` shows.

I tried to create a user on the host (where the dockerd runs) with corresponding uid 5000 and group 5000, together with user remap, but it didnt work. (I might need to try harder)

Also using mount instead of -v also didnt show me more options regarding ownership.

Is there something special about uid 1000? (I know its the docker user on the host from cat /etc/passwd)

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Docker version 19.03.13, build 4484c46
```

**Output of `docker info`:**

<details>
  <summary>Click to expand!</summary>
```
Client:
 Debug Mode: false

Server:
 Containers: 159
  Running: 1
  Paused: 0
  Stopped: 158
 Images: 223
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.130-boot2docker
 Operating System: Boot2Docker 19.03.12 (TCL 10.1)
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 985.4MiB
 Name: local
 ID: WEJA:LZUZ:2QLB:P6B7:Z7EP:RL5X:DZQC:RM6V:DH3T:G3CD:546R:PIOH
 Docker Root Dir: /mnt/sda1/var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
  provider=virtualbox
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine


```
</details>

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mskoenz** [comment]
PS: docker is awesome :) !

**Comment by cpuguy83** [comment]
Linux does not have a means of changing ownership/perms on mount outside of implementing something via FUSE.
DockerForMac does have a translation layer where it maps ownership from the mac into the linux container.
You may want to try that instead of docker-machine.

**Comment by thaJeztah** [comment]
For Linux setups, you may be interested in this answer I wrote up some while back https://stackoverflow.com/a/29251160/1811501

However, if you're running on macOS, I'd highly recommend using Docker Desktop for Mac instead (https://docs.docker.com/docker-for-mac/install/), which makes dealing with permissions easier.

**Comment by mskoenz** [comment]
Thank you very much for the quick answer, I'll take a look at your link!
Feel free to close the issue, since it was more of a question to start with.

Keep up the awesome work :)

**Comment by thaJeztah** [comment]
You're welcome! Let me close, but feel free to continue the conversation after that

**Comment by mskoenz** [comment]
It solved the issue, now the bind-mounted volumes show up with container user and container group permissions.
(Just needed to restart the terminal due to: https://github.com/docker/for-win/issues/7629)
