### ISSUE TITLE
On Windows, %SystemDrive% is not always C:\

### ISSUE THREAD

**Issue by Emeka-NMC** [docker/cli#2839]
**Description**
This is just a minor document clarification.
Under [Dockerfile reference](https://docs.docker.com/engine/reference/builder/#notes-about-specifying-volumes), there's the following --> _"a drive other than `C:`"_ . This assumes that Windows is always installed on `C:\`. 

**Proposal**
On Windows, the OS install drive is %SystemDrive%.
Update the document to include this information.

**Comment by thaJeztah** [comment]
Closing this one, per the discussion on https://github.com/docker/cli/pull/2840#issuecomment-726714416 👍
