### ISSUE TITLE
OCI runtime error while passing a --restart parameter to docker run on AWS Amazon Linux

### ISSUE THREAD

**Issue by codewithpatelo** [docker/cli#2852]
**Description**

I try to run a container with the parameter "--restart unless-stopped" on an AWS EC2 instance with Amazon Linux but an OCI error is thrown.

![image](https://user-images.githubusercontent.com/16574952/100304366-5a758200-2f7d-11eb-99a9-42558f7d2780.png)

**Steps to reproduce the issue:**
1. On a AWS EC2 t2.series Amazon Linux Instance try 

sudo yum install -y docker
sudo groupadd docker
sudo usermod -aG docker ec2-user
sudo systemctl start docker
sudo systemctl enable docker

2. Then build a container
3. Then as my example: docker run -p 8080:3000 orans_2_front --restart unless-stopped

**Describe the results you received:**
OCI Error
![image](https://user-images.githubusercontent.com/16574952/100304512-b0e2c080-2f7d-11eb-93e0-82ae020ddb26.png)

**Describe the results you expected:**
Container running ok. (Happens when --restart parameter is not specified)

**Output of `docker version`:**

```
Docker version 19.03.13-ce, build 4484c46
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

AWS EC2 t2.medium on a Amazon Linux Image

**Comment by codewithpatelo** [comment]
Solved by running  `docker run --restart unless-stopped -p 8080:3000 orans_2_front` instead.

**Comment by thaJeztah** [comment]
Yes, the docker parameters must come before the image name, otherwise they're passed as the "command / entrypoint" for the container.

Let me close this one
