### ISSUE TITLE
Proposal: connect to rootless socket by default if /var/run/docker.sock is not accessible

### ISSUE THREAD

**Issue by AkihiroSuda** [docker/cli#2860]
I suggest modifying `docker` client to connect to the rootless socket `unix://$XDG_RUNTIME_DIR/docker.sock` by default when all the following conditions are satisfied:
- `$DOCKER_HOST` is unset
- `unix:///var/run/docker.sock` does not exist or is not accessible
- `unix://$XDG_RUNTIME_DIR/docker.sock` is accessible

**Comment by AkihiroSuda** [comment]
@thaJeztah @cpuguy83 @tonistiigi @tiborvass 

PTAL, RFC

**Comment by cpuguy83** [comment]
Seems fine to me.

**Comment by AkihiroSuda** [comment]
PR: #2863
