### ISSUE TITLE
A build with BuildKit cannot be fully used as a library

### ISSUE THREAD

**Issue by alexey-igrychev** [docker/cli#2889]
[BuildKit build](https://github.com/docker/cli/tree/40ec81a79afb993d3f77042194ad81a2a8b466a7/cli/command/image/build_buildkit.go)  implementation uses standard streams instead of [docker client instance ones](https://github.com/docker/cli/tree/40ec81a79afb993d3f77042194ad81a2a8b466a7/cli/command/cli.go#L51-L53):
* The user cannot run `build` with context/dockerfile from the docker client stdin: the process hangs on infinitely waiting for data from the standard stdin ([fix](https://github.com/docker/cli/pull/2885)).
* The user cannot work with output because it is written to standard output and error streams.

**Comment by thaJeztah** [comment]
closing this one, because https://github.com/docker/cli/pull/2885 was merged to master (not yet in a release)

**Comment by alexey-igrychev** [comment]
@thaJeztah Could we reopen this issue since the problem is not completely solved or is it better to create a new one?

There is no true way to get the output because BuildKit still uses the standard output and error streams instead of those defined in the docker cli instance. There is no option for both plain and tty settings for the progress option.

**Comment by onegreyonewhite** [comment]
@thaJeztah is this going to be fixed?
