### ISSUE TITLE
docker-proxy process doesn't exit after container is stop/removed, if host part of  "docker run -p" is IPv6.

### ISSUE THREAD

**Issue by dawnfantasy** [docker/cli#2898]
**Description**

For IPv4, if you specify "-p 192.168.0.1:80:80" in docker run, it starts a docker-proxy for you and kills it when the container stops.
For IPv6, this action does not happen. the docker-proxy keeps running and listening to the port.

**Steps to reproduce the issue:**
1. add an IPv6 to eth0 or another interface.
`$ sudo ip addr add fc00:abcd::1/64 dev eth0
`
2. start container, verify port listening.
`$ docker run -itd --rm -p [fc00:abcd::1]:1000:80 --name mynginx nginx
`
3f80f9128f801b1e6428c79f4cc04888cc6f3996499347cb6d036b3a548427ea
`$ sudo ss -plnt | grep 1000
`
LISTEN    0         128          [fc00: abcd::1]:1000               [::]:*        users:(("docker-proxy",pid=2735,fd=4))                                       

3. stop nginx, verify port listening.
`$ docker stop mynginx
`
mynginx
`$ sudo ss -plnt | grep 1000
`
LISTEN    0         128          [fc00: abcd::1]:1000               [::]:*        users:(("docker-proxy",pid=2735,fd=4))  

4. if I manually kill the docker-proxy process
- the process becomes [defunct]
- the port is not freed
- it doesn't show in netstat/ss 
- won't be able to listen to that IP/port combination again (docker fails to start)

**Describe the results you received:**
The port is in LISTEN state and the docker-proxy is still running.

**Describe the results you expected:**
docker-proxy stops and frees the port.

**Additional information you deem important (e.g. issue happens only occasionally):**
IPv6 address in -p parameter.

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           20.10.1
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        831ebea
 Built:             Tue Dec 15 04:34:58 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       f001486
  Built:            Tue Dec 15 04:32:52 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.0-docker)

Server:
 Containers: 3
  Running: 0
  Paused: 0
  Stopped: 3
 Images: 1
 Server Version: 20.10.1
 Storage Driver: vfs
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.20.8-1.el7.elrepo.x86_64
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 976.6MiB
 Name: v2.xxxxy.org
 ID: PK3O:5R5V:N7JR:OMUR:Y4YO:G75Y:JQJT:MHO2:AEWM:Z2PD:DPUR:VNPP
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http://v1.xx.org:33080
 HTTPS Proxy: https://v1.xx.org:33080
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
This looks like a duplicate of https://github.com/moby/moby/issues/41822; are you still seeing this issue on docker 20.10.2?

Note that there's a change in behaviour in 20.10.2 that needs to be discussed; see https://github.com/moby/moby/issues/41858

**Comment by dawnfantasy** [comment]
Thanks, it works in docker 20.10.2. The docker-proxy process is removed properly.
