### ISSUE TITLE
Wrong proxy configuration during build when using Docker context SSH connection

### ISSUE THREAD

**Issue by graylock** [docker/cli#2917]
**Description**

When building docker images on a remote host, which sits behind a proxy, via a configured Docker context, the wrong proxy configuration is used from the local docker client config. Here the endpoint for the Docker context is a SSH connection. The local host is a Windows machine and the remote host is a Linux machine.

**Steps to reproduce the issue:**
1. Remote host running a docker daemon and sitting behind a proxy (Linux machine)
2. Local host with docker CLI (Windows machine)
3. Create context for remote host on local host: `docker context create remote-host --docker "host=ssh://myuser@remote-host"`
4. Configure proxy settings on local host for remote-host in ../.docker/config.json
```JSON
{
	"currentContext": "remote-host",
	"proxies": {
		"default": {
			"httpProxy": "http://dev.proxy.com:8080",
			"httpsProxy": "http://dev.proxy.com:8080"
		},
		"ssh://myuser@remote-host:22": {
			"httpProxy": "http://prod.proxy.com:8080",
			"httpsProxy": "http://prod.proxy.com:8080"
		}
	},
	"stackOrchestrator": "swarm"
}
```
5. Create simple Dockerfile just for example:
```Dockerfile
FROM ubuntu:16.04

RUN apt-get update && apt-get install htop
```
6. Use Docker context: `docker context use remote-host`
7. Build Docker container using example Dockerfile: `docker build .`

**Describe the results you received:**

The following output I gain, when trying to build:

```
Sending build context to Docker daemon  22.02kB
Step 1/2 : FROM ubuntu:16.04
16.04: Pulling from library/ubuntu
be8ec4e48d7f: Pull complete
33b8b485aff0: Pull complete
d887158cc58c: Pull complete
05895bb28c18: Pull complete
Digest: sha256:3355b6e4ba1b12071ba5fe9742042a2f10b257c908fbdfac81912a16eb463879
Status: Downloaded newer image for ubuntu:16.04
Step 2/2 : RUN apt-get update && apt-get install htop
 ---> Running in 48920d81e781
Err:1 http://security.ubuntu.com/ubuntu xenial-security InRelease
  Temporary failure resolving 'dev.proxy.com'
Err:2 http://archive.ubuntu.com/ubuntu xenial InRelease
  Temporary failure resolving 'dev.proxy.com'
Err:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
  Temporary failure resolving 'dev.proxy.com'
Err:4 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
  Temporary failure resolving 'dev.proxy.com'
Reading package lists...
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial/InRelease  Temporary failure resolving 'dev.proxy.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-updates/InRelease  Temporary failure resolving 'dev.proxy.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-backports/InRelease  Temporary failure resolving 'dev.proxy.com'
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/xenial-security/InRelease  Temporary failure resolving 'dev.proxy.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package htop
The command '/bin/sh -c apt-get update && apt-get install htop' returned a non-zero code: 100
```

From this output you can see, that the proxy configuration from the default configuration is used and not the one specified for the SSH endpoint.

**Describe the results you expected:**

Expected that the proxy configuration from SSH endpoint is used. In this case `http://prod.proxy.com:8080` instead of `http://dev.proxy.com:8080`. Even better would be, when the proxy configuration from the remote hosts config would be used (e.g. the configuration file from the user used to login via SSH to the remote host).

Somewhat related is #1621.

**Additional information you deem important (e.g. issue happens only occasionally):**

One other solution for this is to enter the proxy configuration for the remote host in the _default_ label of the ../.docker/config.json file. But this is more a workaround.

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Cloud integration: 1.0.4
 Version:           20.10.0
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        7287ab3
 Built:             Tue Dec  8 18:55:31 2020
 OS/Arch:           windows/amd64
 Context:           holm_hpc_002
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       f001486
  Built:            Tue Dec 15 04:32:40 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    remote-host
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.4.2-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 47
  Running: 0
  Paused: 0
  Stopped: 47
 Images: 216
 Server Version: 20.10.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux nvidia runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-128-generic
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 54.94GiB
 Name: remote-host
 ID: M2S6:IH7K:OH6W:WRF7:V4VQ:UYQE:J64B:O5JY:CKKJ:4MTW:UZUY:VSAI
 Docker Root Dir: /mnt/docker-images
 Debug Mode: false
 HTTP Proxy: 192.168.1.1:8080
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Assuming that a proper SSH key authentification is in place.

**Comment by graylock** [comment]
#1621

**Comment by glebsts** [comment]
So this ticket was just ignored? Struggling with same thing. Should host key in config file proxies section be exactly same as host in context config? With `ssh://`, `username@`, and port?
I really need to pass different proxy setting to container I run on different remote dockers.

I check proxy settings by running `docker [--context foo] run --rm busybox env`.

Can't find a way to pass.

**Comment by ndeloof** [comment]
Hi.
Host key in config file proxies section MUST be exactly the same as host in context config, i.e `ssh://myuser@remote-host` not `ssh://myuser@remote-host:22`. docker/cli uses docker host URL to retrieve proxy configuration from a map, and does not parse the URL to do some clever matching guessing a default port or anything comparable.

I'm closing this issue, feel free to add more comments if you have follow-up questions

**Comment by udondan** [comment]
The proxy setting only seems to work for `docker run`. It is ignored by `docker build`. The only way I was able to set a proxy for `docker build` was to actually provide it via `--build-arg`.

I described my situation and an ugly workaround on [StackOverflow](https://stackoverflow.com/q/72870290/2753241).

**Comment by florianfischer91** [comment]
Sry for commenting on a quiet old issue but i faced the same issue.
I took a quick look into the src-code and if i use `http://docker.example.com` as key in the `proxies` dictionary it picks up the "right" proxy variables. I then tried to fix the actual problem which would be solved by this patch

```diff
diff --git a/cli/context/docker/load.go b/cli/context/docker/load.go
index 77baa15173..00b5945175 100644
--- a/cli/context/docker/load.go
+++ b/cli/context/docker/load.go
@@ -109,7 +109,7 @@ func (ep *Endpoint) ClientOpts() ([]client.Opt, error) {
                        }
                        result = append(result,
                                client.WithHTTPClient(httpClient),
-                               client.WithHost(helper.Host),
+                               client.WithHost(ep.Host),
                                client.WithDialContext(helper.Dialer),
                        )
                }
```
Another option would be 
```diff
diff --git a/cli/connhelper/connhelper.go b/cli/connhelper/connhelper.go
index b98d97c25d..9978f911a0 100644
--- a/cli/connhelper/connhelper.go
+++ b/cli/connhelper/connhelper.go
@@ -56,7 +56,7 @@ func getConnectionHelper(daemonURL string, sshFlags []string) (*ConnectionHelper
                                args = append(args, "system", "dial-stdio")
                                return commandconn.New(ctx, "ssh", append(sshFlags, sp.Args(args...)...)...)
                        },
-                       Host: "http://docker.example.com",
+                       Host: daemonURL,
                }, nil
        }
        // Future version may support plugins via ~/.docker/config.json. e.g. "dind"
```

The first one looks a bit more right, but i'm also not very familiar how all these pieces are connected together or maybe i'm also doing something wrong and there is no problem at all.
