### ISSUE TITLE
Recent CLI breaks test-integration-cli

### ISSUE THREAD

**Issue by AkihiroSuda** [docker/cli#293]
**Description**

**Steps to reproduce the issue:**
1. checkout moby/moby@a9358df62cde2deb8184c742e6fb8d16c98a04a9
2. edit `hack/dockerfile/binaries-commits` to use docker/cli@8df4cd1edcff2d23f0fe55330531f599bbb89e42, instead of the default docker/cli@3dfb8343b139d6342acfd9975d7f1068b5b1c3d3
3. `make test-integration-cli`

**Describe the results you received:**

some tests fails deterministically

e.g.
```
----------------------------------------------------------------------
FAIL: docker_cli_rmi_test.go:227: DockerSuite.TestRmiContainerImageNotFound
                                     
docker_cli_rmi_test.go:248:
    // The image of the running container should not be removed.                
    c.Assert(err, checker.NotNil)
... value = nil
```

**Describe the results you expected:**

CLI should not break existing tests

**Comment by vdemeester** [comment]
There is 2 things here : 

1. Integration tests should not depend on `docker` cli at all (it's in progress)
2. Until this is done, we might want to update the cli binary in `moby/moby` from time to time ? (or at least run a CI on `moby/moby` with integration of the two ?

**Comment by AkihiroSuda** [comment]
@vdemeester 
My opinion is to run CI on `docker/cli` to make sure `docker/cli` does not break existing integration CLI tests.

With regard to `TestRmiContainerImageNotFound`, it was working on 85453417090 but seems broken since ecc8e0a (intermediate commit 8c2f818 doesn't compile)

**Comment by dnephin** [comment]
This is expected. We should not continue to expect that the latest version of the CLI will work for tests. If a test is failing because of a CLI change it should be converted to an API test. 

> at least run a CI on moby/moby with integration of the two ?

This already exists https://jenkins.dockerproject.org/job/docker-integration-tests/. These failures should only be used as a way for us to find tests that need to be either removed, or to prioritize their replacement with API tests.

**Comment by AkihiroSuda** [comment]
> This is expected. We should not continue to expect that the latest version of the CLI will work for tests. 

If existing CLI test fails, doesn't it mean compatibility is broken and existing user shell scripts are unlikely to work, no?

**Comment by dnephin** [comment]
Not in every case. Some changes might be considered bug fixes. Others changes might be removed deprecated behaviour after the normal deprecation period. Some could be changing experimental features.

**Comment by aaronlehmann** [comment]
See also https://github.com/moby/moby/pull/33386

**Comment by dnephin** [comment]
Going to close this issue since this is expected.

**Comment by thaJeztah** [comment]
I'm not sure I 100% agree; even though the integration tests in the moby/moby repository are written for an older version of the CLI, I'd still be interested _what_ breaks, and if the breakage is expected.

Seeing a test fail that (from the message `The image of the running container should not be removed.  `) should not remove an image if it's in use by a container, sounds suspicious.

@vdemeester @aluzzardi do you know if the e2e test suite currently tests "master" against "master" as well?

**Comment by thaJeztah** [comment]
Oh, I see the comment above;

> This already exists https://jenkins.dockerproject.org/job/docker-integration-tests/. These failures should only be used as a way for us to find tests to remove, or to prioritize their replacement with API tests.

Is someone actively looking at breaking tests?

**Comment by dnephin** [comment]
> even though the integration tests in the moby/moby repository are written for an older version of the CLI, I'd still be interested what breaks, and if the breakage is expected.

Yes, I agree that is interesting, but not something that we need to track with an issue on this repo. If we need to track it, we should track it in moby/moby, since that's where the test would need to be fixed.
