### ISSUE TITLE
Add documentation of --chmod flag in ADD and COPY instructions to builder.md

### ISSUE THREAD

**Issue by rcjsuen** [docker/cli#2941]
[`builder.md`](https://github.com/docker/cli/blob/35f023a7c22a51867fb099d29006ef27379bc7fe/docs/reference/builder.md) does not mention the new `--chmod` flag that was added to `ADD` and `COPY` instructions in [Docker CE 20.10](https://github.com/moby/buildkit/pull/1492#issuecomment-758105476).

**Comment by thernstig** [comment]
Isn't this a big oversight that this has not been documented yet?

**Comment by sam-thibault** [comment]
This file has moved to the BuildKit repository at https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/reference.md

**Comment by sam-thibault** [comment]
I created an issue on buildkit since the file is there now:
- https://github.com/moby/buildkit/issues/3721
