### ISSUE TITLE
https://godoc.org/github.com/docker/docker/client is redirected. The new content does not match the previous and is not the latest version

### ISSUE THREAD

**Issue by pmgexpo17** [docker/cli#2966]
Hi,
I am developing a go docker client pkg and was loving the very useful godocs until the url https://godoc.org/github.com/docker/docker/client was suddenly redirected to :
[client · pkg.go.dev](https://pkg.go.dev/github.com/docker/docker@v1.13.1/client)
The v.13.1 version is older than the previous link. For example, @v1.13.1 ContainerWait has this return signature ContainerWait(…) (int64, error) but the latest (or later) version has ContainerWait(…) (<-chan container.ContainerWaitOKBody, <-chan error)
I haven’t even been able to track down the latest godocs version, so I can edit the version label in the link. I tried docker@latest/client but get a 404 error
I posted this query to the docker forum but no one has replied yet.
I searched the existing issues with 'godoc' search word but nothing relevent showed up
Can anyone point me to the latest client godocs ? Thanks in advance !

**Comment by pmgexpo17** [comment]
I've only recently started docker client development and am now aware of issues #39302 and #38507
https://github.com/moby/moby/issues/39302
https://github.com/moby/moby/issues/38507

I use go modules and my code imports v20.10.2 with no issues
github.com/docker/docker v20.10.2+incompatible

But I'm trying to use the godocs ...

Atm, I'm joining https://dockercommunity.slack.com/ which should get me sorted out eventually ...

**Comment by thaJeztah** [comment]
The "versions" tab on pkg.go.dev should show the other available versions; https://pkg.go.dev/github.com/docker/docker@v1.13.1/client?tab=versions

e.g. docs for 20.10.3; https://pkg.go.dev/github.com/docker/docker@v20.10.3+incompatible/client

does that help?

**Comment by pmgexpo17** [comment]
Hi, thanks for getting back
Hmm ... I see the version label "Version v1.13.1" is now a link ... awesome ! cheers
