### ISSUE TITLE
Drop Kubernetes support (compose-on-kubernetes is now unmaintained & archived)

### ISSUE THREAD

**Issue by olivierlemasle** [docker/cli#2967]
Now that [docker/compose-on-kubernetes](https://github.com/docker/compose-on-kubernetes) is archived and unmaintained, docker/cli should stop depending on it.

**Comment by olivierlemasle** [comment]
What is the current state of kubernetes support in [docker/cli](https://github.com/docker/cli)?

As [docker/compose-on-kubernetes](https://github.com/docker/compose-on-kubernetes) has [outdated installation instructions](https://github.com/docker/compose-on-kubernetes/issues/156) which will not be fixed because the project is unmaintained and archived, it seems `cli` should drop Kubernetes support and support only Swarm. Is it acceptable for you?

**Comment by mat007** [comment]
Yes, we plan to drop Kubernetes support for `docker stack`. We’ll add deprecation notices shortly.
