### ISSUE TITLE
Privileged containers running debootstrap have chroot errors, but non privileged containers with SYS_CHROOT capability work without issue.

### ISSUE THREAD

**Issue by eadamsintel** [docker/cli#2969]
**Description**

When using `debootstrap` in a container that is run with `--privileged` it fails to completely work, and there is an error `Failure trying to run: chroot "/temptest"  mount -t proc proc /proc`   If the same container is run with the following capabilities `--cap-add=SYS_CHROOT --cap-add SYS_ADMIN --cap-add MKNO` then it works without error.  However, I am trying to build a virtual machine rootfs in a container and need `--privileged` to properly setup the `/dev/loop` devices that are used as part of an existing script.  If I pass `--privileged` with the capabilities above the `debootstrap` step still fails.  I have not yet found a way in a single container to run `debootstrap` and create a loop device using `losetup` as well as creating/formatting partitions on that loop device. 

**Steps to reproduce the issue:**

The following has the chroot issue
```
$ docker run -ti  --rm -v /dev:/dev --privileged fedora bash"
# dnf install -y debootstrap
# mkdir /temptest
# debootstrap --variant=minbase --arch=amd64 --include=systemd,iptables,init,chrony,kmod  stretch /temptest
```
If the same steps above are run but with capabilities added then it works without the chroot failure.
```
$ docker run -ti  --rm -v /dev:/dev --cap-add=SYS_CHROOT --cap-add SYS_ADMIN --cap-add MKNOD fedora bash"
# dnf install -y debootstrap
# mkdir /temptest
# debootstrap --variant=minbase --arch=amd64 --include=systemd,iptables,init,chrony,kmod  stretch /temptest
```

**Describe the results you received:**

The `debootstrap` fails to properly work with `--privileged`

**Describe the results you expected:**

I would expect that the `--privileged` tag should work with more permissions than just adding a few capabilities and that the `debootstrap` binary wouldn't have a permissions issue inside the container.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
This also happened on version 19.03.9.
```
Client: Docker Engine - Community
 Version:           20.10.3
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        48d30b5
 Built:             Fri Jan 29 14:33:21 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.3
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       46229ca
  Built:            Fri Jan 29 14:31:32 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
```

**Output of `docker info`:**
I should note this also happened when my storage driver was overlay2.
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 13
 Server Version: 20.10.3
 Storage Driver: devicemapper
  Pool Name: docker-253:0-9839022-pool
  Pool Blocksize: 65.54kB
  Base Device Size: 10.74GB
  Backing Filesystem: xfs
  Udev Sync Supported: true
  Data file: /dev/loop8
  Metadata file: /dev/loop9
  Data loop file: /var/lib/docker/devicemapper/devicemapper/data
  Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
  Data Space Used: 1.634GB
  Data Space Total: 107.4GB
  Data Space Available: 105.7GB
  Metadata Space Used: 18.44MB
  Metadata Space Total: 2.147GB
  Metadata Space Available: 2.129GB
  Thin Pool Minimum Free Space: 10.74GB
  Deferred Removal Enabled: true
  Deferred Deletion Enabled: true
  Deferred Deleted Device Count: 0
  Library Version: 1.02.167 (2019-11-30)
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: kata-clh kata-fc kata-qemu kata-qemu-virtiofs runc io.containerd.runc.v2 io.containerd.runtime.v1.linux kata-acrn
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-65-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 96
 Total Memory: 187.7GiB
 Name: sse-tme-bp-01c
 ID: PCRH:JIKP:HYRN:6KFJ:SCTA:2MAZ:66M5:N35B:SLKX:JIDF:ZVFL:CBYT
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
WARNING: No blkio weight support
WARNING: No blkio weight_device support
WARNING: the devicemapper storage-driver is deprecated, and will be removed in a future release.
WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

This is on an Ubuntu 20.04 server.

**Comment by eadamsintel** [comment]
I spent a few more hours on this and have realized that `debootstrap` is unmounting `/proc` from my container and that is causing the issues. It seems that without `--privileged` it can't unmount this folder and `debootstrap` silently keeps working without error. If I run the `debootstrap` command from the `/proc` directory while in a privileged container then it can't umount while running and keeps working.  It seems like it is a `debootstrap` issue, but I don't know enough about how this program works to say for sure.  I am going to close this issue, as I don't think it is a Docker issue.

**Comment by tumbl3w33d** [comment]
Happened to me with `debootstrap 1.0.123+deb11u1` in a debian-based container. Thank you, I like your workaround. :)
