### ISSUE TITLE
[Proposal] Build RPM for Fedora ppc64le

### ISSUE THREAD

**Issue by runlevel5** [docker/cli#3012]
The docker-ce RPM repo https://download.docker.com/linux/fedora/ does not have any packages built for ppc64le platform. For now it is not a big deal because I have been rebuilding the RPMs from the SRPMs (though a bit inconvenient). 

I would like to ask if the team could provide the RPM for Fedora ppc64le too?

I am happy to contribute code changes if it helps.

**Comment by thaJeztah** [comment]
ppc64le packages weren't available for all distros for some time, but we've partnered with the IBM team, and going forward, they will provide packages for s390x and ppc64le, and those will be published on download.docker.com. (Given that these packages are built by a different team, it's possible that they may sometimes be published slightly later than other architectures though);

Packages should now be available for ppc64le (docker 20.10.7); https://download.docker.com/linux/fedora/34/ppc64le/stable/Packages/

Let me close this ticket 👍
