### ISSUE TITLE
FeatureRequest: Make prune commands output what they are pruning before pressing Y

### ISSUE THREAD

**Issue by pwfraley** [docker/cli#3014]
Would it be possible to have the docker prune commands output what they would do, before pressing Y?  I think this would help in assuring that accidental deletion of volumes, containers, etc. could happen.

So instead of:

```
docker volume prune
Are you sure? (Y/N) Y
List of Volumes Pruned
```

```
docker volume prune
List of Volumes
Are you sure you want to delete these volumes? (Y/N)
```

**Comment by olivierlemasle** [comment]
I think adding a "dry-run" option would be better (it keeps the current behaviour and adds a way to get the information you want).

Cf #763 and https://github.com/moby/moby/issues/30623

**Comment by pwfraley** [comment]
Well yes and no. ;)  Some examples:

dryrun:
docker container prune --dry-run
You get the output.
Now someone else logs into the docker server via ssh and stops a container.
Now the first admin, who ran the dry-run command executes the final command.
Now the container stoped by the other admin would also get pruned with the non dry-run command.

I was more like envisioning something like this:
docker container prune
OUTPUTS LIST OF CONTAINERS TO PRUNE
Other Admin logs in and stops a container
First admin presses Y to prune
Only the previously listet containers get prune, not the one that got stoped after the list was shown.

Alternativly to not change the current behaviour, how about a flag like --safe, which would use the new behaviour and a prune without --safe still works like before?

**Comment by thaJeztah** [comment]
> I was more like envisioning something like this:
> docker container prune
> OUTPUTS LIST OF CONTAINERS TO PRUNE
> Other Admin logs in and stops a container
> First admin presses Y to prune
> Only the previously listet containers get prune, not the one that got stoped after the list was shown.

To an extend, the above can be done manually, by combining `docker ps -q` (and some filters) with `docker rm`, e.g.

```bash
# list the IDs of all stopped containers
$ docker ps -a --filter status=exited -q
7ee2ec7183d0
0729f31b5e07
4f5dce176902
9612ce6a3782

# or combined: find IDs of all stopped containers, and pass that list to `docker rm`
$ docker rm $( docker ps -a --filter status=exited -q)
```

The `docker prune` command were created specifically to help with some race conditions; the _intent_ is to prune everything what's not used at the moment the `prune` is executed; _including_ containers that were stopped just at that moment. But even in that case, there will/might be race conditions.

For your case, the _reverse_ can also be true; you request the list of container to be pruned (exited containers), and another admin _starts_ a container that was previously stopped.

I don't think there will be a "real" solution that covers every possible scenario.

That said; I think this is a duplicate (or at least "close to") of https://github.com/docker/cli/issues/763 and https://github.com/moby/moby/issues/30623, so let me close this one in favor of the other issues: feel free to comment after I closed, or to add your use-case to one of those issues.
