### ISSUE TITLE
Docker build no longer prints the names of the intermediate images

### ISSUE THREAD

**Issue by albertvaka** [docker/cli#3016]
**Description**

Since a recent update, `docker build` doesn't print the hashes of the intermediate images. This makes debugging difficult, as it's no longer possible to start a shell on the last image that succeeded to try running commands by hand from there.

**Output of `docker version`:**

```
Docker version 20.10.5, build 55c4c88
```

**Comment by cpuguy83** [comment]
Could you provide the full detail requested in the issue template?

What does your build output look like?
Are you using the buildkit builder? There is no "intermediate image" in that case.

Thanks!

**Comment by albertvaka** [comment]
Thanks for the pointer, I didn't know buildkit was being introduced! Knowing that I could easily find that it can be disabled with `DOCKER_BUILDKIT=0` so I will do that (since I didn't see any advantage and found at least one disadvantage already). Thanks for your time and help :)
