### ISSUE TITLE
docker login outputs different configs when providing username by flag vs. stdin 

### ISSUE THREAD

**Issue by tlowerison** [docker/cli#3022]
`docker login` behaves differently when providing `username` as a flag vs. stdin

The differences lie in how the two modify `~/.docker/config.json`: using the flag correctly adds the credential's `ServerURL` as a field in the `auths` object, while using stdin adds `""` as a key to `auths`. The empty string causes `docker pull` and other commands that require credentials to fail.

**Steps to reproduce the issue:**
1. Run `cat ~/.docker/config.json` to see initial state
2. Remove all keys in the top level`auths` object of `config.json` to reset login state
3. Run `docker login` then input credentials using stdin.
4. Run `cat ~/.docker/config.json` to see the updated state. It should look like `{"auths":{"":{}},...}`
5. Remove all keys in the top level`auths` object of `config.json` to reset login state
6. Run `docker login --username=<my-username>` and input only Password with stdin
7. Run `cat ~/.docker/config.json` to see the updated state. It should look like `{"auths":{"https://index.docker.io/v1/":{}},...}`

**Describe the results you received:**
I received differing configs when they should produce the same result

**Describe the results you expected:**
I expected identical configs.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
$ docker version
Client: Docker Engine - Community
 Cloud integration: 1.0.9
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:13:00 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
 Kubernetes:
  Version:          v1.19.3
  StackAPI:         Unknown
```

**Output of `docker info`:**

```
$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 44
  Running: 42
  Paused: 0
  Stopped: 2
 Images: 71
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.121-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.779GiB
 Name: docker-desktop
 ID: RKZO:RJXE:YDYN:GBFB:2EXG:YNUX:X5C6:ZE74:T3LY:FTX3:M47D:WRRT
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
I'm not able to reproduce the issue on the latest Docker Desktop. with Cloud Integration 1.0.15 (which could be related); are you seeing the same issue if you try running `com.docker.cli login` (instead of `docker login` ? Doing so "skips" the cloud-integration CLI.


The format in which the auth information is stored _does_ depend on wether or not a credential helper is used; docker desktop by default uses a credential helper (to store credentials in the macOS keychain). After logging in, the config file looks like;

```json
{
        "auths": {
                "https://index.docker.io/v1/": {}
        },
        "credsStore": "osxkeychain"
}
```


Doing the same on a cli without a credential helper configured;


Interactive:

```
docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: thajeztah
Password:
WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
```

```json
{
	"auths": {
		"https://index.docker.io/v1/": {
			"auth": "<BASE64 creds>"
		}
	}
}
```

Only password from stdin:

```
docker login --username=myusername
Password:
WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
```

```json
{
	"auths": {
		"https://index.docker.io/v1/": {
			"auth": "<BASE64 creds>"
		}
	}
}
```

**Comment by sam-thibault** [comment]
We were unable to reproduce and there has been no new activity.  I will close this issue as stale.
