### ISSUE TITLE
[Update-Doc] docker-entrypoint.sh executes wrong environment variable

### ISSUE THREAD

**Issue by Sp4Rx** [docker/cli#3026]
**Description**
Wrong environment variable is set when setting environment variable during docker run

**Steps to reproduce the issue:**
My docker file:
```FROM ubuntu:latest

RUN mkdir -p /test
WORKDIR /test

#Default environment
ENV ENV=default

RUN echo "#!/bin/bash \n\
    # Shows the default environment from Dockerfile\n\
    echo wrong: $ENV\n\
    # If we consider $ENV as text then it shows\n\
    # the correct environment from commandline\n\
    eval "echo correct: '$ENV'"\n\
    " >> /usr/local/bin/docker-entrypoint.sh\
    && chmod +x /usr/local/bin/docker-entrypoint.sh

ENTRYPOINT ["docker-entrypoint.sh"]
```

Let's assume `test` is my image name. Now I run the bellow command.
`docker run --rm --env ENV=testing test`
Here the value of `ENV` is `testing`

But in the `docker-entrypoint.sh` when `echo $ENV` is executed I get `default` as output.
But if I consider the it as string and run `eval "echo '$ENV'"` I get the correct output which is `testing`.

Bellow is the full recording of the bug.
[![asciicast](https://asciinema.org/a/402616.svg)](https://asciinema.org/a/402616)

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Cloud integration: 1.0.9
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:17:50 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 6
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.72-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 5.804GiB
 Name: docker-desktop
 ID: CASO:CHSW:OCNL:QA2W:D4BH:2CRB:RXES:EBG4:BME4:TNIH:3FET:VNJU
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by lightmare** [comment]
This is not a bug. Remember that RUN instructions are executed by the shell.
```
RUN echo "whatever $ENV"
```
executes `sh -c 'echo "whatever $ENV"'` in the build container, and so the `$ENV` is expanded at that point.

You can test it with this Dockerfile:
```Dockerfile
FROM ubuntu:latest

#Default environment
ENV ENV=default

# Here $ENV is expanded during build
RUN echo "echo double quoted: $ENV" >>/tmp/test.sh

# Here $ENV is not expanded during build
RUN echo 'echo single quoted: $ENV' >>/tmp/test.sh
```

```sh
docker build -t test .
# check the contents of the written script
docker run --rm test cat /tmp/test.sh
# run it
docker run --rm --env ENV=testing test sh /tmp/test.sh
```

NB: I would suggest putting that entrypoint.sh into its own file, and including it with COPY. That way it'll be much more readable and less error-prone.

**Comment by Sp4Rx** [comment]
Thanks for this explanation @lightmare . Closing this issue

**Comment by Sp4Rx** [comment]
I don't find documentation for the above explanation. I feel documentation needed to be updated. Reopening this issue.

**Comment by lightmare** [comment]
@Sp4Rx Docker does not expand the variables in RUN instructions. It passes the environment and the instruction script to the shell.

Forget docker, try this locally. Put the raw text you have after RUN into file `instruction.txt`:
```
echo "#!/bin/bash \n\
# Shows the default environment from Dockerfile\n\
echo wrong: $ENV\n\
# If we consider $ENV as text then it shows\n\
# the correct environment from commandline\n\
eval "echo correct: '$ENV'"\n\
" > ./docker-entrypoint.sh\
&& chmod +x ./docker-entrypoint.sh
```
This is the script that the RUN instruction will pass to the shell to interpret (actually it will collapse all the backslash-newlines before passing it to shell, but I kept them in because it doesn't change the outcome here, the shell will collapse them as well if they're kept). I only changed the output from `>> /usr/local/bin/docker-entrypoint.sh` to `> ./docker-entrypoint.sh` so that you can test it in local directory.

Now, run this command (which mimicks what docker RUN instruction does, i.e. puts variables in environment and passes the instruction text to the shell): 
```sh
ENV=default /bin/sh instruction.txt
```

```sh
cat docker-entrypoint.sh
```
Here is the expected output of the instruction script:
```
#!/bin/bash 
# Shows the default environment from Dockerfile
echo wrong: default
# If we consider default as text then it shows
# the correct environment from commandline
eval echo correct: $ENV
```

I suspect you're misreading where quoted strings start and end in your script, let me try to clarify.
```dockerfile
RUN echo {{BEGIN1"#!/bin/bash \n\
    # Shows the default environment from Dockerfile\n\
    echo wrong: $ENV\n\
    # If we consider $ENV as text then it shows\n\
    # the correct environment from commandline\n\
    eval "END1}}echo correct: '$ENV'{{BEGIN2"\n\
    "END2}} >> /usr/local/bin/docker-entrypoint.sh\
    && chmod +x /usr/local/bin/docker-entrypoint.sh
```
See, the `echo wrong: $ENV` is inside a double-quoted string, therefore `$ENV` gets expanded. Whereas `echo correct: '$ENV'` is outside double-quotes, and so the single-quotes around `$ENV` prevent its expansion.


Fun fact: there's nothing correct about `eval echo correct: $ENV` :)
```sh
ENV='*' ./docker-entrypoint.sh 
```
```
wrong: default
correct: docker-entrypoint.sh instruction.txt
```

**Comment by Sp4Rx** [comment]
Thanks @lightmare for your effort , is it possible to raise a pr against docker docs?

**Comment by lightmare** [comment]
@Sp4Rx The source for Dockerfile reference is in this repo: https://github.com/docker/cli/blob/master/docs/reference/builder.md
