### ISSUE TITLE
Docker history after local build shows all intermediate image IDs as missing

### ISSUE THREAD

**Issue by erewok** [docker/cli#3028]
**Description**

When I run `docker build` on a local Dockerfile, such as:

`docker build -t some_tag:test .` 

I no longer see layer IDs when I run `docker history` on my image afterward. This is how I have primarily debugged failing builds over the last 5 years, so I'm surprised to not see them anymore.

**Steps to reproduce the issue:**
1. 
```sh
docker build --no-cache -t molotok:exp .
[+] Building 153.5s (25/25) FINISHED
 => [internal] load build definition from Dockerfile                                                                                   0.0s
 => => transferring dockerfile: 37B                                                                                                    0.0s
 => [internal] load .dockerignore                                                                                                      0.0s
 => => transferring context: 35B                                                                                                       0.0s
 => [internal] load metadata for docker.io/condaforge/mambaforge:4.9.2-5                                                               1.6s
 => [auth] condaforge/mambaforge:pull token for registry-1.docker.io
```

2. 
```sh
docker images
REPOSITORY   TAG       IMAGE ID       CREATED          SIZE
molotok      exp       a79d13c6ddeb   30 seconds ago   2.29GB
```

3. 
```sh 
docker history a79d13c6ddeb
IMAGE          CREATED          CREATED BY                                      SIZE      COMMENT
a79d13c6ddeb   34 seconds ago   ENTRYPOINT ["/app/run.sh" "gunicorn -b 0.0.0…   0B        buildkit.dockerfile.v0
<missing>      34 seconds ago   RUN /bin/bash -c . /opt/conda/etc/profile.d/…   2.48kB    buildkit.dockerfile.v0
<missing>      36 seconds ago   SHELL [/bin/bash -c]                            0B        buildkit.dockerfile.v0
```

**Describe the results you received:**

All of the intermediate layers are missing image IDs. The Dockerfile I'm building is 50-lines long, so these missing Image IDs are not from a parent image (plus you can see that their age is "34 seconds ago"). 

**Describe the results you expected:**

Typically I will debug a failing container build by running an intermediate layer using its image ID, but these are missing. I would love to have these back.

**Additional information you deem important (e.g. issue happens only occasionally):**

I read the docs for `docker build` thinking this is maybe a new feature and also googled around but can't seem to find anyone else having this issue?

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Cloud integration: 1.0.9
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:13:00 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 3
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.121-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.847GiB
 Name: docker-desktop
 ID: I54Q:DUNL:3DMV:RYCB:KD4Y:HKHP:KGTI:Z5N6:WY6N:465Q:24DI:6NSU
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 41
  Goroutines: 47
  System Time: 2021-03-26T21:49:30.712256177Z
  EventsListeners: 4
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

OSX 11.2.3
Macbook Pro (mid-2015

**Comment by cpuguy83** [comment]
That's because you are building using the buildkit builder which does not have intermediate image IDs.
You can set `DOCKER_BUILDKIT=0` to use the legacy builder.
It seems Docker has change the default for Docker Desktop.

**Comment by erewok** [comment]
Excellent. Thanks so much for helping me! 

Questions:

- Is there anywhere in the documentation where I should have discovered this on my own?
- If I use the legacy builder, will it eventually be completely deprecated on Docker Desktop? 
- If so, will buildkit eventually offer a way to preserve intermediate image IDs?

Thanks again!

**Comment by cpuguy83** [comment]
> If I use the legacy builder, will it eventually be completely deprecated on Docker Desktop?

The idea is to replace it, but there's a lot to do to bring parity, such as debugging builds.

>  so, will buildkit eventually offer a way to preserve intermediate image IDs?

Buildkit has an open item to offer debugging, how that will be implemented is yet to be seen.

**Comment by cpuguy83** [comment]
re: docs, there are probably docs to say that buildkit is now default on Desktop, and there are possibly docs to say that buildkit doesn't have intermediate images... but are these two things brought together some place, probably not.

**Comment by erewok** [comment]
Fair enough. I appreciate all the help. Thanks.
