### ISSUE TITLE
docker run add shortcut for mounting PWD

### ISSUE THREAD

**Issue by roubles** [docker/cli#3046]
**Description**

*docker run* is a very powerful way to make scripts platform independent. Unfortunately the only way to pass files to a docker run is via a volume mount.

So when I have a script that works as follows:
```bash
my-awesome-script --file ./path/to/some/file
``` 

The dockerized version of calling that script becomes this monstrosity:
```bash
docker run -i -v $(pwd):/mnt containers.example.com/foo/my-awesome-script-img --file /mnt/path/to/some/file
```

https://github.com/docker/cli/pull/1273 adds support for mounting relative paths. The ask for this enhancement is to provide a shortcut (say **-x**) that automounts the pwd, making all files available within the docker at the same relative path location, so, the call to the dockerized version of the script could simply be:

```bash
docker run -ix containers.example.com/foo/my-awesome-script-img --file ./path/to/some/file
```

This will make **docker run** even more convenient/powerful.

This is a very frequent usecase that comes up on SO:
https://stackoverflow.com/questions/41092587/passing-file-as-argument-to-docker-container
https://stackoverflow.com/questions/44421635/how-to-get-docker-container-to-read-from-stdin

**Comment by thaJeztah** [comment]
Support for relative paths was added in https://github.com/docker/cli/pull/3469, which is part of docker 23.0; so this should now work;

```bash
touch hello.txt
docker run -v ./:/somewhere --rm alpine ls -la /somewhere
total 8
drwxr-xr-x    2 root     root          4096 May 19 22:36 .
drwxr-xr-x    1 root     root          4096 May 19 22:36 ..
-rw-r--r--    1 root     root             0 May 19 22:36 hello.txt
```
