### ISSUE TITLE
Add `build.network` field to Compose file v3.x

### ISSUE THREAD

**Issue by dnephin** [docker/cli#305]
See https://github.com/docker/compose/pull/4997

**Comment by dgageot** [comment]
The idea is to make sure the v3.4 of the schema supports (and ignores) `build/network` properties.
V3.4 of the schema is not yet merged in master. It's introduces in #306 in commit https://github.com/docker/cli/pull/306/commits/722e75d54360411eb9f43466087610b05197cff5

**Comment by dnephin** [comment]
There's also a `target` field to add to the `build` section. IT would be good to add them both at the same time.
