### ISSUE TITLE
Unable to execute docker cli commands over Windows SSH session

### ISSUE THREAD

**Issue by aaronla-ms** [docker/cli#3090]
**Description**

Unable to use docker cli when connecting to the machine over SSH terminal. Succeeds when run locally from non-elevated prompt

Connecting from a Windows 10 20H2 client machine using Windows OpenSSH client, connecting to server server running Windows 10 20H2. Admin user on both ends.

Attempting the same commands locally on the machine (aaronla-X), as same user (ntdev\aaronla), from non-elevated command prompt, succeeds

**Steps to reproduce the issue:**

```
aaronla@aaronla-R:scratch$ ssh aaronla-X

ntdev\aaronla@AARONLA-X C:\Users\aaronla>docker -v
Docker version 20.10.6, build 370c289

ntdev\aaronla@AARONLA-X C:\Users\aaronla>docker run -it mcr.microsoft.com/dotnet/sdk:5.0-windowsservercore-ltsc2019
docker: error during connect: In the default daemon configuration on Windows, the docker client must be run with elevated privileges to connect.: Post "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/create": open //./pipe/docker_engine: The system cannot find the file specified.
See 'docker run --help'.
```

**Describe the results you received:**

Error, as indicated above.

**Describe the results you expected:**

Success, as occurs when executing the same commands via an RDP session.

**Additional information you deem important (e.g. issue happens only occasionally):**

On both machines, OS is Windows 10 20H2. User ntdev\aaronla is member of Administrators group on both machines.

**Output of `docker version`:**

```
aaronla@aaronla-x:aaronla$ docker version
Client:
 Cloud integration: 1.0.14
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.16.3
 Git commit:        370c289
 Built:             Fri Apr  9 22:49:36 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.24)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:45:40 2021
  OS/Arch:          windows/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
aaronla@aaronla-x:aaronla$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.1)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 2
  Running: 1
  Paused: 0
  Stopped: 1
 Images: 7
 Server Version: 20.10.6
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 19042 (19041.1.amd64fre.vb_release.191206-1406)
 Operating System: Windows 10 Pro Version 2009 (OS Build 19042.985)
 OSType: windows
 Architecture: x86_64
 CPUs: 6
 Total Memory: 31.92GiB
 Name: aaronla-x
 ID: UGKB:MTXE:D2VT:7P5E:5SDX:5S26:ET6R:NC65:JSXP:XHFS:3BGB:QTO2
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by aaronla-ms** [comment]
A peer helped me identify a workaround. Out-of-box configuration of the sshd user on Windows doesn't impersonate administrators correctly. Fix is to manually add the sshd user to local Administrators group and restart the sshd service. Now commands work correctly.

Closing issue as external.

**Comment by rrmistry** [comment]
For anyone else not finding the `sshd` user, this is `NT SERVICE\sshd`

You can find it using:
![image](https://github.com/docker/cli/assets/25514145/a7c6f101-e568-461e-b788-817b20335e6e)

Remember to change `From this location:` to the current computer
