### ISSUE TITLE
support cross compile for other arch

### ISSUE THREAD

**Issue by andrewhsu** [docker/cli#31]
Would like to build cli binaries for:
* linux/ppc64le
* linux/s390x

But at the moment `gox` does [not support s390x](https://github.com/mitchellh/gox/blob/c9740af9c6574448fd48eb30a71f964014c7a837/platform.go#L38-L45).

**Comment by andrewhsu** [comment]
I created PR to add support to gox: https://github.com/mitchellh/gox/pull/85

**Comment by dnephin** [comment]
FYI #26 might require us to use something other than gox, I'm not sure how that's going to work yet

**Comment by tianon** [comment]
What's the use case for `gox` that isn't already solved by simply using `GOOS`/`GOARCH`?  Go's native cross-compilation support is pretty legendary in my experience (as of around Go 1.5), so I'm curious what `gox` is adding these days?

**Comment by dnephin** [comment]
I don't think there is anything special about it. It's just a convenient way to build a bunch of platforms in parallel from a simple command, with templating for the binary name.
