### ISSUE TITLE
[Feature Request] Add command for "Reset Kubernetes Cluster"

### ISSUE THREAD

**Issue by kevin-lindsay-1** [docker/cli#3101]
Right now, I don't see any command to reset the docker instance of kubernetes via the command line.

As a developer, part of my daily routine is to run a script that sets up my local cluster to a set starting point. I'm currently using Minikube on Mac, but I'd like to try DD for this, as minikube is a little extra complexity that I'm not sure is necessary for my team's needs.

In minikube, you pretty much just run `minikube delete` followed by `minikube start` to reset your cluster, whereas in DD it's a button in the UI; It would be really nice to make the button that resets the DD Kubernetes cluster a CLI command, preferably one that will wait until the reset is complete.

**Comment by mat007** [comment]
Hi @kevin-lindsay-1 
You may want to request this feature on https://github.com/docker/roadmap/issues/172.

**Comment by ndeloof** [comment]
Would indeed make sense to have a docker desktop CLI to replicate the UI commands.
I guess this issue should be closed, as not directly related to the docker CLI. Better report on https://github.com/docker/for-mac
