### ISSUE TITLE
Outdated tab completion for docker compose command

### ISSUE THREAD

**Issue by dipunj** [docker/cli#3118]
Hi,
I recently update to the latest docker version. This version brings in docker-compose as a subcommand of the docker cli, however the tab autocompletion for `docker compose` seems to be missing. 

The way I install tab completion for bash is:

```bash
curl -XGET \
          https://raw.githubusercontent.com/docker/cli/master/contrib/completion/bash/docker \
         > $(brew --prefix)/etc/bash_completion.d/docker
```

Can we include the autocompletion file within the docker installation itself, so the autocompletion logic is updated along with the docker updates?

**Comment by ndeloof** [comment]
Closing as a duplicate for https://github.com/docker/compose-cli/issues/1338

Need to investigate how to integrate a completion script for a CLI plugin

**Comment by thaJeztah** [comment]
Let me close this in favour of https://github.com/docker/compose-cli/issues/1338
