### ISSUE TITLE
K8s mismatch from Docker CLI and Buildx [Question]

### ISSUE THREAD

**Issue by Alvise88** [docker/cli#3144]
I'am working on a custom library with golang; I noticed compose-on-kubernetes is deprecated.
The problem arise when you use other libraries (for example docker buildx) which use a different version of  k8s (k8s.io/api, k8s.io/apimachinery, k8s.io/client-go, k8s.io/klog)

Can we remove kubernetes from docker stack command considering that  compose-on-kubernetes is deprecated ?

**Comment by mat007** [comment]
Same as #2967
There is work in progress, see #3139
