### ISSUE TITLE
Feature Request: Provide option to store images/containers/volumes on other drives

### ISSUE THREAD

**Issue by SetTrend** [docker/cli#3165]
I'm not sure if this is a Windows peculiarity, so I first posted my feature request to the [Docker for Windows issues list](/docker/for-win/issues/11357).

Professional Windows users tend to have more than just a single hard drive in their machines, using the second (and further) drives to store their data, while reserving the first drive (the so-called "C:" drive) for Windows and program installation (i. e., things that can easily be restored when Windows becomes inaccessible due to misconfiguration, hardware failure or whatever).

### Docker currently
lacks the ability to assign a mount point for images, containers and volumes.

At this time, my system disk (C:) is full, just by being mainly filled with WSL 2 containers, volumes and images.

My D: drive, however, is ...
1. empty
2. larger
3. expandable

#### Provide a `data-path` option with Docker
<br/>

1. Provide a __Data Path__ option with the Docker installer, allowing users to define a _default folder_ for storing images, containers and volumes.

1. Add a new __Data Path__ parameter to `docker build`, `docker commit`, `docker container create`, `docker create`, `docker run`, and `docker volume create`:

   `--data-path` {destination path}
<br/>

The destination path is supposed to be a directory wherein the corresponding image, container or volume will create its own, internal, private sub directory to store its data. So, if the destination directory was `D:\DockerData\tmp`, then an image, for example, may first create a sub directory, like `D:\DockerData\tmp\03624fa1359\` to then store its data therein.

<hr/>

Examples:

```batch
> docker build -t fromImage --data-path D:\DockerData\nano\ .
```

```batch
> docker run -d --name test --data-path D:\DockerData\nano\ fromImage
```

```batch
> docker volume create --data-path D:\DockerData\nano\ myStorage
```

**Comment by mat007** [comment]
Thanks @SetTrend, I believe the right location for feature request issues is https://github.com/docker/roadmap
I would transfer the issue but I don’t have the right permissions…

**Comment by SetTrend** [comment]
Thank you, @mat007.

Are you sure? From their readme I got the impression that: "**_We_** want to share with our customers what **_we_** plan"

**Comment by mat007** [comment]
Yes, that’s fine, see a bit below in the readme:
> Q: How can I provide feedback or ask for more information?
A: Please open an issue in this repo! If the issue is a bug or security issue, please follow the separate instructions above.

**Comment by SetTrend** [comment]
Ah, I see ... Thank you for pointing me!

Here's the new issue then: [/docker/roadmap/issues/239](/docker/roadmap/issues/239)
