### ISSUE TITLE
no way to make docker run be quiet

### ISSUE THREAD

**Issue by yaitskov** [docker/cli#3181]
`docker run` produce lots of output if image is not found in local repo.

```
Unable to find image 'dyaitskov/wrapparee:latest' locally
latest: Pulling from dyaitskov/wrapparee




Digest: sha256:1d8914674b341b59f4a4762098b703b770271af669be9417abd217db5e9ed400
Status: Downloaded newer image for dyaitskov/wrapparee:latest
```

I wasn't able to find a way how to disable that.
`--log-level error` or fatal has no effect.

I cannot redirect all output to /dev/null because  my docker container is interactive.

**Comment by thaJeztah** [comment]
Thanks for opening; this somewhat overlaps with https://github.com/docker/cli/issues/2017

I think it could make sense to add a `--quiet` option on `docker run` and `docker create` to suppress the pull output (the flag description should be clear though about _what_ output is suppressed (so only pull-related output), and that output from the container's process itself will still be printed (for non-detached containers)

**Comment by ch33hau** [comment]
Hi @thaJeztah , I took a look at #2017, and seems like `docker pull` has already implemented `quiet`. 
So what's left are docker run and docker create.

Can I take this task?

**Comment by ch33hau** [comment]
I have submitted the PR anyway since the code is already working on my laptop 😄

**Comment by thaJeztah** [comment]
Oh, sorry, I saw your comment fly by in my notifications, but didn't reply yet; thank you!!

**Comment by rmanak22** [comment]
Hi,

It looks like this issue has been completed but I would like to try and start contributing to Docker/CLI but I am not sure on how to configure my coding environment (I am on Mac). On the contributing to Docker page there is a link to setting up a Docker development environment and the contribution process but it goes to a page describing how to contribute to the documentation. Does anyone have any resources on how to set up a development environment on mac(I already have the docker application installed)?
