### ISSUE TITLE
Why the Size getting from 'docker image inspect' is not the same with 'docker image ls'

### ISSUE THREAD

**Issue by houweilong** [docker/cli#3209]
first I using 'docker image inspect' command to get the size of my image , the Size is 2773668963 Byte. Then I get the size using 'docker image ls', it shows 2.77G. But the 2773668963 Byte convert to GB is 2.58G.

**Comment by thaJeztah** [comment]
Difference between GiB and GB? (1024 based, vs 1000 based)? https://docs.ukcloud.com/articles/other/other-ref-gib.html

**Comment by houweilong** [comment]
Yes, Thanks. I have confused GB and GiB. Thanks. I have found the source code in https://github.com/docker/go-units/blob/master/size.go.
