### ISSUE TITLE
x509: certificate specifies an incompatible key usage

### ISSUE THREAD

**Issue by rwanito** [docker/cli#3214]
**Description**

Hi !

I've a CA in my /usr/local/share/ca-certificates folder.
I've restarted docker daemon and when I try to login onto my gitlab private registry (signed with the ca.crt) I have this error :

Error response from daemon : https://registry.../v2/: x509: certificate specifies an incompatible key usage.

My certificate which used to sign the domain has this following key usages :

    Digital signature
    content commitment
    key encipherment
    client auth
    email protection

It is enough or am I on a wrong way ?

Do you have any idea ?
Thanks
**Steps to reproduce the issue:**
1. Use your CA certificate 
2. Restart docker
3. Try docker login

**Describe the results you received:**
Error response from daemon : https://registry.../v2/: x509: certificate specifies an incompatible key usage.

**Describe the results you expected:**
Just a valid authentication

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Version: 20.10.7
Linux/amd64
```
I'm on a fresh install of Debian 11 with only an additional certificate.

**Comment by sfoerster** [comment]
Any details for why you were receiving the incompatible key usage error from letsencrypt?
