### ISSUE TITLE
Support Containerfile

### ISSUE THREAD

**Issue by hendrikhuels** [docker/cli#3251]
**Support Containerfiles**

When we build containers, it would be great if "docker build." would look for a Dockerfile first and then for a containerfile.

**Comment by cedws** [comment]
I'd be willing to send a PR for this but I'm not sure if the Docker team are open to the idea or not. It's the right move for the ecosystem but Docker Inc probably wants to remain at the center of it all. I say this with no hostility.

**Comment by Igorgro** [comment]
Hmm, docker-compose.yml was renamed to compose.yml, why not to rename this one also?

**Comment by benatkin** [comment]
> to keep the docker name out of it

It also keeps the Docker trademark out of it. People at Docker might think they're pleased with all mentions of it, but they might find reasons to object to it. Sure, it's free marketing, but it's also a source of confusion. There's currently a drama over the WordPress trademark.

However this *is* the `docker-cli` so it makes more sense docker would stick with it. Maybe BuildKit, which is a moby project, should support it. They rejected it for `.containerignore`, though. https://github.com/moby/buildkit/issues/3108

**Comment by ayush-suman** [comment]
Explains nicely why our team has switched to Podman and Containerd
