### ISSUE TITLE
-- blkio weight doesn't work. My docker version is docker-ce-1.19.03

### ISSUE THREAD

**Issue by herrywen-nanj** [docker/cli#3275]
My environment：

```
[root@openldap ~]# uname -a
Linux openldap 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
[root@openldap ~]# cat /etc/redhat-release 
CentOS Linux release 7.7.1908 (Core)
[root@openldap ~]# uname -i
x86_64
[root@openldap ~]# docker --version
Docker version 19.03.9, build 9d988398e7
```

I use the following command to test. It doesn't work
```
$ docker run -ti --name c1 --blkio-weight 100 ubuntu:14.04 /bin/bash
$ docker run -ti --name c2 --blkio-weight 1000 ubuntu:14.04 /bin/bash
```

Then I use the following command to test the speed
```
while true;do time dd if=/dev/zero of=test.out bs=1M count=100 oflag=direct;done
```

The same speed of execution in the two containers indicates that the weight does not take effect
![image](https://user-images.githubusercontent.com/33476935/130911370-3336e047-cd7c-43bf-a540-de487461afea.png)

My host IO scheduling algorithm is also CFQ
```
[root@openldap ~]# cat /sys/block/sda/queue/scheduler 
noop [deadline] cfq 
```

So how should I use -- blkio weight?

**Comment by thaJeztah** [comment]
This looks to be an issue in the engine, not the CLI; let me close this one in favour of https://github.com/moby/moby/issues/16173, to prevent the conversation from diverging
