### ISSUE TITLE
Incorrect URL to checkpoint reference doc

### ISSUE THREAD

**Issue by sudhakarau1** [docker/cli#3290]
https://github.com/docker/cli/blob/master/experimental/README.md has a reference to https://github.com/docker/cli/blob/master/docs/reference/commandline/checkpoint-restore.md in the Current Experimental Features section.
https://github.com/docker/cli/blob/master/docs/reference/commandline/checkpoint-restore.md  returns a 404.

**Comment by thaJeztah** [comment]
Ah, thanks for reporting; looks like I didn't update the URL correctly in https://github.com/docker/cli/pull/3267.

The correct location should be https://github.com/docker/cli/blob/master/docs/reference/commandline/checkpoint.md, but I'll open a PR to fix it

**Comment by thaJeztah** [comment]
opened https://github.com/docker/cli/pull/3291
