### ISSUE TITLE
Docker removes bridge entries from containers' /etc/hosts when disconnecting them from unrelated networks

### ISSUE THREAD

**Issue by zugzwang** [docker/cli#3338]
**Description**

When creating a container, some bridge IP is assigned to it and the entry `172.17.0.* <container_id>` is added to `/etc/hosts` (inside said container). This entry gets deleted when connecting and disconnecting the container to another network.

Let `mynet` be a custom network, and `C` be a container. If `C` is connected to `mynet` and then removed, both `mynet` and `bridge` assigned IPs are removed from `C:/etc/hosts`.

The expected behavior is that only the relevant `/etc/hosts` entry is removed.

c.c. @Pagten

**Steps to reproduce the issue:**
1. Run an image `docker run -it --rm --name example debian:latest`
2. Examine `/etc/hosts`: 
```
root@fc801aeeba0c:/# cat /etc/hosts 
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.2	fc801aeeba0c    <----- BRIDGE NETWORK 
```
3. Create `mynet` network: `docker network create --subnet=172.99.0.0/16 mynet`
4. Connect the container to this network: `docker network connect mynet fc801aeeba0c`
5. Inspect `/etc/hosts` again:
```
root@fc801aeeba0c:/# cat etc/hosts
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.2	fc801aeeba0c      <----- BRIDGE NETWORK
172.99.0.2	fc801aeeba0c      <----- MYNET NETWORK
```
6. Disconnect the container from `mynet`: `docker network disconnect mynet fc801aeeba0c`
7. Inspect `/etc/hosts` again:
```
root@fc801aeeba0c:/# cat etc/hosts
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
```
8. Both IPs were removed from `/etc/hosts` in the container. 

Furthermore, connecting `mynet` again will add the `mynet` entry (e.g., connecting to mynet -> disconnecting to mynet -> connecting to mynet is not the identity).

**Describe the results you received:**
The bridge IP assigned to the container was removed from `etc/hosts` after disconnecting the container from an unrelated network.

**Describe the results you expected:**
Only the relevant IP should be removed from `/etc/hosts`.

**Additional information**
When connecting and then disconnecting to `mynet`, `docker network inspect` shows the expected behavior, e.g. the container is connected to `bridge` and disconnected from `mynet`.

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:47 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf583a
  Built:            Fri Oct 18 15:52:23 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 17
  Running: 1
  Paused: 0
  Stopped: 16
 Images: 95
 Server Version: 19.03.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-88-generic
 Operating System: Ubuntu 20.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.33GiB
 Name: <REDACTED>
 ID: <REDACTED>
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
My laptop running Ubuntu 20.04. Other environment details: Nice temperature, respectful neighbors and warm coffee.

**Comment by thaJeztah** [comment]
Thanks for reporting! I see you're running on an older version of Docker (19.03). If you have a test environment to test things, are you able to still reproduce this on the current version (20.10.9 at time of writing)?

I tried reproducing on 20.10, but so far didn't manage to:

```bash
docker run -d --name foobar nginx:alpine
```

Checking `/etc/resolv.conf` and `/etc/hosts` (when attached to the `bridge` network);

```bash
docker exec foobar sh -c 'echo "/etc/resolv.conf:"; cat /etc/resolv.conf; echo "/etc/hosts:"; cat /etc/hosts'

/etc/resolv.conf:
# DNS requests are forwarded to the host. DHCP DNS options are ignored.
nameserver 192.168.65.5
 /etc/hosts:
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.2	a0b516780b9a
```

Create `mynet` and connect the container to that network:

```bash
docker network create --subnet=172.99.0.0/16 mynet
docker network connect mynet foobar
```

Checking `/etc/resolv.conf` and `/etc/hosts` again:

```bash
docker exec foobar sh -c 'echo "/etc/resolv.conf:"; cat /etc/resolv.conf; echo "/etc/hosts:"; cat /etc/hosts'

/etc/resolv.conf:
nameserver 127.0.0.11
options ndots:0
/etc/hosts:
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.2	a0b516780b9a
172.99.0.2	a0b516780b9a
```

In the above, the nameserver is switched to use the embedded DNS (`127.0.0.11`). `/etc/resolv.conf` looks to be correct.


> Other environment details: Nice temperature, respectful neighbors and warm coffee.

That's the best environment! Here's a 🍪 to make it even better 😅

**Comment by zugzwang** [comment]
Thanks for the detailed background. It makes sense, I will try to reproduce in 20.10 as soon as I update (hopefully next week).

**Comment by sam-thibault** [comment]
I don't see any recent activity on this issue.  I will close it as stale.
