### ISSUE TITLE
docker pull not work with proxy

### ISSUE THREAD

**Issue by wgf4242** [docker/cli#3351]
Proxy works with curl.

Bind docker proxy in `/etc/systemd/system/docker.service.d/proxy.conf` , but not work.

Proxy server does not get any request .
```
[Service]
Environment="HTTP_PROXY=http://192.168.42.174:1235/"
Environment="HTTPS_PROXY=https://192.168.42.174:1235/"
```

property correctly.
```
# systemctl show --property Environment docker
Environment=HTTP_PROXY=http://192.168.42.174:1235/ HTTPS_PROXY=https://192.168.42.174:1235/ 
# systemctl daemon-reload
# systemctl restart docker
```

pull failed

```
➜  ~ docker pull mysql
Using default tag: latest
Error response from daemon: Get "https://registry-1.docker.io/v2/": proxyconnect tcp: net/http: TLS handshake timeout
```

logs

```
10月 28 01:06:22 localhost.localdomain dockerd[1593]: time="2021-10-28T01:06:22.709504167+08:00" level=debug msg="Calling HEAD /_ping"
10月 28 01:06:22 localhost.localdomain dockerd[1593]: time="2021-10-28T01:06:22.710627127+08:00" level=debug msg="Calling GET /v1.41/info"
10月 28 01:06:22 localhost.localdomain dockerd[1593]: time="2021-10-28T01:06:22.742388072+08:00" level=debug msg="Calling POST /v1.41/images/create?fromImage=mysql&tag=latest"
10月 28 01:06:22 localhost.localdomain dockerd[1593]: time="2021-10-28T01:06:22.794957913+08:00" level=debug msg="hostDir: /etc/docker/certs.d/y9dkc6wt.mirror.aliyuncs.com"
10月 28 01:06:22 localhost.localdomain dockerd[1593]: time="2021-10-28T01:06:22.795026979+08:00" level=debug msg="Trying to pull mysql from https://y9dkc6wt.mirror.aliyuncs.com/ v2"
10月 28 01:06:32 localhost.localdomain dockerd[1593]: time="2021-10-28T01:06:32.796756601+08:00" level=warning msg="Error getting v2 registry: Get \"https://y9dkc6wt.mirror.aliyuncs.com/v2/\": proxyconnect
10月 28 01:06:32 localhost.localdomain dockerd[1593]: time="2021-10-28T01:06:32.796821901+08:00" level=info msg="Attempting next endpoint for pull after error: Get \"https://y9dkc6wt.mirror.aliyuncs.com/v2/
10月 28 01:06:32 localhost.localdomain dockerd[1593]: time="2021-10-28T01:06:32.796864938+08:00" level=debug msg="Trying to pull mysql from https://registry-1.docker.io v2"
10月 28 01:06:42 localhost.localdomain dockerd[1593]: time="2021-10-28T01:06:42.798291415+08:00" level=warning msg="Error getting v2 registry: Get \"https://registry-1.docker.io/v2/\": proxyconnect tcp: net
10月 28 01:06:42 localhost.localdomain dockerd[1593]: time="2021-10-28T01:06:42.798414130+08:00" level=info msg="Attempting next endpoint for pull after error: Get \"https://registry-1.docker.io/v2/\": prox
10月 28 01:06:42 localhost.localdomain dockerd[1593]: time="2021-10-28T01:06:42.799873228+08:00" level=error msg="Handler for POST /v1.41/images/create returned error: Get \"https://registry-1.docker.io/v2/
l
```

**Comment by araisch** [comment]
Got similar problem with Docker on Windows 10 with WSL 2. Was working for years but stopped working lately.
I tried:
- Set proxy in Docker Desktop - Settings - Resources - Proxies
- Set ENVs https_proxy and http_proxy in upper and lower case via /etc/profile.d in `docker-desktop` distro.
- Set ENVs in Windows
- and all combinations out of those.

But there is definitely no proxy used (according to logs)

**Comment by araisch** [comment]
Likely related to https://github.com/docker/for-win/issues/12503

**Comment by thaJeztah** [comment]
Thanks for linking that ticket, @araisch - yes, it you're running Docker Desktop, then it's most likely due to https://github.com/docker/for-win/issues/12503. You can verify if that's the issue by checking the output of `docker info` - if your configured proxy server does not appear in the output, then it's related to that ticket. This will be fixed in Docker Desktop.


As to the original issue reported by @wgf4242 - I think we need more information; the logs look to be truncated, and the relevant information may be in the part that's not shown (for example, in the output below, there may be an error after `proxyconnect`;


```
Error getting v2 registry: Get \"https://y9dkc6wt.mirror.aliyuncs.com/v2/\": proxyconnect
```

I suspect it may be something in your setup / something specific to the proxy that's used or some other networking issue, but without more details, that's hard to tell

**Comment by sam-thibault** [comment]
I don't see any recent activity on this issue.  I will close it as stale.  We had been waiting for more info.
