### ISSUE TITLE
ENTRYPOINT does not work with symlinks - (Not sure where to file this)

### ISSUE THREAD

**Issue by ORESoftware** [docker/cli#337]
It looks like ENTRYPOINT does not work with symlinks:

`ENTRYPOINT ["/usr/src/app/node_modules/.bin/suman"]`

If you are not familiar with Node.js/NPM, the contents of `node_modules/.bin` are symlinks

doesn't look like that ENTRYPOINT works, because of the symlink thing

**Comment by dnephin** [comment]
If it's a symlink that was created on the host, that points to a host path, then it's expected that it wont work, because the symlink is broken.

Please provide more information about the paths and the contents of the symlink

**Comment by ORESoftware** [comment]
In my Dockerfile

`COPY . . `

where . is the root my project which includes node_modules

does that give you enough info?

**Comment by dnephin** [comment]
Is the symlink created in the Dockerfile or on the host?

**Comment by ORESoftware** [comment]
sorry idk for sure - you tell me, I am copying node_modules from host to container...so I believe the symlink would be copied with COPY.

**Comment by the1mills** [comment]
Bump on this one pls

**Comment by dnephin** [comment]
Yes, it sounds like the symlinks are created on the host. This is not expected to work. symlinks are just small files have that contain target path. The target path on this case will be the nodejs global library directory. This directory is not at the same path in the container as it is on the host (unless you happen to be running a container with a similar distribution as the host, but you should never rely on that).

The solution is most likely to do the `npm install` inside the container. You could add `node_modules/` to `.dockerignore` to prevent them from being copied.


Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)

Closing this issue, but feel free to continue the conversation :+1:
