### ISSUE TITLE
Support for docker stack run is missing

### ISSUE THREAD

**Issue by GabKlein** [docker/cli#34]
Just like a `docker-compose run <service> rake db:migrate` with the whole environment, dependencies and services started (postgres, redis, etc...), it would be very use full to run a container within a deployed stack `docker stack run <stack_name> <service> rake db:migrate`

The workaround would be to ssh the correct node and to run an docker exec on the right container. This is not friendly and can be a source of errors.

**Comment by dnephin** [comment]
Yes, I agree we need some way to encode "project tasks" like database migration in a config format. "within a stack" really just means "on the same network as the services in the stack". So some way to define a service that only runs once and joins the same network would be great.

I don't think a command like `docker stack run` really works with the design we have for the CLI. It implies you would "run a stack" with that command, but really what you want is to run a one-off service on a specific network. 

If we had a config that allows you to define tasks (like database migration), and you could define dependencies between tasks (database migration depends on a stack being deployed first), I think that would provide the functionality you need.

**Comment by GabKlein** [comment]
It depends, I very often find myself running more that one cmd to set an env.
I also like the `run` mode as it let me use the entry point of my image. For instance when I want to open a terminal in production I can run `docker-compose run <service> rails console`.

I'm using docker to build feature branches that are a pile of micro services connected all together. Like you said "on the same network" but also with the same `env variables` and other `dependent services` that all need to be started/deployed before I could run a `cmd`.

Just like `docker-compose run` start all dependent services if not already started, I would expect `docker stack run` to do the same if not already deployed.

An other approach could be a `docker service run <service_name>` using the same stack.yml (to read from the `depends_on:`, or not)

**Comment by dnephin** [comment]
Thanks for the issue. `docker stack run` does not fit the resource/operation pattern we have today in the CLI, but I've opened #359 to discuss other options to support this type of workflow.
