### ISSUE TITLE
Docker run runs command in host, not container on macOS Monterey

### ISSUE THREAD

**Issue by saltermitch** [docker/cli#3400]
**Description**

The command docker run --rm -it --volume $(pwd):/home/node/app node:10.17.0 npm install, which is working on macOS Catalina, is failing on macOS Monterey. Looking at the behavior and the logs, it becomes clear that the npm install command is running on the local machine, with the local node version, and NOT in the container.

**Steps to reproduce the issue:**
1. Create a folder with any sort of node app
2. From the folder, at the same level as the package.json, execute docker run --rm -it --volume $(pwd):/home/node/app node:10.17.0 npm install

**Describe the results you received:**
The command pulls the image, and runs npm install with the LOCAL node version, not the 10.17.0 version from the image.

**Describe the results you expected:**
npm install should run on the container, using version 10.17.0

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Docker version 20.10.12, build e91ed5707e
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.7.1)
  compose: Docker Compose (Docker Inc., v2.2.1)
  scan: Docker Scan (Docker Inc., v0.14.0)

Server:
 Containers: 3
  Running: 3
  Paused: 0
  Stopped: 0
 Images: 5
 Server Version: 20.10.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 1.942GiB
 Name: docker-desktop
 ID: WK4Q:QIHX:Q74H:QAX5:MSNV:J7FQ:IUAF:PXHI:LWXB:FLQS:QVDJ:4BQD
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
macOS Monterey

**Comment by thaJeztah** [comment]
Hmm.. can you provide more details what lead to the conclusion it's running the wrong node version (and that it's running on the host?)

I'm not a node developer, but I had some old version of npm installed on my machine;

```bash
npm --version
6.4.1
```

I took the "Sample application" steps from https://docs.docker.com/language/nodejs/build-images/#sample-application


```bash
mkdir repro-3400 && cd repro-3400
npm init -y
npm install ronin-server ronin-mocks

cat > server.js <<'EOF'
const ronin = require('ronin-server')
const mocks = require('ronin-mocks')

const server = ronin.server()

server.use('/', mocks.server(server.Router(), false, true))
server.start()
EOF
```


Trying your reproduction steps;

```
docker run --rm -it --volume $(pwd):/home/node/app node:10.17.0 npm install

npm WARN saveError ENOENT: no such file or directory, open '/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/package.json'
npm WARN !invalid#2 No description
npm WARN !invalid#2 No repository field.
npm WARN !invalid#2 No README data
npm WARN !invalid#2 No license field.

up to date in 0.408s
found 0 vulnerabilities
```

Given that it's complaining about a missing `package.json`, I suspect your repro steps need the working directory inside the container to be set (so that the `npm instal` command is exected from within that directory);

```bash
docker run --rm -it --volume $(pwd):/home/node/app -w /home/node/app node:10.17.0 npm install

npm WARN repro-3400@1.0.0 No description
npm WARN repro-3400@1.0.0 No repository field.

audited 106 packages in 1.48s
found 0 vulnerabilities
```

Also to verify it's indeeed running inside the container;

```bash
docker run --rm -it --volume $(pwd):/home/node/app -w /home/node/app node:10.17.0 npm --version
6.11.3
```

**Comment by saltermitch** [comment]
Looks like confusion on my part, between behavior on my (Catalina) system and behavior viewed in meetings on other devs' Monterey systems. Seem to have resolved things (with the help of the reply above), and the following appears to work:

docker run --rm -it --platform=linux/amd64 -v $(pwd):/home/node/app -w /home/node/app node:10.17.0 /bin/bash -c "npm install && npx gulp"

**Comment by thaJeztah** [comment]
Ah, if you tried using `npm install && npx gulp` (without `bash -c`) before, then the first command (`npm install`) would've run inside the container, and then `npx gulp` would run "after the container run exited" and be run in the host; perhaps that's what happened
