### ISSUE TITLE
Unable to install docker on a raspberry pi - not sure why? 

### ISSUE THREAD

**Issue by jonathanalevi** [docker/cli#3403]
**Description**

I'm trying to install Docker on a raspberry pi (I've tried two different ones, a 3B and a 4B) with Octopi installed.

**Steps to reproduce the issue:**
1. SSH into Octopi install
2. apt-get update
2. Run curl -sSL https://get.docker.com | sh

**Describe the results you received:**

```
# Executing docker install script, commit: 93d2499759296ac1f9c510605fef85052a2c32be
+ sudo -E sh -c apt-get update -qq >/dev/null
+ sudo -E sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
E: Essential packages were removed and -y was used without --allow-remove-essential.
```

Docker doesn't seem to be installed. 

**Describe the results you expected:**
Docker should install. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
-bash: docker: command not found
```

**Output of `docker info`:**

```
-bash: docker: command not found
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
Hmm.. not sure what would cause that; how does Octopi differ from raspbian? (I know for sure the script won't be tested on Octopi). Is your install a 32-bit or 64-bit install? (as we currently only have 32-bit packages for raspbian, but 64-bit packages for debian)

**Comment by sam-thibault** [comment]
I don't see any recent activity on this issue.  I will close it as stale.
