### ISSUE TITLE
Feature Request: Allow multiple containers to have the same port exposed.

### ISSUE THREAD

**Issue by AlixPlayzz** [docker/cli#3404]
I know this has been talked about _a bit_ before. But all the few things I've found haven't really given me a conclusive answer.

Anyway. Currently two docker containers cant have the same port exposed. This causes quite a lot of problems. For example, what if two docker containers need to communicate. That won't work, and I don't understand why this isn't possible.
I get that it _could_ introduce problems in some cases. But at least give people the option to do it, maybe with like a warning or something.

I'm assuming this would take like 10 minutes for you guys to implement and it would help out so so many people.
Thanks - Alex

**Comment by thaJeztah** [comment]
Multiple containers can expose and listen on the same port (on their own IP address), for example, you can start multiple nginx containers listening on port 80. But when mapping a port to the host's network interface, the host's port can only be used once (it's not possible to have multiple processes use the same port on a machine).

Can you describe a bit more in detail (perhaps with an example) what you're trying to do, and what didn't work?

**Comment by sam-thibault** [comment]
I don't see any recent activity on this issue.  I will close it as stale.
