### ISSUE TITLE
Command: docker context show does not exist for Linux client

### ISSUE THREAD

**Issue by mattKaczorowski** [docker/cli#3425]
**Description**

When typing `docker context`, the help menu shows the `context show` command is missing.

```
$ docker context

Usage:  docker context COMMAND

Manage contexts

Commands:
  create      Create a context
  export      Export a context to a tar or kubeconfig file
  import      Import a context from a tar or zip file
  inspect     Display detailed information on one or more contexts
  ls          List contexts
  rm          Remove one or more contexts
  update      Update a context
  use         Set the current docker context

Run 'docker context COMMAND --help' for more information on a command.

```

**Steps to reproduce the issue:**
1. Download docker for a linux machine (in my case Ubuntu)
2. Run: docker context show

**Describe the results you received:**
Docker client shows the help screen for `docker context`

**Describe the results you expected:**
I expect to see the output describing the name of my current context: `default`
I also expect the command to exist.

**Additional information you deem important (e.g. issue happens only occasionally):**
I have the same client version installed on an M1 mac and the expected command is there.

**Output of `docker version`:**

Client Version Info:
```
$ docker version
Client: Docker Engine - Community
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:45:33 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.12
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.12
  Git commit:       459d0df
  Built:            Mon Dec 13 11:43:42 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

**Output of `docker info`:**

```
$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.7.1-docker)
  scan: Docker Scan (Docker Inc., v0.12.0)

Server:
 Containers: 7
  Running: 0
  Paused: 0
  Stopped: 7
 Images: 430
 Server Version: 20.10.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.13.0-28-generic
 Operating System: Ubuntu 20.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 24
 Total Memory: 62.71GiB
 Name: zen
 ID: 5OKD:WYZW:6QEP:27NA:ANWB:WNMZ:TH2T:D5FP:L6ZR:BL3L:SKLR:VXN7
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: mkaczorowski
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
local machine

**Comment by thaJeztah** [comment]
Looks like the `docker context show` subcommand was something that was added in the "cloud integration", which is a wrapper for the `docker` cli that's maintained in the https://github.com/docker/compose-cli repository, and adds some additional functionality to the CLI. To install the cloud integration CLI on Linux, you can follow the instructions on https://docs.docker.com/cloud/aci-integration/ and https://docs.docker.com/cloud/ecs-integration/

I'm not sure if a decision was made to port that subcommand to the main CLI

/cc @chris-crone @ndeloof @mat007

**Comment by ndeloof** [comment]
this is indeed a new verb introduced by compose-cli: https://github.com/docker/compose-cli/blob/c11a458666ac7e2de05719c5a0f461d0269f7d5d/cli/cmd/context/show.go#L30

**Comment by thaJeztah** [comment]
Heh, I recall https://github.com/docker/cli/pull/2500 was probably created for the same purpose at the time (looks like it was done shortly before https://github.com/docker/compose-cli/pull/109)

**Comment by mattKaczorowski** [comment]
> a useful one to write scripts which depend on the active context

:100: 

Saves me a bit of ugly bash.

**Comment by mattKaczorowski** [comment]
ty!

**Comment by mattKaczorowski** [comment]
> If you need this right now, without installing the cloud wrapper, you can use this to get the current context;
> 
> ```shell
> docker version --format='{{.Client.Context}}'
> ```

One bit of feedback for this workaround. The command tends to hang if the remote host is unreachable (which is a different problem altogether). It's certainly slower than the docker context show command.
