### ISSUE TITLE
Labels do not support heredocs

### ISSUE THREAD

**Issue by marceloboeira** [docker/cli#3448]
**Description**

From the docker docs, it seems that it should be possible to use `heredocs` to declare multi-line commands/items and labels. However, when trying to do that with labels specifically, it doesn't work:
 
```docker
FROM scratch
LABEL "foo.bar" <<-eot
[{
  "this": "is",
  "a": "json",
  "file": "yEAHHhH"
}]
eot

COPY hello /
CMD ["/hello"]
```

or even:

```docker
FROM scratch
LABEL "foo.bar" <<EOF
[{
  "this": "is",
  "a": "json",
  "file": "yEAHHhH"
}]
EOF

COPY hello /
CMD ["/hello"]
```

I have tried many symbol combinations and nothing really worked.

**Steps to reproduce the issue:**
1. copy the example Dockerfile
2. run `docker build .`
3. see it fail

**Describe the results you received:**
Docker errors
```
[+] Building 0.1s (2/2) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                     0.0s
 => => transferring dockerfile: 173B                                                                                                                                                     0.0s
 => [internal] load .dockerignore                                                                                                                                                        0.0s
 => => transferring context: 2B                                                                                                                                                          0.0s
failed to solve with frontend dockerfile.v0: failed to create LLB definition: dockerfile parse error line 3: unknown instruction: [{
```

**Describe the results you expected:**

* The container image is built
* The container image contains the multi-line label

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:20 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:10 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-rc.3)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 820
 Images: 1
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.47-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 1.938GiB
 Name: docker-desktop
 ID: QRYH:BHI5:XVWC:RNOG:MKZ6:W77T:3Y63:55DI:XXSC:4FKE:TZUL:2ZQB
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by ndeloof** [comment]
heredocs is only available with buildkit custom syntax, see https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/syntax.md

basically, you just need to add `# syntax=docker/dockerfile:1.4` on top of your `Dockerfile`

**Comment by thaJeztah** [comment]
^^ generally, for the stable front-end, I'd recommend using `# syntax=docker/dockerfile:1`, doing so will always use the latest stable syntax when building with BuildKit enabled (it will check if the latest syntax is present, and otherwise pull it before building); https://docs.docker.com/engine/reference/builder/#official-releases

In this case, the dockerfile 1.4 syntax was not yet released (it's still a release candidate:  https://github.com/moby/buildkit/releases/tag/dockerfile%2F1.4.0-rc2), so until it's GA (`v1.4.0`) you may need to temporarily use either:

```dockerfile
# syntax=docker.io/docker/dockerfile-upstream:1.4.0-rc2
```

or the `labs` variant ("unstable" - with new features before they reach the "stable" syntax);

```dockerfile
# syntax=docker.io/docker/dockerfile:1-labs
```

**Comment by thaJeztah** [comment]
oh, actually, just realised heredocs, are not yet supported for `LABEL`, only for `RUN` and `CMD`. During the implementation it was decided to limit scope; https://github.com/moby/buildkit/pull/2132#issuecomment-849117230
If you have specific use-cases for `LABEL`, you can comment on https://github.com/moby/buildkit/issues/2169, which is tracking that.


Let me close this ticket, as this doesn't look to be a bug in the cli code, but a feature request for BuildKit (see the link above), but feel free to continue the conversation

**Comment by marceloboeira** [comment]
@thaJeztah thanks for confirming it and pointing me to the other issue! I'll share the use-cases there!
