### ISSUE TITLE
docker stats panic，get error “panic: send on closed channel”

### ISSUE THREAD

**Issue by kkltcjk1** [docker/cli#3482]
**Description**
When run command: docker stats --no-stream, and start a container at the same time, there is a low probability that this panic occurs.

the line cause panic is:
https://github.com/docker/cli/blob/0e3c9b282e877c87cd06b4c8c8661d8463f412b6/cli/command/container/stats.go#L79

the channel close in:
https://github.com/docker/cli/blob/0e3c9b282e877c87cd06b4c8c8661d8463f412b6/cli/command/container/stats.go#L154

So it is quite clear ,before return the channel has been closed, but there is a new container start at the same time, and send a event in monitorContainerEvents goroutine, then write this event to the channel which has been closed. Then the panic occurs.

**Steps to reproduce the issue:**
1.docker stats --no-stream
2.docker run -itd hello-world /bin/bash

It is hard to reproduce it, but I did get this panic serveral times. I have a way to reproduct it by a little change in 
https://github.com/docker/cli/blob/0e3c9b282e877c87cd06b4c8c8661d8463f412b6/cli/command/container/stats.go#L154

```
eventChan := make(chan events.Message)
go eh.Watch(eventChan)
go monitorContainerEvents(started, eventChan)
defer func(c chan events.Message) {
	close(c)
	time.Sleep(120*time.Second)
}(eventChan)
// defer close(eventChan)
<-started
```

**Describe the results you received:**
get error “panic: send on closed channel”

**Describe the results you expected:**
no panic

**Comment by thaJeztah** [comment]
Thanks for reporting; I haven't looked closely at the code (or a possible solution) yet, but it appears you already did some investigating; if you have a fix in mind, are you interested in contributing, and opening a pull request?
