### ISSUE TITLE
[feature] respect .containerignore if present

### ISSUE THREAD

**Issue by Jiehong** [docker/cli#3484]
Hi,

Today, docker reads `.dockerignore` file to know what to ignore when sending data to the build context.

Given a repository, if people use other container engines, such as podman, they might want to use `.containerignore` instead (even though today podman also reads `.dockerignore`), to be more agnostic of the build engine.

It would be nice if docker would also handle `.containerignore`.

**Comment by thaJeztah** [comment]
Thanks for opening this proposal; per my comment on https://github.com/docker/cli/issues/3251#issuecomment-1063338859, I don't think we have plans on supporting this.

**Comment by kittydoor** [comment]
Would it be possible to consider a flag such as `--ignorefile` used by podman to enable use of a custom name, as the counterpart to #3251 `-f` for Dockerfile alt names?

**Comment by thaJeztah** [comment]
There was a proposal for a `--ignore` option in https://github.com/moby/moby/issues/12886, but it was rejected in favor of supporting a `<name of Dockerfile>.dockerignore` file  (so if your Dockerfile would be named `MyDockerfile`, and a `MyDockerfile.dockerignore`, that ignore file is preferred over `.dockerignore` (if present)

**Comment by kamikaze** [comment]
what a shame
