### ISSUE TITLE
-compose -version

### ISSUE THREAD

**Issue by jfmunoz00** [docker/cli#3515]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by ndeloof** [comment]
no description, maybe related to docker/compose but wrong repository. closing
