### ISSUE TITLE
docker run mcr.microsoft.com/windows/servercore:ltsc2022 -i --isolation=hyperv resulting in errors

### ISSUE THREAD

**Issue by jt0dd** [docker/cli#3548]
**Description**

According to Docker's [documentation](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/version-compatibility?tabs=windows-server-2022%2Cwindows-11-21H2), using `--isolation=hyperv` should make most versions of windows images compatible:

![enter image description here](https://i.stack.imgur.com/QBpuO.png)

So it seems like compatibility shouldn't be an issue with hyper-v.

Well, when I run:
```
    docker run mcr.microsoft.com/windows/servercore:ltsc2022 -i --isolation=hyperv
```
**Describe the results you received:**

I get the error (see the bottom of the thread, I'm aware the top is just a matter of the image being pulled):

```
    docker : Unable to find image 'mcr.microsoft.com/windows/servercore:ltsc2022' locally
    At line:1 char:1
    + docker run mcr.microsoft.com/windows/servercore:ltsc2022 -i --isolati ...
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : NotSpecified: (Unable to find ...sc2022' locally:String) [], RemoteException
        + FullyQualifiedErrorId : NativeCommandError
     
    ltsc2022: Pulling from windows/servercore
    8f616e6e9eec: Pulling fs layer
    037d5740b404: Pulling fs layer
    037d5740b404: Verifying Checksum
    037d5740b404: Download complete
    8f616e6e9eec: Verifying Checksum
    8f616e6e9eec: Download complete
    8f616e6e9eec: Pull complete
    037d5740b404: Pull complete
    Digest: sha256:343f8c95ec604913c74597f6d541e388f83bc0ce373ee8ea5bb26d268879f338
    Status: Downloaded newer image for mcr.microsoft.com/windows/servercore:ltsc2022
    docker: Error response from daemon: container 597ea2d8b5564b2a8771980c3c809b6e059d00d8bc831e97b3cf14a071820aed encountered an error during hcsshim::System::CreateProcess: failure in a Windows system call: The system cannot find 
    the file specified. (0x2)
    [Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]
    [Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]
    [Event Detail: onecore\vm\compute\management\orchestration\vmhostedcontainer\processmanagement.cpp(173)\vmcomputeagent.exe!00007FF61BE0EFBD: (caller: 00007FF61BDB4E97) Exception(2) tid(3c8) 80070002 The system cannot find the 
    file specified.
        CallContext:[\Bridge_ProcessMessage\VmHostedContainer_ExecuteProcess] 
     Provider: 00000000-0000-0000-0000-000000000000].
```

This is after I've tried many different images, with and without hyper-v, restarted my PC, and reset Docker to factory default settings.

Removing `--isolation=hyperv` results in precisely the same error. I've also tried `--isolation=process` and gotten the same error.

**Describe the results you expected:**

A Windows shell

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
    Client:
     Cloud integration: v1.0.22
     Version:           20.10.13
     API version:       1.41
     Go version:        go1.16.15
     Git commit:        a224086
     Built:             Thu Mar 10 14:13:04 2022
     OS/Arch:           windows/amd64
     Context:           default
     Experimental:      true
    
    Server: Docker Desktop 4.6.1 (76265)
     Engine:
      Version:          20.10.13
      API version:      1.41 (minimum version 1.24)
      Go version:       go1.16.15
      Git commit:       906f57f
      Built:            Thu Mar 10 14:08:21 2022
      OS/Arch:          windows/amd64
      Experimental:     false
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.1)
  compose: Docker Compose (Docker Inc., v2.3.3)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 3
  Running: 0
  Paused: 0
  Stopped: 3
 Images: 4
 Server Version: 20.10.13
 Storage Driver: windowsfilter
  Windows: 
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 22000 (22000.1.amd64fre.co_release.210604-1628)
 Operating System: Windows 10 Pro Version 2009 (OS Build 22000.556)
 OSType: windows
 Architecture: x86_64
 CPUs: 16
 Total Memory: 31.92GiB
 Name: DESKTOP-4KS9BL7
 ID: CVZW:NI3U:JZC6:N763:N5AR:34KN:3QAO:KGIQ:SYDS:WODV:YDGK:U2X7
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I'm running a valid, licensed copy of Windows 11 Pro on a physical PC.

**Comment by jt0dd** [comment]
I just noticed that if I run the *image* directly from the Docker for Windows CLI, it works. I get a shell, no problems. So why could the CLI be broken?

**Comment by jt0dd** [comment]
I figured out the issue. All of this testing has been from a PowerShell ISE terminal. And that's creating the issue somehow. From any other terminal, it actually works.

**Comment by jt0dd** [comment]
It's just been brought to my attention that [this is a known thing](https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/run-your-first-container#run-a-windows-container) but the documentation wording there sounds more like it's a bug the dev team didn't feel like fixing. That's fin, but at least catch this error and produce a helpful error message please.

With all the many docker docs out there, most people are not going to notice that little (*btw no PS ISE*) mention on one page.

**Comment by jt0dd** [comment]
Ok, *the plot thickens*.

I don't mean to complicate things, but each time I think it's working, I find a different thing causing a problem.

This works:
`docker run -it mcr.microsoft.com/windows:20H2 --isolation=hyperv`

This doesn't:
`docker run -it mcr.microsoft.com/windows:20H2 --isolation=hyperv --name workstation_1`

When I add the --name workstation_1 argument, which according to `docker run --help` is a valid argument:

![img](https://i.gyazo.com/db76732821c4760badbf9d8badcffb6a.png)

I get this error:

```
docker: Error response from daemon: container 1118d316b0700307943bec10392b39266b79db08350311618fb5bfc247e2fa8d encountered an error during hcsshim::System::CreateProcess: failure in a Windows system call: The system cannot find the file specified. (0x2)
[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]
[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000]
[Event Detail: onecore\vm\compute\management\orchestration\vmhostedcontainer\processmanagement.cpp(173)\vmcomputeagent.exe!00007FF6EBB1A40B: (caller: 00007FF6EBAD5C8B) Exception(1) tid(398) 80070002 The system cannot find the file specified.
    CallContext:[\Bridge_ProcessMessage\VmHostedContainer_ExecuteProcess]
 Provider: 00000000-0000-0000-0000-000000000000].
```

**Comment by thaJeztah** [comment]
Looks like the same cause as your other ticket https://github.com/docker/cli/issues/3549

As to documentation; documentation of images on docker hub is maintained by the respective image publishers (in this case Microsoft); if there's issues with that documentation, it's best to report it via the link mentioned under the "support" section on that page.

**Comment by thaJeztah** [comment]
> In most CLIs can't the argument orders (especially named arguments), be used more freely?

The [POSIX guidelines](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html) generally recommends flags (options) to appear before positional arguments (operands). While tools often are somewhat more flexible, for example, while on `docker inspect` the flags _should_ be used before the image name, the cli also accepts them to be reversed;

```bash
docker inspect --format="{{.ID}}" busybox:latest

docker inspect busybox:latest --format="{{.ID}}" 
```

This can only work for _some_ commands though, and was not _intentional_ (but has worked in the past, so we kept the "feature" to not unnecessarily break users), but we don't document (nor officially support) this.

> Would it be so hard for Docker CLI to just do better parsing of the arguments passed to it?

... for example, on `docker run`, `docker create`, and `docker exec` the order _cannot_ be reversed, because the position where they appear has a different meaning.

For example, on a Linux container with `/bin/busybox` as entrypoint, the `--help` flag after the image name is handled by busybox in the container;

```bash
$ docker run --rm --entrypoint=/bin/busybox busybox:latest --help
BusyBox v1.34.1 (2022-03-10 23:58:34 UTC) multi-call binary.
...
...
```

Putting the `--help` flag _before_ the image name, means it's an option to handle by the `docker run` command:

```bash
$ docker run --rm --entrypoint=/bin/busybox --help busybox:latest
Usage:  docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

Run a command in a new container
...
```

> It isn't exactly difficult to parse --flag=value from a string after all.

Don't under-estimate the complexity involved in parsing command-line options 😅; command-line parsing can be _very_ complicated; there's many corner-cases (see https://twitter.com/thaJeztah/status/1260921988102656002?s=20 and https://github.com/urfave/cli/issues/1092 for some fun), and depending on the platform or executable in use, sometimes literally _impossible_ (see https://github.com/opencontainers/runtime-spec/pull/998 for some discussion on that (and, yes, that pull request came from Microsoft, and no, they were not able to fix it in Windows itself)).

**Comment by jt0dd** [comment]
Thanks for the explanations, clearly this is a subject I was incredible naive on.
