### ISSUE TITLE
 Can I cancel the process of docker pull image? without ctrl+c

### ISSUE THREAD

**Issue by GuoYingLong** [docker/cli#3570]
Can I cancel the process of docker pull image? without ctrl+c

**Comment by cpuguy83** [comment]
I"m not sure I understand the case here.
The way to cancel is to kill the process.
`ctrl+c` is equivalent of `kill -s SIGINT <docker cli pid>` which is a graceful way to kill the process.

**Comment by ndeloof** [comment]
There's indeed no other way to cancel a `docker pull` but to send SIGINT signal to the process, which is the same as Ctrl+C in your terminal. Can you please clarify the context and reasons you want to cancel a pull?
