### ISSUE TITLE
Dead external link

### ISSUE THREAD

**Issue by craig-osterhout** [docker/cli#3589]
Issue From: https://github.com/docker/docker.github.io/issues/11239

File: [engine/extend/legacy_plugins.md](https://docs.docker.com/engine/extend/legacy_plugins/)

Dead link: https://connect.nimblestorage.com/community/app-integration/docker

Update the Nimble DVP to https://scod.hpedev.io/docker_volume_plugins/hpe_nimble_storage/index.html

**Comment by thaJeztah** [comment]
looks like this was fixed through https://github.com/docker/cli/pull/3590
