### ISSUE TITLE
Feature request: --silent flag for docker create

### ISSUE THREAD

**Issue by princefishthrower** [docker/cli#3596]
Hello Docker team,

I was wondering if a `--silent` flag could be create for the `docker create` command. Currently, there is no built-in way to supress the container ID that is output when creating a container, i.e.:

```shell
docker create my-awesome-image-tag
5c1a30c64bb61b6bc6b237ed6f29e9ecbd1f1a2256c0f0dccf16f6011ee0e767
```

Could be:

```shell
docker create --silent my-awesome-image-tag
```

I know I can redirect `stdout` with `1>/dev/null`:

```shell
docker create my-awesome-image-tag 1>/dev/null
```

So perhaps a `--silent` command is considered not necessary. Not sure what the philosophy here is.

Interested to hear thoughts on this.

**Comment by thaJeztah** [comment]
Yes, I don't think we should do this; we have `--quiet` option on some command to suppress the _informational_ output (progress bars etc), but as this output is considered the "functional" output of the command, I would consider piping the output to `/dev/null` to be the correct approach to suppress this.

FWIW, the reason this output is printed on STDOUT is to allow chaining commands, which allows (e.g.);

```bash
docker create busybox | xargs docker inspect
```

**Comment by princefishthrower** [comment]
Fair enough on my side, I'll close I guess. Thanks for the input from everyone! 😄
