### ISSUE TITLE
Docs - bullet in filtering list isn't displaying correctly

### ISSUE THREAD

**Issue by mbentley** [docker/cli#361]
**Description**

Originally reported in https://github.com/docker/docker.github.io/issues/3219; was suggested to submit an issue here.  Formatting issue with the documentation due to pipes in example: 

![screenshot 2017-07-12 at 2 15 04 pm](https://user-images.githubusercontent.com/414445/28133005-89e38f10-670c-11e7-99ac-4799aa689bf0.png)

**Steps to reproduce the issue:**
n/a - docs

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by glyif** [comment]
#dibs

**Comment by glyif** [comment]
already seems to be fixed with this: https://github.com/docker/cli/pull/393
