### ISSUE TITLE
Docker REST API documentation requires "Reservation" without "s" at the end.

### ISSUE THREAD

**Issue by sanderegg** [docker/cli#3611]
**Description**

The documentation provided for the Docker Rest API v1.41 for Create Service requires a "Reservation" object (singular) when in fact it takes the plural form.

**Steps to reproduce the issue:**
1. Start a service with Reservation field

**Describe the results you received:**
No reservation set on the service

**Describe the results you expected:**
A reservation set.

**Additional information you deem important (e.g. issue happens only occasionally):**

Please correct the documentation, as in fact using the plural form "Reservations" works.

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rumpl** [comment]
👋 @sanderegg I opened a PR in moby/moby where the API is defined: https://github.com/moby/moby/pull/43605

**Comment by rumpl** [comment]
The documentation is updated now, closing, thanks @sanderegg
