### ISSUE TITLE
would you able to support for --all option for stop, rm, kill...

### ISSUE THREAD

**Issue by boojongmin** [docker/cli#3622]
I usually use command 

```shell
	docker stop $(docker ps -a -q)
	docker rm $(docker ps -a -q)
```

I referenced [stackoverflow deleting-all-docker-images-and-containers](https://stackoverflow.com/questions/38060279/deleting-all-docker-images-and-containers), [docker reference command rm](https://docs.docker.com/engine/reference/commandline/rm/)

I often forget `$(docker ps -a -q)`

when add option `--all`
I think adding this option will improve usability, what do you think?

like this
```shell
	docker stop --all
	docker rm --all
```

thank you for 

ps - `docker system prune` aren't fit for my use cases. :)

**Comment by photra** [comment]
Hi @boojongmin, this issue had previously been raised in #3565. We currently have PR #3580 currently in design review. Feel free to follow them for updates!

**Comment by boojongmin** [comment]
@photra 

I'm so happy by PR #3580. I hope merge soon. thank you very much :)
