### ISSUE TITLE
Feature Request: docker swarm join --label-add key=value

### ISSUE THREAD

**Issue by lifubang** [docker/cli#3626]
Hi, I want to label some nodes automatically after they joined in a swarm cluster. 
At this time, after some nodes joined, I had to login to the manager node to use `docker node update --label-add key=value nodeName` to add some labels to these nodes. It's not convenient for me to do some large node scaling.

I think the node should have its initial labels when joining the swarm cluster.

I checked the `docker swarm join` command, and didn't find this type option.
```
root@exam-temp:~# docker swarm join --help

Usage:  docker swarm join [OPTIONS] HOST:PORT

Join a swarm as a node and/or manager

Options:
      --advertise-addr string   Advertised address (format: <ip|interface>[:port])
      --availability string     Availability of the node ("active"|"pause"|"drain") (default "active")
      --data-path-addr string   Address or interface to use for data path traffic (format: <ip|interface>)
      --listen-addr node-addr   Listen address (format: <ip|interface>[:port]) (default 0.0.0.0:2377)
      --token string            Token for entry into the swarm
```

If someone could provide some helps, thanks very much.

**Comment by thaJeztah** [comment]
Per the above, I don't think this can be implemented (at least not without breaking an essential part of the design considerations of swarm), so I'll close this ticket, but feel free to continue the conversation

**Comment by lifubang** [comment]
> you _can_ configure the engine itself to have labels

Thanks very much. I think it may be useful for me.

**Comment by thaJeztah** [comment]
Great!


So just to be clear (and for future readers who arrive here); the "engine" labels appear in a different part of the node info. For example, the node below has a _swarm_ label "swarm-label01", and two engine labels ("label1", "label2");

```bash
docker node inspect swarm-test-04
```

```json
[
    {
        "ID": "n41b2cijmhifxxvz56vwrs12q",
        "Version": {
            "Index": 385318
        },
        "CreatedAt": "2019-03-29T23:43:26.73415124Z",
        "UpdatedAt": "2022-05-20T17:54:12.85523956Z",
        "Spec": {
            "Labels": {
                "region": "region-b",
                "swarm-label01": "foobar"
            },
            "Role": "worker",
            "Availability": "active"
        },
        "Description": {
            "Hostname": "swarm-test-04",
            "Platform": {
                "Architecture": "x86_64",
                "OS": "linux"
            },
            "Resources": {
                "NanoCPUs": 1000000000,
                "MemoryBytes": 1033375744
            },
            "Engine": {
                "EngineVersion": "20.10.16",
                "Labels": {
                    "label1": "one",
                    "label2": "two"
                },
                "Plugins": [
                  "..."
                ]
            }
        },
        "Status": {
            "State": "ready",
            "Addr": "xxxxx"
        }
    }
]
```

And (for example) you can filter nodes by either `label` (which are engine labels) and `node.label` (which are swarm labels); https://docs.docker.com/engine/reference/commandline/node_ls/#filtering
