### ISSUE TITLE
Proxy authentication not working

### ISSUE THREAD

**Issue by roebst** [docker/cli#3649]
[x ] I have tried with the latest version of Docker Desktop
[x ] I have tried disabling enabled experimental features
 I have uploaded Diagnostics
Diagnostics ID:
Actual behavior
I configured  proxy as described here:
https://docs.docker.com/network/proxy/#configure-the-docker-client
and
https://docs.docker.com/config/daemon/systemd/#httphttps-proxy

docker pull hello-world
```
Using default tag: latest
Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on 172.19.96.1:53: read udp 172.19.107.241:50415->172.19.96.1:53: i/o timeout

```
Expected behavior
Proxy Authentication works

Information
Windows Version: Win 10 Build 19042
Docker Desktop Version: 20.10.14, build a224086
WSL2 or Hyper-V backend? wsl2

**Comment by thaJeztah** [comment]
Let me close this one in favor of https://github.com/docker/for-win/issues/12758, as this may be specific to docker desktop
