### ISSUE TITLE
Adding aliases to config.json

### ISSUE THREAD

**Issue by Bungogood** [docker/cli#3673]
Hello Team,

Problem description
It's a feature request/idea. I find using docker that certain commands are run over and over for example `docker stop -f $(docker ps -q)` to stop all containers or `docker run --rm -it` to jump into an image but kill the container once I've exited. Would it be possible to add aliases to dockers config.json

For example using a similar system to git with .gitconfig:
```
[alias]
	cm = commit -m
        ca = commit --amend
```

Example config.json:
```json
{
    ...
    "alias" : {
        "end": "rm -f $(docker ps -a -q)",
        "pause": "stop -f $(docker ps -q)",
        "tmp": "run --rm -it"
    }
}
```
Bad names for the alias but just some examples.

Thanks

**Comment by h3n4l** [comment]
Maybe using a shell alias can do the same thing?

**Comment by thaJeztah** [comment]
Yes, I think this is a bit out of scope for the docker cli itself; this is similar to the proposal that was made in https://github.com/moby/moby/issues/16702 (implementation in https://github.com/moby/moby/pull/16703), where we also concluded that this would be re-implementing what the shell already provides.

Having arbitrary commands in the aliases could also be a potential security risk (e.g., think of `$(curl <something>)` or `$(cat ~/.ssh/...)`), which may lead to, erm, unexpected results.

I'm closing this ticket for now, as I don't see this as something we'd want to implement currently
