### ISSUE TITLE
Docker completion missing in 4.9.1?

### ISSUE THREAD

**Issue by kbd** [docker/cli#3689]
Just took the auto-update from Docker Desktop (Mac) to 4.9.1 (81317) and now completion is broken.

Getting:

```
compinit:527: no such file or directory: /usr/local/share/zsh/site-functions/_docker
```

I had previously followed the instructions to set up Zsh completion here: https://docs.docker.com/desktop/mac/#zsh

```
etc=/Applications/Docker.app/Contents/Resources/etc
ln -s $etc/docker.zsh-completion /usr/local/share/zsh/site-functions/_docker
ln -s $etc/docker-compose.zsh-completion /usr/local/share/zsh/site-functions/_docker-compose
```

Looks like the `docker.zsh-completion` file is missing in this version?

```
$ ls /Applications/Docker.app/Contents/Resources/etc
_docker*  docker-compose.bash-completion*  docker-compose.zsh-completion
docker*   docker-compose.fish-completion   docker.fish*
```

**Comment by nicks** [comment]
thanks for the report! ya, this is a regression, we have a fix for it in the next release. Please follow along here - https://github.com/docker/for-mac/issues/6343

**Comment by thaJeztah** [comment]
let me close this one in favour of https://github.com/docker/for-mac/issues/6343 as it's specific to Docker Desktop
