### ISSUE TITLE
Move docker iptables Rules Into Their Own Chains

### ISSUE THREAD

**Issue by KimBrodowski** [docker/cli#3698]
Hello,
when integrating docker into wider Linux environments, often automated tools are used to manage firewall rules. In our case, we use a wrapper around [ferm](http://ferm.foo-projects.org/). Others utilize iptables/nftables more directly, or ufw and other high level solutions.

Unfortunately, docker manipulates iptables rules directly. For individual containers, it is feasible to disable iptables rule creation in docker and setup rules yourself. This is mostly how we do things now.

When using docker-compose however, complexity increases. Since docker-compose configuration files are often pulled from upstream, required changes might not even by obvious.

Since automated updates are important for security reasons, this can end up breaking services quickly.

An easy solution for this would be to just leave docker alone doing it's thing and just managed all the firewall rules around the ones provided by docker.

There's a problem though: It's not trivial to identify and leave rules created by docker.

As can be since in [this example provided by iptables-docker](https://github.com/garutilorenzo/iptables-docker), docker sets up dynamic rules in the FORWARD and POSTROUTING chains as well. If docker were to confine itself to static rules in standard chains, we could provide these in our firewall configuration and just leave the docker specific chains as they are. Ideally we would also be able to tell docker not to create static, but only dynamic chains then.

This is the solution I'm proposing here.

An alternative would be to add an option to docker so it can fix iptables rules without restarting the docker daemon. Firewall changes happen frequently for us. Restarting docker entirely every time firewall rules change would lead to a significant downtime of services, especially since some docker containers need a significant time to start.

Projects like iptables-docker clearly show that integration of docker into other managed iptables environments is a somewhat common issues. Furthermore, the unpredictable nature of docker's firewall implementation can also lead to security problems. I had a service being accidentally exposed to the internet on one of my private machines due to rules setup by docker. The nasty bit of that problem was, that it only happened under very specific circumstances, when docker was started after my firewall, but no DSL disconnect took place.

I'd also like to point out that I'm not familiar with the structure of docker's GitHub repos, so feel free to move this issue if appropriate.

Thank you for your time.

**Comment by thaJeztah** [comment]
Looks like this is related to the upstream docker/moby daemon code, which sets up the iptables rules; unfortunately the issue tracker for that is in a different org, so I cannot transfer the ticket; could you open a new ticket in https://github.com/moby/moby ?

**Comment by matthijskooijman** [comment]
I've posted an issue which is essentially a repost of this issue at https://github.com/moby/moby/issues/44816
