### ISSUE TITLE
Add support for stop_signal in docker stack deploy

### ISSUE THREAD

**Issue by christopherobin** [docker/cli#370]
**Description**

`stop_signal` support was added to `swarmkit` in [docker/swarmkit#1924](https://github.com/docker/swarmkit/pull/1924) and `docker` in [moby/moby#30754](https://github.com/moby/moby/pull/30754) but it is still not supported via `docker stack deploy -c compose-file.yml stack_name`.

It would be a welcome addition since some of our containers need SIGINT to properly exit.
If it's fine with you guys I could probably do a PR with this functionality.

**Steps to reproduce the issue:**

1. Add `stop_signal: SIGINT` to a docker-compose file
2. `docker stack deploy -c <file> <name>`
3. `docker stack scale service=0`

**Describe the results you received:**

The service gets a SIGTERM signal

**Describe the results you expected:**

The service gets a SIGINT signal

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   3dfb8343
 Built:        Sat Jul  8 20:56:41 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87617
 Built:        Sat Jul  8 22:56:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
N/A
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

N/A

**Comment by thaJeztah** [comment]
Support for stop-signal was added to services in docker 17.04 through https://github.com/moby/moby/pull/30754, and https://github.com/moby/moby/pull/31091, so this should just be adding the option to the docker-compose file specs and cli

**Comment by salzig** [comment]
![bildschirmfoto 2019-01-15 um 13 06 10](https://user-images.githubusercontent.com/99911/51179608-5cbd1e80-18c6-11e9-82d2-e00121a178df.png)
https://docs.docker.com/compose/compose-file/#not-supported-for-docker-stack-deploy

The Documentation is still telling us another story.

**Comment by thaJeztah** [comment]
@salzig thanks! Looks like the documentation side changes never found their way in; see 
https://github.com/docker/cli/pull/388#issuecomment-319532708

Are you interested in opening a pull request to make that change? There's an "edit this page" link on the top-right of that page in the documentation; that should open an editor on GitHub and you can open a pull-request from that 🤗
