### ISSUE TITLE
found non-compliant/unsecure ciphers in docker port 2376 & 2377

### ISSUE THREAD

**Issue by vishnuRamesh96** [docker/cli#3740]
**Description**

</head>

<body link="#0563C1" vlink="#954F72">

please let me know the procedure to remove following unsecure cipher suites for docker port : 2376 and 2377

docker port 2376 (Used for encrypted communication with the daemon) :

Hexcode | Cipher Suite Name (OpenSSL) | Encryption | Cipher Suite   Name (IANA/RFC)
-- | -- | -- | --
x1303 | TLS_CHACHA20_POLY1305_SHA256 | ChaCha20 | TLS_CHACHA20_POLY1305_SHA256
xc014 | ECDHE-RSA-AES256-SHA | AES | TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
xc013 | ECDHE-RSA-AES128-SHA | AES | TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA

docker port 2377 (Used for communication between the nodes of a Docker Swarm or cluster)
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/visrames/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/visrames/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

Hexcode | Cipher Suite Name (OpenSSL) | Encryption | Cipher Suite   Name (IANA/RFC)
-- | -- | -- | --
x1303 | TLS_CHACHA20_POLY1305_SHA256 | ChaCha20 | TLS_CHACHA20_POLY1305_SHA256
xcca9 | ECDHE-ECDSA-CHACHA20-POLY1305 | ChaCha20 | TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
xc00a | ECDHE-ECDSA-AES256-SHA | AES | TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
xc009 | ECDHE-ECDSA-AES128-SHA | AES | TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA

</body>

</html>

</body>

</html>

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
un-secure ciphers are found

**Describe the results you expected:**
Only necessary and secure ciphers should be present in the system

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```

Client: Docker Engine - Community
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:03:11 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:29 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

**Output of `docker info`:**

```

Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 14
  Running: 12
  Paused: 0
  Stopped: 2
 Images: 17
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: mxwfniooro0p9x13u6rnn76xw
  Is Manager: true
  ClusterID: 5vv1h7xxmn2u8fmuauc43426y
  Managers: 2
  Nodes: 2
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 135.250.142.150
  Manager Addresses:
   135.250.142.150:2377
   135.250.142.151:2377
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc version: v1.1.2-0-ga916309
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.18.0-372.9.1.el8.x86_64
 Operating System: Red Hat Enterprise Linux 8.6 (Ootpa)
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 122.7GiB
 Name: VM150
 ID: GQX5:AHYO:AHYV:7RLY:MLSI:2IXA:O5SZ:37ZV:T5HR:XS7H:QEO7:GSTY
 Docker Root Dir: /nfmt/images
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  0.0.0.0/0
  127.0.0.0/8
 Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by vishnuRamesh96** [comment]
please let me know if any findings have been made regarding this issue

**Comment by laurazard** [comment]
Hiya! This issue is more of a Docker Engine (Moby) issue than a CLI issue, and indeed there have been issues/discussions opened about this there. This [discussion](https://github.com/moby/moby/discussions/45121) in particular is relevant, and we have a [ticket](https://github.com/docker/go-connections/blob/58542c764a1173ea3dac965d89146c931a2946f7/tlsconfig/config.go#L44-L49) for this in the upstream `go-connections` where these weak ciphers are being set.

I'll close this issue here, but feel free to contribute to those other issues/discussions.
