### ISSUE TITLE
(When) is there going to be a new release?

### ISSUE THREAD

**Issue by frebib** [docker/cli#3750]
### Description

20.10 is almost 2 years old at this point. Is there a new release planned?
I see the 22.06 milestone created and went stale pretty fast with little movement recently.
Is there a timeline, roadmap or plan going forward?

**Comment by s4ke** [comment]
There is a beta release available for 22.06 :)

https://github.com/moby/moby/releases/tag/v22.06.0-beta.0

**Comment by thaJeztah** [comment]
docker 23.0 and 24.0 have now been released
