### ISSUE TITLE
docker port CONTAINER should return stable output

### ISSUE THREAD

**Issue by inikulshin** [docker/cli#3856]
### Description

This is very minor issue, but I think that every call for `docker port CONTAINER` for the same container should return exactly the same output.
Currently it seems that order of ports is not stable.

I can think of

1. Order by port number
2. Order of `EXPOSE` in `.dockerfile`

Any one of them is better then unstable output.

**Comment by thaJeztah** [comment]
Thanks for reporting; yes, it would make sense to show them in a consistent order; option "2." probably won't be possible, as the order in which they're defined in `EXPOSE` is not preserved, but we can sort the output in a consistent way.

Let me have a quick look to implement that.
