### ISSUE TITLE
[dev] Allow to rebuild dev environments

### ISSUE THREAD

**Issue by ThePlenkov** [docker/cli#3911]
### Description

Hi!

I've decided to explore Beta feature dev environments. The idea is great but of course is not new - we've already been used to develop in containers within some time which even led to a separate spec: https://containers.dev/

One of the most convenient features in devcontainers for me - is the ability to change the environment quickly without touching the code itself. Just for example - changing base OS image build version - easy, updating devcontainer.json/compose.yaml/Dockerfile with a new version and rebuilding container with VS Code/Gitpod/Codespace and etc..

The problem with docker dev environment is that changing compose-dev.yaml file has no impact on the  existing development environment. To apply the change currently I need to make this change, push to git and to create a new environment - which is not what I want for sure. In this case I have to initialize many things manually again, install dependencies, VS Code extensions and so on.

So I just thought, having something like `docker dev rebuild my-service-devcontainer` or `docker dev start my-service-devcontainer --rebuild` would solve the issue probably. 

What do you think?

Thanks!

**Comment by thaJeztah** [comment]
Let me transfer this ticket to the dev-environments issue tracker, as that feature is not maintained in this repository.

**Comment by ThePlenkov** [comment]
@thaJeztah what's the right way to post the issue there? =) thanks!

**Comment by thaJeztah** [comment]
@ThePlenkov as I haven't got permissions yet to transfer the ticket, perhaps you can open a new one in https://github.com/docker/dev-environments, which is where feedback and reports related to dev-environments can be reported.

**Comment by ThePlenkov** [comment]
Yes - i already see similar requests there. We can close this one then. 
https://github.com/docker/dev-environments/issues/134
https://github.com/docker/dev-environments/issues/101
https://github.com/docker/dev-environments/issues/22

**Comment by thaJeztah** [comment]
Thanks!
