### ISSUE TITLE
Broken blog link on Docker run reference page

### ISSUE THREAD

**Issue by PaulVittorino** [docker/cli#3938]
### Description

https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities contains a link to https://blog.docker.com/2013/09/docker-can-now-run-within-docker/ but that page now lives at <https://www.docker.com/blog/docker-can-now-run-within-docker/>.

### Reproduce

In the following sentence

> Additional information about running with --privileged is available on the [Docker Blog](https://blog.docker.com/2013/09/docker-can-now-run-within-docker/).

click on the Docker Blog link. Observe the link redirects to <https://www.docker.com/blog/>.

### Expected behavior

Link goes to https://www.docker.com/blog/docker-can-now-run-within-docker/

### docker version

```bash
N/A
```

### docker info

```bash
N/A
```

**Comment by vvoland** [comment]
Thanks, I opened a PR: https://github.com/docker/cli/pull/3939

**Comment by thaJeztah** [comment]
fixed in https://github.com/docker/cli/pull/3939
