### ISSUE TITLE
`docker image rm -f` should exit with 1 if the image was not removed

### ISSUE THREAD

**Issue by dnephin** [docker/cli#394]
This was changed in #160, but there are some problems with this new behaviour.

`rm -f /some/file` still exits with 1 if you don't have permission to remove it.
`docker image rm -f` should exit with 1 if the image was not removed.

**Comment by dnephin** [comment]
cc @thaJeztah @vieux

**Comment by thaJeztah** [comment]
ah, yes, if it _failed_ to remove it should exit with 1, if the image did not exist in the first place, we can ignore; does that SGTY?

**Comment by dnephin** [comment]
Yes, that sounds correct to me

**Comment by adshmh** [comment]
#dibs

**Comment by abhinavkorpal** [comment]
I am not able to clean the /var/lib/docker/overlay ...Any suggestion should i get ?

**Comment by eiais** [comment]
@dnephin I think this should have been closed after #654 merged.

**Comment by dnephin** [comment]
yup, thanks!
