### ISSUE TITLE
zsh autocompletion: docker compose

### ISSUE THREAD

**Issue by mateusz-was** [docker/cli#3955]
### Description

Hi!

Just finished setup of my new VM (Ubuntu + zsh + ohmyzsh) and discovered that:

1. On zsh, using `docker com [tab]` doesn't have compose in it. It provides: 
```
> docker com [tab]
commit     -- Create a new image from a container's changes
config     -- Manage Docker configs
container  -- Manage containers
context    -- Manage contexts
```
2. Using the same on `bash` works without an issue.
3. Using `docker-compose [tab]` works as expected.
4. Using `docker compose version` works as expected. Any command written manually works ok.
5. Using `docker composer [tab]` doesn't work (no suggestions).

Took a look on the https://github.com/docker/cli/tree/master/contrib/completion and, yup, there are no subcommands for compose for zsh.
Relevant config for bash is here: https://github.com/docker/cli/blob/master/contrib/completion/bash/docker#L5400

Small note, if you find this before the feature is implemented, the easiest workaround is using https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/docker-compose, which provides handy `dco` alias for `docker-compose` ;)

**Comment by sam-thibault** [comment]
Looks like we need something for zsh similar to this change for bash: https://github.com/docker/cli/pull/3752

**Comment by floviolleau** [comment]
Hi,

Any clues?

**Comment by andresrinivasan** [comment]
Based on reading through https://github.com/ohmyzsh/ohmyzsh/issues/11751, I used `docker completion zsh >~/.zfunc/_docker` (I don't use Oh My Zsh) and made sure `~/.zfunc` was early in my fpath.

```
$ docker --version
Docker version 24.0.3, build 3713ee1eea

$ docker compose version
Docker Compose version 2.19.1

$ docker com[tab]
commit   compose

$ docker compose [tab]
build    -- Build or rebuild services
config   -- Parse, resolve and render compose file in canonical format
cp       -- Copy files/folders between a service container and the local filesystem
create   -- Creates containers for a service.
down     -- Stop and remove containers, networks
events   -- Receive real time events from containers.
exec     -- Execute a command in a running container.
images   -- List images used by the created containers
kill     -- Force stop service containers.
logs     -- View output from containers
ls       -- List running compose projects
pause    -- Pause services
port     -- Print the public port for a port binding.
ps       -- List containers
pull     -- Pull service images
push     -- Push service images
restart  -- Restart service containers
rm       -- Removes stopped service containers
run      -- Run a one-off command on a service.
start    -- Start services
stop     -- Stop services
top      -- Display the running processes
unpause  -- Unpause services
up       -- Create and start containers
version  -- Show the Docker Compose version information
```

**Comment by brlipi** [comment]
@andresrinivasan Doing this fixed the `docker compose [tab]` autocomplete not working (in my case I dropped the file at `/usr/share/zsh/site-function` but I believe the effect it the same). But if you diff the file that gets output by `docker completion zsh` it has way fewer features than the completion file that comes in `/usr/share/zsh/vendor-completion` (of which I had to copy manually to site-functions so I could finally get any autocomplete).

Maybe someone with more knowledge of completion scripts could merge the advantages of both into one?

**Comment by thomscode** [comment]
@brlipi,
Try this file. I was able to more or less combine them so you can have both `docker` completions and `docker compose` completions for ZSH: [docker.zsh-completion.txt](https://github.com/user-attachments/files/16897424/docker.zsh-completion.txt)

**Note:** I had to add the`.txt` extension to allow upload here.

**Comment by laurazard** [comment]
@thomscode @brlipi 

> Doing this fixed the docker compose [tab] autocomplete not working (in my case I dropped the file at /usr/share/zsh/site-function (I'm on Fedora) but I believe the effect it the same). But if you diff the file that gets output by docker completion zsh it has way fewer features than the completion file that comes in /usr/share/zsh/vendor-completion (of which I had to copy manually to site-functions so I could finally get any autocomplete).

Part of the reason why this file is shorter than the previous file is that this file relies on completion logic inside the CLI itself (and compose) for the autocompletion logic. A lot of the complex logic (checking running containers, volumes, projects, etc.) instead is executed by the actual binary and returned.

We're moving to try to standardize on using the cobra completions and the other file isn't actively maintained, so I'd suggest using the file generated by `docker completion zsh` – however, if you do find any missing feature please report it so that we can address it.

**Comment by thomscode** [comment]
@laurazard,
Thank you for that update. The last time I tried the generated completions for ZSH they did not work for Docker Compose. They are working now and I'm happy to have them available for use.
