### ISSUE TITLE
Subsequent `docker cp` fail after overwriting /etc/hosts in a container

### ISSUE THREAD

**Issue by mklepaczewski** [docker/cli#398]
**Description**

When *overwriting* a file in container subsequent requests to docker cp fail. It's no longer possible to either overwrite the file or even to copy it from container to host system. It's also impossible to copy *any* file from the container.

**Steps to reproduce the issue:**

I'm using simple nginx image as an example. The issue has been reproduced on other images and other systems.
1. docker run --name ngx nginx
2. docker cp /etc/hosts ngx:/etc/hosts
3. docker cp ngx:/etc/hosts temp.tmp

**Describe the results you received:**

`Error response from daemon: invalid argument`

**Describe the results you expected:**

Copy of ngx:/etc/hosts on the host system

**Additional information you deem important (e.g. issue happens only occasionally):**

It seems that there's additional mount point that's not cleared properly:
```
$ mount|grep hosts
/dev/vda1 on /var/lib/docker/aufs/mnt/c0edd0ce31bb7f73480f516781204d8f00a2c7cdb30ca27640243404f8af1ced/etc/hosts type ext4 (rw,relatime,data=ordered)
```

It's impossible to remove the container:
```
$ docker rm ngx
Error response from daemon: Driver aufs failed to remove root filesystem 0febc7530439452c5b98d1bd04a6d82860acaa4c33e29e3e6db01f3a84957f34: aufs: unmount error after retries: /var/lib/docker/aufs/mnt/c0edd0ce31bb7f73480f516781204d8f00a2c7cdb30ca27640243404f8af1ced: device or resource busy
```

**Output of `docker version`:**

```
Docker version 1.12.6, build 78d1802
```

**Output of `docker info`:**

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 1
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 7
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-83-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.953 GiB
Name: ubuntu-2gb-fra1-01
ID: Z7WH:R6XG:UUJB:O5RL:6ZZ7:KECR:ZTH7:RQFQ:LH2T:A5QR:2CZM:MK3U
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

First machine:
```
$ uname -a
Linux ubuntu-2gb-fra1-01 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

Second:
```
$ uname -a
Linux speedy 4.8.0-36-generic #36~16.04.1-Ubuntu SMP Sun Feb 5 09:39:57 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by thaJeztah** [comment]
Do you see this happening specific with `/etc/hosts`? When using the default bridge network, `/etc/hosts` is managed for service discovery (i.e. when using `--link`, docker adds entries to the file). Wondering if that's related here

**Comment by mklepaczewski** [comment]
Indeed, it seems to be a problem specific to /etc/hosts file.

**Comment by thaJeztah** [comment]
Is here a specific reason you're overwriting that file? Note that there's also the `--add-host` flag, which allows you to add custom host entries (if you're not able to setup a DNS server)

**Comment by mklepaczewski** [comment]
I have three containers which depend on each other and need to communicate with each other. I can't use --add-host because IP address of any container might change during runtime (due to restarts or anything else). I can't use --link since it's deprecated. I'm pretty sure there is a better way to do it but it probably requires more knowledge about docker/dns/other things. My approach might not be the best but it is.. familiar and easy enough for a novice user. 

I currently use following workaround:

- copy the /etc/hosts to host layer,
- update the file on the host side,
- use `docker exec {container} sh -c "echo \"$(cat /modified/etc/hosts)\" > /etc/hosts"` to update /etc/hosts in containers,

All in all I'm willing to accept that it can't be done the way I initially intended to do it. However in this case Docker should prevent me from overwriting any of those special files (e.g. /etc/hosts) and give me clear error message when I try to do it. The dangling mount point is also an issue  which in my opinion should be taken care of.

**Comment by thaJeztah** [comment]
Right yes, there's no need to go through these steps; containers, if attached to the same docker network are able to communicate with eachother by name; something like this should do;

1. create a network

```
docker network create mynet
```

2. start your containers with a name, and using the network you just created

```
docker run -d --name=one --network=mynet nginx:alpine

docker run -d --name=two --network=mynet nginx:alpine
```

Now container `two` can connect with container `one` using `one` as hostname. The other way round works as well; `one` can connect to `two`, using `two` as hostname.

Regarding `--link`; this flag is still supported, but using it with the default network (which rewrites `/etc/hosts`) is discouraged.

When using custom networks (like my example above) `--link` uses a built-in DNS server, and more reliable, which is perfectly fine to use

**Comment by vvoland** [comment]
/etc/hosts can no longer be replaced, so this issue doesn't happen anymore.

```bash
$ docker cp /etc/hosts ngx:/etc/hosts
Error response from daemon: Error processing tar file(exit status 1): unlinkat /etc/hosts: device or resource busy
```

Container should reference other containers by their name and there's no need to replace the `/etc/hosts`.
