### ISSUE TITLE
Does the interactive mode actually attach both STDIN and STDOUT?

### ISSUE THREAD

**Issue by Chung-NB** [docker/cli#4003]
### Description

+ I'm trying to dockerize a python file, which both requires me to enter some inputs and receive some outputs

+ After building the 'Dockerfile', I run the commands of `docker build .` and `docker run -i imageId`, then restart the container with `docker start -i containerId`

+ Here, i only use the `-i` flag, and do not use the `-a` flag which attach STDOUT anywhere, but i'm both able to enter inputs and listen to outputs from the container

### Reproduce

docker build .
docker run -i imageId
docker start -i containerId

### Expected behavior

I do not attach the STDOUT with the `-a` flag but I'm able to listen to the outputs from the container

### docker version

```bash
Docker version 20.10.21
```

### docker info

```bash
Docker version 20.10.21 running on MacOS Ventura 13.0.1
```

**Comment by qlanduril** [comment]
If you look at the [docker run reference](https://docs.docker.com/engine/reference/run/#foreground) you can see that adding just `-i` flag without `-a` flag adds both the `STDIN` and `STDOUT`.
