### ISSUE TITLE
*docker stack deploy* interprets *version: "3.0"* differently than *version: "3"*

### ISSUE THREAD

**Issue by gatisnolv** [docker/cli#4006]
### Description

docker stack deploy interprets Compose file version specification of "3.0" differently than "3", in contrast to what the documentation would suggest here: [https://docs.docker.com/compose/compose-file/compose-versioning/#version-3](https://docs.docker.com/compose/compose-file/compose-versioning/#version-3), specifically the part "_If no minor version is given, 0 is used by default and not the latest minor version._"

While I realize the doc might be talking about 'docker compose' rather than 'docker stack deploy', this is surprising and unexpected, and I would expect the implementations to behave identically in this regard.

### Reproduce

1. On a docker Swarm manager node, store a secret, e.g. `echo "verysecret" | docker secret create a_secret -`
2. Deploy a docker Stack to the Swarm using the minimal Compose file using Secrets (importantly a 3.1 feature) `docker stack deploy -c compose.yml a_stack`:
```
version: "3.0"
services:
  alpine:
    image: alpine
    command: top
    secrets:
      - a_secret
secrets:
  a_secret:
    external: true
```
The CLI expectedly reports the error:
`services.alpine Additional property secrets is not allowed`
3. Remove the Stack, and change "3.0" to "3" and deploy it again.
4. The Stack runs using a 3.1 feature, in this case, Secrets. I don't know what minor version it _does_ assume, perhaps the latest, who knows?

### Expected behavior

There should be no difference in 'docker stack deploy' whether "3.0" or "3" is specified as the version, as [https://docs.docker.com/compose/compose-file/compose-versioning/#version-3](https://docs.docker.com/compose/compose-file/compose-versioning/#version-3) suggests.
In both cases the CLI should report the error.

### docker version

```bash
Client: Docker Engine - Community
 Version:           23.0.0
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        e92dd87
 Built:             Wed Feb  1 17:46:28 2023
 OS/Arch:           linux/arm64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.0
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       d7573ab
  Built:            Wed Feb  1 17:46:28 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.16
  GitCommit:        31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.15.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 8
 Server Version: 23.0.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: s55867kpzhizhkqgi82a5fvdh
  Is Manager: true
  ClusterID: ujzyje1rv3mtpvfk2jfq7wzaf
  Managers: 1
  Nodes: 3
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 192.168.64.9
  Manager Addresses:
   192.168.64.9:2377
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-57-generic
 Operating System: Ubuntu 22.04.1 LTS
 OSType: linux
 Architecture: aarch64
 CPUs: 2
 Total Memory: 3.82GiB
 Name: node1
 ID: 1aeba1b1-e943-44ab-9323-c4b6f7291036
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
Addressed by https://github.com/docker/docs/pull/17516. See the discussion on https://github.com/docker/cli/pull/4335 for more details 👍

**Comment by gatisnolv** [comment]
While the resolution was different to what I suggested here, it does address the core concern I had originally,

> While I realize the doc might be talking about 'docker compose' rather than 'docker stack deploy', this is surprising and unexpected, and **I would expect the implementations to behave identically in this regard**.

Thanks!
