### ISSUE TITLE
docker build with issue: "ERROR: failed to solve"

### ISSUE THREAD

**Issue by swoiow** [docker/cli#4012]
### Description

when i want to build a new images with dockerfile, the docker build command response with issue `ERROR: failed to solve: process "/bin/sh -c set -xe     apk add --no-cache         --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community`

this issue appear in used `docker build` and `docker buildx build`

- I can use dig to check dl-cdn.alpinelinux.org, and responsed was fine, but in build it doesn't work. 
- I try to add `dns` option in `/etc/docker/daemon.json`, usefuless.
- `/etc/resolv.conf` has set with `1.1.1.1` and `8.8.8.8`

Anyway to debug or comfirm this issue?

### Reproduce

docker build
docker buildx build

`/etc/docker/daemon.json` is 
```
{
  "registry-mirrors": ["https://mirror.gcr.io"],
  "dns": [ "1.1.1.1", "172.17.0.1", "127.0.0.11", "8.8.8.8"],
  "default-shm-size": "64M",
  "ipv6": false,
  "experimental": false,
  "features": {
    "buildkit" : true
  }
}
```

### docker version

```bash
Client: Docker Engine - Community
 Version:           23.0.0
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        e92dd87
 Built:             Wed Feb  1 17:47:51 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.0
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       d7573ab
  Built:            Wed Feb  1 17:47:51 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.16
  GitCommit:        31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.15.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 6
  Running: 5
  Paused: 0
  Stopped: 1
 Images: 56
 Server Version: 23.0.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 31aa4358a36870b21a992d3ad2bef29e1d693bec
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-58-generic
 Operating System: Ubuntu 22.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 969.5MiB
 Name: 
 ID:
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://mirror.gcr.io/
 Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
@swoiow thanks for reporting;

- do you have a minimal Dockerfile to reproduce the issue?
- does the issue reproduce if you disable buildkit? (`DOCKER_BUILDKIT=0 docker build ..`)?

**Comment by swoiow** [comment]
Thanks, @thaJeztah. I just take a break and recheck it on another machine (the older docker version). And get why will cause the issue. 

<img width="1097" alt="image" src="https://user-images.githubusercontent.com/7948020/217589201-c150497c-ffae-4802-a06c-ab85db2255f1.png">

Look at the photo above. I think the red color and the final error tips catch my eye (the newer version on left), so think that maybe is a network issue. 
And when I used the right version, it showed me that my command has some problems. 
The right error print is very clear, maybe the new version I need time to adapt.

**Comment by thaJeztah** [comment]
Ah, thanks for updating! Yes, the BuildKit error output can sometimes be a bit verbose (and maybe a bit hard to find the underlying error).

I think the BuildKit team is still exploring some options, but its sometimes difficult to find the right balance (more details can be equally useful for debugging as well as "too verbose" for other cases); suggestions / feedback welcome; if you do: feel free to open a ticket (or start a discussion) in https://github.com/moby/buildkit 👍
