### ISSUE TITLE
Autocomplete for docker compose "-f" option

### ISSUE THREAD

**Issue by ricky0123** [docker/cli#4034]
### Description

I am having an issue with autocomplete for docker compose with respect to the -f option. I believe I am using the most recent docker engine ce on ubuntu (docker version shows 23.0.1). When I type docker compose -f and hit tab to complete, the behavior is as follows. I hit tab once and it completes a "y". I hit it again and it shows the words "yaml" and "yml" as possible completions. However, if I continue to type, eg "yaml" (not that I would actually want to), and hit tab, it deletes what I have typed and just keeps the "y" again.

### Reproduce

Type `docker compose -f ` and hit tab.

### docker version

```bash
Client: Docker Engine - Community
 Version:           23.0.1
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        a5ee5b1
 Built:             Thu Feb  9 19:47:01 2023
 OS/Arch:           linux/amd64
 Context:           desktop-linux
```

### docker info

```bash
Client:
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.16.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan
```

**Comment by sam-thibault** [comment]
- https://github.com/docker/compose/issues/9941

**Comment by ricky0123** [comment]
I see, thanks!
