### ISSUE TITLE
Docker run creates hidden folders in the volume mounted as root

### ISSUE THREAD

**Issue by Divya1388** [docker/cli#4052]
### Description

We are running terragrunt inside docker container and when terragrunt runs it creates a folder .terragrunt-cache on the volume mounted to the container (path in vm). 

We are passing a user to run the container as with -u $(id -u):$(id -g) 
This helps in creating all the files as this user except for the .terragrunt-cache directory. 

And this is causing issues in the Azure devops pipelines to cleanup the work space

### Reproduce

Run terragrunt inside a docker container in RHEL vm

### Expected behavior

the .terragrunt-cache is created as non root user

### docker version

```bash
lient: Docker Engine - Community
 Version:           23.0.1
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        a5ee5b1
 Built:             Thu Feb  9 19:49:07 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.1
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       bc3805a
  Built:            Thu Feb  9 19:46:47 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.18
  GitCommit:        2456e983eb9e37e47538f59ea18f2043c9a73640
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
lient:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.16.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 23.0.1
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 2456e983eb9e37e47538f59ea18f2043c9a73640
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 4.18.0-425.10.1.el8_7.x86_64
 Operating System: Red Hat Enterprise Linux 8.7 (Ootpa)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.581GiB
 Name: l7lo2arcaue0001
 ID: cff9027d-ad44-46e2-a113-039b0affe0dd
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by sam-thibault** [comment]
Can you share the complete docker command you are running (that includes `-u`)?
Also more information about which image you are running could help us investigate also.

**Comment by Divya1388** [comment]
@sam-thibault 
We are using a custom Docker image with our internal container registry 
The command is: 

docker run --rm --name plantf -v "$(Build.SourcesDirectory):/home/usr/tmp/terragrunt-repository" -v "$(Build.ArtifactStagingDirectory):/output" -u ${id -u}:${id -g} --env HTTPS_PROXY=$(proxyURL) --env NO_PROXY=$(noProxy) --env-file "$(Agent.TempDirectory)/azure-tf-$(azureSubscription).env" $(containerRegistry)/$(terragruntContainer) -command plan -modulePath $(modulePath) -authType bearer -token $(system_accesstoken) -projectURI $(SetProjectURI.ProjectURI)

**Comment by sam-thibault** [comment]
Can you provide a minimal image to reproduce this so we can attempt to debug?

**Comment by akerouanton** [comment]
@Divya1388 Docker creates the host directory with root if it doesn't exist yet. Then, the container starts with an explicit uid/gid. If that path was just created by the daemon, your user can't write to the mounted directory.

As such, a few questions:

* Is the same host directory reused across your CI jobs (ie. `Build.SourcesDirectory` or `Build.ArtifactStagingDirectory` are always the same)?
* If yes, are you sure you removed it properly and added the right mkdir command to your CI config before running any new job?

**Comment by thaJeztah** [comment]
Let me close this ticket for now, as it looks like it went stale.
