### ISSUE TITLE
CLI `docker pull` requires authentication when already logged in via the macOS app 

### ISSUE THREAD

**Issue by conradwt** [docker/cli#408]
**Description**

**Steps to reproduce the issue:**
1. docker pull scylladb/scylla
2.
3.

**Describe the results you received:**

Please login prior to pull:
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.

**Describe the results you expected:**

I would expect that I wouldn't get this message being that I have already logged in using Docker CE for macOS.  Thus, I should be able to pull without having to authenticate.

**Additional information you deem important (e.g. issue happens only occasionally):**

This issue started with I installed the latest release of Docker CE for macOS.

**Output of `docker version`:**

```
Client:
 Version:      17.07.0-ce-rc1
 API version:  1.31
 Go version:   go1.8.3
 Git commit:   8c4be39
 Built:        Wed Jul 26 05:20:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.07.0-ce-rc1
 API version:  1.31 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   8c4be39
 Built:        Wed Jul 26 05:25:01 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 33
 Running: 0
 Paused: 0
 Stopped: 33
Images: 182
Server Version: 17.07.0-ce-rc1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 3addd840653146c90a254301d6c3a663c7fd6429
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.38-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: moby
ID: 6PJS:4POB:FND5:FMTI:KMVQ:DIC3:5AYC:JIBW:N5Y3:YP4V:PINE:PLKF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 18
 Goroutines: 28
 System Time: 2017-08-01T19:22:09.390826879Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by shouze** [comment]
@conradwt still experiencing this issue with the today update? On my side, I've never experienced this one at any time.

**Comment by conradwt** [comment]
@shouze I tested it last week and it things have been resolved for me after installing an update last week.  Thus, I’m going to close this issue.
