### ISSUE TITLE
Bash completion does not work for compose.

### ISSUE THREAD

**Issue by peredwardsson** [docker/cli#4102]
### Description

Any bash competion of the form `docker compose <anything> <tab>` fails on my system. It produces nothing but beeps.

### Reproduce

I have a little script which I run on new machines.

```
#!/bin/bash

function install_docker() {
    # check if docker is already installed
    if [ -x "$(command -v docker)" ]; then
        echo "Docker is already installed"
        return
    fi
    sudo apt-get remove docker-ce docker-ce-cli containerd.io docker-compose-plugin
    sudo apt-get update
    sudo apt-get install -y \
        apt-transport-https \
        ca-certificates \
        curl \
        gnupg-agent \
        software-properties-common
    sudo mkdir -p /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
        $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin
    sudo usermod -aG docker $USER

    sudo docker run hello-world

    echo "Docker installed successfully, relog to apply changes"
}

function install_nvidia_docker() {
    distribution=$(. /etc/os-release;echo $ID$VERSION_ID) \
      && curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg \
      && curl -s -L https://nvidia.github.io/libnvidia-container/$distribution/libnvidia-container.list | \
            sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
            sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list

    sudo apt-get update && sudo apt-get install -y nvidia-docker2
    sudo systemctl restart docker
    sudo docker run --rm --gpus all dustynv/ros:humble-ros-base-l4t-r35.1.0 nvidia-smi
    echo "Nvidia docker installed successfully"
}

install_docker
install_nvidia_docker
```
This is how I install docker. At this point, bash completion does not work.

### Expected behavior

Completion should work intelligently. Or, it should at least fall back to completing files.

### docker version

```bash
$ docker version
Client: Docker Engine - Community
 Version:           23.0.1
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        a5ee5b1
 Built:             Thu Feb  9 19:46:32 2023
 OS/Arch:           linux/arm64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.1
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.5
  Git commit:       bc3805a
  Built:            Thu Feb  9 19:46:32 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.15
  GitCommit:        5b842e528e99d4d4c1686467debf2bd4b88ecd86
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.16.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 11
  Running: 0
  Paused: 0
  Stopped: 11
 Images: 4
 Server Version: 23.0.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: nvidia runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b842e528e99d4d4c1686467debf2bd4b88ecd86
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 5.10.104-tegra
 Operating System: Ubuntu 20.04.4 LTS
 OSType: linux
 Architecture: aarch64
 CPUs: 8
 Total Memory: 29.82GiB
 Name: hugo-rally
 ID: IUSF:OO2I:ECTU:R3V3:34W3:IPXO:PDUU:N5T7:UP4R:UY4H:GKBQ:TMP7
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: hugorobot
 Registry: https://index.docker.io/v1/
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

$ docker compose version
Docker Compose version v2.16.0
$ apt show docker-ce
Package: docker-ce
Version: 5:23.0.1-1~ubuntu.20.04~focal
Priority: optional
Section: admin
Maintainer: Docker <support@docker.com>
Installed-Size: 70.1 MB
Depends: containerd.io (>= 1.6.4), docker-ce-cli, iptables, libseccomp2 (>= 2.3.0), libc6 (>= 2.17), libdevmapper1.02.1 (>= 2:1.02.97), libsystemd0
Recommends: apparmor, ca-certificates, docker-ce-rootless-extras, git, libltdl7, pigz, procps, xz-utils
Suggests: cgroupfs-mount | cgroup-lite
Conflicts: docker (<< 1.5~), docker-engine, docker-engine-cs, docker.io, lxc-docker, lxc-docker-virtual-package
Replaces: docker-engine
Homepage: https://www.docker.com
Download-Size: 13.5 MB
APT-Manual-Installed: yes
APT-Sources: https://download.docker.com/linux/ubuntu focal/stable arm64 Packages
Description: Docker: the open-source application container engine
 Docker is a product for you to build, ship and run any application as a
 lightweight container
 .
 Docker containers are both hardware-agnostic and platform-agnostic. This means
 they can run anywhere, from your laptop to the largest cloud compute instance and
 everything in between - and they don't require you to use a particular
 language, framework or packaging system. That makes them great building blocks
 for deploying and scaling web apps, databases, and backend services without
 depending on a particular stack or provider.

N: There are 32 additional records. Please use the '-a' switch to see them.

$ apt show docker-ce-cli
Package: docker-ce-cli
Version: 5:23.0.1-1~ubuntu.20.04~focal
Priority: optional
Section: admin
Source: docker-ce
Maintainer: Docker <support@docker.com>
Installed-Size: 34.8 MB
Depends: libc6 (>= 2.17)
Recommends: docker-buildx-plugin, docker-compose-plugin
Conflicts: docker (<< 1.5~), docker-engine, docker-engine-cs, docker.io, lxc-docker, lxc-docker-virtual-package
Breaks: docker-ce (<< 5:0)
Replaces: docker-ce (<< 5:0)
Homepage: https://www.docker.com
Download-Size: 12.0 MB
APT-Manual-Installed: yes
APT-Sources: https://download.docker.com/linux/ubuntu focal/stable arm64 Packages
Description: Docker CLI: the open-source application container engine
 Docker is a product for you to build, ship and run any application as a
 lightweight container
 .
 Docker containers are both hardware-agnostic and platform-agnostic. This means
 they can run anywhere, from your laptop to the largest cloud compute instance and
 everything in between - and they don't require you to use a particular
 language, framework or packaging system. That makes them great building blocks
 for deploying and scaling web apps, databases, and backend services without
 depending on a particular stack or provider.

N: There are 32 additional records. Please use the '-a' switch to see them.

**Comment by peredwardsson** [comment]
Indeed, I can't seem to reproduce the problem except for the one you mention. Thanks for looking into it. I don't seem to have `docker completion`, can I get the bash completion script elsewhere?

**Comment by laurazard** [comment]
Sure! I believe the gist linked in this comment has the relevant script – https://github.com/docker/compose/issues/9941#issuecomment-1411701772 (although if you're on 23.01 you should have that command).

Just to add some additional information, the script there is the one generated by cobra for autocompletion, and is not as "battle-tested" as the default scripts packaged in the normal docker installation, so YMMV. I'll also be looking into addressing the `docker compose -f<TAB>` issue.
