### ISSUE TITLE
Checkout the appropriate commit for specific docker version

### ISSUE THREAD

**Issue by anhilde** [docker/cli#412]
Hi,

this is perhaps not really an issue, however I would like to checkout the docker/cli projects source tree for a specific docker version. Since you do not use git tags, how can I easily find the commit associated with docker version: "Docker version 1.12.6, build 88a4867/1.12.6"?

Best Regards,

André

**Comment by dnephin** [comment]
cc @andrewhsu @tiborvass 

The commit associated with a release is not available from this repo. Releases are managed from https://github.com/docker/docker-ce, which has git tags and branches for releases.

The cli source is available from `components/cli` in that repo.

**Comment by thaJeztah** [comment]
The 1.12.6 commit you're referring to is not an official build; it's a commit in the Red Hat fork of Docker https://github.com/projectatomic/docker/commit/88a4867

The commit of the official 1.12.6 docker (which was before the introduction of the "Moby project", thus in another repository) is https://github.com/moby/moby/releases/tag/v1.12.6 (https://github.com/moby/moby/commit/78d18021ecba00c00730dec9d56de6896f9e708d)
