### ISSUE TITLE
Add support for "isolaton" in Compose files

### ISSUE THREAD

**Issue by Techwolfy** [docker/cli#414]
The Compose v3 format includes a parameter to specify the type of [container isolation](https://docs.docker.com/engine/reference/commandline/run/#specify-isolation-technology-for-container-isolation) that the host should use.  This is always `default` on Linux, but can be either `process` or `hyperv` on Windows. This setting was added in v2.1 and has remained in the documentation since.

However, it was left out of the v3+ schema definition, so it currently can't be used in newer Compose files despite working correctly if the file version is downgraded. I've submitted a patch in docker/compose#5075 to fix this for local deployments. Swarm has never had support for this feature though so it will likely be a bit more complicated to fix.

Currently, running `docker stack deploy -c docker-compose.yml swarm` results in the error message `isolation Additional property isolation is not allowed`. I'm working on a Windows-based Swarm application and not all of the servers share an OS version so this feature would be quite helpful to me.

**Comment by thaJeztah** [comment]
For reference; this depends on https://github.com/moby/moby/issues/31616 to be decided on (and implemented) first
