### ISSUE TITLE
non-lazy local cache importer from moby/buildkit

### ISSUE THREAD

**Issue by kevingentile** [docker/cli#4148]
### Description

We are encountering a bug that was fixed in https://github.com/moby/buildkit/pull/3493 and landed in [`moby/buildkit v0.11.2+`](https://github.com/moby/buildkit/pull/3540).

The necessary bump is already on `master` in https://github.com/docker/cli/commit/e60c748c1471badb74102d32ab31ed4c8c316bbe. Is there a timeline to cut a `v23.0.3` release?

/cc @thaJeztah

**Comment by thaJeztah** [comment]
v23.0.x uses BuildKit v0.10, and won't be updated to v0.11 (as there's many changes in between those versions), but we're currently building first test builds of Docker 24.0.0 (24.0.0-beta.1), which does contain BuildKit 0.11.

Also note that this is the CLI repository, and the BuildKit vendor update you linked to won't affect anything (the actual build is handled by the Docker Engine daemon, which is built from https://github.com/moby/moby)

**Comment by thaJeztah** [comment]
Let me close this one, per the comment above, and https://github.com/docker/cli/pull/4149#issuecomment-1492570681
