### ISSUE TITLE
[Proposal] Integration test suite

### ISSUE THREAD

**Issue by dnephin** [docker/cli#417]
We should add an integration test suite to support testing against different versions of the daemon (platforms, EE/CE, API versions).

## Proposal

A new test suite should be written for the `docker/cli` repo.  The suite should accept two variables:
* `DOCKER_BINARY_PATH` - the path to the compiled docker binary (default to `build/docker`)
* `DOCKER_HOST` - the url to the docker daemon API

CI should test PRs against an appropriate matrix of daemons.

Each test case should be written in an end-to-end test style:
* set requirements for minimum supported API version, platform, experimental, etc
* setup appropriate test state required for the test
* run the binary using `docker/docker/pkg/testutil/cmd`
* assert expected ExitCode, Stdout/Stderr, and local filesystem state (The state of the daemon should **not** be tested! That behaviour is outside of the CLI, so is already covered by daemon test cases).

## Guidelines for integration testing

All code changes should have unit test coverage. Integration tests do not replace unit tests.

Each feature (subcommand) should generally only have one integration testing for the success case ("happy path"). The test should include all (or most) flags/options supported by that feature.

In some rare cases a couple additional integration tests may be written for a sufficiently complex and critical feature (ex: `container run`, `service create`, `docker build` may have ~3 cases each).

In some rare cases a sufficiently critical error path may have a single integration test case.

In all other cases the behaviour should be covered by unit tests.

If a code change adds a new flag, that flag should be added to the existing "success case" integration test.

If a code change fixes a bug, that bug fix should be covered either by adding assertions to the existing integration test, or with unit tests. 

## Integration suite details

* use `go test` with `testify.assert/suite` and  `docker/docker/pkg/testutil`
* add a `Jenkinsfile` to the repo to run the test matrix on each PR: moby/moby master (sometimes failures can be ignored), latest CE release, latest EE release, current RC release)
* tests should go into `./test-e2e/` (or `./features`, or something like that) and mirror the directory structure of commands:
    ```
    .
    |- test-e2e
    |     |- image
    |     |    |- pull_test.go
    |     |    |- build_test.go
    |     |    \- ...
    |     |- container
    |     |    | ...
    ```

### Related
* #37 - tracking issue for missing unit tests
* #201 - tracking issue for missing integration tests

**Comment by dnephin** [comment]
An alternative that is being considered is to port over the existing `docker/docker/integration-cli` suite. I believe that is a mistake for many reasons, but primarily:
* that would leave us with almost no testing on `moby/moby` which is where those tests are most valuable.
* the cost of moving the suite to `docker/cli` would actually out-weight any value it provides (more explanation below).

`integration/cli` is ~2000 test which cover both cli and api behaviour. Even tests which exercise the engine through the CLI are actually testing features of the engine. Now that CLI and API are in separate repos we must split these test cases into two: cases which exercise and test only the CLI behaviour, and cases which exercise and test only the API behaviour. We will continue to encounter problems until we have finished this split. I believe any effort must focus on this direction.

By porting over the test suite we make no progress toward the actual goal, but the work involved to port the suite is roughly comparable to the work involved to create a new suite.  In the long term the cost to maintain the old suite far outweighs the cost of writing a new test suite with proper guidelines.

**Comment by tiborvass** [comment]
The biggest change is: `assert expected ExitCode, Stdout/Stderr, and local filesystem state (The state of the daemon should not be tested! That behaviour is outside of the CLI, so is already covered by daemon test cases).`

I'm in favor of the proposal. Bikeshedding: I don't like `test-e2e` but I'm not sure what else to suggest, we've used up many names already.

**Comment by vieux** [comment]
I'm also in favor of this proposal 👍

**Comment by dnephin** [comment]
I'm fine with another name for the directory. I'd like to avoid `integration` because I think that term is heavily overloaded and not really specific enough. Something like: `acceptance/` , `features/`, `e2e/`, `end-to-end/`, `e2e-tests/`, would be my preference.

**Comment by tiborvass** [comment]
@dnephin would you mind describing in English a perfect test case to make a point on how it differs from current integration-cli tests ?

**Comment by dnephin** [comment]
Sure, I can do that, but I think it's probably easier to see with examples. 

A test case should (like all code) be self-documenting. The purpose of the test should be immediately obviously. I think this can be accomplished by following these guidelines:
* a clear test name in the form `Test<Feature>[<Case>]`. Since we'll be splitting tests for each component into different packages we don't need to include things like `CLI` , `Command`, or the component (container, image, service, etc) in the test name.
* keeping the test short. A test that is longer than ~10 statements is not going to be immediately obvious. Any boilerplate setup/assertion logic should be moved out into helper functions to keep the test readable
* making the 3 sections of the test obvious. All tests generally have 3 sections (setup/run/assert, or in gherkin given/when/then). Each of these sections should be immediately obvious when looking at the test.

Another major difference between this proposal and the current integration-cli is the guideline for when to write an "integration" test. In docker/docker we wrote way too many integration tests for things that should not be integration tests. I think there are many reasons for this that I wont get into here, but simply writing more unit tests and fewer integration tests is another important difference.

Finally, some rough examples of what the tests might look like with this proposal:

**acceptance/stack/remove_test.go**
```go
func TestRemove(t *testing.T) {
    stackname := "test-stack-remove"
    deployFullStack(t, stackname)
    
    result := icmd.RunCommand("docker", "stack", "rm", stackname)

    result.Assert(t, icmd.Expected{Out: icmd.None})
    golden.Assert(t, result.Stderr(), "stack-remove-success")
}
```

**acceptance/image/build_test.go**
```go
func TestBuildFromFilesystemContext(t *testing.T) {
    dockerfile := `
        FROM testregistry:5555/alpine
        COPY . /data
        RUN  cat /data/foo
    `
    contextdir := fs.NewTempDir(t, WithFiles(map[string]string{
        "Dockerfile": dockerfile,
        "foo": "this is a file", 
    })
    defer contextdir.Remove()

    result := icmd.RunCommand("docker", "build", "-t", "mytag", contextdir.Path())

    result.Assert(t, icmd.Expected{Err: icmd.None})
    assertBuildOutputContains(t, result.Stdout(), golden.File(t, "build-from-fs-context"))
}
```
