### ISSUE TITLE
docker-init ("docker init" command) sources?

### ISSUE THREAD

**Issue by christian-korneck** [docker/cli#4184]
### Description

Question: Are the sources for the new `docker-init` CLI plugin (new `docker init` command included with the latest Docker Desktop release) available somewhere or is this a closed source binary? I coud neither find it in the `docker-cli` repo nor did I see a repo under the github/docker.

### Reproduce

Search for the source code of `docker-init` executable on github. No match. :-)

### Expected behavior

being able to find the source code. :-)

### docker version

```bash
DD 4.18.0 (104112)
```

### docker info

```bash
DD 4.18.0 (104112)
```

**Comment by thaJeztah** [comment]
It's a plugin, and currently closed source @christophermclellan may know if there's plans to open-source it

**Comment by nunocoracao** [comment]
Hello, @christian-korneck the plugin is closed-source and we have no plans at the moment to open-source it. Out of curiosity, what information were you looking for in the source code or what was your goal?

**Comment by christian-korneck** [comment]
@nunocoracao Thanks for taking the time to clarify. I mainly wanted to see if I can add my own templates.

**Comment by nunocoracao** [comment]
@christian-korneck we are considering how to open up that part more. Any ideas on what you would like to see/do?

**Comment by minwook-shin** [comment]
@sam-thibault , @nunocoracao 
interested in that project source too.
how about get the URL of Github repository similar to cookie cutter template (ex: psql to Maria DB, or built-in lib case)?
and how about supporting a good template to upload Extensions Marketplace?
thank you always.

**Comment by thaJeztah** [comment]
@minwook-shin the repository (https://github.com/docker/docker-init) is still private.

I think the best approach is to open a ticket in our public roadmap, and describing your use-case / request; https://github.com/docker/roadmap

**Comment by worldofgeese** [comment]
Does Docker intend to release new products to OSS? It looks like all new product releases (Scout and Init) are closed.

**Comment by tylertitsworth** [comment]
@minwook-shin I have a use case to create templates related to AI Frameworks (TensorFlow, PyTorch, Classical ML, etc.). Docker init is a great idea that could be significantly expanded upon by Open Source Contributions.

**Comment by thaJeztah** [comment]
@tylertitsworth best place might be to open a suggestion in our public roadmap; those are reviewed periodically, and suggestions may help prioritising work; https://github.com/docker/roadmap
