### ISSUE TITLE
multi platform share same tag

### ISSUE THREAD

**Issue by cole-dda** [docker/cli#4189]
### Description

different platform images can share same tag and not auto set to <none> when change platform

```bash
#whether show platform column?
$docker image ls
```
<img width="628" alt="screenshot_5826" src="https://user-images.githubusercontent.com/1077830/230834950-4c7d5a5b-9091-4220-9561-54009667bab0.png">

### Reproduce

```bash
$docker run -it --rm --platform linux/amd64 ubuntu:22.04 uname -m
$docker image ls
```
<img width="620" alt="screenshot_5823" src="https://user-images.githubusercontent.com/1077830/230833877-d69e8cb6-d6c4-4f63-9e3b-0e99a5fd98a4.png">

```bash
$docker run -it --rm --platform linux/arm64 ubuntu:22.04 uname -m
$docker image ls
```
<img width="547" alt="screenshot_5824" src="https://user-images.githubusercontent.com/1077830/230834003-85b9e569-472a-489a-8ce2-627470624667.png">

```bash
#again run linux/amd64,again pull??
$docker run -it --rm --platform linux/amd64 ubuntu:22.04 uname -m
```
<img width="668" alt="screenshot_5825" src="https://user-images.githubusercontent.com/1077830/230834279-8a6cfeb1-8349-4409-b30c-9c5b2532125f.png">

```bash
$docker image ls
```
<img width="625" alt="screenshot_5827" src="https://user-images.githubusercontent.com/1077830/230835107-b65b89bb-b666-490a-863f-1dd7b2a52679.png">

### Expected behavior

local registry keep multi platform image and not change tag，each time，change  to other platform，always issue "unable find image xxx locally，waiting load metadata。

and when docker build or docker buildx build，change to other platform，load metadata waiting too long

### docker version

```bash
Client:
 Cloud integration: v1.0.31
 Version:           20.10.24
 API version:       1.41
 Go version:        go1.19.7
 Git commit:        297e128
 Built:             Tue Apr  4 18:21:21 2023
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.18.0 (104112)
 Engine:
  Version:          20.10.24
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.19.7
  Git commit:       5d6db84
  Built:            Tue Apr  4 18:18:42 2023
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.6.18
  GitCommit:        2456e983eb9e37e47538f59ea18f2043c9a73640
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.10.4)
  compose: Docker Compose (Docker Inc., v2.17.2)
  dev: Docker Dev Environments (Docker Inc., v0.1.0)
  extension: Manages Docker extensions (Docker Inc., v0.2.19)
  init: Creates Docker-related starter files for your project (Docker Inc., v0.1.0-beta.2)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.25.0)
  scout: Command line tool for Docker Scout (Docker Inc., v0.9.0)
```

**Comment by sam-thibault** [comment]
It looks like you are using Docker Desktop.  Have you enabled the beta feature "Use containerd for pulling and storing images"?  This introduces multi-platform image support.

There is additional active work in this area.  See here:
- https://github.com/moby/moby/issues/44582

**Comment by sam-thibault** [comment]
I will close this issue.

**Comment by cole-dda** [comment]
when trun on the features, work ok,but when exec:
```bash
$docker run -it --rm --platform linux/amd64 ubuntu:22.04 uname -m
$docker run -it --rm --platform linux/arm64 ubuntu:22.04 uname -m
$docker image ls
```
image id equals? 

<img width="483" alt="screenshot_5846" src="https://user-images.githubusercontent.com/1077830/232182887-3b1277e1-7d6c-4824-90c1-3f8e349105a0.png">
