### ISSUE TITLE
Add/modify a mechanism to detect pulling interruption

### ISSUE THREAD

**Issue by ANoneTypeOn** [docker/cli#4237]
### Description

Today I faced a problem with pulling python:3.11 from Docker hub. I Googled a problem and found next issues:

- https://github.com/docker/for-mac/issues/2083
- https://github.com/moby/moby/issues/22598

At the end it all came down to to "restart dockerd or server". In general pull problems are caused by network issues (see links), and this problem cannot be solved by the user.

That's why Docker's "pull" should receive a mechanism to prevent or fix it.

**Comment by sam-thibault** [comment]
Can you share what version you are running and platform information?  Are you running Docker Desktop?
