### ISSUE TITLE
Docker build skips certain stage

### ISSUE THREAD

**Issue by apetrut** [docker/cli#4340]
### Description

I have the following Dockerfile.

```dockerfile
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0  AS build
#restore, build and publish a .csproj file
#generate several .sql scripts using dotnet-ef

FROM mcr.microsoft.com/mssql-tools AS sql
RUN mkdir -p /var/opt/mssql/backup

RUN /opt/mssql-tools/bin/sqlcmd -S $SERVER -d $DATABASE -U $USER -P $PASSWORD -i /var/opt/mssql/backup/my_script.sql

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENV ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
EXPOSE 32239
ENTRYPOINT ["dotnet", "MyApp.dll"]
```

Until a few weeks all the steps were executed correctly in this order from Azure DevOps CI pipeline.

Now the **sql** stage is being skipped and the sql script that I generated in the previous step is not being executed anymore. No errors are thrown, docker build just goes to step which is quite at the bottom of the file:

```
FROM base AS final
WORKDIR /app
```

I even added the  --no-cache=true option to force the cli not using the cache.

### Reproduce

Execute docker build command from Azure DevOps CI.

### Expected behavior

It should run all the steps.

### docker version

```bash
2.221.0
```

### docker info

```bash
N/A
```

**Comment by apetrut** [comment]
@thaJeztah Thanks for your answer. Can you confirm when the BuildKit has been changed?

**Comment by thaJeztah** [comment]
BuildKit has always done this, but Docker 23.0 and up use BuildKit by default (older versions required `DOCKER_BUILDKIT=1` to be set to enable it).

Note that the classic builder is still used to build Windows images (as BuildKit does not yet support Windows images).
