### ISSUE TITLE
Filter "until=3d" not working

### ISSUE THREAD

**Issue by dhs-rec** [docker/cli#4390]
### Description

Documentation says:
> The until filter can be Unix timestamps, date formatted timestamps, or Go duration strings...

OTOH, the Go documentation states:
> A duration string is a possibly signed sequence of decimal numbers, each with optional fraction and a unit suffix, such as "300ms", "-1.5h" or "2h45m". Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h", "d", "w", "y".

But specifying `--filter until=3d` results in the following error:
> ERROR: "until" filter expects a duration (e.g., '24h'): time: unknown unit "d" in duration "3d"

Specifying "72h" works fine thow.

### Reproduce

`docker image prune --filter until=3d`

### Expected behavior

"until" filter should behave as documented, so that dangling images older than 3 days are removed when specifying "3d".

### docker version

```bash
# docker version
Client: Docker Engine - Community
 Version:           23.0.6
 API version:       1.42
 Go version:        go1.19.9
 Git commit:        ef23cbc
 Built:             Fri May  5 21:18:28 2023
 OS/Arch:           linux/amd64
 Context:           default
```

### docker info

```bash
Not relevant for this issue.
```

**Comment by vvoland** [comment]
Days are not supported by Go duration strings:

> ParseDuration parses a duration string. A duration string is a possibly signed sequence of decimal numbers, each with optional fraction and a unit suffix, such as "300ms", "-1.5h" or "2h45m". Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h". 

Source: https://pkg.go.dev/time#ParseDuration

**Comment by dhs-rec** [comment]
Oh, damn. The first hit you get from Google for "Go duration strings" is this: https://pkg.go.dev/maze.io/x/duration. Sorry for the fuzz.

Anyway, maybe Docker could use this library, so that days will be supported in the future...

**Comment by thewrath** [comment]
maybe the documentation can be updated to give the link to the Go documentation to avoid misunderstanding? 

I had the same problem ...
