### ISSUE TITLE
Docker pull returns EOF

### ISSUE THREAD

**Issue by samdavies1906** [docker/cli#4398]
### Description

When running the command:
docker pull busybox
I get back error:
error pulling image configuration: download failed after attempts=6: EOF

I've tried reinstalling docker and colima, and I keep getting the same error.

I have also tried on and off a VPN and with public repos from docker hub and ecr public.
I have also tried increasing cpu and memory resources.

### Reproduce

docker pull busybox

### Expected behavior

docker pull busybox should pull down the image from docker hub

### docker version

```bash
Client: Docker Engine - Community
 Version:           24.0.2
 API version:       1.42 (downgraded from 1.43)
 Go version:        go1.20.4
 Git commit:        cb74dfcd85
 Built:             Thu May 25 20:26:27 2023
 OS/Arch:           darwin/arm64
 Context:           colima

Server:
 Engine:
  Version:          23.0.6
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       9dbdbd4b6d7681bd18c897a6ba0376073c2a72ff
  Built:            Fri May 12 13:54:36 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.0
  GitCommit:        1fbd70374134b891f97ce19c70b6e50c7b9f4e0d
 runc:
  Version:          1.1.7
  GitCommit:        860f061b76bb4fc671f0f9e900f7d80ff93d4eb7
 docker-init:
  Version:          0.19.0
  GitCommit:
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    24.0.2
 Context:    colima
 Debug Mode: false

Server:
 Containers: 3
  Running: 0
  Paused: 0
  Stopped: 3
 Images: 1
 Server Version: 23.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1fbd70374134b891f97ce19c70b6e50c7b9f4e0d
 runc version: 860f061b76bb4fc671f0f9e900f7d80ff93d4eb7
 init version:
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 6.1.29-0-virt
 Operating System: Alpine Linux v3.18
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 3.836GiB
 Name: colima
 ID: 34aa8077-2407-4577-9eeb-085eb220feb4
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by bsousaa** [comment]
EOF usually means that the daemon crashed (or the VM it is running in) and possibly corrupted the data. If you have daemon logs we can have a deeper look.

**Comment by samdavies1906** [comment]
@bsousaa
time="2023-07-13T15:07:21+01:00" level=info msg="- - - - - - - - - - - - - - -"
time="2023-07-13T15:07:21+01:00" level=info msg="daemon started by colima"
time="2023-07-13T15:07:21+01:00" level=info msg="Run `/usr/bin/pkill -F /Users/samdavies/.colima/default/daemon/daemon.pid` to kill the daemon"
time="2023-07-13T15:07:21+01:00" level=info msg="Using search domains: [xxobfscuatedxx.co.uk]"
time="2023-07-13T15:07:21+01:00" level=info msg="waiting for clients..."
time="2023-07-13T15:07:23+01:00" level=info msg="new connection from  to /Users/samdavies/.colima/default/daemon/gvproxy.sock"

**Comment by akerouanton** [comment]
It looks like a networking issue with Colima. Have you tried to report this issue on their repo?

Also, could you provide the logs for the Docker daemon running inside the VM please ?

**Comment by rakeshkhopade12** [comment]
Docker images have a manifest that describes their layers. It's possible that the manifest of the busybox image is corrupted or unavailable. Try pulling a different image to see if the issue is specific to the busybox image.

**Comment by sam-thibault** [comment]
I will close this one as stale.
