### ISSUE TITLE
Add unsupported key `build`

### ISSUE THREAD

**Issue by cdrage** [docker/cli#450]
Hey all,

We use the `docker/cli` in order to parse Docker Compose YAML files in a Kubernetes project: https://github.com/kubernetes/kompose

Unfortunately I see that `build` is an unsupported key, however (I don't remember which issue), I believe this will be implemented in the future in docker/cli. https://github.com/docker/cli/blob/master/cli/compose/types/types.go#L9

Is it possible to add `build` to ServiceConfig (https://github.com/docker/cli/blob/master/cli/compose/types/types.go#L78) so we can at-least use the struct to retrieve build key information?

Similar to how this is implemented in libcompose here: https://github.com/docker/libcompose/blob/master/config/types.go#L88

**Comment by cdrage** [comment]
ping @vdemeester and @cpuguy83 (Brian added support for `configs` a while back)

**Comment by dnephin** [comment]
If you want to open a PR to add the structs/field we should be able to accept it, but it's unlikely to stay up-to-date with the schema unless you continue to submit PRs to add new fields as we add them to the schema.

**Comment by cdrage** [comment]
@dnephin The schema is automatically generated, no? Would it be as easy as adding it and generating it?

Looking for some help here since I'm not exactly experienced in the `hack` folder with the schema generation.

**Comment by dnephin** [comment]
The jsonschema files in `cli/compose/schema/data` are not generated. They are the official definition of each version of the format. Those files are generated into `cli/compose/schema/bindata.go` so they can be included in the binary as a static asset.

If you are just interested in the types and loader then all you need to do is add the field and structs to `cli/compose/types/types.go`.

**Comment by thaJeztah** [comment]
Looks like https://github.com/docker/cli/pull/481 was merged; can this issue be closed or is there anything left to be done @cdrage ?

**Comment by dnephin** [comment]
We should be good to close
