### ISSUE TITLE
docker build fails when using $@ and --label with whitespace

### ISSUE THREAD

**Issue by lchrennew** [docker/cli#4502]
### Description

`docker build $@` fails when there are --label arguments with values include whitespaces.

### Reproduce

1. `set -- --label "a=b c" .`
2. `docker build "$@"`
3. fails

### Expected behavior

The same behavior as `docker build --label "a=b c" .`

### docker version

```bash
Client:
  Version:        24.0.2
  API version:    1.41(downgraded from 1.43)
  Go version:     go1.20.4
  Git commit:     cb74dfc
  Built:          Thu May 25 21:50:49 2023
  OS/Arch:        linux/amd64
  Context:        default
```

### docker info

```bash
Client:
  Version:        24.0.2
  API version:    1.41(downgraded from 1.43)
  Go version:     go1.20.4
  Git commit:     cb74dfc
  Built:          Thu May 25 21:50:49 2023
  OS/Arch:        linux/amd64
  Context:        default
```

**Comment by struharv** [comment]
I believe that `docker build "$@"` expands the variable as `docker build --label a=b c .`

**Comment by vvoland** [comment]
That's just a matter of shell expanding `$@` differently than `"$@"`:

assuming `--label "a=b c" .`:

1. `docker build $@`
Args: 6
0 => `docker`
1 => `build`
2 => `--label`
3 => `a=b`
4 => `c`
5 => `.`

2. `docker build "$@"`
Args: 5
0 => `docker`
1 => `build`
2 => `--label`
3 => `a=b c`
4 => `.`



Let me close this issue, as it's not related to Docker.
