### ISSUE TITLE
Sometimes docker does not pull the latest version if we use mirrors

### ISSUE THREAD

**Issue by Nefcanto** [docker/cli#4569]
### Description

I'm using `/etc/docker/daemon.json` to configure some mirrors. After setting it restarting docker and using `docker system info` I can verify that they are in place:

```
 Registry Mirrors:
  https://first-mirror.tld/
  https://second-mirror.tld/
  https://third-mirror.tld/
```

Now when I build an image and push it to docker hub, which I can verify by seeing the latest public version of that image inside the docker hub site, and then use `docker pull image-name:latest` it does not work and it tells me that the latest version already exists.

### Reproduce

1. Create an image and push it to docker hub
2. Configure a mirror for docker
3. Push a new version of your image
4. use `docker pull image:latest`
5. Sometimes you should see that docker does not pull the latest image

### docker version

```bash
Client: Docker Engine - Community
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:31:44 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:31:44 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    24.0.6
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 10
  Running: 10
  Paused: 0
  Stopped: 0
 Images: 8
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.2.0-32-generic
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.49GiB
 Name: local
 ID: 6def1339-1e91-4e8d-87eb-c4ac3e5f2c59
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: nefcanto
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://first/
  https://second/
  https://third/
 Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
How are the mirrors configured? Are the mirrors up-to-date in that case, or are they still serving the old version? 

I'd have to dig into the full logic, but I think there's some configuration options for registries that may determine some of that (e.g. I see there's a TTL that can be configured) https://github.com/distribution/distribution/blob/69023c7f85071b33ad61bd61f149a3d0c065aa7e/docs/recipes/mirror.md

Which may mean that the mirror continues serving the initial version of the image (before it was updated) if it has it cached locally, and until the TTL expires.

**Comment by Nefcanto** [comment]
@thaJeztah is there any option to tell the mirror to not honor the local cache and get the image directly from the upstream?

**Comment by thaJeztah** [comment]
Not sure, and I _may_ be completely wrong in my assumptions; you could try to check the logs of each of your mirrors to see if the engine indeed hits those registries (to resolve the digest), and if those logs provide details on what strategy the mirror took.

Perhaps @milosgajdos knows from the top of his head w.r.t. configuration options. The question then of course is: is there still a use for a mirror if it would always fetch from upstream? 🤔 (I guess _to some extent_ if it would use that information to invalidate the cache instead of using a TTL).

**Comment by Nefcanto** [comment]
@thaJeztah, you're right. If a mirror always gets the image from the source, then it seems to be useless. But if we can configure it, then it's not. It's more or less similar to DNS queries. I'm not a master of it, but I think it's possible to ask for **authoritative** answer instead of a cache.

**Comment by sam-thibault** [comment]
I'll close this issue for now.
