### ISSUE TITLE
All docker commands hang after fresh install on Arch Linux

### ISSUE THREAD

**Issue by mWalrus** [docker/cli#4579]
### Description

After installing docker through pacman, all sub-commands hang without any output. Judging from the `journalctl` output below, it seems like `containerd` isn't starting due to an error.

### Reproduce

1. `pacman -S docker`
2. `systemctl enable docker.service`
3. reboot
4. `docker <any_sub_command...>`

### Expected behavior

Sub-commands should work.

### docker version
`docker version` does not work. Output of `docker --version`:
```
Docker version 24.0.5, build ced0996600
```

### docker info
`docker info` does not work.

### Additional Info

`journalctl -eu docker` reports the following:
```
Sep 27 11:31:07 work systemd[1]: Starting Docker Application Container Engine...
Sep 27 11:31:07 work dockerd[592]: time="2023-09-27T11:31:07.093370804+02:00" level=info msg="Starting up"
Sep 27 11:32:07 work dockerd[592]: failed to start daemon: failed to dial "/run/containerd/containerd.sock": failed to dial "/run/containerd/containerd.sock": context deadline exceeded
Sep 27 11:32:07 work systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Sep 27 11:32:07 work systemd[1]: docker.service: Failed with result 'exit-code'.
Sep 27 11:32:07 work systemd[1]: Failed to start Docker Application Container Engine.
Sep 27 11:32:09 work systemd[1]: docker.service: Scheduled restart job, restart counter is at 1.
```

Something seems to be wrong with containerd but I cannot figure out what exactly (aside from it not seeming to start up). Trying to (re)start `containerd` using `systemd` reports `Failed to start containerd.service: Unit containerd.service is masked`.

**Comment by mWalrus** [comment]
I seem to have solved this issue now. I'm still unsure as to what caused this issue in the first place but at least it works again.

The steps I took was:
1. Find all `containerd` related files:
```bash
find / -name 'containerd*' -not -path '*/*cache/*' -or -name 'ctr' -not -path '*/*cache/*'
```
2. Delete the files listed
4. Reinstall containerd: `pacman -S containerd`
5. Enable the service: `systemctl enable containerd`
6. Reboot

I can finally run `docker version` and `docker info` again so here is that information.

### `docker version`
```bash
Client:
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.6
 Git commit:        ced0996600
 Built:             Wed Jul 26 21:44:58 2023
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          24.0.5
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.6
  Git commit:       a61e2b4c9c
  Built:            Wed Jul 26 21:44:58 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.6
  GitCommit:        091922f03c2762540fd057fba91260237ff86acb.m
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
### `docker info`
```bash
Client:
 Version:    24.0.5
 Context:    default
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 24.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 091922f03c2762540fd057fba91260237ff86acb.m
 runc version: N/A
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.5.4-arch2-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 30.63GiB
 Name: work
 ID: 2b3ec960-2358-444a-b491-e7651a7b67b7
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

As I'm unsure what the cause was and if there is more investigation to be done, I'll keep this issue open even though it is resolved in my case.

**Comment by mWalrus** [comment]
Seems like my installation of `runc` was messed up as well as it failed to be queried reporting `exec format error` which hints towards it being compiled for a different architecture. I'm clueless as to why all of this happened but after performing the above steps for `runc` as well (manually deleting files and reinstalling), it seems to now work again.

**Comment by sam-thibault** [comment]
I will close this issue for now.
