### ISSUE TITLE
Fix 'sirupsen/logrus' import statements

### ISSUE THREAD

**Issue by vdemeester** [docker/cli#465]
Related to https://github.com/moby/moby/issues/33641, from initial issue on `moby/moby`

It appears that everything in this project is using the package name `Sirupsen/logrus` instead of `sirupsen/logrus` as is suggested by [the readme](https://github.com/sirupsen/logrus/blob/master/README.md):

> **Seeing weird case-sensitive problems?** Unfortunately, the author failed to realize the consequences of renaming to lower-case. Due to the Go package environment, this caused issues. Regretfully, there's no turning back now. Everything using logrus will need to use the lower-case: github.com/sirupsen/logrus. Any package that isn't, should be changed.

`moby/moby` is fixing it (i.e. using `sirupsen` lowercase) and as it is a dependency of `cli` (as `docker/docker` for now), we are also going to handle that in this repository. This issue is there to track that move.

- [ ] Wait for https://github.com/moby/moby/issues/33641 to get handled
- [ ] Dependencies to handle (open PRs there and wait for it to be updated)
  - [ ] https://github.com/docker/notary
  - [ ] https://github.com/opencontainers/runc (moby/moby#33641)
  - [ ] https://github.com/docker/go-events
  - [ ] https://github.com/docker/swarmkit (moby/moby#33641)
  - [ ] https://github.com/docker/distribution
  - [ ] https://github.com/Azure/go-ansiterm

**Comment by shouze** [comment]
@vdemeester ok I've just encountered that issue... as I wanted to upgrade `github.com/docker/docker` hash to the one of the merge of https://github.com/moby/moby/pull/34590 & continue work on https://github.com/moby/moby/issues/32816 fix so this is blocking me ATM.

I've check and looks like that only notary is waiting for https://github.com/docker/notary/pull/1211 to get merged then it will be ok no? All the other dependencies have been fixed, so close to a cli patch 😉.

Anyway I'm ok to contribute to unlock that when https://github.com/docker/notary/pull/1211 will get merged.

**Comment by shouze** [comment]
@vdemeester ok since https://github.com/docker/notary/pull/1225 has been merged, I guess this issue can be closed no?
