### ISSUE TITLE
Resolving `default` context from Docker API fails with "context "default": context not found: open C:\...\meta.json: The system cannot find the path specified."

### ISSUE THREAD

**Issue by tiesmaster** [docker/cli#4676]
### Description

In Minikube, the docker context is resolved, however, that fails with the `default` context. As discovered [here](https://github.com/kubernetes/minikube/issues/16788#issuecomment-1822741002), it is believed to be an issue upstream in Docker, as opposed to a bug in Minikube, since the bug can be reproduced without minikube (see the reproduction steps below).

### Reproduce

1. Install Docker Desktop on Windows, using the WSL backend
2. Install golang on Windows, and make a new main.go, and add the code below (full reproduction [here](https://gist.github.com/tiesmaster/820fa6ed9255472167b9cad2efc788a6))
3. Start this via `go run`

`main.go`:
```golang
package main

import (
	"fmt"
	dconfig "github.com/docker/cli/cli/config"
	ddocker "github.com/docker/cli/cli/context/docker"
	dstore "github.com/docker/cli/cli/context/store"
)

func main() {
	currentContext := "default"
	storeConfig := dstore.NewConfig(
		func() interface{} { return &ddocker.EndpointMeta{} },
		dstore.EndpointTypeGetter(ddocker.DockerEndpoint, func() interface{} { return &ddocker.EndpointMeta{} }),
	)
	st := dstore.New(dconfig.ContextStoreDir(), storeConfig)
	_, err := st.GetMetadata(currentContext)
	if err != nil {
		fmt.Printf("Unable to resolve the current Docker CLI context %q: %v\n", currentContext, err)
		return
	}
}

```

### Expected behavior

No error on [`st.GetMetadata(...)`](https://gist.github.com/tiesmaster/820fa6ed9255472167b9cad2efc788a6#file-main-go-L17), but successful result returning a `Metadata` object.

### docker version

```bash
Client:
 Cloud integration: v1.0.35+desktop.5
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:32:48 2023
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Desktop 4.25.2 (129061)
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:32:16 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    24.0.6
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2-desktop.5
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.23.0-desktop.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.9
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scan.exe
  scout: Docker Scout (Docker Inc.)
    Version:  v1.0.9
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 23
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
 Kernel Version: 5.15.133.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 15.48GiB
 Name: shuri
 ID: e4e5d808-1391-4fb7-974b-56720d32a06f
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
WARNING: daemon is not using the default seccomp profile
```

### Diagnostics ID

43A84B06-B2E9-4A91-AD86-D20310385529/20231125195036

### Additional Info

I'm not a developer on the minikube team, so I don't have full context of how the code there came to be, and 100% certain that this isn't a bug in the way the API is being used, but it seems reasonable. Next, stepping into the code of `st.GetMetadata(...)`, and verifying that it tried to open the `meta.json`, which clearly isn't handling the fact that for the `default` context, the `meta.json` file is in memory, as identified [here](https://github.com/kubernetes/minikube/issues/16788#issuecomment-1703911426). So it makes sense that this should be special cased somehow in the golang package.

**Comment by thaJeztah** [comment]
Yes; there's a "ContextStore with default" wrapper that's used to intercept handling the special `default` context. The context store itself doesn't support it (but has some guards in place to disallow it as a reserved name). The code for that wrapper currently lives here; https://github.com/docker/cli/blob/48e889023fa99e4c1ed2cb67f2a9a7763555ebec/cli/command/defaultcontextstore.go#L32

That said, the context code is overly complicated, and in dire need of a proper cleanup, but there's some other re-thinking of if related to that, so not sure in what term that work will happen.


I don't think there's a bug at hand here, so I'll close this ticket for housekeeping, but feel free to continue the conversation 👍

**Comment by tiesmaster** [comment]
@thaJeztah Thnx! That definitely explains, and agree to close. I will take this downstream again, and suggest to make use of the wrapper instead in Minikube, that might be a sufficient fix for this issue.

If there is going to be a big overheal on this area, I suppose they can ingest that change when that happens. No need to wait for that.

---

BTW The guards don't seem to kick in, seeing that the `GetMetadata()` function still tries to calculate a path for a `meta.json` file, and open that open. Returning the IO error when that fails. 🤷

**Comment by thaJeztah** [comment]
Also feel free to let us know if it worked out (and/or post a link here to the upstream ticket), and of course, tickets or contributions are welcome in case needed.
