### ISSUE TITLE
docker EE still mentioned in README

### ISSUE THREAD

**Issue by nicks** [docker/cli#4677]
### Description

The README says:
https://github.com/docker/cli/blob/5aa3077c362d808ee739d3686725deb111708a4c/README.md?plain=1#L11

```
This repository is the home of the cli used in the Docker CE and
Docker EE products.
```

my understanding is that Docker EE doesn't exist anymore?

### Reproduce

n/a

### docker version

```bash
n/a
```

### docker info

```bash
n/a
```

**Comment by thaJeztah** [comment]
Ah, yes, the readme could use a bit of a cleanup there. ISTR it wasn't removed immediately, because initially Mirantis was allowed to continue the "Docker EE" trademark/branding during the transition period, and I guess it never got removed when that expired.
