### ISSUE TITLE
Additional property pull_policy is not allowed

### ISSUE THREAD

**Issue by markixy** [docker/cli#4688]
### Description

i try to deploy service using Docker Swarm. command like that:
`docker stack deploy -c docker-compose.yml myStack`
i got the error : services.app-front Additional property pull_policy is not allowed

i want to force pull image when container start，i can found it in the docs https://docs.docker.com/compose/compose-file/05-services/#pull_policy
how do I solve this? or have other way to implement it？

**Comment by markixy** [comment]
> Docker Swarm uses the uses the legacy Compose file version 3 (Compose V1): https://docs.docker.com/compose/compose-file/compose-file-v3/ which doesn't support the `pull_policy`.

thx.
has other way to force pull image?

**Comment by vvoland** [comment]
I don't think there's a way to do this automatically, but you can trigger it manually by updating the service:

```
docker service update --image <image> <service>
```

**Comment by thaJeztah** [comment]
I think stack deploy will always resolve the digest of the image when deploying; from the `docker stack deploy --help` usage;

```
      --resolve-image string   Query the registry to resolve image digest and supported platforms ("always", "changed", "never") (default "always")
```

After it has resolved the image, it pins the deployed services by that digest so that all instances of a service will always use the exact same version of the image.
