### ISSUE TITLE
Broken link on docker windows documentation

### ISSUE THREAD

**Issue by rubensfig** [docker/cli#473]
Hello,

The link for the experimental features in the docker documentation for windows [here](https://docs.docker.com/docker-for-windows/#experimental-mode) is broken. It is the first link. I don't think where it is supposed to go, or I'd fix it.

**Comment by dnephin** [comment]
Thanks!  It should link here now: https://github.com/docker/cli/blob/master/experimental/README.md

I've opened https://github.com/docker/docker.github.io/pull/4371. Merging that isn't going to auto-close this issue since it's cross repo, so going to close this now.
