### ISSUE TITLE
Docker stack ps  - Incorrect exit code

### ISSUE THREAD

**Issue by FrenchBen** [docker/cli#478]
**Description**
When using the docker cli, it's consistent for the exit code to reflect the status of resources. 
exists - > 0
does not exists -> 1

However this behavior/pattern is not consistent across all CLI. For example:
```
~ $ docker stack ps missingstack
Nothing found in stack: missingstack
~ $ echo $?
0
```
Yet docker service will reply as expected:
```
~ $ docker service ps missingservice
no such services: missingservice
~ $ echo $?
1
~ $
```

**Steps to reproduce the issue:**
1. Create a docker swarm
2. Check if a stack exists `docker stack ps somestack`
3. Verify exit code: `echo $?`

**Describe the results you received:**
Exit code of `docker stack ps invalidstack` is `0`

**Describe the results you expected:**
Exit code of `docker stack ps invalidstack` is `1`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      17.06.1-ee-1
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   4dd6e94
 Built:        Sat Aug 12 01:18:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.1-ee-1
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   4dd6e94
 Built:        Sat Aug 12 01:25:18 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
Same issue in `17.07.0-ce-rc4`

**Comment by ripcurld0** [comment]
calling #dibs
