### ISSUE TITLE
Missing features in bash completion for Docker 17.07.0-ce

### ISSUE THREAD

**Issue by albers** [docker/cli#483]
Several updates to bash completion are missing in Docker 17.07.0-ce, e.g. support for configs (which was present in bash completion for 17.06.1-ce).

See the [17.07.0 milestone](https://github.com/docker/cli/issues?utf8=%E2%9C%93&q=is%3Aclosed%20milestone%3A17.07.0%20author%3Aalbers) for my PRs that were marked as completed.
This list has 8 PRs, of which only two actually arrived in the 17.07.0-ce release.

Missing: #382, #334, #321, #284, #283, #279.
Present: #282, #285

**Comment by albers** [comment]
4 of the 6 missing PRs were present in 17.06.1-ce: #321, #284, #283, #279, so the features effectively got removed.

**Comment by dnephin** [comment]
cc @andrewhsu @tiborvass @mlaventure

**Comment by tiborvass** [comment]
cc @seemethere

**Comment by albers** [comment]
Looks like nobody cares, and as the next release (17.09.0) is already out, this is no longer relevant.

cc @thaJeztah There should be some todo item somewhere in the release process to make sure that features cherry-picked into a stable patch release also get cherry-picked into the next edge release.
This went wrong here for bash completion.
