### ISSUE TITLE
v25.0.1 : Network not work correctly in project start

### ISSUE THREAD

**Issue by neerfix** [docker/cli#4842]
### Description

Since updating to Docker version 25.0.1, I've encountered an error with my Traefik saying, 'Could not resolve host: xxx.xxxxxxxx.local' for 'http://xxx.xxxxx.local/me'.

I spent the entire day trying to solve this problem, and finally found a solution. By creating a new temp network in the project and reinstalling it with docker compose up -d, my original network started working again and I resolved the 'Could not resolve host' issue.

However, the problem is not consistently present. In some of my projects, the issue persists, while in others, Traefik and the network function normally.

### Reproduce

Setting Up Traefik: Configure Traefik to use your existing Docker network. It is after this setup that you might encounter the mentioned error ("Could not resolve host").
Reproducing the Problem: Attempt to access a specific service or route managed by Traefik. At this point, you should encounter the "Could not resolve host" error.
Creating a New Temporary Network: Create a new Docker network named temp. This can be done using Docker commands or Docker Compose.
Reinstalling with Docker Compose: Run docker compose up -d to redeploy your services using the newly created temp network.
Testing the Solution: After redeployment, try accessing the same service or route through Traefik again. If the solution is effective, the "Could not resolve host" error should no longer occur. This step verifies whether the new network setup resolves the issue.

### docker version

```bash
Client: Docker Engine - Community
 Version:           25.0.1
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        29cf629
 Built:             Tue Jan 23 23:09:23 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.1
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       71fa3ab
  Built:            Tue Jan 23 23:09:23 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.27
  GitCommit:        a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc:
  Version:          1.1.11
  GitCommit:        v1.1.11-0-g4bccb38
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    25.0.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.2
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan

Server:
 Containers: 32
  Running: 28
  Paused: 0
  Stopped: 4
 Images: 49
 Server Version: 25.0.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: a1496014c916f9e62104b33d1bb5bd03b0858e59
 runc version: v1.1.11-0-g4bccb38
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.5.0-15-generic
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 30.78GiB
 Name: LINUX25
 ID: d5f34c19-4626-4449-8e44-ee960d2641b5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by akerouanton** [comment]
Hi @neerfix, thanks for reporting.

This repo is for the CLI itself, not the Engine. Unfortunately we can't move this issue to the right repo (because it's not the same GH org). Could you create a new issue in https://github.com/moby/moby with a minimal reproducer please? To debug that issue we'd need:

- A minimal Compose file with 2 services (make sure you're still able to reproduce the issue) ;
- The output of `docker network inspect` for the network connecting both containers ;
- The output of `docker inspect` for both containers ;
- The content of `/etc/resolv.conf`, from the container where Traefik is running, when the issue occurs ;

**Comment by neerfix** [comment]
new Issue : https://github.com/moby/moby/issues/47290
