### ISSUE TITLE
Canceling "volume prune" prints "Total reclaimed space: 0B" but likely shouldn't

### ISSUE THREAD

**Issue by thaJeztah** [docker/cli#4851]
### Description

I noticed that canceling `docker volume prune` (using `N`, or pressing `ENTER`) prints a summary of the amount of data reclainmed. Given that the user asked to _cancel_ the command (don't perform `prune`), it likely should not print that message. If it _does_ print a message, that message should reflect the course of action taken (i.e.; the command was canceled, not executed).

```bash
$ docker volume prune
WARNING! This will remove anonymous local volumes not used by at least one container.
Are you sure you want to continue? [y/N]
Total reclaimed space: 0B
```

Suggested changes:

- Consider omitting the message, OR printing an alternative message (canceled the command).
- And/or consider printing `N` if the user presses `ENTER` (which is equivalent to "use the default (`N`))

Perhaps just printing the taken option would be enough (and minimal amount of noise)? i.e. after pressing `ENTER`, it would show;

```bash
$ docker volume prune
WARNING! This will remove anonymous local volumes not used by at least one container.
Are you sure you want to continue? [y/N] N
$
```

I also (briefly) went looking for "prior art". It looks like Bash (and other shells), simply print a prompt, but without printing default, nor printing the action taken (looks to be default is `no`);

```bash
$ touch some-file.txt
$ rm -i some-file.txt
rm: remove regular empty file 'some-file.txt'?
$ ls -a
.  .. some-file.txt
$ rm -i some-file.txt
rm: remove regular empty file 'some-file.txt'? y
$ ls -a
.  ..
```

```zsh
thajeztah@m1book cli % rm -i some-file.txt
remove some-file.txt?

thajeztah@m1book cli % ls
.  .. some-file.txt
```

I'm personally not a fan of that approach, as

- it's unclear "what happened" (what was the default? what happened when I pressed `ENTER`?)
- what are valid options? (I assumed `y`, `n`, but it doesn't show)

(But open to better suggestions!)

**Comment by thaJeztah** [comment]
cc @jalonsogo @laurazard @krissetto

**Comment by laurazard** [comment]
I'm on board with **both** printing the "n" (this is standard and it's wild that somehow it's not printed here) and omitting that message when no action was taken.

(would you take a jab at it @krissetto?)

**Comment by thaJeztah** [comment]
> I think here, I'd prefer replacing the "0 bytes reclaimed" message when cancelled (whether via "n" or "enter") with something like "Action cancelled." or just "Cancelled."

Yes, I'm good with using a different message (don't have good suggestions yet (was indeed thinking about "something something cancelled", but also wanted to avoid any confusion with the dreaded `context cancelled`.

Honestly; trying to find good examples of the `[y/N]` convention; I know it was based on _something_ (at least I _really_ recall there's tools using that convention) but now trying to find some (to see how they behave, and if there's some common ground / expectations 😂)

**Comment by laurazard** [comment]
I'm pretty sure I've seen tools that go
```
Prompt [y/N]:
Invalid input, exiting..
```
too.

**Comment by krissetto** [comment]
I guess we want to make the actions taken by the command more clear to the user. 

Looking at other commands that prompt the user for a confirmation before executing something or not, I'd suggest **first** aligning the behavior to those commands, **then** thinking about how to make the experience better for all the commands, keeping things as uniform as possible. 

In this case I'd suggest removing the `Total reclaimed space: 0B` msg and not printing the `n/N` as the selected default when the user simply presses the `ENTER` key.  So i think for now we should just exit without printing anything, and with status code 0, just like the other `prune` commands do.

What do you think? @jalonsogo

**Comment by laurazard** [comment]
Sounds good to me for a first improvement :+1:

**Comment by thaJeztah** [comment]
Yes, I'd be good with starting to align behavior first. The `Total reclaimed space: 0B` stood out to me as it _seems_ to indicate "we ran a prune, but nothing was pruned" which _for sure_ is an incorrect message.

**Comment by thaJeztah** [comment]
(I honestly didn't check what the other commands printed yet, but if those don't print anything, then 👍 👍 👍 )

**Comment by krissetto** [comment]
Opened https://github.com/docker/cli/pull/4854 for this
