### ISSUE TITLE
Internal network with opt drivers

### ISSUE THREAD

**Issue by rFond** [docker/cli#4864]
### Description

I'm encountering an issue with Docker version 25.0.3. When I use docker-compose with an internal network, specifying a name and an IP address in the driver opts, the IP address isn't accessible from the physical machine.
I use this from 1 or 2 years before I haven't this problem.

### Reproduce

Into docker compose

  mosquitto:
    image: mosquitto
    container_name: mosquitto
    restart: always
    volumes:
      - /etc/ssl/private/:/etc/ssl/private/:ro
    ports:
      #- 1883:1883
      #- 9001:9001
      #- 8883:8883
      - 8081:8081
    dns: 0.0.0.0
    networks:
      vpcbr_external:
        ipv4_address: 172.18.0.5
      vpcbr_mosquitto:

networks:
  agent_network:
    driver: overlay
  vpcbr_external:
    internal: true
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: docker1
    ipam:
     config:
       - subnet: 172.18.0.0/16
         gateway: 172.18.0.254

### Expected behavior

sudo ifconfig
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        ether 02:42:ae:3d:aa:27  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

docker1: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.18.0.254  netmask 255.255.0.0  broadcast 172.17.255.255
        ether 02:42:ae:3d:aa:27  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

### docker version

```bash
Client: Docker Engine - Community
 Version:           25.0.3
 API version:       1.44
 Go version:        go1.21.6
 Git commit:        4debf41
 Built:             Tue Feb  6 21:14:26 2024
 OS/Arch:           linux/arm64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.3
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       f417435
  Built:            Tue Feb  6 21:14:26 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    25.0.3
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.5
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 12
 Server Version: 25.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.10.162-cip24
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 1.888GiB
 Name: iot2050-debian
 ID: XOPT:IZSK:VVY7:3B5A:7K2S:RDT2:P74F:ZW7H:47CG:FHCJ:ROPR:SFDT
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

The goal is for a service on the physical machine to access Mosquitto to send it requests.

**Comment by thaJeztah** [comment]
cc @robmry FYI
