### ISSUE TITLE
Docker compose no longer completes service names.

### ISSUE THREAD

**Issue by systemmonkey42** [docker/cli#4874]
### Description

Using the <kbd>Tab</kbd> completion key after a `docker compose` command (like `docker compose exec`) produces a full list of services, even if you have typed a partial service name.

### Reproduce

1. Type `docker compose logs` <kbd>Tab</kbd>, see list of services, assuming there is a service called "web",
2. Type `docker compose logs w`<kbd>Tab</kbd>, see a complete list of services, ignoring the 'w' prefix.

### Expected behavior

Completion should filter completion options based on typed prefix.

### docker version

```bash
Not a docker runtime issue.
```

### docker info

```bash
Not a docker runtime issue.
```

### Additional Info

There is a typo in the `__docker_complete_plugin()` function where line 1175 (line 1164 in original commit aa0aa4a) which defines `$cur` as the variable containing the text before the cursor, then uses `$current` (an undefined variable) in its place.

**Comment by AndreasMietk** [comment]
Thanks for pointing out this bug! I got the same issue with service names only..

**Comment by jslegers73** [comment]
> Thanks for pointing out this bug! I got the same issue with service names only..

Hi,

I also had this issue on a RPI. I did an apt update and upgrade and now docker compose version is :

pi@pi-server:~ $ docker compose version
Docker Compose version v2.24.7

And after this update and it works again.
