### ISSUE TITLE
Capture Engine CLI experimental annotations on commands and flags

### ISSUE THREAD

**Issue by johndmulhausen** [docker/cli#494]
@mstanleyjones commented on [Tue Feb 14 2017](https://github.com/docker/docker.github.io/issues/1663)

### Problem description

It would be good to capture, in the CLI YAML, when a command or a flag is experimental. Here are some examples in the code:

- [experimental command](https://github.com/docker/docker/blob/master/cli/command/checkpoint/cmd.go#L16)
- [experimental flag](https://github.com/docker/docker/blob/master/cli/command/image/build.go#L115)

If this info was surfaced in the YAML, we could template it to automatically mark commands and flags as experimental.

cc/ @johndmulhausen @thaJeztah @dnephin @vieux 

---

@thaJeztah commented on [Tue Feb 14 2017](https://github.com/docker/docker.github.io/issues/1663#issuecomment-279870497)

There's also an [API version annotation](https://github.com/docker/docker/blob/master/cli/command/image/build.go#L116), which could be used to document "new in version x.y.z" (if we translate API version to docker version

---

@FrenchBen commented on [Tue Feb 14 2017](https://github.com/docker/docker.github.io/issues/1663#issuecomment-279870707)

Experimental command example:
https://github.com/docker/docker/blob/master/cli/command/checkpoint/cmd.go

Experimental flag example:
https://github.com/docker/docker/blob/master/cli/command/container/start.go

**Comment by johndmulhausen** [comment]
Ping @tiborvass

**Comment by thaJeztah** [comment]
Oh, I think this will be resolved by https://github.com/docker/cli/pull/523 (still catching up on my post-vacation notifications, so didn't see this one)

@johndmulhausen can you have a look at that one, and if that would resolve things for you?
