### ISSUE TITLE
Proposal: Adding `docker init` Command to Docker CLI

### ISSUE THREAD

**Issue by sswastik02** [docker/cli#4991]
### Description

Introduce `docker init` directly into the CLI so it is accessible via the command-line without Docker Desktop dependency. Here are the [docs](https://docs.docker.com/reference/cli/docker/init/) for the command.

**Comment by thaJeztah** [comment]
`docker init` is a closed-source extension to the CLI that's part of Docker Desktop. The best place to ask for providing this functionality in other setups would be the public roadmap, and it looks like someone already opened a ticket for that;

- https://github.com/docker/roadmap/issues/610

I'll close the ticket here, as this is a product decision, and not something that can be addressed in this repository.
