### ISSUE TITLE
It is helpful to match the commands with the printouts

### ISSUE THREAD

**Issue by johndmulhausen** [docker/cli#500]
@gdennie commented on [Sat Apr 22 2017](https://github.com/docker/docker.github.io/issues/3007)

File: [engine/reference/commandline/ps.md](https://docs.docker.com/engine/reference/commandline/ps/), CC @mstanleyjones 

While `docker ps --format` uses `Go templates`, the current implementation does miss the opportunity to make the field names match the report column titles. In particular, it seems that the current possible field names should be used as the corresponding printout column titles. (I have belated suspect the pattern of lowercase with capitalized first letter; however, I think the suggestion is still good.)

**Comment by thaJeztah** [comment]
The placeholders are based on the JSON that's returned by the API; the table column captions are a "human readable" version for those, and only known when printing the table-headers.

You can see those fields when formatting the output as JSON:

```bash
docker ps --no-trunc --format '{{json .}}'
```
```json
{
  "Command": "\"nginx -g 'daemon off;'\"",
  "CreatedAt": "2017-09-13 12:42:02 +0200 CEST",
  "ID": "934ccf7db5973963e0b08b49ff7fd404ee8bc3f790829800a8a17f78467c87b6",
  "Image": "nginx:alpine",
  "Labels": "",
  "LocalVolumes": "0",
  "Mounts": "",
  "Names": "foo",
  "Networks": "bridge",
  "Ports": "80/tcp",
  "RunningFor": "About an hour ago",
  "Size": "0B",
  "Status": "Up About an hour"
}
```

Adding the table columns as "alias" for all these fields would probably introduce quite a bit of code that needs to be maintained, so I'm not sure we should do so.

@dnephin wdyt?

**Comment by dnephin** [comment]
Having the headers match the fields would have been a good idea, but it's too late to fix that now. 

The docs seem pretty clear on what to use in the format string (https://docs.docker.com/engine/reference/commandline/ps/#formatting) so I think we can close this issue.

**Comment by thaJeztah** [comment]
Agreed, let me close this

**Comment by gdennie** [comment]
Sorry for the delay in return to this...

Documentation is specification. You should not have to explain the documentation to the target audience.

(
Documentation is code to the consumer of your application and specification to the implementation. Specifically, it is not some incidental after thought like in-code comment. Unless you expect your users to become familiar with the innards of the architecture sufficient to compensate for such foibles or to read the documentation in such thoroughness as to self clarify, there are enough puzzles in coding and the rest of the world for documentation should not become one of them.
Consequently, as far as I am concern this remains open.
)

**Comment by thaJeztah** [comment]
Can you explain what exactly you're missing in the documentation? The fields that are supported for the format are described in the documentation; is there anything in there you think would be helpful to add?

**Comment by gdennie** [comment]
My concern is philosophical since I am not directly working with docker presently and the issue I raised is no longer relevant for me personally. However, philosophically, consistency eliminates puzzlement otherwise encountered by the thousands of individuals who will use your tool. If it only takes them five minutes to figure out an unnecessary puzzle that is still five minutes multiplied by say five thousand minds or about four hundred hours. Further, such puzzles are not met in isolation, further complicating the situation. That my $0.02. The issue can be closed. :)

**Comment by jcrben** [comment]
> Having the headers match the fields would have been a good idea, but it's too late to fix that now.

This bit me today when working with `docker image ls` and left me scratching my head for a bit longer than I'd really like to admit.

> Adding the table columns as "alias" for all these fields would probably introduce quite a bit of code that needs to be maintained, so I'm not sure we should do so.

In the long run, it seems like keeping these consistent could end up resulting in a reduced maintenance burden?

Additionally, format is a command which crosses multiple concerns. It appears that the labels are documented for ps over at https://docs.docker.com/engine/reference/commandline/ps/#formatting but I don't see them documented for, say, https://web.archive.org/web/20170705084543/https://docs.docker.com/engine/reference/commandline/image_ls/
