### ISSUE TITLE
Is it possible to merge two base images in Docker?

### ISSUE THREAD

**Issue by Nefcanto** [docker/cli#5022]
### Description

I did not know where to post this feature request related to the `Dockerfile`. Thus, I sent it here.

I'm stuck at this problem. I have a custom image for my API that inherits from `FROM mcr.microsoft.com/vscode/devcontainers/dotnet:8.0-bookworm-slim`, and I have other custom images for my website and react panel that inherits from `FROM node:lts-bookworm-slim`.

However, I need node.js in my API projects, and I also need some stuff that I install in my custom API image, in my react and site images.

I need to be able to create a common base image that combines both `mcr.microsoft.com/vscode/devcontainers/dotnet:8.0-bookworm-slim` and `node:lts-bookworm-slim` into one final image. Then I can install my common npm packages and apt packages on that merged image, and use it for all of my needs for API, React panels, Qwik sites, ...

Can you please add that functionality? Is that possible? Is it an easy task?

**Comment by vvoland** [comment]
Docker CLI doesn't build image on its own, the engine uses [Buildkit](https://github.com/moby/buildkit), so any `Dockerfile`-related features should go into Buildkit's issue tracker.

However, merging two arbitrary and already built images would be extremely difficult, if not impossible.

Let me close the issue, as it's out of scope of the docker CLI.
