### ISSUE TITLE
add "docker tags" command

### ISSUE THREAD

**Issue by theCodedMike** [docker/cli#5032]
### Description

In some countries, developers cannot access `hub.docker.com` normally, so they cannot view all the tags of a certain image (they need to pull a image with specified tag)

Before I specify a tag, I need to know which tags the image has.

The effect I hope to achieve is that when I input `docker tags mysql` on the terminal, I will see all the tags of the `mysql` image, and then I input `docker pull mysql:x.x.x` on the terminal to download.

Another example is:
docker tags ubuntu/mysql
docker pull ubuntu/mysql:x.x.x

I think this feature is very useful, and I look forward to you implementing it.

**Comment by thaJeztah** [comment]
Thanks for opening this ticket; this is (somewhat) related to;

- https://github.com/moby/moby/issues/17238


The slightly tricky bit here is that this command would not deal with images in the local image store, but to query the registry. We currently have `docker search` / `docker image search` which uses the v1 search API implemented by some registries (but it's separate from the OCI distribution specification, so not implemented by all registries).

Listing these tags _is_ possible, as the OCI specification defines an endpoint for this as part of "content discovery"; https://github.com/opencontainers/distribution-spec/blob/v1.1.0/spec.md#content-discovery

However, that endpoint is not guaranteed to return all tags (registries are allowed to limit the number of results); even if unlimited, that can produce a very large number of tags, and it may be complicated to limit the result (but show the most "relevant" ones), as the list must be returned in lexical order;

> the tags MUST be in lexical order (i.e. case-insensitive alphanumeric order).

That may mean that only the oldest tags are returned, not the current one (which will limit its usefulness)

For cases where all tags are returned, that list may be long; for example, the list of tags for the official `debian` image is currently 2107 tags (but I seem to recall there's cases where there's literally _millions_ of tags in a repository);

```
repo=library/debian
token="$(curl -fsSL "https://auth.docker.io/token?service=registry.docker.io&scope=repository:$repo:pull" | jq --raw-output '.token')"
curl -s -H "Authorization: Bearer $token" "https://registry-1.docker.io/v2/$repo/tags/list" | jq '.tags | length'
2107
```

In that case, having a better _search_ for this could possibly be better (also for situations where different tags have very different purposes, e.g. [the `php` image](https://hub.docker.com/_/php) has various different variants, but all versioned)


So I think we may need to look;

- Where would this functionality be best implemented (it could be to provide auto-completion for (e.g.) `docker pull` and `docker run`)
- If it should be part of `docker search` (and making that better) or a separate (sub) command (e.g. `docker registry xxx` to clearly indicate it's to query the registry, not local images)
- If it's possible at all to implement with the currently available options (tag-list not guaranteed to return all results, and being sorted alphabetically)
