### ISSUE TITLE
`docker run --init` equivalent for compose

### ISSUE THREAD

**Issue by LukeusMaximus** [docker/cli#51]
[This PR](https://github.com/docker/compose/pull/4716) introduces init support to compose v2.2. Please can compose v3 also support this option.

**Comment by cpuguy83** [comment]
I don't think services support the init option. This would have to change in swarmkit, then update the docker API, and then update here.

**Comment by thaJeztah** [comment]
Compose file support was implemented in https://github.com/docker/cli/pull/1129, and completed a long chain of PR's to implement this feature :tada:
