### ISSUE TITLE
Bash autocompletion works incorrect with inspect

### ISSUE THREAD

**Issue by and800** [docker/cli#512]
**Description**

When I try to inspect the image and hint for image tags, the completion duplicates image name

**Steps to reproduce the issue:**
1. pull any image, e.g. `docker pull debian`
2. type `docker inspect debian:`
3. press TAB

**Describe the results you received:**
`user@localhost:~$ docker inspect debian:debian:latest`

**Describe the results you expected:**
`user@localhost:~$ docker inspect debian:latest`

**Output of `docker version`:**

```
Docker version 17.07.0-ce, build 8784753
```

**Comment by dnephin** [comment]
cc @albers

**Comment by albers** [comment]
Thanks for reporting. Completion of images needs rework, see also https://github.com/moby/moby/issues/27791.

I'll take care of this in about one month.

@dnephin I still haven't got privileges on this repo, can you please assign this issue to me?

**Comment by dnephin** [comment]
It won't let me assign it to you, I guess it's the same issue
