### ISSUE TITLE
fatal: morestack on g0

### ISSUE THREAD

**Issue by huhouhua** [docker/cli#5217]
### Description

Docker service restarts after a period of time
**Output**:

> Jul 02 22:15:27 docker systemd[1]: Starting Docker Application Container Engine...
> Jul 02 22:15:29 docker systemd[1]: Started Docker Application Container Engine.
> Jul 02 22:25:39 docker systemd[1]: docker.service: Main process exited, code=killed, status=11/SEGV
> Jul 02 22:25:39 docker systemd[1]: docker.service: Failed with result 'signal'.
> Jul 02 22:25:41 docker systemd[1]: docker.service: Scheduled restart job, restart counter is at 1.
> Jul 02 22:25:41 docker systemd[1]: Stopped Docker Application Container Engine.
> Jul 02 22:25:41 docker systemd[1]: Starting Docker Application Container Engine...
> Jul 02 22:25:41 docker systemd[1]: Started Docker Application Container Engine.
> Jul 02 23:15:22 docker dockerd[1959]: fatal: morestack on g0
> Jul 02 23:15:23 docker systemd[1]: docker.service: Main process exited, code=killed, status=11/SEGV
> Jul 02 23:15:23 docker systemd[1]: docker.service: Failed with result 'signal'.
> Jul 02 23:15:25 docker systemd[1]: docker.service: Scheduled restart job, restart counter is at 2.
> Jul 02 23:15:25 docker systemd[1]: Stopped Docker Application Container Engine.
> Jul 02 23:15:25 docker systemd[1]: Starting Docker Application Container Engine...
> Jul 02 23:15:25 docker systemd[1]: Started Docker Application Container Engine.
> Jul 02 23:18:10 docker dockerd[2185]: panic during panic
> Jul 02 23:18:10 docker dockerd[2185]: SIGSEGV: segmentation violation
> Jul 02 23:18:10 docker dockerd[2185]: PC=0x557486a4a267 m=2 sigcode=1
> Jul 02 23:18:10 docker dockerd[2185]: goroutine 0 [idle]:
> Jul 02 23:18:10 docker dockerd[2185]: runtime.retake(0x36d38e43177)
> Jul 02 23:18:10 docker dockerd[2185]:         /usr/local/go/src/runtime/proc.go:5683 +0x67 fp=0x7ff67adc0cc0 sp=0x7ff67adc0c80 pc=0x557486a4a267
> Jul 02 23:18:10 docker dockerd[2185]: runtime.sysmon()
> Jul 02 23:18:10 docker dockerd[2185]:         /usr/local/go/src/runtime/proc.go:5634 +0x32f fp=0x7ff67adc0d28 sp=0x7ff67adc0cc0 pc=0x557486a4a0ef
> Jul 02 23:18:10 docker dockerd[2185]: runtime.mstart1()
> Jul 02 23:18:10 docker dockerd[2185]:         /usr/local/go/src/runtime/proc.go:1602 +0x95 fp=0x7ff67adc0d50 sp=0x7ff67adc0d28 pc=0x557486a41775
> Jul 02 23:18:10 docker dockerd[2185]: runtime.mstart0()
> Jul 02 23:18:10 docker dockerd[2185]:         /usr/local/go/src/runtime/proc.go:1559 +0x76 fp=0x7ff67adc0d80 sp=0x7ff67adc0d50 pc=0x557486a416b6
> Jul 02 23:18:10 docker dockerd[2185]: runtime.mstart()
> Jul 02 23:18:10 docker dockerd[2185]:         /usr/local/go/src/runtime/asm_amd64.s:394 +0x5 fp=0x7ff67adc0d88 sp=0x7ff67adc0d80 pc=0x557486a712c5
> Jul 02 23:18:10 docker dockerd[2185]: goroutine 1 [chan receive, 62 minutes]:
> Jul 02 23:18:10 docker dockerd[2185]: runtime: g 1: unknown pc 0x560aa4a421ce
> Jul 02 23:18:10 docker dockerd[2185]: stack: frame={sp:0xc000179018, fp:0x0} stack=[0xc000176000,0xc00017a000)
> Jul 02 23:18:10 docker dockerd[2185]: 0x000000c000178f18:  0x000000c00045f958  0x0000000000000004
> Jul 02 23:18:10 docker dockerd[2185]: 0x000000c000178f28:  0x0000000000000004  0x000000c000159174
> Jul 02 23:18:10 docker dockerd[2185]: 0x000000c000178f38:  0x0000000000000004  0x0000000000000004
> Jul 02 23:18:10 docker dockerd[2185]: 0x000000c000178f48:  0x000000c00045f958  0x0000000000000004
> Jul 02 23:18:10 docker dockerd[2185]: 0x000000c000178f58:  0x0000000000000004  0x000000c000159178
> Jul 02 23:18:10 docker dockerd[2185]: 0x000000c000178f68:  0x0000000000000004  0x0000000000000004
> Jul 02 23:18:10 docker dockerd[2185]: 0x000000c000178f78:  0x000000c00045f958  0x0000000000000004
> Jul 02 23:18:10 docker dockerd[2185]: 0x000000c000178f88:  0x0000000000000004  0x000000c00015917c
> Jul 02 23:18:10 docker dockerd[2185]: 0x000000c000178f98:  0x0000000000000004  0x0000000000000004
> Jul 02 23:18:10 docker dockerd[2185]: 0x000000c000178fa8:  0x000000c00045f958  0x0000000000000004
> Jul 02 23:18:10 docker dockerd[2185]: 0x000000c000178fb8:  0x0000000000000004  0x000000c000159180
> Jul 02 23:18:10 docker dockerd[2185]: 0x000000c000178fc8:  0x0000000000000004  0x0000000000000004
> Jul 02 23:18:10 docker dockerd[2185]: 0x000000c000178fd8:  0x000000c00045f958  0x0000000000000004
> Jul 02 23:18:10 docker dockerd[2185]: 0x000000c000178fe8:  0x0000000000000004  0x000000c000159184
> Jul 02 23:18:10 docker dockerd[2185]: 0x000000c000178ff8:  0x0000000000000004  0x0000000000000004
> Jul 02 23:18:10 docker dockerd[2185]: 0x000000c000179008:  0x000000c00045f958  0x0000000000000004
> Jul 02 23:18:10 docker dockerd[2185]: 0x000000c000179018: <0x0000000000000004  0x000000c000159188
> Jul 02 23:18:10 docker dockerd[2185]: 0x000000c000179028:  0x0000000000000004  0x0000000000000004
> Jul 02 23:18:10 docker dockerd[2185]: 0x000000c000179038:  0x000000c00045f958  0x0000000000000004
> Jul 02 23:18:10 docker dockerd[2185]: 0x000000c000179048:  0x0000000000000004  0x000000c00015918c
> Jul 02 23:18:10 docker dockerd[2185]: 0x000000c000179058:  0x0000000000000004  0x0000000000000004
> Jul 02 23:18:10 docker dockerd[2185]: 0x000000c000179068:  0x000000c00045f958  0x0000000000000004
> Jul 02 23:18:10 docker dockerd[2185]: 0x000000c000179078:  0x0000000000000004  0x000000c000159190
> Jul 02 23:18:10 docker dockerd[2185]: 0x000000c000179088:  0x0000000000000004  0x0000000000000004
> Jul 02 23:18:10 docker dockerd[2185]: 0x000000c000179098:  0x000000c00045f958  0x0000000000000004
> Jul 02 23:18:10 docker dockerd[2185]: 0x000000c0001790a8:  0x0000000000000004  0x000000c000159194
> Jul 02 23:18:10 docker dockerd[2185]: 0x000000c0001790b8:  0x0000000000000004  0x0000000000000004
> Jul 02 23:18:10 docker dockerd[2185]: 0x000000c0001790c8:  0x000000c00045f958  0x0000000000000004
> Jul 02 23:18:10 docker dockerd[2185]: 0x000000c0001790d8:  0x0000000000000004  0x000000c000159198
> Jul 02 23:18:10 docker dockerd[2185]: 0x000000c0001790e8:  0x0000000000000004  0x0000000000000004
> Jul 02 23:18:10 docker dockerd[2185]: 0x000000c0001790f8:  0x000000c00045f958  0x0000000000000004
> Jul 02 23:18:10 docker dockerd[2185]: 0x000000c000179108:  0x0000000000000004  0x000000c00015919c
> Jul 02 23:18:10 docker dockerd[2185]: runtime: g 1: unknown pc 0x560aa4a421ce
> Jul 02 23:18:10 docker dockerd[2185]: stack: frame={sp:0xc000179018, fp:0x0} stack=[0xc000176000,0xc00017a000)

### Reproduce

1. execute `systemctl start docker`
2. Then the service automatically restarts after an interval of about 30 minutes.

### Expected behavior

The docker service is running normally

### docker version

```bash
Client: Docker Engine - Community
 Version:           26.1.4
 API version:       1.45
 Go version:        go1.21.11
 Git commit:        5650f9b
 Built:             Wed Jun  5 11:32:04 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          26.1.0
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.9
  Git commit:       c8af8eb
  Built:            Mon Apr 22 17:08:46 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.33
  GitCommit:        d2d58213f83a351ca8f528a95fbd145f5654e957
 runc:
  Version:          v1.7.19
  GitCommit:        v1.1.13-0-g58aa9203
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    26.1.4
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.27.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 3
  Running: 0
  Paused: 0
  Stopped: 3
 Images: 3
 Server Version: 26.1.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d2d58213f83a351ca8f528a95fbd145f5654e957
 runc version: v1.1.13-0-g58aa9203
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 5.10.0-60.139.0.166.oe2203.x86_64
 Operating System: openEuler 22.03 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.23GiB
 Name: docker
 ID: bbe2dbb3-5e7b-4ff1-9cda-545dc27374d6
 Docker Root Dir: /data/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.1
  0.0.0.0/0
  127.0.0.0/8
 Registry Mirrors:
  https://docker.mirrors.ustc.edu.cn/
  https://hub-mirror.c.163.com/
  https://registry.cn-shanghai.aliyuncs.com/
  https://registry.docker-cn.com/
  https://b9pmyelo.mirror.aliyuncs.com/
 Live Restore Enabled: false
```

### **1. os-release**

> NAME="openEuler"
> VERSION="22.03 LTS"
> ID="openEuler"
> VERSION_ID="22.03"
> PRETTY_NAME="openEuler 22.03 LTS"
> ANSI_COLOR="0;31"

### **2. uname**
Linux docker 5.10.0-60.139.0.166.oe2203.x86_64 #1 SMP Thu May 30 05:17:57 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by vvoland** [comment]
Looks like you installed our official packages for other distro (CentOS?). We don't provide packages for openEuler and don't support it.

If you experience the same issue on a supported distro, please open a new issue in https://github.com/moby/moby/issues.
