### ISSUE TITLE
Please have releases to indicate latest releases

### ISSUE THREAD

**Issue by githubofkrishnadhas** [docker/cli#5257]
### Description

Hello Team,

I think it is a best practice to have releases created whenever a change or fix is done. I see that tags are been created. It could be helpful to create releases along with tags as well.

![image](https://github.com/user-attachments/assets/7eb610d2-25cd-4270-983f-f24ed4a08524)
![image](https://github.com/user-attachments/assets/e8b13589-ff94-4523-ad9d-dbc9eec51d8f)

Thanks.

**Comment by vvoland** [comment]
The CLI release cycle is coupled with the Docker Engine releases.
You can find the combined release notes in the Moby releases: https://github.com/moby/moby/releases

**Comment by githubofkrishnadhas** [comment]
oh okay. i was not aware of this. But it is more appropriate to have the releases added here as well source code is here.

i checked moby/moby repo, thats good enough workaround for me. Thanks
