### ISSUE TITLE
terminating `docker attach` container prints `context canceled` error

### ISSUE THREAD

**Issue by thaJeztah** [docker/cli#5294]
### Description

I noticed this while updating the docs in https://github.com/docker/cli/pull/5289. Terminating an attach (`CTRL-c`, killing the container) prints a `context canceled` error.

Based on the example I was updating (assuming the example was correct!), older versions did not print these errors, and as they don't provide much value to the user, we should probably not print them 🤔 

```bash
docker run -d --name topdemo alpine /usr/bin/top -b

docker attach topdemo
Mem: 1397860K used, 6629032K free, 928K shrd, 168848K buff, 329628K cached
CPU:   0% usr   0% sys   0% nic  97% idle   1% io   0% irq   0% sirq
Load average: 0.25 0.16 0.08 1/342 6
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
    1     0 root     R     1712   0%   4   0% /usr/bin/top -b
^Ccontext canceled
```

I reproduced this with v27.0.3 and v27.1.1 (but haven't checked older versions)

**Comment by thaJeztah** [comment]
cc @Benehiko @laurazard

**Comment by laurazard** [comment]
Bisect says it was introduced in 3f0d90a2a939afa04a784b810dbdb035a0dff669 (cc @Benehiko)

**Comment by laurazard** [comment]
I can take a quick look, and add a test.

**Comment by Benehiko** [comment]
This should've been fixed in https://github.com/docker/cli/pull/5247

**Comment by thaJeztah** [comment]
> This should've been fixed in #5247

Oh! Hm.. need to double check now if I checked with 27.0 or 27.1 (or if there's still an issue at hand)

**Comment by laurazard** [comment]
I don't think it is,`attach` uses different code paths from `run`. I've got a commit with some tests and a fix on the way :)

**Comment by Benehiko** [comment]
> I don't think it is,`attach` uses different code paths from `run`. I've got a commit with some tests and a fix on the way :)

oh you're right! I didn't look too closely at the issue my mind just went to the code that was problematic at the "attach" section in the run command :sweat_smile:
