### ISSUE TITLE
Add container to container capability to "docker cp"

### ISSUE THREAD

**Issue by rolla-cluster** [docker/cli#5329]
### Description

Allow users to perform a container -> container copy. E.g.:
docker cp CONTAINER:/path/to.file CONTAINER2:/path/to.file

Currently throws:
https://github.com/docker/cli/blob/master/cli/command/container/cp.go#L199C1-L200C67
"copying between containers is not supported"

**Comment by vvoland** [comment]
There's already a tracking ticket on the engine repository: https://github.com/moby/moby/issues/42006

Let me close this one as duplicate, but feel free to continue the discussion there.
