### ISSUE TITLE
docker service ps does not group global services' tasks together properly

### ISSUE THREAD

**Issue by wsong** [docker/cli#533]
**Description**

`docker service ps` for a service is supposed to group tasks together by slot, but global services don't have a slot. It looks here like the intention is that tasks running on the same node should get grouped together and historical tasks should get a `\_` prefix so that they get indented under their other tasks on that same node:

https://github.com/docker/cli/blob/master/cli/command/task/print.go#L71

But this doesn't work because we sort tasks by slot:

https://github.com/docker/cli/blob/master/cli/command/task/print.go#L15

But global services' tasks don't have a slot.

**Steps to reproduce the issue:**
1. Create a global service on multiple nodes
2. Run `docker service ps` on that node
3. See that the service's tasks are not sorted by node

**Comment by dnephin** [comment]
So how should these tasks be sorted? I guess `tasksBySlot` needs to be renamed and updated to account for tasks without a slot? Should slot-less-tasks be sorted before or after tasks with a slot?

**Comment by wsong** [comment]
Theoretically, the tasks in `docker service ps` will either all have a slot or none will; tasks for a replicated service have a slot, but tasks for a global service don't.

**Comment by dnephin** [comment]
`docker service ps` accepts multiple service ids/names, so you could call it with one service that is global and one that is replicated. So I think we do need to consider how to sort them together.

**Comment by wsong** [comment]
Oh yeah, you're right. Well, whether slot-less tasks go before or after tasks with a slot doesn't really matter, so long as they don't get interleaved.

Seems like it'd make the most sense to first sort by service, then by slot/node ID.
