### ISSUE TITLE
security hazard for developers (when using default ip)

### ISSUE THREAD

**Issue by devkral** [docker/cli#5367]
### Description

The docker daemon should never assume that the default ip where the services are published is 0.0.0.0.
This is correct for servers but developers are endangered when someone doesn't set the ip explicit in the docker service file.

I know you can set the default ip in daemon.json but is too easy to forget it, so docker should just refuse to start a service if no default ip is set and no bind ip was provided. And when starting the bind ip should be mentioned in the output.

Additional for a while already the firewall (ufw) iptables are seemingly overwritten. I noticed it by having problems connecting to a public hotspot,

### Reproduce

running any docker service with ports and no bind ip mapped.

Try to use ufw to block the port and then connect via an external system.

This is to demonstrate the danger of having as default 0.0.0.0 and tampering with the firewall.

### docker version

```bash
Client:
 Version:           27.1.2
 API version:       1.46
 Go version:        go1.23.0
 Git commit:        d01f264bcc
 Built:             Sun Aug 18 14:43:14 2024
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          27.1.2
  API version:      1.46 (minimum version 1.24)
  Go version:       go1.23.0
  Git commit:       f9522e5e96
  Built:            Sun Aug 18 14:43:14 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.20
  GitCommit:        8fc6bcff51318944179630522a095cc9dbf9f353.m
 runc:
  Version:          1.1.13
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    27.1.2
 Context:    default
 Debug Mode: false
 Plugins:
  compose: Docker Compose (Docker Inc.)
    Version:  2.29.2
    Path:     /usr/lib/docker/cli-plugins/docker-compose
Server:
 Containers: 4
  Running: 0
  Paused: 0
  Stopped: 4
 Images: 35
 Server Version: 27.1.2
 Storage Driver: overlay2
  Backing Filesystem: btrfs
  Supports d_type: true
  Using metacopy: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fc6bcff51318944179630522a095cc9dbf9f353.m
 runc version: 
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.10.6-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 15.02GiB
 Name: mobarch2
 ID: ff311f36-301d-41b0-bf59-bc1618103173
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Additional Info

Note: most probably this is a docker daemon bug but I couldn't find the daemon repo.

**Comment by devkral** [comment]
Anyway congratulations for the idea to use the FORWARD chain. This way you bypass most firewalls and expose the services directly to the internet.

I mean it is clever but you have much higher security requirements when doing so. People who use docker for development and run their docker services with default pws are simply exposed when developing in public hotspots.

**Comment by laurazard** [comment]
The repo you're looking for is likely https://github.com/moby/moby.
