### ISSUE TITLE
Docker login in 27.2.0 no longer overwrites existing config.json

### ISSUE THREAD

**Issue by thiago-gitlab** [docker/cli#5382]
### Description

In Docker 27.1.2, running `docker login` multiple times causes the authentication information in `~/.docker/config.json` to be updated with the latest successful execution.

In 27.2.0, the first successful authentication prevents `config.json` from being updated.

This is a breaking change because the existing expectation is that `docker login` always overwrites the authentication information.

### Reproduce

1. docker login repository-a
2. docker login repository-b
3. docker push repository-b/image

The push will fail since the authentication information recorded is for `repository-a`.

I've reproduced this in https://gitlab.com/gitlab-org/gitlab/-/issues/481917#note_2081566814 by removing `config.json` before performing the second authentication.

### Expected behavior

`docker login` always updates `config.json` with the successful authentication credentials.

### docker version

```bash
Client 27.2.0 and 27.1.2
```

### docker info

```bash
No relevant
```

### Additional Info

https://gitlab.com/gitlab-org/gitlab/-/issues/481917

**Comment by thiago-gitlab** [comment]
A workaround is to downgrade to `27.1.2`. Another workaround is to delete the `config.json` before authenticating for a second time. [Example](https://gitlab.com/gitlab-org/secure/tests/thiagocsf-secure-tests/test-deploy-token/-/commit/e1a8bb6cb83b99f6f5626f79f96b7b12c05bffb5)

**Comment by thaJeztah** [comment]
Thanks for reporting!

From that linked ticket;

```bash
$ docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credential-stores
Login Succeeded
$ docker pull registry.gitlab.com/gitlab-org/security-products/analyzers/container-scanning:latest
latest: Pulling from gitlab-org/security-products/analyzers/container-scanning
e4fff0779e6d: Pulling fs layer
,,,
,,,
Digest: sha256:84c7ee8800ce979ef5482d5ca21086f05fbf50d3a477f8194e4b5e87233a5c24
Status: Downloaded newer image for registry.gitlab.com/gitlab-org/security-products/analyzers/container-scanning:latest
registry.gitlab.com/gitlab-org/security-products/analyzers/container-scanning:latest


$ if [ -n "$CS_DEPLOY_USERNAME" ] && [ -n "$CS_DEPLOY_PASSWORD" ]; then # collapsed multi-line command
Login Succeeded
WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credential-stores
The push refers to repository [registry.gitlab.com/security-products/container-scanning]
5f70bf18a086: Preparing
11c61dfd316c: Preparing
...
...
5f70bf18a086: Layer already exists
b70d9e93136f: Layer already exists
...
...
errors:
denied: requested access to the resource is denied
unauthorized: authentication required
```


Unfortunately the second login call is shown as "collapsed", but IIUC, the reproducer is effectively;


```bash
docker login some-registry.example.com/repository/name
...

docker login some-registry.example.com/other-repository/name
...
```

The problem looks to be that 27.2 is not converting the given registry to its hostname, and instead preserves the path (repository name), therefore storing each under a different key;

```bash
echo $PASS | docker login -u <USERNAME> --password-stdin registry.hub.docker.com
# ...
Login Succeeded

echo $PASS | docker login -u <USERNAME> --password-stdin registry.hub.docker.com/repository/name
# ...
Login Succeeded

echo $PASS | docker login -u <USERNAME> --password-stdin registry.hub.docker.com/other-repository/name
# ...
Login Succeeded

cat ~/.docker/config.json
{
	"auths": {
		"registry.hub.docker.com": {
			"auth": "<REDACTED>"
		},
		"registry.hub.docker.com/other-repository/name": {
			"auth": "<REDACTED>"
		},
		"registry.hub.docker.com/repository/name": {
			"auth": "<REDACTED>"
		}
	}
}
```

doing the same with 27.1;


```bash
echo $PASS | docker login -u <USERNAME> --password-stdin registry.hub.docker.com
# ...
Login Succeeded

echo $PASS | docker login -u <USERNAME> --password-stdin registry.hub.docker.com/repository/name
# ...
Login Succeeded

echo $PASS | docker login -u <USERNAME> --password-stdin registry.hub.docker.com/other-repository/name
# ...
Login Succeeded

cat ~/.docker/config.json
{
	"auths": {
		"registry.hub.docker.com": {
			"auth": "<REDACTED>"
		}
	}
}
```

**Comment by thaJeztah** [comment]
cc @laurazard PTAL - looks like somewhere we're missing a call to `ConvertToHostname` https://github.com/docker/cli/blob/6273e65ceedc8544765ddc940a4a6dc7c2a2a491/cli/config/credentials/file_store.go#L95

**Comment by laurazard** [comment]
FYI @thiago-gitlab, running `docker login [registry address]` with the repository name/image included in the repo (such as `docker login -u <USERNAME> index.docker.io/repository/name`) is undocumented behavior – we're fixing this for now, but no guarantees about the future unless we settle on explicitly supporting it. In general it would be safer to not include the repo name when running `docker login`.

**Comment by thiago-gitlab** [comment]
Thank you for letting me know, @laurazard. We'll fix that on our scripts and any user documentation.

And also thanks everyone for the amazingly quick response and fix. 🚀 🎉
