### ISSUE TITLE
build natively on arm64 architecture

### ISSUE THREAD

**Issue by Pennyzct** [docker/cli#539]
Description
The cross-compile binary for arm(docker-linux-arm) which you must cross-compile in x86-64 machine cant't work out in arm64 machine.

Steps to reproduce the issue:
on one arm64 machine and run docker-linux-arm binary.

Describe the results you received:
`-bash: ./docker-linux-arm: cannot execute binary file: Exec format error` or `Segmentation fault`

Describe the results you expected:
It should work well in  arm64 machine

Additional information you deem important (e.g. issue happens only occasionally):
I notice that in issue "build natively on the cross compile architectures #183", @dnephin has mentioned that we may change the base image for different arch. However, changing the base image for [arm64](https://hub.docker.com/r/arm64v8/golang/) still can't fix all errors, you still need 'apk  add' gcc and its dependent library. This string of actions are kind of a bummer for arm64-users. Maybe we can build another Dockerfile.arm64 for arm64 arch just like  
moby/moby? or add some few lines in docker.Makefile to fix this problem?

**Comment by Pennyzct** [comment]
I realize that the docker.io/golang:1.8.3-alpine has already been the manifestlist, but it still contains one amd64 image for now, maybe in the future it will implement multiple arch. 
As I said before, even it will contain arm64 base image(https://hub.docker.com/r/arm64v8/golang/), it still exists a few bugs. maybe we can redact the dockerfile.dev or docker.Makefile to fix this? 
@GordonTheTurtle @dnephin

**Comment by thaJeztah** [comment]
closing as this went stale
