### ISSUE TITLE
failed on pulling image from when pulling from mac os station

### ISSUE THREAD

**Issue by bwomsm1** [docker/cli#5475]
### Description

When I am running:
`docker pull ghcr.io/significa/app-distribution-server:sha-8732770`

I am getting:
`Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

I am running on Mac OS 15.0

### Reproduce

Run:
`docker pull ghcr.io/significa/app-distribution-server:sha-8732770`
Or
`docker pull alpine`

From Mac OS, install only the docker CLI tools

### docker version

```bash
Client: Docker Engine - Community
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.23.1
 Git commit:        ce1223035a
 Built:             Fri Sep 20 11:01:47 2024
 OS/Arch:           darwin/arm64
 Context:           default
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

### docker info

```bash
Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false

Server:
ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
errors pretty printing info
```

**Comment by bwomsm1** [comment]
@laurazard can you please help with that issue? thanks!

**Comment by laurazard** [comment]
Hi @bwomsm1,

The Docker CLI is a client for talking to the Docker Engine – when you run `docker pull ...`, the CLI initiates a call to the engine to ask the engine to pull the image requested.

The error message you're seeing:
> `Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

is the CLI looking for a running engine socket (in the default location – `/var/run/docker.sock`).

Hence, the CLI needs an engine to work – either an engine running locally, or you can configure your CLI to use a remote engine, such as:

```console
docker context create my-remote-engine --docker "host=ssh://remote-address"
docker context use my-remote-engine
```

**Comment by bwomsm1** [comment]
> Hi @bwomsm1,
> 
> The Docker CLI is a client for talking to the Docker Engine – when you run `docker pull ...`, the CLI initiates a call to the engine to ask the engine to pull the image requested.
> 
> The error message you're seeing:
> 
> > `Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`
> 
> is the CLI looking for a running engine socket (in the default location – `/var/run/docker.sock`).
> 
> Hence, the CLI needs an engine to work – either an engine running locally, or you can configure your CLI to use a remote engine, such as:
> 
> ```
> docker context create my-remote-engine --docker "host=ssh://remote-address"
> docker context use my-remote-engine
> ```

@laurazard thanks, 
the 2 lines that you offered did work without any exception, its just that once I called to :
`docker pull alpine` or `docker pull ghcr.io/significa/app-distribution-server:sha-8732770` my command line got stuck,

Any more actions I should do?

**Comment by bwomsm1** [comment]
> > Hi @bwomsm1,
> > The Docker CLI is a client for talking to the Docker Engine – when you run `docker pull ...`, the CLI initiates a call to the engine to ask the engine to pull the image requested.
> > The error message you're seeing:
> > > `Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`
> > 
> > 
> > is the CLI looking for a running engine socket (in the default location – `/var/run/docker.sock`).
> > Hence, the CLI needs an engine to work – either an engine running locally, or you can configure your CLI to use a remote engine, such as:
> > ```
> > docker context create my-remote-engine --docker "host=ssh://remote-address"
> > docker context use my-remote-engine
> > ```
> 
> @laurazard thanks, the 2 lines that you offered did work without any exception, its just that once I called to : `docker pull alpine` or `docker pull ghcr.io/significa/app-distribution-server:sha-8732770` my command line got stuck,
> 
> Any more actions I should do?

It got stuck and eventually stopped with timeout error:
```
error during connect: Post "http://docker.example.com/v1.47/images/create?fromImage=alpine&tag=latest": command [ssh -o ConnectTimeout=30 -T -- ghcr.io docker --host unix:///significa/app-distribution-server:sha-8732770 system dial-stdio] has exited with exit status 255, make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=ssh: connect to host ghcr.io port 22: Operation timed out
```

or 
```
mac-auto-04@mac-auto-04 tmp % docker pull ghcr.io/significa/app-distribution-server:sha-8732770
error during connect: Post "http://docker.example.com/v1.47/images/create?fromImage=ghcr.io%2Fsignifica%2Fapp-distribution-server&tag=sha-8732770": command [ssh -o ConnectTimeout=30 -T -- ghcr.io docker --host unix:///significa/app-distribution-server:sha-8732770 system dial-stdio] has exited with exit status 255, make sure the URL is valid, and Docker 18.09 or later is installed on the remote host: stderr=ssh: connect to host ghcr.io port 22: Operation timed out
```

**Comment by laurazard** [comment]
As I said:
> the CLI needs an engine to work – either an engine running locally, or you can configure your CLI to use a remote engine, such as ...

Those two lines were an example.

> From Mac OS, install only the docker CLI tools

You cannot just install the Docker CLI and expect it to work – the CLI is a **client** for the Docker **engine**, and as such needs a running Docker engine to pull images/run containers/etc. If you're on macOS, Docker Desktop can be used to set up a running Docker Engine for your CLI.

**Comment by bwomsm1** [comment]
> As I said:
> 
> > the CLI needs an engine to work – either an engine running locally, or you can configure your CLI to use a remote engine, such as ...
> 
> Those two lines were an example.
> 
> > From Mac OS, install only the docker CLI tools
> 
> You cannot just install the Docker CLI and expect it to work – the CLI is a **client** for the Docker **engine**, and as such needs a running Docker engine to pull images/run containers/etc. If you're on macOS, Docker Desktop can be used to set up a running Docker Engine for your CLI.

ok, hold on, I need to read some more. 

we can close the ticket.

**Comment by bwomsm1** [comment]
> > As I said:
> > > the CLI needs an engine to work – either an engine running locally, or you can configure your CLI to use a remote engine, such as ...
> > 
> > 
> > Those two lines were an example.
> > > From Mac OS, install only the docker CLI tools
> > 
> > 
> > You cannot just install the Docker CLI and expect it to work – the CLI is a **client** for the Docker **engine**, and as such needs a running Docker engine to pull images/run containers/etc. If you're on macOS, Docker Desktop can be used to set up a running Docker Engine for your CLI.
> 
> ok, hold on, I need to read some more.
> 
> we can close the ticket.

@laurazard is it possible to install docker engine on mac os **with docker desktop?**
