### ISSUE TITLE
User error:  ~--net=host does not provide access to the hosts netlink interface~

### ISSUE THREAD

**Issue by NiklasBeierl** [docker/cli#5576]
### Description

It appears that the `--net=host` option does not expose the hosts netlink interface to applications running inside the container.
This is extremely confusing, because some tools (like `ip`) can manage host interfaces, but those using netlink can't. 

I guess this could also be an issue with some upstream component (`moby/?`), but I wouldn't know how to figure that out.

Example use cases affected: 
- Managing the hosts firewall via `iptables` 
- Managing the hosts interfaces via libraries / tools that use netlink to communicate with the kernel, such as `pyroute2` or `wgctrl-go`

What I have tried:
- user root
- Adding `CAP_NET_ADMIN`
- `ipc=host`
- privileged
- unconfined seccomp

The reproduction I am providing is compose based, but I repeated all my experiments with `docker run` as well.

### Reproduce

```dockerfile
# Dockerfile
FROM alpine
RUN apk add iproute2 iptables bash
```
```yml
# docker-compose.yml
services:
  test-host-network:
    image: network-tooling
    build: .
    command: bash
    network_mode: host
    user: root
    ipc: host
    security_opt:
      - seccomp=unconfined
    privileged: true
    cap_add:
      - NET_ADMIN
```

1. docker compose build
2. docker compose run test-host-network (you are being dropped into a shell)
3. ip link -> shows the hosts interfaces
4. iptables -S -> shows iptables different from host

For other netlink-clients the issue might manifest differently. 

### Expected behavior

I expect to be able to manage the hosts network stack with netlink if I set `network_mode: host` on a container.

### docker version

Client:
 Version:           27.3.1
 API version:       1.47
 Go version:        go1.23.1
 Git commit:        ce1223035a
 Built:             Wed Sep 25 14:43:43 2024
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          27.3.1
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.23.1
  Git commit:       41ca978a0a
  Built:            Wed Sep 25 14:43:43 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.7.22
  GitCommit:        7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c.m
 runc:
  Version:          1.1.14
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

### docker info

Client:
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  0.17.1
    Path:     /usr/lib/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  2.29.7
    Path:     /usr/lib/docker/cli-plugins/docker-compose

Server:
 Containers: 9
  Running: 6
  Paused: 0
  Stopped: 3
 Images: 113
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c.m
 runc version:
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.11.2-arch1-1
 Operating System: Arch Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.12GiB
 Name: ANUBIS
 ID: 94d32065-1590-41fd-a4ac-b6f65867566a
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Default Address Pools:
   Base: 172.32.0.0/11, Size: 24

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

**Comment by akerouanton** [comment]
> Sorry for the noise!

No worries! Always happy to help people.

I'll close this ticket as the error isn't on our side.
