### ISSUE TITLE
Handle "docker login --username USER REGISTRY" command

### ISSUE THREAD

**Issue by jgueytat** [docker/cli#5582]
**I enter the credentials**
user:~$ docker login --username user https://registry-1.docker.io
Password: 
Login Succeeded

**Option 1 : docker login**
user:~$ docker login https://registry-1.docker.io
Authenticating with existing credentials...
Login Succeeded

**Option 2 : docker login --username**
user:~$ docker login --username user https://registry-1.docker.io
Password:

=> The Password should not be asked in that situation as the proper entry already exists in the password store.

The need is related to setup automation.

**Comment by thaJeztah** [comment]
>  had a quick peek, and I think this logic is in the docker cli itself (which decides whether to check for stored credentials, or ask for a password to verify, and store new credentials).

This line checks whether _both_ username and password are empty; https://github.com/docker/cli/blob/1875d9fdcb5562eafdc2260024948f5d7e581ccd/cli/command/registry/login.go#L100-L101

This is passed to `GetDefaultAuthConfig` as `checkCredStore`; so if _either_ password _or_ username is not-empty, it will not check the credentials store; https://github.com/docker/cli/blob/1875d9fdcb5562eafdc2260024948f5d7e581ccd/cli/command/registry.go#L73-L79

In which case we go back to the first function, which then asks the user to log in; https://github.com/docker/cli/blob/1875d9fdcb5562eafdc2260024948f5d7e581ccd/cli/command/registry/login.go#L106-L113



There's quite some complexity involved in the login code for backward-compatibility with various implementations and older versions (which used different config-file formats, but are still in use by some 3rd party implementations), so we'd have to check if there's any implications on changing thtat logic.

**Comment by thaJeztah** [comment]
cc @laurazard 

I applied both "bug" and "enhancement" labels, as I haven't verified if this behavior changed in recent versions 😂

**Comment by laurazard** [comment]
Thanks @thaJeztah, will look into it.

**Comment by jgueytat** [comment]
Hi guys, thanks a lot for checking the ticket.

The point is to get a setup for a user an unix environment in changing network situations. The point is to update proxy, server selection,... depending on the computer network location (behind the vpn, in DMZ, in the office,...). So at startup, we detect the location and then we check all the major services like git, docker,...
The "setup" will be called often.
EIther this is the first setup, and it is normal to enter again the username, otherwise this is not the first setup and only the network has changer, then we need to check the services again, but the username and password will remain the same.
This is like a sanity environment / infrastructure check.

The re-used username is stored in git configuration directly. Also there is a file stored in password store per username, so it would even make sense if two username / password were saved in the password store.

Best Regards !

**Comment by jgueytat** [comment]
```
user=$(get_user)

if [ -n "$user" ]; then
    dockerOption="--username $user"
fi

docker login $dockerOption https://registry-1.docker.io/
```

**Comment by laurazard** [comment]
I checked [`v25.0.6`](https://github.com/moby/moby/releases/tag/v25.0.6), and saw:
```console
$ docker login -u laurabrehm651]
$ cat ~/.docker/config.json
{
        "auths": {
                "https://index.docker.io/v1/": {
                        "auth": "<omitted>"
                }
        }
[...]
}
$ docker login -u laurabrehm651
Password:
}
```
Same thing if I include the registry `https://registry-1.docker.io/`:
```console
$ docker login -u laurabrehm651 https://registry-1.docker.io
Password:
WARNING! Your password will be stored unencrypted in /home/laurabrehm/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credential-stores

Login Succeeded
$ cat ~/.docker/config.json
{
        "auths": {
                "https://index.docker.io/v1/": {
                        "auth": "<omitted>"
                },
                "registry-1.docker.io": {
                        "auth": "<omitted>"
                }
        },
[...]
}
$ docker login -u laurabrehm651 https://registry-1.docker.io
Password:
```
Same thing with [`v23.0.15`](https://github.com/moby/moby/releases/tag/v23.0.15)
```console
$ docker login -u laurabrehm651 https://registry-1.docker.io
Password:
```

So it's not new behavior, which means we must be careful changing it.

**Comment by laurazard** [comment]
@jgueytat you could get around this in a few ways – you could parse `~/.docker/config.json` before attempting to log in and check if it already has credentials configured:
```console
$ jq '.auths."registry-1.docker.io".auth' ~/.docker/config.json
"<omitted>"
```

**Comment by jgueytat** [comment]
**This is the content i have for the config file :**
```
{
        "auths": {
                "registry-1.docker.io": {}
        },
        "credsStore": "pass"
}
```

**And this is the content of the password store :**

![Image](https://github.com/user-attachments/assets/c52e48b3-9007-4e29-9304-c397d20fe97a)

It seems here the docker login would pick one random user credential.
We also need to check if the token for a specific user is still good at each startup.

As of now, I will simply not precise the username. So if its credentials are already good and there is only a single one for this registry, this will be ok. If he provides the username, and there is no credential yet, he will just don't understand why he has to provide his username again.

**Comment by laurazard** [comment]
> It seems here the docker login would pick one random user credential.

Not sure what you mean for this. Right now (I'd love to change this but we'll have to consider how to do it/what it would look like) the docker CLI only supports configuring one set of credentials per registry.

When you are using a credential helper (configured by the `credsStore` key in your `config.json`), and you do a `docker login` to store credentials, then the CLI will create an entry for it inside the `auths` field in `config.json` (to store the user's email, if used) and then store the actual secret in the credential helper (as you can see from running `pass ls`.

**Comment by laurazard** [comment]
In either case, we'd love to make some improvements in this area! Make sure to stay tuned/open an issue if you've feedback to give about eventual enhancements. I'll close this one for now.
