### ISSUE TITLE
in dockerswarm mode, the service cannot get the client's real IP

### ISSUE THREAD

**Issue by 175222277** [docker/cli#5587]
### Description

When I deploy the springboot program using dockerswarm mode, I try to get the user client IP in the request. No matter what the client IP is, it returns 10.0.0.2. This is not the real client IP. It seems to be the IP of the ingress network.

### Reproduce

request.getRemoteAddr();

### docker version

Client:
 Version:           25.0.5
 API version:       1.44
 Go version:        go1.21.8
 Git commit:        5dc9bcc
 Built:             Tue Mar 19 15:04:17 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          25.0.5
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.8
  Git commit:       e63daec
  Built:            Tue Mar 19 15:05:39 2024
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.7.13
  GitCommit:        7c3aca7a610df76212171d200ca3811ff6096eb8
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

### docker info

Client:
 Version:    25.0.5
 Context:    default
 Debug Mode: false

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 6
 Server Version: 25.0.5
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7c3aca7a610df76212171d200ca3811ff6096eb8
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 4.18.0-348.el8.x86_64
 Operating System: CentOS Linux 8
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.586GiB
 Name: 192.168.2.112
 ID: 76177108-ce6d-4f48-a946-da3b9330389f
 Docker Root Dir: /data/docker
 Debug Mode: false
 HTTP Proxy: http://192.168.2.63:10809/
 HTTPS Proxy: http://192.168.2.63:10809/
 No Proxy: localhost,127.0.0.1,.example.com
 Experimental: true
 Insecure Registries:
  192.168.2.130
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

**Comment by thaJeztah** [comment]
Thanks for reporting; this is not an issue related the the CLI itself, but the daemon, and there's some existing tickets related to this (which may contain more information);

- https://github.com/moby/moby/issues/15086


I'm closing this ticket because of the above, but you can follow the linked ticket (and it contains links to, and is linked to various other tickets that may be related).
