### ISSUE TITLE
support `max-chunk-length` for push imge

### ISSUE THREAD

**Issue by harris2012** [docker/cli#5589]
### Description

considering someone is pushing a very large image like 2G. 

Without the `max-chunk-length`.
any little network failure will let him patch whole image from 0%.

With the `max-chunk-length`.
He can patch the image every 30M. When networkle failure at 40%, he will continue to retry from 40%.

`distribution-spec` support the `POST/PATCH/PUT` method to push chunked image. if docker-cli support this, will be very useful.

**Comment by laurazard** [comment]
Hi @harris2012, thanks for the report.

The Docker CLI is only a client for the Docker Engine ([moby/moby](https://github.com/moby/moby/)), so this ticket is better suited for that repository. If the engine implements support for this feature, we'll make it available in the CLI.

Other than that though, there's an open issue in `distribution/distribution` to implement support for setting max chunk length when pushing – https://github.com/distribution/distribution/pull/4144. While the impetus there is to support registries hinting the client as to what max chunk length to use, we'd likely want to see that discussion/implementation resolved before implementing support for this in the engine. There's ongoing discussion related to this in `distribution-spec` (here's a proposal – https://github.com/opencontainers/distribution-spec/issues/485).

I'll close this for now, but feel free to open a ticket related to this in [moby/moby](https://github.com/moby/moby/) if you'd like to continue the discussion.
