### ISSUE TITLE
Not able to pull latest docker images

### ISSUE THREAD

**Issue by meetatmoe** [docker/cli#5694]
### Description

So, I'm trying to pull docker:latest, docker:cli on arm, amd but it throws manifest not found. But with older version, it seems to be working.

This seems to be happening with latest pushed images; sharing the ref 

<img width="1419" alt="Image" src="https://github.com/user-attachments/assets/f48b3f03-201d-4e3c-8470-ce100af17f57" />

### Reproduce

1. docker pull docker:latest
2. docker pull docker:cli

### Expected behavior

It will throw, manifest not found.

<img width="647" alt="Image" src="https://github.com/user-attachments/assets/8a959f95-047c-45c6-8467-d0553ae3f679" />

### docker version

```bash
Client:
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.18.6
 Git commit:        100c701
 Built:             Sat Dec  3 04:13:49 2022
 OS/Arch:           linux/arm64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.6
  Git commit:       a89b842
  Built:            Sat Dec  3 04:14:28 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        5fd4c4d144137e991c4acebb2146ab1483a97925
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false

Server:
 Containers: 5
  Running: 3
  Paused: 0
  Stopped: 2
 Images: 19
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc version: 5fd4c4d144137e991c4acebb2146ab1483a97925
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.157-139.675.amzn2.aarch64
 Operating System: Amazon Linux 2
 OSType: linux
 Architecture: aarch64
 CPUs: 2
 Total Memory: 3.665GiB
 Name: ip-172-31-38-205.ec2.internal
 ID: PXBI:RVT2:3ICC:YY6A:OZBR:X2DO:ZSAQ:T5GS:OFWT:4ORM:OFGN:VKAD
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
This is not an issue that can be fixed in this repository though, but to be handled through the issue tracker for the official images; I see there's already been tickets opened;

- https://github.com/docker-library/docker/issues/519
- https://github.com/docker-library/docker/issues/520

**Comment by meetatmoe** [comment]
Okie, since it is already opened; closing this issue

**Comment by thaJeztah** [comment]
Thanks! And thanks for reporting; I'm also trying our internal slack to see if someone is online that may have insight / access to more information

**Comment by thaJeztah** [comment]
The `docker:dind` and `docker:latest` images should now work again; things may be rolling out still for other tags.

**Comment by thaJeztah** [comment]
Update on this issue; a colleague confirmed that the list of official images should be all processed. The verification script will still be running for some hours, but we're updating the statuspage to "monitoring"

There may be some images in the platform-specific orgs that are used as intermediate image that may not yet be addressed, and (given much lower / corner-case use), e.g. images in the platrform-specific namespace (e.g. https://hub.docker.com/u/arm64v8/, and other similar namespaces listed in; https://github.com/docker-library/official-images#architectures-other-than-amd64. Those namespaces are effectively intermediate stages for the multi-platform images. These images will likely be processed later, which may be done after the weekend.
