### ISSUE TITLE
Vendor Usage

### ISSUE THREAD

**Issue by vito-c** [docker/cli#57]
Hello,
I originally had a application that was using `github.com/docker/docker/cli/command` to create a DockerCli and then handle login to the private docker registry by creating a types.AuthConfig struct and passing it to `dockerCli.CredentialsStore(authConfig.ServerAddress).Store(authConfig)` but now that you have changed the types.AuthConfig to a vendor instead I am no longer able to utilize the `dockerCli.CredentialsStore` is there something I'm doing wrong?

**Comment by dnephin** [comment]
If you're using `docker/cli` as a package you have to make sure to remove `docker/cli/vendor` so that the canonical `api/types` is used and not the vendored copy.

**Comment by cpuguy83** [comment]
Is this good to close?

**Comment by vito-c** [comment]
how can I add the docker/cli to my vendor dir then? I'm getting type mismatches now with my vendored docker stuff

**Comment by cpuguy83** [comment]
You must remove all nested vendors.

**Comment by dnephin** [comment]
Some dependency management tools will do this for you. I know https://github.com/Masterminds/glide does this.
