### ISSUE TITLE
Proposal: docker stop should allow you to specify which initial signal to use, instead of always using SIGTERM

### ISSUE THREAD

**Issue by alecbz** [docker/cli#583]
`docker stop my_container` sends `SIGTERM` to `my_container`, waits an amount of time configured by the `--time` flag, and, if the container hasn't stopped, sends `SIGKILL` to the container.

It'd be nice to have options to configure what initial signal is used. E.g., `docker stop --signal=INT my_container` will instead send `SIGINT` to `my_container`, wait 10 seconds, and then send `SIGKILL`.

**Comment by dnephin** [comment]
`docker kill` does support a signal, but doesn't have the timeout flag

**Comment by AlecBenzer** [comment]
@dnephin Yeah, I'm aware, but if you need timeout functionality what can you do? `docker wait` doesn't support a timeout (https://github.com/docker/cli/issues/582), but even if it did, it feels like a kind of cumbersome workflow to re-implement the "stop gracefully with a timeout to a hard-kill" workflow just to use a different graceful stop signal.

**Comment by AlecBenzer** [comment]
Ah, just learned about [`STOPSIGNAL`](https://docs.docker.com/engine/reference/builder/#stopsignal) and `docker run --stop-signal`, which can be used to control `docker stop`'s behavior. I think it's still useful to be able to control this from `docker stop` itself, but having these other knobs makes it much less necessary.

**Comment by thaJeztah** [comment]
Yes, I think the original thinking behind having the `--stop-signal` on start, and inside the Dockerfile is that stopping the container would automatically use the correct signal for the container. This would be a "nice to have" but not really necessary.

**Comment by thaJeztah** [comment]
This was implemented in https://github.com/docker/cli/pull/3614, which is part of the upcoming v23.0.0 release
