### ISSUE TITLE
show output on docker unpause

### ISSUE THREAD

**Issue by johndmulhausen** [docker/cli#589]
@surajnarwade commented on [Thu Apr 20 2017](https://github.com/docker/docker.github.io/issues/2951)

### Problem location

https://docs.docker.com/engine/reference/commandline/unpause/

- I saw a problem on the following URL: <URL>

- I couldn't find the information I wanted. I expected to find it near the following URL: <URL>

- Other: <DETAILS>

### Suggestions for a fix

as `$ docker unpause my_container` is written as command, we should show its output also

---

@surajnarwade commented on [Thu Apr 20 2017](https://github.com/docker/docker.github.io/issues/2951#issuecomment-295690901)

@londoncalling @johndmulhausen thoughts, hackathon :)

---

@johndmulhausen commented on [Thu Apr 20 2017](https://github.com/docker/docker.github.io/issues/2951#issuecomment-295717325)

Hey @surajnarwade -- quick note, only bugs that we have labeled "hackathon" count towards the hackathon. You are free to file bugs and PRs, though. :)

---

@surajnarwade commented on [Thu Apr 20 2017](https://github.com/docker/docker.github.io/issues/2951#issuecomment-295718055)

@johndmulhausen , no  worries :)

**Comment by jadametz** [comment]
Hey guys, I'm going to take a crack at this one. If I'm over simplifying let me know, but after just trying this on my laptop, the output is simply the container name...

```bash
$ docker unpause my_container
my_container
```

Anyway, PR on the way!
