### ISSUE TITLE
dockerd configuration reloading section missing options that get reloaded

### ISSUE THREAD

**Issue by johndmulhausen** [docker/cli#590]
@edmorley commented on [Mon Jul 10 2017](https://github.com/docker/docker.github.io/issues/3854)

File: [engine/reference/commandline/dockerd.md](https://docs.docker.com/engine/reference/commandline/dockerd/), CC @mstanleyjones 

Hi!

The configuration reloading section here lists which prefs are reloaded when the dockerd process receives a `SIGHUP`:
https://docs.docker.com/engine/reference/commandline/dockerd/#configuration-reloading

However it appears there are a few entries missing from that list, such as:
* Daemon shutdown timeout 
* Insecure registries
* Registry mirrors

For the full list of settings that get reloaded, see:
https://github.com/moby/moby/blob/master/daemon/reload.go

Many thanks!

**Comment by thaJeztah** [comment]
Looks like `registry-mirrors` and `insecure-registries` are  documented now in https://github.com/docker/cli/blob/master/docs/reference/commandline/dockerd.md, only `shutdown-timeout` is missing

**Comment by mstanleyjones** [comment]
@gbarr01 can you tackle this one?
