### ISSUE TITLE
cap-add=ALL not the same as privileged=true

### ISSUE THREAD

**Issue by hpresnall** [docker/cli#597]
**Description**
For chaos/resiliency testing, I am trying to create a container that can kill a host OS process.

If I run `docker run --rm -it --pid=host --cap-add=ALL alpine:latest /bin/sh`, calling `ps` does list all the host processes. However, when I try and kill a process, I get permission denied.

In order for this to work, I have to run with `--privileged=true`.

**Steps to reproduce the issue:**
1. docker run --rm -it --pid=host --cap-add=ALL alpine:latest /bin/sh
2. ps -aef inside the container
3. kill `<pid>`

**Describe the results you received:**
Kill returns a permission denied error.

**Describe the results you expected:**
What is `--privileged=true` doing that `--cap-add=ALL` does not? I would expect these settings to be equivalent.
If they are not, this should be documented in the man for Docker run.

**Output of `docker version`:**
```
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:00:17 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:11 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**
```
Containers: 10
 Running: 10
 Paused: 0
 Stopped: 0
Images: 25
Server Version: 17.06.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-89-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.36GiB
Name: <hidden>
ID: ED3L:FI2I:BTG5:SI44:VR4S:P5D3:GWBK:TONY:DS2I:PTQB:K7D6:IO3H
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 10.140.132.215:5001
 <hidden>
 127.0.0.0/8
Live Restore Enabled: true
```

**Comment by dnephin** [comment]
They are not the same, some docs are here: https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities

**Comment by hpresnall** [comment]
Ok I missed this in the docs. Guess I do have to use privileged.
