### ISSUE TITLE
Nesting a volume inside a read-only volume produces an error

### ISSUE THREAD

**Issue by idlsoft** [docker/cli#622]
It's not a typical use-case, but I need to have a read-write directory inside a read-only one.
Something like
```
work
+--out
```
where only `out` will be read-write.
I specify 2 mappings one for `/work` and one for `/work/out` , but docker fails to start a container unless the `work` mapping already has an out subdirectory.

Here is a a little bash script to reproduce the problem:

```bash
#!/bin/bash

[ -e work ] && rm -rf work

mkdir -p work/out
mkdir -p work/root1/out
mkdir -p work/root2


# this works
docker run -t -v $PWD/work/root1:/work:ro -v $PWD/work/out:/work/out busybox touch /work/out/t1.txt
exit_code1=$?
# this fails
docker run -t -v $PWD/work/root2:/work:ro -v $PWD/work/out:/work/out busybox touch /work/out/t2.txt
exit_code2=$?

echo -e "\nExit codes: $exit_code1, $exit_code2, files: $(ls -1 work/out)"
```

**Comment by dnephin** [comment]
This is unlikely a problem with the CLI. I would suggest you open an issue at https://github.com/docker/for-linux or upstream at https://github.com/moby/moby. Please also include the error message.

**Comment by idlsoft** [comment]
Done, thx
