### ISSUE TITLE
Error running make build

### ISSUE THREAD

**Issue by ehazlett** [docker/cli#63]
Upon a fresh clone, I get 
`./scripts/build/binary: 3: ./scripts/build/binary: source: not found` trying to `make build`.  Perhaps we should default to build in the container?

OS: Debian Sid
Kernel: 4.10.1
Shell: bash

**Comment by dnephin** [comment]
We need to document this, the "container" targets are in `docker.Makefile`, 

Try:
```
make -f docker.Makefile build
```

We kept the two makefiles separate because they have very different responsibilities. By keeping them separate we may be able to replace one of them easily when a better tool is available.

**Comment by dnephin** [comment]
We've updated the Makefile, and #99 covers other improvements, so going to close this issue.
