### ISSUE TITLE
Create config files from a directory

### ISSUE THREAD

**Issue by moncho** [docker/cli#634]
This adds support to the docker config subcommand to allow creating **config** files for every file found on a directory, if a directory is given to the subcommand.

If a directory is given, config names will be taken from the file names.  Existing limitations for config names still apply (invalid characters, length). 

E.g.
``` 
.
|_ my-conf-dir
     |_ foo.txt
     |_ bar.yaml
```

To create configs: 
```
$ docker config create my-conf-dir

gsggkx171uuv9fm2de4bxhh18
ubltrg4eqy97pdqkhm8x7c8vz
```
Checking the result:
```
$ docker config ls

ID                          NAME          CREATED            UPDATED
gsggkx171uuv9fm2de4bxhh18   foo.txt       2 minutes ago      2 minutes ago
ubltrg4eqy97pdqkhm8x7c8vz   bar.yaml      2 minutes ago      2 minutes ago
```
PR will soon follow.

**Comment by dnephin** [comment]
Please provide some additional information about why you believe this feature needs to be part of the Docker cli.

**Comment by moncho** [comment]
Sure. I think it is not uncommon having to create a few configuration files as part of your Swarm setup. In my experience, these files are typically stored together at the origin, downloaded locally and then iterated somehow (e.g. bash loop) running `docker config create` for each file. 

This feature does the iteration and the `docker config create` invocation on the CLI, easing the config creation process. Not a big functional change, but I find it useful and it does not break existing behavior.

**Comment by moncho** [comment]
Closing the issue, see #635.
