### ISSUE TITLE
Add CheckRedirect for GO 1.8

### ISSUE THREAD

**Issue by dnephin** [docker/cli#64]
We need to make sure that we get the fix from https://github.com/moby/moby/issues/32127 if we want to build the client with GO 1.8.

The changes in that PR will not affect the cli because a client is created in `cli/command/cli.go`, so we need to use the `CheckRedirect` function from that PR where we create the client.

**Comment by dnephin** [comment]
The referenced PR was merged so we can now make this change.

**Comment by ripcurld0** [comment]
@dnephin does that make sense if I call #dibs on that?

**Comment by dnephin** [comment]
That would be great, thank you!

**Comment by ripcurld0** [comment]
@dnephin it seems like https://github.com/moby/moby/pull/32127 was added in https://github.com/docker/cli/pull/45 so I think we can close this.

I built this on my computer and `CheckRedirect` works.

**Comment by dnephin** [comment]
This repo doesn't use the code from moby/moby to create an `http.Client`. I'll open a PR, it should be small.
