### ISSUE TITLE
Notary repo moving

### ISSUE THREAD

**Issue by endophage** [docker/cli#643]
With acceptance of Notary in to CNCF, it is moving to a new home. Going forward it will live at `GitHub.com/theupdateframework/notary` and all imports and vendoring should be updated to reflect that new location.

The repo will be moved using GH's tools so a redirect will be in place allowing the old location to continue working, but people vendoring for example, docker cli _and_ notary directly may run in to issues, so the imports should be updated ASAP.

I will be moving notary in the next 48 hours and I'm happy to take on the task of updating this repo to reflect the new location.

**Comment by thaJeztah** [comment]
opened https://github.com/docker/cli/pull/652
