### ISSUE TITLE
"dockercli -SwitchDaemon" doesn't reflect in the settings UI

### ISSUE THREAD

**Issue by haniamr** [docker/cli#656]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**Description**
If I run `dockercli -SwitchDaemon` in order to switch Docker from Windows to Linux, the UI still thinks it's on Windows containers and doesn't show Linux-specific settings (i.e. Shared drives)

**Steps to reproduce the issue:**
1. Make sure Docker is using Windows containers
2. Run `dockercli -SwitchDaemon`
3. Open Docker settings

**Describe the results you received:**
Linux-specific settings are not visible (i.e. Shared drives, Advanced, Network, etc.)

**Describe the results you expected:**
The UI should reflect to the correct mode if switching via the command line

**Output of `docker version`:**

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:50:27 2017
 OS/Arch:      windows/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 10
Server Version: 17.09.0-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 15063 (15063.0.amd64fre.rs2_release.170317-1834)
Operating System: Windows 10 Enterprise
OSType: windows
Architecture: x86_64
CPUs: 12
Total Memory: 11.72GiB
Name: haniamr-dd
ID: VKX7:TIEF:FEKC:UDQZ:F2GF:V7KL:T64I:Y4FI:O37P:QONK:ADVQ:6EMW
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 23
 System Time: 2017-10-30T11:09:06.4061186-07:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
This looks to be an issue for the Docker for Windows UI; can you reopen this in https://github.com/docker/for-win/issues so that it gets the attention from the people maintaining that?

I'll close the issue here, but thanks for reporting, and feel free to comment after I closed

**Comment by haniamr** [comment]
Thanks for the quick response, will do that!

**Comment by thaJeztah** [comment]
Thank you!
