### ISSUE TITLE
Docker Image / Container Prune using 2 or more filter attributes

### ISSUE THREAD

**Issue by HariSekhon** [docker/cli#669]
I'm using docker image and container prune and cannot see a way in the docs of filtering on more than one attribute at the same time. Eg. I can filter on repository or time but it's not clear from the documentation if there is any way to filter on both at the same time.

What I'm trying to do is remove old containers and images but only for certain images older than X days. I can script my way around this but it would be nice if the `--filter` argument can handle it.

If this can't currently be done, please consider this a feature request.

If there is a way to do this then can this be considered a documentation request, eg:

https://docs.docker.com/engine/reference/commandline/container_prune/#filtering

**Comment by dnephin** [comment]
The first line from that section:

>  If there is more than one filter, then pass multiple flags  (e.g., --filter "foo=bar" --filter "bif=baz")

Seems to me like it is documented.

**Comment by HariSekhon** [comment]
Sorry I missed that, been a long day, I think my eyes were scanning for expessions rather than multiple swithces, closing.
