### ISSUE TITLE
[feat] docker volume prune

### ISSUE THREAD

**Issue by Leryan** [docker/cli#675]
**Description**

When using `docker volume prune`, we're asked to confirm if we really want to remove unused volumes, but those that will be deleted are now displayed.

When using `docker-compose` volumes have readable names and are useful.

So the feature idea is the following: have a command that will list prune-able volumes.

**Comment by Leryan** [comment]
Just got the idea to search for `docker volume ls` help…

The command:

```
docker volume ls -f "dangling=true"
```

**Comment by thaJeztah** [comment]
Also see https://github.com/moby/moby/issues/30623
