### ISSUE TITLE
Enhancement: builder: support progress report when no TTY is available.

### ISSUE THREAD

**Issue by erikhakansson** [docker/cli#688]
Currently, Docker build suppresses progress output when running in a script, e.g. when triggered from Maven.
This is sane since otherwise the output would be garbled and weird.

However, it would be nice to have at least SOME output.

For example, I several times per day build a docker image with a build context of about 2 gigabytes. When building manually, I get a progress report for the "Sending build context..." part, but when running through Maven (which will automatically supply relevant --build-args) I get no output at all until the context is sent.

It would be nice to have at least something, like an output every 5% or so.
The same goes for docker pull and any other progress report.

Thanks!

**Comment by erikhakansson** [comment]
@thaJeztah do you know if this will be looked at? I'd be happy to contribute myself but I'm not very comfortable with golang so I'm not sure if that's such a good idea 😄

**Comment by thaJeztah** [comment]
> It would be nice to have at least something, like an output every 5% or so.

It should probably be time-limited; for things that go fast, it's fine to just show a "completed" message (and not 20 lines of progress), whereas if things take long, progress output could be useful (also see https://github.com/docker/swarmkit/pull/1352).

I'm not sure we should automatically enable this; _not_ showing progress was a feature requested by many (admittedly; mostly because the progress was _too_ noisy in CI / scripts; see https://github.com/moby/moby/issues/3694)

The other day, I noticed this in the help output for `apk` (alpine package manager);

```
  --progress              Show a progress bar
  --progress-fd FD        Write progress to fd
  --no-progress           Disable progress bar even for TTYs
```

Three separate flags is a bit over the top likely, but posting it for discussion.

Alternatively, we could decide to make this a configuration-file only option (i.e., not a flag for each command that show progress-bars, but have an option in `~/.docker/config.json` that allows configuring the behaviour (`enabled | disabled | interactive-only`)

Also see https://github.com/docker/cli/pull/553, which adds a `--quiet` option to `docker pull`

ping @dnephin @vdemeester any thoughts?

**Comment by erikhakansson** [comment]
@thaJeztah both those alternatives sound nice for me. I agree that it shouldn't be enabled by default. 

Apart from that, I would be very happy with either a flag per command or a global config. I can imagine some people might want the extra control per command, especially if they don't have full control over the environment a script/CI is run in, but for our use case either is fine!

**Comment by gabor-boros** [comment]
@GordonTheTurtle @thaJeztah Is there any update on this topic?

**Comment by thaJeztah** [comment]
@gabor-boros yes, there's progress; when using the (experimental) BuildKit builder in Docker 18.06, you can set the `--console` option to `auto` (detect if a console is present), `true` (print "human-friendly" redraw/update output), and `false` (print progress summary) 

Also see https://github.com/moby/buildkit/pull/504


Default (auto) or "true" (as I'm running in an interactive terminal);

```bash
export DOCKER_BUILDKIT=1

docker build .
[+] Building 2.0s (2/2) FINISHED                                                                                                                                                                                                                                                     
 => local://context (.dockerignore)                                                                                                                                                                                                                                             0.0s
 => => transferring context: 142B                                                                                                                                                                                                                                               0.0s
 => local://dockerfile (Dockerfile)                                                                                                                                                                                                                                             0.0s
 => => transferring dockerfile: 9.26kB         
  =>local://context                                                                                                                                                                                                                                                    0.8s
 => => transferring context: 35.40MB                                                                                                                                                                                                                                            0.8s
 => docker-image://docker.io/tonistiigi/copy:v0.1.3@sha256:e57a3b4d6240f55bac26b655d2cfb751f8b9412d6f7bb1f787e946391fb4b21b                                                                                                                                            0.7s
 => => resolve docker.io/tonistiigi/copy:v0.1.3@sha256:e57a3b4d6240f55bac26b655d2cfb751f8b9412d6f7bb1f787e946391fb4b21b                                                                                                                                                         0.1s
 => => sha256:f5fd20edad0c69902cf702c6b080bcfac264c392f71871eccd39a5f171b01149 00B / 751.94kB                                                                                                                                                                                   0.7s
 => => sha256:7b75ca719cf195ac5ed9863efe1e677c4ed7a0b87db3e2f5daf895f9f84340d8 00B / 172.86kB                                                                                                                                                                                   0.7s
 => => sha256:58370f0d30e03a5cd4641c95b7e02d2983d1ebf3d6b34f7051d690b9b8512cb6 00B / 70.72kB     
```

Setting `--console=false`;


```bash
export DOCKER_BUILDKIT=1

docker build --console=false .

#1 local://context (.dockerignore)
#1       digest: sha256:5def64dec3dda2b0e68e42f4c7b3d9da618cd14c4f60a6a579a6215910c4141d
#1         name: "local://context (.dockerignore)"
#1      started: 2018-07-31 12:28:35.891052244 +0000 UTC
#1    completed: 2018-07-31 12:28:35.89110343 +0000 UTC
#1     duration: 51.186µs
#1      started: 2018-07-31 12:28:35.891894235 +0000 UTC
#1    completed: 2018-07-31 12:28:35.919628797 +0000 UTC
#1     duration: 27.734562ms
#1 transferring context: 142B done


#2 local://dockerfile (Dockerfile)
#2       digest: sha256:4f0e1c50eede6e25a61fcbb8fe0e70e97950564f42bc1c0405a375861214eec6
#2         name: "local://dockerfile (Dockerfile)"
#2      started: 2018-07-31 12:28:35.889300211 +0000 UTC
#2    completed: 2018-07-31 12:28:35.923366713 +0000 UTC
#2     duration: 34.066502ms
#2 transferring dockerfile: 9.26kB 0.0s done
```

**Comment by thaJeztah** [comment]
With BuildKit no longer being experimental (but still opt-in), I think we can close this one. I don't think there will be plans to backport this feature for the classic builder, but when using buildkit, this feature should be available 👍
