### ISSUE TITLE
Proposal: docker run return custom parameters

### ISSUE THREAD

**Issue by sumerc** [docker/cli#690]
How about being able to query some information of the container with _run_ command instead of calling _inspect_ after _run_ which requires multiple API calls? As an example:

```
> docker run -itd --query_param="NetworkSettings:Ports:HostPort" 
{"container_id": XXXX, "NetworkSettings:Ports:HostPort":32456}
```

I can see some use cases around this, such as retrieving IP address/port or any other dynamically allocated resource on the container.

**Comment by thaJeztah** [comment]
Hm, I'd be "-1" on this; the CLI would still have to make the API call to actually inspect the container, and the `--query_param=` option would basically mean we'd be re-implementing the `--format` option that's on `docker inspect`.

Given that there's already a workable solution (`docker inspect` after the container was created), I don't think we should overload `docker run` with even more options.

**Comment by sumerc** [comment]
Fair enough. I thought there might be some kind of way of preventing double work to retrieve some basic info like this at _run_ time without too much effort. 

Thanks for the answer.

**Comment by thaJeztah** [comment]
closing as stale
