### ISSUE TITLE
add support for volume quota's

### ISSUE THREAD

**Issue by xenoterracide** [docker/cli#725]
what I'd like to be able to do mount a large disk for `/var/lib/docker/volume` and then give the "docker volumes" a quota, e.g. this mounted volume is only allowed to use 2G of space, out of 100G, this is to avoid out of space issues. Of course I'd want this to trickle down to swarm, service, compose, and stack (especially being aware of whether the node has enough space) and whatever.

**Comment by dnephin** [comment]
This sounds like a feature request that would need to be implemented primarily in the engine. It's probably a better idea to open this issue in https://github.com/docker/for-linux/issues

**Comment by dnephin** [comment]
Replaced by https://github.com/docker/for-linux/issues/178
