### ISSUE TITLE
Dockerfile from stdin breaks build caching

### ISSUE THREAD

**Issue by opatut** [docker/cli#731]
**Steps to reproduce the issue:**
1. Use `docker build -f -` to read Dockerfile contents from stdin (e.g. generated)  
  (The dockerfile contains something like `ADD . /foo`)
2. Do the same thing again.

**Describe the results you received:**
* no cache hits

**Describe the results you expected:**
* cache hits second time

**Additional information you deem important (e.g. issue happens only occasionally):**

I think I [found the problem](https://github.com/docker/cli/blob/0b050a599f04d8401c04493f9c7f787b74fd6511/cli/command/image/build/context.go#L352). The docker file from stdin is added under a random name to the context, which changes on every run. That filename is added to .dockerignore, so its contents change on every run, too. That way, **unless** `.dockerignore` contains itself (yes, that works, it is still sent to the context and used but skipped in ADD/COPY instructions), the context is different, and instructions like `ADD . /foo` do not hit the cache.

**Possible solutions:**

1. use the same name for the generated dockerfile every time (i.e. something very random that *probably* won't collide, but is static), or
2. automatically add `.dockerignore` to the `.dockerignore` (might be unexpected by users, and is technically different behaviour, but who needs the .dockerignore inside the image anyway?)
3. hash the Dockerfile contents (from stdin) to generate the filename (not the same caching behaviour as with a normal Dockerfile, since the build cache hashes are created from the actual parsed instructions, not the full file content!)
4. Just warn the user if `.dockerignore` does not contain itself and `-f -` is used, so they know how to work around this issue if they need the cache.

I think I'd prefer (1). It's just an implementation detail which name is used anyway, and not public API. The only breakage this might create is people (*ab*)using the current behaviour instead of using `--no-cache`, but I would [consider it a bugfix](https://xkcd.com/1172/) anyway.

**Output of `docker version`:**

```
Client:
 Version:      17.10.0-ce
 API version:  1.33
 Go version:   go1.9.2
 Git commit:   f4ffd2511c
 Built:        Sun Nov 19 18:46:29 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.10.0-ce
 API version:  1.33 (minimum version 1.12)
 Go version:   go1.9.2
 Git commit:   f4ffd2511c
 Built:        Sun Nov 19 18:46:37 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 16
 Running: 7
 Paused: 0
 Stopped: 9
Images: 420
Server Version: 17.10.0-ce
Storage Driver: devicemapper
 Pool Name: docker-254:0-7733276-pool
 Pool Blocksize: 65.54kB
 Base Device Size: 10.74GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 25.33GB
 Data Space Total: 107.4GB
 Data Space Available: 79.64GB
 Metadata Space Used: 52.04MB
 Metadata Space Total: 2.147GB
 Metadata Space Available: 2.095GB
 Thin Pool Minimum Free Space: 10.74GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.145 (2017-11-03)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 0351df1c5a66838d0c392b4ac4cf9450de844e2d
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.14.3-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.58GiB
Name: vanilla
ID: Y4Y7:WN4C:RABW:O7KK:MI4S:2JU5:YTRO:FNWD:T6CN:PLWB:6CI3:RJV5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
```

**Comment by dnephin** [comment]
We do (2) if `.dockerignore` doesn't already exist in the context, but if the file does exist then we don't want to ignore it.

I like option 1, it really doesn't need to be random.

This would be a lot easier if the `build` API accepted the `.dockerignore` and `Dockerfile` as separate fields, instead of as part of the tar context. Personally I think that would be a much better API.

cc @tonistiigi

**Comment by thaJeztah** [comment]
> This would be a lot easier if the build API accepted the .dockerignore and Dockerfile as separate fields, instead of as part of the tar context. Personally I think that would be a much better API.

Yes, definitely +1 on that; that option was discussed a couple of times in the past (also makes docker content trust easier IIRC, as it currently has to rewrite the Dockerfile, and inject the rewritten version into the build context)

**Comment by tonistiigi** [comment]
> This would be a lot easier if the build API accepted the .dockerignore and Dockerfile as separate fields, instead of as part of the tar context. Personally I think that would be a much better API.

That API already exists

```
 # ls -la
total 12
drwxr-xr-x    2 root     root          4096 Dec  5 18:01 .
drwxr-xr-x    3 root     root          4096 Dec  5 18:00 ..
-rw-r--r--    1 root     root             4 Dec  5 18:01 .dockerignore
-rw-r--r--    1 root     root             0 Dec  5 18:01 baz
 # docker build --stream -f -  . < ../Dockerfile
Streaming build context to Docker daemon      60B
Step 1/3 : from alpine
latest: Pulling from library/alpine
2fdfe1cd78c2: Pull complete
Digest: sha256:ccba511b1d6b5f1d83825a94f9d5b05528db456d9cf14a1ea1db892c939cda64
Status: Downloaded newer image for alpine:latest
 ---> e21c333399e0
Step 2/3 : add . /foo
 ---> 938a14bbf488
Step 3/3 : run ls -la /foo
 ---> Running in 1ef53dd7f862
total 12
drwxr-xr-x    2 root     root          4096 Dec  5 18:03 .
drwxr-xr-x    1 root     root          4096 Dec  5 18:03 ..
-rw-r--r--    1 root     root             4 Dec  5 18:01 .dockerignore
-rw-r--r--    1 root     root             0 Dec  5 18:01 baz
Removing intermediate container 1ef53dd7f862
 ---> a121cd349771
Successfully built a121cd349771
 #
 # docker build --stream -f -  . < ../Dockerfile
Streaming build context to Docker daemon      52B
Step 1/3 : from alpine
 ---> e21c333399e0
Step 2/3 : add . /foo
 ---> Using cache
 ---> 938a14bbf488
Step 3/3 : run ls -la /foo
 ---> Using cache
 ---> a121cd349771
Successfully built a121cd349771
```

**Comment by opatut** [comment]
Ok can you explain what's going on? If see you're using `--stream`, but I cannot find any documentation on it (e.g in man page or `--help` output). What does it do?

**Comment by sam-thibault** [comment]
This is an old issue.  I will close it as stale.  note that --stream was deprecated: https://docs.docker.com/engine/deprecated/#docker-build---stream-flag-experimental
