### ISSUE TITLE
add --chown flag to docs for COPY and ADD

### ISSUE THREAD

**Issue by johndmulhausen** [docker/cli#738]
@metalivedev commented on [Mon Dec 04 2017](https://github.com/docker/docker.github.io/issues/5441)

File: [engine/reference/builder.md](https://docs.docker.com/engine/reference/builder/), CC @mistyhacks 

Per https://github.com/moby/moby/issues/6119#issuecomment-338920866 `ADD` and `COPY` now support `--chown`. Please add these to the main documentation.

**Comment by thaJeztah** [comment]
Docs were added in PR https://github.com/docker/cli/pull/467, and (with some delay :blush:) merged
