### ISSUE TITLE
Rebuild command line option

### ISSUE THREAD

**Issue by justyntemme** [docker/cli#766]
This is a feature request. I am a linux go-lang developer and would be happy to work on this if deemed acceptable.

Currently to rebuild and delete an existing image with the same name you must
`docker images`
`docker rmi image-name`
`docker build . -t image-name`

If you skip deleting the old image, it becomes an image without a tag. A rebuild option could simply automate this process and delete the existing image before building the new image, or vice versa.

**Comment by justyntemme** [comment]
After further thought, this could simply become a flag to build. I believe -d and -r are taken, something else could be thought of. This flag could simply tell docker to remove any image with the same name before building.

**Comment by thaJeztah** [comment]
removing the image before building also (potentially) removes the build cache; could you describe the use case a bit more?

**Comment by justyntemme** [comment]
Sure, perhaps the container could be removed after the build command by grabbing it's ID first. Then building the new container, then removing the old one by the container ID rather than the label.

I use docker on cloud instances for developing projects, as well as hosting them. Every few weeks have to go and delete all of the un-labeled containers as they start taking up quite a bit of space on a limited cloud server.

I see two possible solutions. There could be an option to delete all un-labeled container, although some times containers in production are not always labeled. Which brings me to my proposed solution of adding a -d (if d is not taken) flag to tell docker to remove the old container after re-building.

**Comment by thaJeztah** [comment]
The `docker system prune` command (and related commands, such as `docker image prune`, `docker container prune`) was created for this purpose, and allows you to remove containers, images, networks etc, that are no longer in use.

I'd rather not add more features to the `docker build` command; especially since there is a workable solution already; either combine the commands you showed, which could easily be scripted, or using the "prune" commands, which could be run with a cron-job if needed

**Comment by justyntemme** [comment]
I did not know of `prune`. Thank you for your time and consideration of this feature request.

**Comment by thaJeztah** [comment]
You're welcome! Hope it solves your use-case 👍
