### ISSUE TITLE
Avoid "please" in docs and messages

### ISSUE THREAD

**Issue by thaJeztah** [docker/cli#770]
We should try to avoid using "please" in the documentation and in (error) messages. There's a couple in this repository that may need some rephrasing; https://github.com/docker/cli/search?q=please&type=Code&utf8=✓ (also see https://github.com/docker/cli/pull/721#discussion_r158818855)

See;

- https://ux.stackexchange.com/questions/25500/why-avoid-the-word-please-in-error-messages
- https://ux.stackexchange.com/questions/10853/should-an-interface-ever-say-please

/cc @mistyhacks

**Comment by ggracechoi** [comment]
Hi @thaJeztah ! I'm a student at UT Austin, and I'm looking to contribute to an open source project for my Virtualization class. Is this issue still available? If not, do you think I'd be able to take on [issue #923](https://github.com/docker/cli/issues/923)?

**Comment by kolyshkin** [comment]
> Hi @thaJeztah! I'm a student at UT Austin, and I'm looking to contribute to an open source project for my Virtualization class. Is this issue still available? If not, do you think I'd be able to take on [issue #923](https://github.com/docker/cli/issues/923)? I tried reaching out to @kolyshkin but wasn't able to get in contact.

This is open source and collaborative development, you don't have to ask a permission to work on something. Please go ahead and open your PR, and we'll go from there.
