### ISSUE TITLE
[k8s] stacks should have their own namespace

### ISSUE THREAD

**Issue by thaJeztah** [docker/cli#776]
When using stacks with docker-compose or docker stack deploy (on SwarmKit), services are prefixed with the name of the stack. This came up in the review of https://github.com/docker/cli/pull/721#issuecomment-355036628

When deploying a stack to Kubernetes, no prefix is added, which prevents multiple stacks with a service having the same name to be deployed.

For example:

```yaml
version: '3.4'
services:
  web:
    image: nginx:alpine
```

```bash
$ docker stack deploy -c docker-compose.yml stack1
Stack stack1 was created
Waiting for the stack to be stable and running...
 - Service web has one container running
Stack stack1 is stable and running
```

Deploying the same stack again but with a different name;

```bash
$  docker stack deploy -c docker-compose.yml stack2
service web already present in stack named stack1
```

We should either prefix service names (as we do in swarmkit/docker-compose), or automatically use a namespace for each stack, similar to;

```bash
$ docker stack deploy --namespace com.docker.stacks.stack2 -c docker-compose.yml stack2
```

**Comment by silvin-lubecki** [comment]
The user may not have the right to create namespaces. I think it's the user's responsibility to specify the namespace, using `--namespace` flag, to avoid service collision.

**Comment by thaJeztah** [comment]
kubernetes integration was deprecated and removed; let me close this one
