### ISSUE TITLE
[k8s] document differences and current limitations of stack deploy on k8s

### ISSUE THREAD

**Issue by thaJeztah** [docker/cli#778]
relates to https://github.com/docker/cli/pull/721

Docker 18.01 will ship with a preview/experimental support for deploying stacks on k8s. We should document the differences between deploying on SwarmKit, current limitations, and known issues. At least;

- how to enable k8s integration on Docker for Desktop
- how to use against an existing k8s cluster (is this currently possible?)
- limitations around deploying multiple stacks with a service that has the same name (https://github.com/docker/cli/issues/776)
- limitations around re-deploying a stack that uses secrets (or configs); https://github.com/docker/cli/issues/777
- a known issue with the `--namespace` option not working (or not fully working) for stacks
- that this preview only supports the `docker stack` commands, but other commands are not yet available.

**Comment by thaJeztah** [comment]
We can add a document in https://github.com/docker/cli/tree/master/experimental and link to that from the documentation

**Comment by motin** [comment]
Does these have separate tracking issues yet, or any documentation?
* how to use against an existing k8s cluster (is this currently possible?)
* a known issue with the --namespace option not working (or not fully working) for stacks
The state of these limitations affect current decisions in our projects

**Comment by adeniyistephen** [comment]
@thaJeztah Hi,I would love to work on this, Please provide pointers and input on how to work on it. Thanks

**Comment by thaJeztah** [comment]
kubernetes integration was deprecated and removed; let me close this one
