### ISSUE TITLE
[k8s] Add e2e tests to the experimental kubernetes integration

### ISSUE THREAD

**Issue by vdemeester** [docker/cli#782]
Add e2e tests for kubernetes

- [x] easy start of a simple, single node k8s cluster
- [x] `docker stack deploy`, `docker stack rm`, `docker stack ls`, `docker stack ps`

**Comment by vdemeester** [comment]
Current work is https://github.com/docker/cli/pull/801

**Comment by simonferquel** [comment]
We are working on moving Compose on Kubernetes CI to [Kind](https://github.com/kubernetes-sigs/kind). Cluster provisioning is really fast, and we can use Compose on Kubernetes `install` package to prepare the test environment.

**Comment by thaJeztah** [comment]
kubernetes integration was deprecated and removed; let me close this one
