### ISSUE TITLE
[k8s] Implement all `docker stack deploy` flags

### ISSUE THREAD

**Issue by vdemeester** [docker/cli#783]
Should we implement all the following flags (that are only available for `docker stack deploy` when pointing to swarm) ?

 + [ ] `--prune` Prune services that are no longer referenced
 + [ ] `--resolve-image` Query the registry to resolve image digest and supported platforms ("always"|"changed"|"never") (default "always")
 + [ ] `--with-registry-auth` Send registry authentication details to Swarm agents
  
cc @thaJeztah @dnephin

**Comment by thaJeztah** [comment]
At first sight; yes, I think those are useful to have. I still have the `--with-registry-auth` (but that's another topic), and `--resolve-image` needs a proper review in general (so also a separate discussion), but I think we should have them :)

**Comment by adeniyistephen** [comment]
@thaJeztah Hi,I would love to work on this, Please provide pointers and input on how to work on it. Thanks

**Comment by thaJeztah** [comment]
kubernetes integration was deprecated and removed; let me close this one
