### ISSUE TITLE
docker service ls/ps is not truncating digests anymore

### ISSUE THREAD

**Issue by nishanttotla** [docker/cli#79]
Here's an example from (more or less) master:
```
$ docker service create --name atest alpine sleep 1000
dhbc2sl1p79s95eqj9ps8chrk
Since --detach=false was not specified, tasks will be created in the background.
In a future release, --detach=false will become the default.

$ docker service ls
ID                  NAME                MODE                REPLICAS            IMAGE                                                                                              PORTS
dhbc2sl1p79s        atest               replicated          1/1                 docker.io/library/alpine@sha256:c0537ff6a5218ef531ece93d4984efc99bbf3f7497c0a7726c88e2bb7584dc96

$ docker service ps atest
ID                  NAME                IMAGE                                                                                              NODE                DESIRED STATE       CURRENT STATE           ERROR               PORTS
oibpq5yjwda8        atest.1             docker.io/library/alpine@sha256:c0537ff6a5218ef531ece93d4984efc99bbf3f7497c0a7726c88e2bb7584dc96   7766acd77ab4        Running             Running 9 seconds ago
root@7766acd77ab4:/go/src/github.com/docker/docker#
```

This was implemented in https://github.com/moby/moby/pull/28539. I think this is a regression, possibly related to https://github.com/docker/distribution/pull/2142

cc @dmcgowan

**Comment by dmcgowan** [comment]
Possibly related, we added a `FamiliarString` for outputting the reference as a string as expected by the docker cli.

**Comment by aaronlehmann** [comment]
Why does the reference end up without a tag? That seems like the real bug to me. I would have expect it to be `alpine:latest@sha256:c0537ff6a5218ef531ece93d4984efc99bbf3f7497c0a7726c88e2bb7584dc96`, and I believe it used to end up this way.

**Comment by nishanttotla** [comment]
@aaronlehmann I'll open a PR to make sure that there is a default tag.

**Comment by nishanttotla** [comment]
Closing this in favor of https://github.com/moby/moby/pull/33279

**Comment by nishanttotla** [comment]
To actually fix this issue, we do also need to revendor `docker/docker` into `docker/cli`, to bring in the changes from https://github.com/moby/moby/pull/33279. Should I open a vendor PR, or is there a different procedure for cherry picking?
