### ISSUE TITLE
[RFC] CLI Experimental Flag should resemble the interface of its daemon

### ISSUE THREAD

**Issue by kevtainer** [docker/cli#790]
# [RFC] - Experimental Flag should be a boolean

related: #758 

This is somewhat confusing, the experimental flag on the daemon is a `bool`. As I fumbled with this for about 15 minutes I did some research (see above related link) and learned it was decided it would be a `string` value because there are plans for this to become a "feature" toggle at some point. This coupled with the `--experimental` flag (on `dockerd`) seems inconsistent. I don't necessarily believe the design of a significantly related interface should pigeonhole another but it should certainly warrant consideration.

Please consider adding a `experimentalOptions<string>` in the future, [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it), and switching the experimental flag to a Boolean rather than a descriptor.

**Comment by bsousaa** [comment]
CLI experimental options are now enabled by default. https://github.com/docker/cli/pull/2774
