### ISSUE TITLE
Script Error: scripts/docs/generate-man.sh hang up

### ISSUE THREAD

**Issue by Taeung** [docker/cli#794]
This problem is scripts/docs/generate-man.sh hang up error.
(So I don't include `docker version` and `docker info`)

You can reproduce this issue like below:
```
  $ ./scripts/docs/generate-man.sh
```
If running it, it is stopped

I guess the reason is below `line 10` on generate-man.sh :
i.e. when doing go-build, it does not work.
```go
go build -o /tmp/gen-manpages github.com/docker/cli/man
```
Why this hang up error occurs ?

**Comment by dnephin** [comment]
Try with `bash -x ./scripts/docs/generate-man.sh` to see why it fails.

It should be run from inside a container:

```
make -f docker.Makefile shell
# in the container
./scripts/docs/generate-man.sh
```
