### ISSUE TITLE
make cross failing, and warnings

### ISSUE THREAD

**Issue by thaJeztah** [docker/cli#815]
just noticed this when running `make -f docker.Makefile cross`;

```
docker run --rm -e VERSION=18.01.0-dev -e GITCOMMIT -e PLATFORM -v "/Users/sebastiaan/go/src/github.com/docker/cli":/go/src/github.com/docker/cli docker-cli-cross make cross
./scripts/build/cross
Building binaries for all platforms
Building build/docker-darwin-amd64
unexpected directory layout:
	import path: k8s.io/apimachinery/pkg/apis/meta/v1
	root: /go/src
	dir: /go/src/github.com/docker/cli/vendor/k8s.io/apimachinery/pkg/apis/meta/v1
	expand root: /go/src
	expand dir: /go/src/github.com/docker/cli/vendor/k8s.io/apimachinery/pkg/apis/meta/v1
	separator: /
Building statically linked build/docker-linux-amd64
Generating windows resources
Building build/docker-windows-amd64
Building statically linked build/docker-linux-arm
Building statically linked build/docker-linux-ppc64le
Building statically linked build/docker-linux-s390x
make: *** [cross] Error 1
Makefile:35: recipe for target 'cross' failed
make: *** [cross] Error 2
```

**Comment by dnephin** [comment]
I was able to run that command locally and it worked for me. It's also running fine in CI. Maybe an issue with your local checkout?

**Comment by RobTiki** [comment]
ThaJeztah,

Building cross and binary-windows was failing for me on centos 7.6 with kernel 3.10.0-957.5.1.el7.x86_64.  I installed 4.20.7 mainline kernel by elrepo and was able to build.  My errors did mention that APIClient missing yada yada yadya.  Your's is not as detailed.

docker run --rm -e VERSION=18.09.0-dev -e GITCOMMIT -e PLATFORM -v "/root/docker-vscode/cli-18.09.1":/go/src/github.com/docker/cli docker-cli-cross make binary-windows
./scripts/build/windows
Generating windows resources
/go/src/github.com/docker/cli/scripts/gen/../winresources/common.rc:11: digit exceeds base
/go/src/github.com/docker/cli/scripts/gen/../winresources/common.rc:12: digit exceeds base
/go/src/github.com/docker/cli/scripts/gen/../winresources/common.rc:11: digit exceeds base
/go/src/github.com/docker/cli/scripts/gen/../winresources/common.rc:12: digit exceeds base
Building build/docker-windows-amd64
# github.com/docker/cli/vendor/github.com/docker/docker/client
vendor/github.com/docker/docker/client/interface_stable.go:10:5: cannot use Client literal (type *Client) as type APIClient in assignment:
        *Client does not implement APIClient (missing SwarmUpdate method)
Makefile:39: recipe for target 'binary-windows' failed
make: *** [binary-windows] Error 2
make: *** [binary-windows] Error 2
