### ISSUE TITLE
Pull from private image not working

### ISSUE THREAD

**Issue by roysG** [docker/cli#825]
I am struggling for hours to do a "simple" pull from my private image!

This is so frustrating..

I am working on the las docker version:

Client:
Version:	17.12.0-ce
API version:	1.35
Go version:	go1.9.2
Git commit:	c97c6d6
Built:	Wed Dec 27 20:03:51 2017
OS/Arch:	darwin/amd64

Server:
Engine:
Version:	17.12.0-ce
API version:	1.35 (minimum version 1.12)
Go version:	go1.9.2
Git commit:	c97c6d6
Built:	Wed Dec 27 20:12:29 2017
OS/Arch:	linux/amd64
Experimental:	true

I tried the command:
docker tag docker_service1 roydocker/service1
docker push roydocker/service1

docker login (entered the username and password correctly)

and then..

docker pull roydocker/service1
Error response from daemon: manifest for roydocker/service1:latest not found.

Does it a bug or i miss something?

**Comment by rkgade** [comment]
Can you print out the docker daemon log?

**Comment by sam-thibault** [comment]
I don't see any recent activity on this issue.  I will close it as stale.
