### ISSUE TITLE
docker trust commands don't work on 18.01-ce

### ISSUE THREAD

**Issue by molepigeon** [docker/cli#830]
**Description**

When using Docker 18.01 CE, `docker trust` commands fail with "docker trust is only supported when experimental cli features are enabled", regardless of the setting of experimental features in the config.json.

**Steps to reproduce the issue:**
1. Install Docker 18.01 CE from the edge channel
2. Enable experimental features:
    - On Linux, as root, edit /etc/docker/daemon.json to contain `{"experimental":true}`. Then, as root, run `service docker restart` to apply the setting.
    - On Mac, open Docker's Preferences pane, then check the "Enable experimental features" checkbox, and click "Apply and restart" to apply the setting.
3. From a terminal, run `docker trust --help`.

**Describe the results you received:**
```
$ docker trust --help
docker trust is only supported when experimental cli features are enabled
```

**Describe the results you expected:**

The help text for the `docker trust` commands to be displayed (the below is taken from a Docker 17.12 install from the stable channel):
```
$ docker trust --help

Usage:	docker trust COMMAND

Manage trust on Docker images (experimental)

Options:


Management Commands:
  key         Manage keys for signing Docker images (experimental)
  signer      Manage entities who can sign Docker images (experimental)

Commands:
  inspect     Return low-level information about keys and signatures
  revoke      Remove trust for an image
  sign        Sign an image
  view        Display detailed information about keys and signatures

Run 'docker trust COMMAND --help' for more information on a command.
```

**Additional information you deem important (e.g. issue happens only occasionally):**

As hinted above, if I install Docker 17.12 from the stable channel on the same machine, I am able to use the trust commands as expected.

**Output of `docker version`:**

```
Client:
 Version:	18.01.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	03596f5
 Built:	Wed Jan 10 20:11:05 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.01.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	03596f5
  Built:	Wed Jan 10 20:09:37 2018
  OS/Arch:	linux/amd64
  Experimental:	true
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 18.01.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-112-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859GiB
Name: redeye-ubuntu
ID: DRZL:SSAR:XW2L:HT5Y:SUDS:OSYT:SPQY:R2Y2:5CDB:UVDY:D3GN:LDNT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Verified on Ubuntu 16.04 on VirtualBox (shown in the outputs of `docker info` and `docker version` above) and on the physical host, running Mac OS 10.13.2 on Docker version 18.01.0-ce-mac48 (22004).

**Comment by dnephin** [comment]
It needs to be `{"experimental": "enabled"}`, but that isn't clear from the error message.

cc @vdemeester 

We should probably:
* remove this from `trust`, since it was already in a release without this disabling
* support bools as well as strings for enabled/disabled

**Comment by molepigeon** [comment]
@dnephin is that the case on Mac as well? I saw `{"experimental": "enabled"}` in a previous issue, but couldn't apply it on Mac because it insisted that `experimental` was a boolean type:

![](https://i.imgur.com/Q942qHM.png)

Checking the box on the "Basic" tab sets it to boolean `true`.

**Comment by dnephin** [comment]
Oh, that is the wrong config. There is a client config at `~/.docker/config.json`. 

We should probably make that more clear in the error message as well.

**Comment by molepigeon** [comment]
Ah, great. Adding `"experimental":"enabled"` into `~/.docker/config.json` worked. Thanks!

Feel free to repurpose this issue to clarifying the error message, if you'd like.

**Comment by thaJeztah** [comment]
I was also discussing with the Docker for Mac team to have a checkbox to enable/disable experimental CLI features (similar as the one that's present for enabling/disabling the daemon experimental features)

**Comment by n4ss** [comment]
Ran into this, I agree that it'd be great to also be able to do the configuration of the cli through the D4M/D4W PrefPane.

**Comment by vdemeester** [comment]
Closing as of 18.03, `docker trust` commands are now out of experimental :angel:
