### ISSUE TITLE
CLI ref YAML generation script creating munged YAML

### ISSUE THREAD

**Issue by mistyhacks** [docker/cli#856]
Somehow the script is creating YAML with some of the letters missing from the extended description. See https://github.com/docker/docker.github.io/issues/5876#issuecomment-362043855. For some reason, the `Do` part of `Docker` is truncated in the extended description. It impacts at least the reference for `docker inspect` and not sure which others. Not sure which labels to put on this.

**Comment by thaJeztah** [comment]
oh, possibly https://github.com/docker/cli/pull/564, didn't revisit that one yet to check Daniel's comment

**Comment by thaJeztah** [comment]
not sure why `D` and `o` would be stripped though 🤔

**Comment by dnephin** [comment]
D, o, and c are in `Description`, k is not, so  it strips Doc

#564 will fix it

**Comment by thaJeztah** [comment]
Fixed by https://github.com/docker/cli/pull/564
