### ISSUE TITLE
Add new option --cwd as shortcut for '-v "$PWD:/cwd" -w /cwd'

### ISSUE THREAD

**Issue by matthewadams** [docker/cli#861]
**Description**
When I want my current working directory on the host machine to be the current working directory in the container, typing `-v "$PWD:/cwd" -w /cwd` is a pain.  I'd rather have an option `--cwd` to do that.

**Steps to reproduce the issue:**
N/A

**Describe the results you received:**
N/A

**Describe the results you expected:**
N/A

**Additional information you deem important (e.g. issue happens only occasionally):**
N/A

**Output of `docker version`:**

```
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: false```

**Output of `docker info`:**

```
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 25
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.49-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: moby
ID: H7X6:PAES:R6JP:KG5Q:IAF5:WJQT:N6KO:TOBX:6QA7:STNM:2OTE:52VA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 18
 Goroutines: 29
 System Time: 2018-02-01T14:24:10.93966567Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
N/A

**Comment by matthewadams** [comment]
Bonus points for a short version of the option, because I'd rather type `-x` than `--cwd`.  :)

**Comment by thaJeztah** [comment]
docker 23.0 and up now allows for relative paths to be specified (see https://github.com/docker/cli/pull/3469)

I'll close this one

**Comment by matthewadams** [comment]
Don't close.  Still has merit.
