### ISSUE TITLE
Remove go-bindata

### ISSUE THREAD

**Issue by marwan-at-work** [docker/cli#864]
The author of go-bindata has removed their github account which has been replaced by another author. It seems from this file that you do a go get and not vendor go-bindata directly: 

https://github.com/docker/cli/blob/819df0ebf600560698cd127a961f3d7753f59278/dockerfiles/Dockerfile.dev#L14

What it's generating: https://github.com/docker/cli/blob/6686ada6a4cf4e872af4d9bf3f61c387be934d87/cli/compose/schema/schema.go

Here are some alternatives that accomplish the same job: 
https://github.com/rakyll/statik
https://github.com/gobuffalo/packr

Related tweet and discussion: https://twitter.com/francesc/status/961249107020001280

**Comment by dnephin** [comment]
Yes, we need to look at using another tool. 

https://github.com/mjibson/esc is another option

> It seems from this file that you do a go get and not vendor go-bindata directly:

That is true, but we do vendor the artifact created by `go-bindata`, so it can't change unexpectedly without us knowing about it.
