### ISSUE TITLE
docker pull lose all header while 302 redirect

### ISSUE THREAD

**Issue by athurg** [docker/cli#865]
While you run a `docker pull` on a server. If the registry server return a 302 redirect response, the docker client will then follow the new url in the response's **Location** header.

But if the new location's domain is not safe domain (same as or sub of the origin domain host, and the port must be same too), the docker client (golang's default http client) will drop **Authorization** header.

**Comment by thaJeztah** [comment]
This is the correct behaviour for redirects: passing authorisation information to a non-related location would be a security leak.

Also see https://github.com/moby/moby/pull/33707, https://stackoverflow.com/a/17116714/1811501
