### ISSUE TITLE
Make cli work on OpenBSD

### ISSUE THREAD

**Issue by unkaktus** [docker/cli#873]
cli does not build on OpenBSD anymore. This is the issue to track the progress on fixing related dependencies.

**Steps to reproduce the issue:**
1. `GOOS=openbsd GOARCH=amd64 go get github.com/docker/cli/cmd/docker`

**Describe the results you received:**
Various compile-time errors (non-impemented functions, missing syscalls etc)

**Describe the results you expected:**
Docker cli builds on OpenBSD.

Stages:
- [x] https://github.com/moby/moby/pull/36276
- [x] https://github.com/docker/cli/pull/872
- [x] https://github.com/tonistiigi/fsutil/pull/27
- [x] https://github.com/containerd/continuity/pull/104
- [x] https://github.com/containerd/containerd/pull/2712
- [x] https://github.com/containerd/containerd/pull/2713
- [ ] https://github.com/containerd/continuity/pull/109
- [ ] update vendor in cli repo
- [ ] add `openbsd/amd64` to cross build

**Comment by dnephin** [comment]
I added another task to the list. We should build it as part of cross so that we catch regressions.

**Comment by thaJeztah** [comment]
Moby changes are brought in through https://github.com/docker/cli/pull/892

**Comment by nogoegst** [comment]
updated the list as there three more new blockers, ah.

**Comment by bsousaa** [comment]
Closing for now as there is no active work being done here. Though contributions are welcome.
