### ISSUE TITLE
Fetch the Image ID of docker plugin

### ISSUE THREAD

**Issue by PraveenSenathi** [docker/cli#91]
I am not sure how I can fetch the plugin image ID of a docker plugin which should match the config.digest field in the manifest stored in the registry

For docker images once I build the image and push the image to the registry, the Image ID found when I run this command "docker images $Image_Name"  exactly matches the config.digest field in the manifest for that image in the registry since Image ID's are now content addressable SHA's.

I want to do the same thing for docker plugin.  I create a plugin with the "docker plugin create" command and push the plugin to the registry. Docker plugin create/install command creates a container and run's the plugin in it and now there is no way to get the Image ID of the plugin to compare with the config.digest of the manifest in the registry.

Is there a way to do this or am I missing something? I am using docker client 1.13 and the latest registry using schemaversion2. This is helpful for our signing service where we allow docker pull for only signed/valid images or plugin.

Thanks

**Comment by sam-thibault** [comment]
This is an old issue.  I will close it as stale.
