### ISSUE TITLE
dead link in cli/CONTRIBUTING.md

### ISSUE THREAD

**Issue by abhisheksp** [docker/cli#937]
File: cli/CONTRIBUTING.md 
In the first sentence "setting up a Docker development environment and the contribution process" redirects to a page explaining how to contribute to documentation(https://docs.docker.com/opensource/)

**Intended dead link**: https://docs.docker.com/opensource/project/who-written-for/

**Comment by dvdksn** [comment]
The instructions on how to set up your development environment for contributing to docker/cli doesn't exist on the main docs site anymore.

Do we want to maintain such a setup guide on the docs site, or should it live directly in the contribution guide for specific repositories? e.g., cli, compose, and moby.

CC @thaJeztah

**Comment by achneerov** [comment]
@thaJeztah Could I try to tackle this? and do you have any suggestions/recommendations? many thanks!
