### ISSUE TITLE
Make fails with `make: *** [binary] Error 1`

### ISSUE THREAD

**Issue by dave-tucker** [docker/cli#94]
Make fails with the helpful error message of `make: *** [binary] Error 1`

A little debugging shows that https://github.com/docker/cli/blob/master/scripts/build/.variables#L7 is the issue.

On OSX:

```
$ date --utc --rfc-3339 ns
date: illegal option -- -
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
```

I know that the `README` now shows the Dockerized make targets so this will only be an issue for people like me on OSX who didnt RTFM 😁 

I guess it would be nice to be fixed or for the dockerized makefile to be the default one.

**Comment by thaJeztah** [comment]
What exact command did you run? `make binary` or just `make` ?

**Comment by dave-tucker** [comment]
just `make`

**Comment by dnephin** [comment]
I believe I fixed this in #78 , are you on latest master?

**Comment by dnephin** [comment]
> I guess it would be nice to be fixed or for the dockerized makefile to be the default one.

This was discussed in #78 as well: https://github.com/docker/cli/pull/78#discussion_r116527704

I think we'll look at replacing `docker.Makefile` with a `./build.sh` for now

**Comment by dave-tucker** [comment]
Yes I'm on latest master. Both `make` and `make binary` insta-fail on OSX.

**Comment by thaJeztah** [comment]
Oh, :facepalm: this is the docker/cli repo, ignore me

**Comment by dnephin** [comment]
We could probably also add a check to the `Makefile` that warns if it's not being run from an expected environment. Maybe `docker.Makefile` (and the future `./build.sh`) could set `DOCKER_CLI_THIS_IS_FINE=`. Anyone know has setup their host can export that as well to remove the warning.

Then in `Makefile` if the environment variable isn't set we can warn "you probably want `./build.sh`"

**Comment by dnephin** [comment]
This has been partially fixed by removing the "develop on the host" instructions from the README. We also have #99 to track other related improvements. #107 introduces the script I suggested here.

Going to close this issue since we have another tracking issue.
