### ISSUE TITLE
[quality] content trust tests coverage

### ISSUE THREAD

**Issue by vdemeester** [docker/cli#951]
While porting `DockerTrustSuite` from `moby/moby`, few tests weren't ported (because a bit tricky to achieve as is), see https://github.com/docker/cli/pull/924#discussion_r175119661

This issues is there to track progress on adding test coverage on `content trust features`, this means unit and e2e tests.

- [ ] `container`
- [ ] `image`
- [ ] `plugin`
- [ ] `services`
- [ ] `build`

**Comment by thaJeztah** [comment]
Related https://github.com/docker/cli/issues/1218
