### ISSUE TITLE
Fish completion for docker trust

### ISSUE THREAD

**Issue by eiais** [docker/cli#977]
I should be able to get this done relatively soon.

I also noticed while looking at this that some descriptions are out of date. I'll update those as well.

**Comment by eiais** [comment]
Bash commands are also missing key and signer. Is that to avoid issues with them going an extra level of sub coommands?

**Comment by eiais** [comment]
cc @dnephin

**Comment by eiais** [comment]
The image subcommand also needs to be added for fish. There is also an issue where subcommands that are named the same show flags that are valid for any

**Comment by vdemeester** [comment]
@eiais yeah I think the `fish` completion needs an updates on lot's of commands/subcommands
