### ISSUE TITLE
[k8s] docker could error out more clearly when there is no kubernetes configuration file

### ISSUE THREAD

**Issue by vdemeester** [docker/cli#985]
When `kubernetes` is use as the `orchestrator` but there is not `$HOME/.kube/config`, the docker cli errors out without too much context.

```
$ docker stack deploy -c docker-compose.yml foo
Failed to load kubernetes configuration file '/home/vincent/.kube/config'
```

We may want to add more context on the error, like why we're looking at that file, etc..

cc @thaJeztah @silvin-lubecki

**Comment by olljanat** [comment]
@vdemeester this one looks to be fixed?

**Comment by thaJeztah** [comment]
Yes, looks like this was fixed through https://github.com/docker/cli/pull/1216
