### ISSUE TITLE
Docker CLI does not use /etc/hosts to resolve host names

### ISSUE THREAD

**Issue by marksztainbok-okta** [docker/cli#995]
**Description**

In our environment we set an entry in /etc/hosts on the local machine which we then use in the URL in the `DOCKER_HOST` environment variable and have our Docker machine set up with a custom certificate for that name for SSL. When we use the docker command line what we're finding is that the docker command fails with an error similar to `error during connect: Get https://rum-docker.okta1.com:2376/v1.37/containers/json: x509: certificate is not valid for any names, but wanted to match rum-docker.okta1.com`. On investigation this is due to the docker client using DNS to resolve `rum-docker.okta1.com` instead of the /etc/hosts and getting the wrong address so it is contacting the wrong Docker endpoint (in this case rum-docker.okta1.com is resolving to 127.0.0.1 from DNS). This used to work previously and I validated that the issue doesn't occur in version 17.03 or 17.09 of the client but does in versions 17.12 and 18.03 and happens on Mac, Windows and Linux.

**Steps to reproduce the issue:**
1. Configure a Docker machine created with `docker-machine` to have a custom SSL certificate with a host name
2. Add an entry for the host name in the SSL certificate in /etc/hosts (or platform equivalent) with the Docker endpoint IP address
3. Access the Docker machine using the docker client to run a command (e.g. `docker info`, `docker ps`, etc.) with `DOCKER_HOST` set to use the hostname (e.g. `tcp://rum-docker.okta1.com:2376`) and TLS verify enabled (i.e. `DOCKER_TLS_VERIFY=1`)

**Describe the results you received:**
The command fails with an error similar to  `error during connect: Get https://rum-docker.okta1.com:2376/v1.37/containers/json: x509: certificate is not valid for any names, but wanted to match rum-docker.okta1.com`

**Describe the results you expected:**
The command succeeds and shows the correct output for the command from Docker

**Additional information you deem important (e.g. issue happens only occasionally):**
This occurs on Mac, Windows and Linux and only with newer clients (validated with 17.12 and 18.03). It does not occur with 17.03 or 17.09 so it is most likely due to code change between 17.09 and 17.12.

**Output of `docker version`:**

```
Docker version 18.03.0-ce, build 0520e24 (not working)
Docker version 17.03.2-ce, build f5ec1e2 (working)
```

**Output of `docker info`:**
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.09.0-ce-rc1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.87-boot2docker
Operating System: Boot2Docker 17.09.0-ce-rc1 (TCL 7.2); HEAD : ffa0e38 - Thu Sep  7 17:36:03 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 9.746GiB
Name: cpc
ID: HS4N:IOWC:LJPJ:655K:QPPL:EXL4:KDDV:Y7IF:DHJG:HFKU:O3HB:LS7E
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 18
 Goroutines: 26
 System Time: 2018-04-10T19:33:29.821395822Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VirtualBox

**Comment by thaJeztah** [comment]
ping @cyli @n4ss PTAL

**Comment by cyli** [comment]
Is there a DNS SAN entry for your certificate or just the common name?  There was a change in go 1.9 I believe which stopped matching the host name with the common name:  https://github.com/golang/go/issues/22922

This may account for why it works in 17.03 vs 18.03.

**Comment by marksztainbok-okta** [comment]
@cyli The certificate had some IP address SAN entries but no DNS entry. I regenerated the certificate with a DNS SAN entry as well and it now works with the latest client (18.04).

The documentation probably should indicate that a DNS SAN entry is required in any certificates.

**Comment by bsousaa** [comment]
It looks like this issue went stale. Let me close it for now. Feel free to comment and we can re-open if we have more info.
